### ISSUE TITLE
Stacktrace reports wrong line number

### ISSUE THREAD

**Issue by truesri** [withastro/astro#5465] opened 2022-11-24 02:21 UTC
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When accessing data that is undefined the stacktrace reports the wrong line number. When using no integrations the line number seems to be off by 1, but when using the tailwindcss integration it is off by more.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vdxjk2?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dsomel21** [comment] 2023-03-02 00:39
@bluwy, are we sure that this is a p3 ("An edge case that only affects very specific usage"). 

It was happening to me in #6372 when I was basically doing:

```astro
---
const response = await fetch(
  "https://clean-dragons-hear-198-54-132-72.loca.lt/api/v1/books"
);
const data = await response.json();
const book = data.books.find((b) => b.id == id); // This is breaking cuz the fetch failed
---
```

Nothing _too_ specific. 

I can look into it, but can you share some details about where to look (is it the `astro` repo, or what).

**Comment by JoshuaKGoldberg** [comment] 2023-04-08 12:39
It this an appropriate place for me to suggest this be raised to a p2? I agree with @dsomel21, it's really quite a poor onboarding experience for folks like me new to Astro.

I'd love to look into helping fix this if you can give a few starting pointers 🙂

**Comment by Princesseuh** [comment] 2023-05-02 16:25
> It this an appropriate place for me to suggest this be raised to a p2? I agree with @dsomel21, it's really quite a poor onboarding experience for folks like me new to Astro.
> 
> I'd love to look into helping fix this if you can give a few starting pointers 🙂

Sorry for the late answer, I didn't see your comment. The causes of this are quite various, so it's generally hard to pinpoint the problem and give guidance.

In most cases, apart from CSS errors, the reason is source map related, either the source map that our compiler generated isn't accurate, or the source map isn't linked correctly / configured correctly.

For frontmatter errors in particular, there's a bit of a special situation where the frontmatter is reparsed to give a better error message: <https://github.com/withastro/astro/blob/72c6bf01fe49b331ca8ad9206a7506b15caf5b8d/packages/astro/src/vite-plugin-astro/compile.ts>, which I feel might be partially responsible? I'm not sure. 

For CSS, generally the problem is that due to how the processing is done, we lose the original position of the style tag. We try to guess it, but it fails in most cases. I'm not 100% sure what we could do there, perhaps the compiler could return some positions as well

**Comment by bluwy** [comment] 2023-06-02 09:31
I looked into this over the week and it's quite a rabbithole. Things I've uncovered:

1. The tailwind integration causing worser line offsets is caused by [astro:scripts:page-ssr](https://github.com/withastro/astro/blob/80e86d65fa5c16247f6b6696152d0edea065947e/packages/astro/src/vite-plugin-scripts/page-ssr.ts#L33-L39). I _think_ MagicString isn't outputting the right sourcemap when using `prepend` with `\n`.
2. Vite's SSR rewrite seems to not rewrite some paths to the right source (#7273)
3. Vite's `combineSourcemap` implementation seems to generate an incorrect sourcemap, particularly [this line](https://github.com/vitejs/vite/blob/bf0cd25adb3b8bb5d53433ba9323d0a95e9f756a/packages/vite/src/node/utils.ts#L765). Which means there might be a bug in `remapping`?

I'm testing with https://evanw.github.io/source-map-visualization/ for those who want to debug this. Overall I think the issue lies in Vite, but this also only covers the issue's original repro. I haven't checked the others yet.

**Comment by kireerik** [comment] 2023-06-17 03:42
This would be very useful. I could add development class names if this works properly.

related example:
- # [Refo](https://github.com/kireerik/refo)

&nbsp;
current workaround:
- [getModuleName.js](https://github.com/kireerik/refo/blob/48072d16f27d007e5c16d628cec1c00a91a67235/example/index/getModuleName.js)

- [style/css.js#L20](https://github.com/kireerik/refo/blob/48072d16f27d007e5c16d628cec1c00a91a67235/example/index/style/css.js#L20)

**Comment by bluwy** [comment] 2023-06-27 09:58
This issue's repro and the CSS error repro (https://github.com/withastro/astro/issues/6971) should be fixed in #7273 and #7491 respectively. Not sure if that's all the issues to be able to close this?

**Comment by remorses** [comment] 2023-06-28 12:38
You can now use https://github.com/antfu/vite-plugin-inspect to inspect source maps issues (even in SSR code)

https://github.com/antfu/vite-plugin-inspect/assets/31321188/cd139c1b-b1c1-42fd-a9bc-9fa292695b70

**Comment by remorses** [comment] 2023-06-29 11:40
The sourcemaps for the astro files are correct, the issue must be in the way they are applied to the stack trace

**Comment by bluwy** [comment] 2023-06-29 11:58
Are using the latest version of Astro? It should fix the stacktrace numbers (with Vite) and uses hi-res sourcemaps so the merged sourcemap isn't degraded.

**Comment by kireerik** [comment] 2023-06-29 13:56
With my use case the line numbers are still wrong.

**Comment by bluwy** [comment] 2023-06-29 14:38
@kireerik can you provide a repro for your usecase? I don't quite understand how it's related to Astro.

**Comment by kireerik** [comment] 2023-06-30 17:01
Sure:
- # [Refo](https://github.com/kireerik/refo)

&nbsp;
If I emit an `Error` on this line for example:
- [example/index/style/css.js#L23](https://github.com/kireerik/refo/blob/0d08f7e3bcbd97cb2fdf1738493ed60e77b910de/example/index/style/css.js#L23)

Then I get incorrect line numbers with the `Error` for example for this function call:
- [example/index/index/site/main/header/index.jsx#L17](https://github.com/kireerik/refo/blob/0d08f7e3bcbd97cb2fdf1738493ed60e77b910de/example/index/index/site/main/header/index.jsx#L17)

> I would need the correct line number (I would expect `17` in the above case (for that file)). So I can then import for example the `header` component module as `raw` and based on the correct line number extract the variable name (`Header` in the case of the above example) and set that as a class name label (in `development` mode).

**Comment by bluwy** [comment] 2023-07-01 03:06
@kireerik that's not a reproduction. https://antfu.me/posts/why-reproductions-are-required

**Comment by kireerik** [comment] 2023-07-02 00:10
I have created one for you:
- https://stackblitz.com/edit/github-tdgy2y?file=index%2Fstyle%2Fcss.js,index%2Findex%2Fsite%2Fmain%2Fheader%2Findex.jsx

**Comment by bluwy** [comment] 2023-10-02 14:17
@kireerik Sorry for the late reply. I just checked your repro, and what you're trying to do is unfortunately not something supported by Vite currently. Vite needs to transform SSR code in a different way for it to work, and that transformation affects the stacktrace generated from `new Errro()`.

While Vite tries to fix it, it can only fix for thrown and caught errors. The `console.log(new Error())` is simply creating an error and consuming it itself. So there's no way for Vite to intercept it. I'd suggest finding another way to achieve what you're aiming for. Acquiring the stacktrace this way isn't always safe.

I'm going to close this as we haven't got any new reports so far. And new ones should be created as new issues.

**Closed by bluwy** 2023-10-02 14:17 UTC
Labels: - P4: important
