### ISSUE TITLE
[3.0.0-beta.1] Build and dev fails with missing collapseDuplicateSlashes export

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#8052] opened 2023-08-13 12:07 UTC
### What version of `astro` are you using?

3.0.0-beta.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm (also failed with npm)

### What operating system are you using?

Linux

### What browser are you using?

N/A

### Describe the Bug

`build` and `dev` fails with the latest beta. Only changed from beta.0 to beta.1.

```console
$ pnpm build

> @fflaten/website@0.0.1 build /workspaces/Website
> astro build

 error   The requested module '../core/path.js' does not provide an export named 'collapseDuplicateSlashes'
file:///workspaces/Website/node_modules/.pnpm/astro@3.0.0-beta.1_@types+node@20.4.9_sass@1.65.1_typescript@5.1.6/node_modules/astro/dist/vite-plugin-astro-server/request.js:5
import { collapseDuplicateSlashes, removeTrailingForwardSlash } from "../core/path.js";
         ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '../core/path.js' does not provide an export named 'collapseDuplicateSlashes'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
 ELIFECYCLE  Command failed with exit code 1.
```

### What's the expected result?

Build should work.

### Link to Minimal Reproducible Example

3.0 not compatible with Stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-08-14 09:06
Looks like it's because that feature got mixed up during rebases for the `@astrojs/internal-helpers` package. We'd need to re-release it.

**Comment by natemoo-re** [comment] 2023-08-14 13:23
Should be closed by https://github.com/withastro/astro/pull/8064

**Comment by natemoo-re** [comment] 2023-08-14 15:07
Confirmed that this is fixed!

**Closed by natemoo-re** 2023-08-14 15:07 UTC
Labels: - P4: important
