### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by m4rrc0** [withastro/astro#2829] opened 2022-03-18 16:52 UTC
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Encountered an inconsistency between dev and build.
When
- using a 'catch all' file like `[...path].astro` and
- returning something like `{ params: { path: '/some/path' } }` in `getStaticPaths()`

The page (or path) fails when running `astro dev` while it works fine when running `astro build && astro preview`.

Just to clarify, returning `{ params: { path: 'some/path' } }` (no starting '/') works in both cases.

I am not sure of all the implications of allowing the failing case... This bug bit me as I was generating paths programmatically and obviously wanted to use these paths in`href` attributes (thus wanted to have the starting '/').

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hgmebk?file=src/pages/index.astro

**Comment by FredKSchott** [comment] 2022-03-21 05:37
This is expected behavior, imagine if instead of path you did something like "src/pages/[...color].astro":

```
/red -> {color: 'red'}
{color: 'red'} -> /red
```

Now, to bring back your `[...path]` example, with the same URL:

```
/red -> {path: 'red'}
{path: 'red'} -> /red
```

Closing this as not a bug and expected behavior, but if you have any ideas here for how we can improve this use-case without introducing inconsistency with how we handle paths, please create a discussion in our suggestions & rfcs repo: https://github.com/withastro/rfcs/discussions

**Closed by FredKSchott** 2022-03-21 05:37 UTC
