### ISSUE TITLE
cannot click to blog page

### ISSUE THREAD

**Issue by npmrun** [withastro/astro#4381] opened 2022-08-18 16:21 UTC
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

cannot click to blog page
![image](https://user-images.githubusercontent.com/62639956/185445261-9b1e3b33-0623-483b-a4e7-dab86f8d30c3.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-nqgqjz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2022-08-18 16:54
Hi @npmrun — this is because you have moved the blog posts (`first-post.md`, `second-post.md` etc.) _out_ of the `src/pages/blog/` directory and into `src/content/`. To make a Markdown or MDX file a page on your site, the files [must be inside `src/pages/`](https://docs.astro.build/zh-cn/core-concepts/astro-pages/).

This is also why the links are missing in the list of posts because although you updated the `Astro.glob` in `src/pages/blog.astro` to use the new content location, in the template `post.url` will not be defined because files outside of `src/pages/` do not have a `url` property.

I’ll close this as it is not a bug with Astro, but if you run into any other issues, you can join our Discord chat where the community will be happy to help! https://astro.build/chat

**Closed by delucis** 2022-08-18 16:54 UTC
