### ISSUE TITLE
Server mode w Netlify adapter - cookies don't seem to work across endpoints

### ISSUE THREAD

**Issue by sashafklein** [withastro/astro#9978] opened 2024-02-05 01:03 UTC
### Astro Info

```block
Astro                    v4.3.2
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/react
```

### Describe the Bug

Note: Maybe the same as [this one](https://github.com/withastro/astro/issues/9969)?

My app has several API endpoints, including `src/pages/api/login.ts` and `src/pages/api/profile.ts`. These endpoints are essentially proxies for an external API I don't run. The first authenticates and saves the auth token to cookies. The second fetches the auth token from cookies, and, if it's present, makes a request for the authenticated user.

The login endpoint code looks like this:

```ts
export const justUnderOneHour = 59 * 60 * 60 * 1000;

export const POST: APIRoute = async ({ request, cookies }) => {
  const { email, password } = (await request.json()) as {
    email: string;
    password: string;
  };

  if (!email) return badRequest("Missing email.");
  if (!password) return badRequest("Missing password.");

  try {
    const user = await login(email, password);
    const expires = new Date(Date.now() + justUnderOneHour);
    const path = "/";

    console.log("SETTING", cookies.get("userToken")?.value);

    cookies.set("userToken", user.token, { expires, path });

    console.log("GETTING", cookies.get("userToken")?.value);
    return jsonResponse(user);
  } catch (error) {
    console.error(error);
    return badRequest("Invalid email or password.");
  }
};
```

And the profile path, which is designed to check for the token, and then fetch the authenticated user:

```ts
export const GET: APIRoute = async ({ request, cookies }) => {
  const wbHeaders = await getWbAuthHeaders();
  const tokenFromCookie = cookies.get("userToken") as string | undefined;

  console.log("tokenFromCookie", tokenFromCookie);
  // Return empty, to prompt a re-request. The token has been expired
  if (!tokenFromCookie) return jsonResponse(null);

  const { token, ...user } = await fetchJson<WbUser>(`/user`, {
    headers: wbHeaders,
  });

  console.log(user);

  return jsonResponse(user);
};
```

When I hit the login endpoint, it authenticates correctly, such that the `"GETTING"` log logs the just-set user token. Moreover if I'd already logged in, the `"SETTING"` log logs the previous cookie -- as in, the cookie seems to be stored "within" that endpoint. The cookie is also visible in developer tools:

<img width="478" alt="image" src="https://github.com/withastro/astro/assets/149210369/10b606a2-ebeb-4a1e-865d-a6ac6d153dad">

**However**, if hit the `/profile` endpoint, the `"tokenFromCookie"` log is always undefined (not even an empty Cookies value object.) I think this is a bug, unless I'm misunderstanding how this should work.

### What's the expected result?

I expect a cookie set in one endpoint to be available in another (*definitely* if I set `path` to `/`).

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/sashafklein/astro-cookie-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment] 2024-02-09 18:08
I'm still trying to understand the issue. Are you expecting a fetch call between the triple dashes to include cookies in its request?

<img width="423" alt="image" src="https://github.com/withastro/astro/assets/69170106/5203e012-a85e-4606-98a8-2d101f1ee5d3">

**Comment by sashafklein** [comment] 2024-02-09 20:30
@lilnasy 

Yes. Perhaps I'm misunderstanding. I thought each server endpoint would have access to server-side cookies, through the `cookies` object injected into the function arg object. I might be totally misunderstanding how this works. 

Basically, my problem is that I want to be able to share the authenticated user data between different components in my app. Once I've logged in, I want the header to be able to get the logged-in user data, and API calls to be authenticated with that user's token. 

My thought was that cookies solve this, by letting me store the result from the auth call to a value shared between endpoints. But maybe I've got this totally wrong?

**Comment by lilnasy** [comment] 2024-02-09 20:45
What you're describing seems to best suited for [locals](https://docs.astro.build/en/guides/middleware/#storing-data-in-contextlocals).

As for missing cookies, I suspect it is happening because the request youre reading on the server comes from the server itself.

For context, the lines of code between the triple dashes run on the server, and a fetch call made by a server does not include cookies unless you manually add a `Set-Cookie` header.

**Comment by amrfarid140** [comment] 2024-02-10 14:48
To me this seems to describe the same logic as ["Adding authentication with firebase"](https://docs.astro.build/en/guides/backend/google-firebase/#adding-authentication-with-firebase) doc. Which also isn't working for me (using Astro v4).

I can see the cookie value on the browser but server-side logic still can't read it.

**Comment by sebastianjnuwu** [comment] 2024-02-11 00:15
Any solution? Does this method or logic work?

**Comment by lilnasy** [comment] 2024-02-11 00:22
@sebastianjnuwu The reproduction project in the issue involves the server sending a request to itself. You wouldn't want to do that, because it could lead to infinite loops.

Using code already written in an endpoint elsewhere is described here: [Call endpoints from the server](https://docs.astro.build/en/recipes/call-endpoints).

**Comment by sebastianjnuwu** [comment] 2024-02-11 20:24
@lilnasy

**Comment by lilnasy** [comment] 2024-02-13 16:47
Closing as there doesn't seem to be a bug - it comes down to fetch calls made by the node server predictably not having cookies. Feel free to reopen of you think there is more to the issue.

**Closed by lilnasy** 2024-02-13 16:47 UTC
Labels: needs response
