### ISSUE TITLE
Astro.glob applies is:global styles

### ISSUE THREAD

**Issue by isaac-mcfadyen** [withastro/astro#5037] opened 2022-10-10 13:06 UTC
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

When using `Astro.glob()` with `.astro` files (so for example, `await Astro.glob("/src/pages/news/*.astro")`)
- any `is:global` styles used on any component within that Astro file (even imported components) are immediately applied
- even if the import is not used (i.e. all you do is console.log it), the styles are still applied

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ysxamc?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2022-10-10 13:11
This is a duplicate of https://github.com/withastro/astro/issues/3816

A known limitation of Astro.glob. We're going to be working on an alternative API to fix this problem when you only want the metadata about a page.

**Closed by matthewp** 2022-10-10 13:11 UTC
