### ISSUE TITLE
Astro Image component giving type error for local image

### ISSUE THREAD

**Issue by abhi375** [withastro/astro#6015] opened 2023-01-28 17:52 UTC
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Astro Image component giving Type Error for local image even if aspectRatio is provided. based on the docs, it's possible to either just give aspectRatio or provide width and height.

Attaching you the error images for the same.

Thanks for the help. 

<img width="855" alt="CleanShot 2023-01-28 at 22 00 37@2x" src="https://user-images.githubusercontent.com/70268613/215277823-a7ae4455-cd06-4c66-87c0-4d01e051536f.png">
<img width="295" alt="CleanShot 2023-01-28 at 22 00 42@2x" src="https://user-images.githubusercontent.com/70268613/215277826-aa50792d-3909-44eb-baeb-9972b4a71db3.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-bq9owg?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by abhi375** [comment] 2023-01-28 17:55
Also in docs, it says that for local images you can just provide aspect ratio https://stackblitz.com/edit/withastro-astro-bq9owg?file=src/pages/index.astro

is it correct? or does component needed at least a width or height. Attaching a discord thread for the same https://discord.com/channels/830184174198718474/1068925095915048971/1068929829354864640

**Comment by Princesseuh** [comment] 2023-01-28 19:25
Have you updated your types like indicated here? <https://docs.astro.build/en/guides/integrations-guide/image/#update-envdts>

**Comment by ehowey** [comment] 2023-01-30 06:01
Just a note that I am seeing this too, but with remote images - I had not switched out the types, but did do this and am still seeing the error.  I tried the updating `tsconfig.json` as well to no avail. Just in case it was something odd I restarted VS Code as well.

**Comment by Princesseuh** [comment] 2023-01-30 08:37
> Just a note that I am seeing this too, but with remote images - I had not switched out the types, but did do this and am still seeing the error.  I tried the updating `tsconfig.json` as well to no avail. Just in case it was something odd I restarted VS Code as well.

width and height are required for remote images, so if you get the same error message it's valid.

**Comment by abhi375** [comment] 2023-01-30 09:30
Yeah, agreed, width/height is required for remote images, but it's not mandatory for local images right? I am getting this type error for local image

And based on documentation, it's not mandatory if aspect ratio is provided

**Comment by rhizodigital** [comment] 2023-01-30 09:36
I thought to use aspectRatio you need to provide either a width or a height. Since 2.0 I am still getting type error when providing width with aspectRatio.

**Comment by Princesseuh** [comment] 2023-01-30 09:56
> Yeah, agreed, width/height is required for remote images, but it's not mandatory for local images right? I am getting this type error for local image
> 
> And based on documentation, it's not mandatory if aspect ratio is provided 

Have you updated your types like my previous message suggest? Your reproduction has the wrong types set up.

**Comment by marcellocurto** [comment] 2023-01-30 11:25
I'm not sure why, but when I open your stackblitz example and remove `aspectRatio` it just works and there is no type error.

However, Astro complains that:
```
files in the public directory are served at the root path.
Instead of /public/placeholder-about.jpg, use /placeholder-about.jpg.
```

If I then follow this advice Astro complains even more:
```
ENOENT: no such file or directory, open '/placeholder-about.jpg'
```

See my [stackblitz fork here](https://stackblitz.com/edit/withastro-astro-nie5fe?file=src%2Fpages%2Findex.astro).

**Comment by Princesseuh** [comment] 2023-01-30 11:52
Stackblitz does not show type errors in the editor for Astro files. Also, yes, one of `width` or `height` is required for the `aspectRatio` property to take effect. The property is exclusively used to infer a width or height when it wasn't provided

See the docs for more information https://docs.astro.build/en/guides/integrations-guide/image/#aspectratio

**Comment by Princesseuh** [comment] 2023-02-09 22:04
Closing in favor of https://github.com/withastro/astro/issues/6194

The initial issue here are caused by not updating the types and probably a misunderstanding on what's remote and what's local

**Closed** 2023-02-09 22:04 UTC
Labels: needs response, image
