### ISSUE TITLE
🐛 BUG: dynamic routing is overwriting explicit page (should be the other way around)

### ISSUE THREAD

**Issue by schlichtanders** [withastro/astro#2560] opened 2022-02-09 11:47 UTC
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When using dynamic routing, the expected behaviour is that as soon as a page is both defined via an explicit page and via dynamic routing, the explicitly defined page should be taken.

* That is indeed also the case for `npm run dev` (hence I haven't noticed it on time)
* However it is the opposite for `npm run build && npm run preview`, which unfortunately is the one which gets deployed (and broke my website).

Hence this is crucial bug.

-----------
fails also on astro 0.21, 0.22, and 0.23 next, was working on astro 0.20

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5snnxg-ib612h?file=src/pages/index.astro

**Comment by tony-sull** [comment] 2022-02-09 12:25
This is a really interesting one!  `src/pages/[lang]/index.astro` is using `getStaticPaths()` to match both the `/en/` and `/de/` URLs, but that collides with the `src/pages/de/index.astro` route

`npm run dev` will match routes when the request comes in and it prioritizes `src/pages/de/index.astro` since it's a direct match.   `npm run build` is probably building both and keeping the last file it writes to `dist/de/index.html`

This can be worked around by removing `de` from the `getStaticPaths()` call, but it'd probably make sense if Astro was catching the duplicated paths in `build` and only building it once from the `src/page` template with the best match to the URL

**Comment by schlichtanders** [comment] 2022-02-09 12:58
The order that static routes should be priorized is the correct one which was there in astro 0.20 and is also documented on https://docs.astro.build/en/core-concepts/routing/#dynamic-routes

> Static routes without path params will take precedence over all other routes, and named path params over catch all path params. Take a look at the following examples:
> - pages/post/create.astro - Will match /post/create
> - pages/post/[pid].astro - Will match /post/1, /post/abc, etc. But not /post/create
> - pages/post/[...slug].astro - Will match /post/1/2, /post/a/b/c, etc. But not /post/create, /post/abc

**Comment by tony-sull** [comment] 2022-02-09 18:18
Thanks for the solid reproduction here @schlichtanders!  I just flipped this over to `Accepted`on our bug tracker so we can get this one tracked down and fixed

**Comment by schlichtanders** [comment] 2022-04-24 17:15
@tony-sull Any progress here? I guess this is quite simple to fix. It is the core bone for my internationalization. Would be great if this could be solved

**Comment by pointout** [comment] 2022-05-03 14:34
I am also struggeling with dynamic routes. This could be related (Astro v1.0.0-beta.20):
```
pages/[lang]/[...collections].astro
pages/[lang]/[about].astro         
```
`en/catalog/category` is working, but `en/catalog` not as it interfears with the [about].astro. I think it should not.
[https://stackblitz.com/edit/github-jufgs3-5prcke?file=src/pages/[lang]/[...collection].astro](https://stackblitz.com/edit/github-jufgs3-5prcke?file=src/pages/[lang]/[...collection].astro)

A second example:
```
pages/[lang]/[...catalog].astro
pages/[lang]/[...portfolio].astro
```
Here all in `[lang]/[...catalog].astro` is working, but nothing in `[lang]/[...portfolio]`. I also think this should be possible, as different params are used. 
[https://stackblitz.com/edit/github-jufgs3-q7xmxm?file=src/pages/[lang]/[...portfolio].astro](https://stackblitz.com/edit/github-jufgs3-q7xmxm?file=src/pages/[lang]/[...portfolio].astro)

**Comment by tony-sull** [comment] 2022-05-10 20:33
Marking this as "to be disucssed" mainly to make sure we align on the exact priority order for dynamic routes and document the full rules set, but this is definitely a priority before the 1.0 release!

**Comment by FredKSchott** [comment] 2022-05-12 21:58
Followup: we used to have this documented but it appears to have been lost to time. We intend to match SvelteKit's support as defined here, so we should document this on our own site AND make sure to fix any bugs where we deviate. Tests should be covering this already but we may not be as complete as needed.

https://kit.svelte.dev/docs/routing#advanced-routing-sorting

**Comment by pointout** [comment] 2022-05-18 10:20
Then my examples above are intended not work and correspond with the sorting. Sometimes it would help to structure the rules, if they would work.

**Closed** 2022-05-20 19:58 UTC
Labels: p4-important, s2-medium, routing
