### ISSUE TITLE
Middleware dependencies are incorrectly bundled

### ISSUE THREAD

**Issue by danielo515** [withastro/astro#10164] opened 2024-02-20 07:58 UTC
### Astro Info

```block
Astro                    v4.4.1
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/svelte       
```

### Describe the Bug

I am using a middleware to handle auth. In local dev mode, everything works as expected. However, when deployed to vercel, one of the imported constants becomes `noop` instead of being an array.

To give you an idea of how it looks.
Here is the original middleware

```ts
import { errors, jwtVerify, type JWTPayload } from "jose";
import { defineMiddleware } from "astro/middleware";
import { TOKEN, PUBLIC_ROUTES } from "./constants";

const secret = new TextEncoder().encode(import.meta.env.JWT_SECRET);

//... etc
```

Then, the constants files contains:

```ts
export const TOKEN = "token";
export const PUBLIC_ROUTES = [
  "/",
  "/login",
  "/api/login",
];
```

However, this is the generated middleware (part)

```js
import { jwtVerify, errors } from 'jose';
import './astro_BxjT5Sqv.mjs';
import { P as PUBLIC_ROUTES, T as TOKEN } from './prerender_BwN9fO_L.mjs'; //<- key part

// bla bla bla
```

And this is the file where PUBLIC_ROUTES is being imported from:

```js
const noop = () => {};
export const P = noop;
export const T = noop;
export const _ = noop;
export const a = noop;
export const b = noop;
export const c = noop;
export const d = noop;
export const i = noop;
export const l = noop;

```

### What's the expected result?

I expect the constants to be inlined in the generated middleware so it can properly work

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t5xhyw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-02-20 08:38
@danielo515, please replace the `Astro info` block with the information returned by the command `Astro info`. This information is vital to us so we can triage your issue.

**Comment by mikenicklas** [comment] 2024-02-20 11:05
I am seemingly running into this issue out of nowhere as well and I can't even run `astro info`.

```
mikenicklas@Mikes-MacBook-Pro fe % npm run astro info

> fe@0.0.1 astro
> astro info

6:02:24 AM [vite] Error when evaluating SSR module /Users/mikenicklas/Sites/Work/fe/astro.config.mjs:
|- ReferenceError: crypto is not defined
    at Module.netlifyIntegration (file:///Users/mikenicklas/Sites/Work/fe/node_modules/@astrojs/netlify/dist/index.js:16:30)
    at /Users/mikenicklas/Sites/Work/fe/astro.config.mjs:16:19
    at async instantiateModule (file:///Users/mikenicklas/Sites/Work/fe/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:54696:9)

[astro] Unable to load your Astro config

crypto is not defined
  Stack trace:
    at Module.netlifyIntegration (file:///Users/mikenicklas/Sites/Work/fe/node_modules/@astrojs/netlify/dist/index.js:16:30)
    at async instantiateModule (file:///Users/mikenicklas/Sites/Work/fe/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:54696:9)
```

**Comment by ematipico** [comment] 2024-02-20 12:24
> This project is heavily under development and yesterday everything was fine 🤷‍♂️

Does that mean that you updated some dependency?

**Comment by mikenicklas** [comment] 2024-02-20 12:29
@ematipico The only dependency change I made yesterday was via `npx astro add netlify`. When I tried deploying I ran into a very similar (maybe the same?) `crypto is not defined` bug in the netlify build logs. Found [this issue](https://github.com/withastro/astro/issues/7920) and was able to get it working. Everything was fine locally the rest of the da.

Then this morning I tried to `npx astro add @qwikdev/astro` and saw that error again.

**Comment by ematipico** [comment] 2024-02-20 12:59
It seems that the issue is around the vercel adapter. I tried with the node adapter, and the module is correctly kept in the source code. cc @lilnasy

**Comment by danielo515** [comment] 2024-02-21 12:42
> @danielo515, please replace the `## Astro info` block with the information returned by the command `astro info`. This information is vital to us so we can triage your issue.

As someone mentioned, I can't put the output of the command because I get an error about crypto not being defined.
I was initially using the netlify adapter, but because their SSR was very slow, I moved to vercel. I didn't removed the netlify yet, so that may be causing some conflicts, I am not sure.

**Comment by ematipico** [comment] 2024-02-21 13:16
It's possible you're running an old version of Node.js. What's your version?

**Comment by lilnasy** [comment] 2024-02-21 14:59
The error about `crypto` being undefined is fixed in astro 4.4.1.

I'm guessing you meant to place `src/ap/login.ts` in `src/pages/api/login.ts`, and in your real project you have non-prerendered routes as well, which makes the middleware run.

I see the issue with the node adapter as well. And it seems to be the same underlying bug as https://github.com/withastro/astro/issues/8596 - rollup crudely combining user-written modules and astro naively turning the entire combined chunk into no-ops.

**Comment by danielo515** [comment] 2024-02-21 15:13
> I'm guessing you meant to place `src/ap/login.ts` in `src/pages/api/login.ts`, and in your real project you have non-prerendered routes as well, which makes the middleware run.

Where are you seeing that route? login.ts is inded under `src/pages/api/login.ts`
<img width="347" alt="Screenshot 2024-02-21 at 16 11 58" src="https://github.com/withastro/astro/assets/2270425/98192c29-2849-47e7-8627-540cb027afa7">


> in your real project you have non-prerendered routes as well, which makes the middleware run.

Yes, I noticed that the middleware runs at build time, which is super weird and probably a bug on the hybrid mode.

**Comment by danielo515** [comment] 2024-02-21 15:15
```
➜ pnpm ls astro
Legend: production dependency, optional only, dev only

dependencies:
astro 4.3.7
```

> The error about `crypto` being undefined is fixed in astro 4.4.1.

How lucky I am 😂 can I update to 4.4.1? When was it released? my project is quite recent

**Comment by danielo515** [comment] 2024-02-21 15:18
Awesome, updating to astro 4.4 allows me to finally run astro info:

```
Astro                    v4.4.1
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

Not very useful information though, I could have told you that if you asked for my astro.config.mjs
Well, I guess one less problem! Now just need to fix the bundling one

**Comment by danielo515** [comment] 2024-02-21 15:33
@lilnasy reviewed my reproduction, and it is correct:
<img width="210" alt="Screenshot 2024-02-21 at 16 33 05" src="https://github.com/withastro/astro/assets/2270425/da0d27c0-e47d-4a2c-87fb-876f4d94f1ae">

**Comment by danielo515** [comment] 2024-02-21 15:37
Updated the reproduction to be correct @lilnasy 
You can check the  output doin this in the console
```bash
npm build
cat .vercel/output/functions/_render.func/.vercel/output/_functions/chunks/prerender_Li4whjEZ.mjs
```

**Comment by danielo515** [comment] 2024-02-21 15:38
> It's possible you're running an old version of Node.js and vercel adapter, and the polyfill isn't triggered. What's your version?

For completeness, here are all my versions:

```bash
dependencies:
@astrojs/check 0.5.4                  @lucia-auth/adapter-postgresql 3.1.0  jose 5.2.2                            tailwindcss 3.4.1                     
@astrojs/svelte 5.0.3                 @vercel/postgres 0.7.2                lucia 3.0.1                           typescript 5.3.3                      
@astrojs/tailwind 5.1.0               astro 4.4.1                           nanoid 5.0.5                          
@astrojs/vercel 7.3.1                 effect 2.3.6                          oslo 1.1.2                            
@effect/schema 0.62.8                 fp-ts 2.16.2                          svelte 4.2.10         
```

**Comment by danielo515** [comment] 2024-02-21 16:57
> > Yes, I noticed that the middleware runs at build time, which is super weird and probably a bug on the hybrid mode.
> 
> No, that's expected. In hybrid mode, static generation is run by default, and you have to opt-out if you want to have a route that needs to run in SSR.

But the middleware is something runtime specific, I don't see a reason to run it at build time, not even for static pages

**Comment by matthewp** [comment] 2024-06-17 17:36
Are people still having this issue? Noticed that https://github.com/withastro/astro/pull/10279 was made to address this, but the issue is still open. @danielo515 @mikenicklas ?

**Comment by ematipico** [comment] 2024-06-20 12:26
I am going to assume that's closed and fixed. Fee free to **open a new issue** if you experience a similar issue, because we recently refactored our bundling strategy.

**Closed by ematipico** 2024-06-20 12:26 UTC
Labels: needs response, - P3: minor bug

**Comment by ezriharmusial** [comment] 2024-08-26 20:41
Well it seems like I have similar issues related to my middleware. (Thanks for pointing me in this direction) Have been scouring the internet for a few days now, not finding any relatable problem to my issues. My middleware is used to set User session cookies, and runs fine in Dev mode, but not when building locally or in production.

I also use Oslo and Lucia like Daniel, but in combination with Astro:DB to store users and sessions, both my local build as the builds on netlify choke on dependencies needed by Astro:DB when generating my SSR functions. Once I remove the Middleware file and replace my Astro.locals with data, everything builds fine.

Is this issue related? Am I in the right thread? What do I do?

**Comment by ematipico** [comment] 2024-08-26 21:06
@ezriharmusial as per my last comment, please open a new issue with a minimal reproduction and instructions to reproduce it.

We will attempt to triage it and see how it goes. Thank you.

**Comment by ezriharmusial** [comment] 2024-08-26 21:10
Will do so. Thankyou.
