### ISSUE TITLE
Default setup on Windows

### ISSUE THREAD

**Issue by reinisg** [withastro/astro#6491] opened 2023-03-09 19:39 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

Hello, tried to find other topic about this bug, but didn't found.
So problem is if run `npm create astro@latest` i got error on second question and I don't know how to resolve it.

1. Running powershell with admin rights: [image1](https://i.ibb.co/gZc85Nx/astro1.png)
2. Running cmd with admin rights and added --verbose: [image2](https://i.ibb.co/VDVgg5w/astro2.png)

Could someone help to run this default command correctly?
As you also see have node v18 and npm v8.6

### Link to Minimal Reproducible Example

empty

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment] 2023-03-09 19:56
This looks like it's more related to your local npm / node setup? 

Do you mind posting this in the #support channel on Astro's discord?

**Comment by reinisg** [comment] 2023-03-10 06:18
> This looks like it's more related to your local npm / node setup?
> 
> Do you mind posting this in the #support channel on Astro's discord?

Thanks, for answering!
Yes, we can post there? What  I need to do? 
Ps what kind of details I need provide to better inspect this case?

**Comment by ematipico** [comment] 2023-03-10 13:46
> Yes, we can post there? What I need to do?

Open a new thread in support channel and explain what's your issue (maybe link this issue too)

> Ps what kind of details I need provide to better inspect this case?

It would be great if you could share the error you get, so we can understand the cause of the problem

**Comment by bluwy** [comment] 2023-03-13 09:43
Yeah I think moving this to the support channel would be the best move as you'll get more eyes there. We also only keep issues for identified bugs. Closing this for now.

**Closed by bluwy** 2023-03-13 09:43 UTC
