### ISSUE TITLE
🐛 BUG: Missing `serialize-javascript` package causing build to fail

### ISSUE THREAD

**Issue by zadeviggers** [withastro/astro#3467] opened 2022-05-28 08:54 UTC
### What version of `astro` are you using?

`astro`: `1.0.0-beta.36`
`@astrojs/solid-js`: `0.1.2`
`solid-js`: `1.4.3`

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When running a production build, I get an error about a package called `serialize-javascript`. I think it could possibly have something to do with SolidJS 1.4? I couldn't figure out for certain what was causing the error though, and I haven't been able to reproduce it in an online editor (it worked fine in both stackblitz and gitpod).
```
08:46:52 pm [build] Completed in 680ms.
 generating static routes 
 error   Cannot find package 'serialize-javascript' imported from C:\...\project\dist\entry.mjs
  Did you mean to import serialize-javascript@6.0.0/node_modules/serialize-javascript/index.js?
    at new NodeError (node:internal/errors:377:5)
    at packageResolve (node:internal/modules/esm/resolve:910:9)
    at moduleResolve (node:internal/modules/esm/resolve:959:20)
    at defaultResolve (node:internal/modules/esm/resolve:1174:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
```
Just installing `serialize-javascript` as a `devdependency` seems to fix the issue.

**Comment by retronav** [comment] 2022-05-30 06:04
Hi @zadeviggers, everything seems to work fine on my side, can you send a reproduction?

**Comment by coldino** [comment] 2022-05-30 14:02
This happens to me also, but only when I include `outDir: '../wwwroot'` in config.

**Comment by matthewp** [comment] 2022-05-31 18:40
You need to use `shamefully-hoist: true` for pnpm at the moment.

This is a dupe of https://github.com/withastro/astro/issues/2817 so closing.

**Closed by matthewp** 2022-05-31 18:40 UTC
Labels: framework-solid, bb:investigate
