### ISSUE TITLE
MDX cannot find entry point module '@astrojs/mdx/dist/server.js'.

### ISSUE THREAD

**Issue by awgeorge** [withastro/astro#12615] opened 2024-12-03 22:35 UTC
### Astro Info

```block
Astro                    v5.0.1
Node                     v22.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Safari

### Describe the Bug

1. Create a folder with a space eg. `Software Projects`.
2. `cd Software\ Projects`
3. `npm create astro@latest`
4. `cd {new astro project}`
5. `npx astro add mdx`
6. `npm run dev`

Fails with error described below.

```
➜  1. Projects npm create astro@latest
Need to install the following packages:
create-astro@4.11.0
Ok to proceed? (y) y


> npx
> create-astro


 astro   Launch sequence initiated.

   dir   Where should we create your new project?
         ./fast-fireball

  tmpl   How would you like to start your new project?
         A basic, minimal starter

  deps   Install dependencies?
         Yes

   git   Initialize a new git repository?
         Yes

      ✔  Project initialized!
         ■ Template copied
         ■ Dependencies installed
         ■ Git initialized

  next   Liftoff confirmed. Explore your project!

         Enter your project directory using cd ./fast-fireball 
         Run npm run dev to start the dev server. CTRL+C to stop.
         Add frameworks like react or tailwind using astro add.

         Stuck? Join us at https://astro.build/chat

╭─────╮  Houston:
│ ◠ ◡ ◠  Good luck out there, astronaut! 🚀
╰─────╯
➜  1. Projects cd fast-fireball 
➜  fast-fireball git:(main) npx astro add mdx
✔ Resolving packages...

  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭──────────────────────────────────╮
 │ npm install @astrojs/mdx@^4.0.1  │
 ╰──────────────────────────────────╯

✔ Continue? … yes
⠹ Installing dependencies...
✔ Installing dependencies...

  Astro will make the following changes to your config file:

 ╭ astro.config.mjs ─────────────────────────────╮
 │ // @ts-check                                  │
 │ import { defineConfig } from 'astro/config';  │
 │                                               │
 │ import mdx from '@astrojs/mdx';               │
 │                                               │
 │ // https://astro.build/config                 │
 │ export default defineConfig({                 │
 │   integrations: [mdx()]                       │
 │ });                                           │
 ╰───────────────────────────────────────────────╯

✔ Continue? … yes
  
   success  Added the following integration to your project:
  - @astrojs/mdx
➜  fast-fireball git:(main) ✗ npm run dev

> fast-fireball@0.0.1 dev
> astro dev

22:29:00 [types] Generated 0ms
22:29:00 [vite] Port 4321 is in use, trying another one...

 astro  v5.0.1 ready in 100 ms

┃ Local    http://localhost:4322/
┃ Network  use --host to expose

22:29:00 [content] Syncing content
22:29:00 [content] Astro version changed
22:29:00 [content] Clearing content store
22:29:00 [content] Synced content
22:29:00 watching for file changes...
22:29:01 Configuration file updated. Restarting...
22:29:01 [types] Generated 0ms
22:29:01 [vite] Port 4321 is in use, trying another one...
22:29:07 [ERROR] [vite] cannot find entry point module '/Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/@astrojs/mdx/dist/server.js'.
  Stack trace:
    at fetchModule (file:///Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:51151:13)
    at async handleInvoke (file:///Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:43947:22)
22:29:17 [vite] changed tsconfig file detected: /Users/awgeorge/Documents/1. Projects/fast-fireball/tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
22:29:18 Configuration file updated. Restarting...
22:29:18 [types] Generated 0ms
22:29:18 [vite] Port 4321 is in use, trying another one...
22:29:18 [ERROR] [vite] cannot find entry point module '/Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/@astrojs/mdx/dist/server.js'.
  Stack trace:
    at fetchModule (file:///Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:51151:13)
    [...] See full stack trace in the browser, or rerun with --verbose.
22:29:18 [ERROR] [vite] cannot find entry point module '/Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/@astrojs/mdx/dist/server.js'.
  Stack trace:
    at fetchModule (file:///Users/awgeorge/Documents/1.%20Projects/fast-fireball/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:51151:13)
    [...] See full stack trace in the browser, or rerun with --verbose.
```

### What's the expected result?

I should be able to load the website.

*WORKAROUND* Remove whitespace from parent folder

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ekoxs8?title=Astro%20Starter%20Kit:%20Basics
```
cd astro\ website
npm install && npm run dev
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by apatel369** [comment] 2024-12-04 05:41
I cannot access your reproduction. Please providea valid reproduction.

**Comment by ematipico** [comment] 2024-12-04 06:19
@awgeorge use stackblitz to provide a reproduction

**Comment by awgeorge** [comment] 2024-12-04 11:33
Doesn't look like stackblitz works. `npm i` fails with:

```
~/projects/withastro-astro-6e2m68
❯ npm install && npm run dev
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-12-04T11_16_46_034Z-debug-0.log
```

It appears that this issue occurs if a parent directory contains a space ` `. Astro 4 and the 5 beta were ok.

**Comment by awgeorge** [comment] 2024-12-04 11:55
Stackblitz works on chrome: https://github.com/stackblitz/webcontainer-core/issues/1402

https://stackblitz.com/edit/withastro-astro-ekoxs8?title=Astro%20Starter%20Kit:%20Basics
```
cd astro\ website
npm install && npm run dev
```

**Comment by ematipico** [comment] 2024-12-04 12:12
The issue is the folder with the space. This is a duplicate of https://github.com/withastro/astro/issues/12556

**Closed by ematipico** 2024-12-04 12:12 UTC
Labels: - P4: important, needs repro, pkg: mdx
