### ISSUE TITLE
Warning messages when reading cookies in middleware functions with hybrid output

### ISSUE THREAD

**Issue by RaphaelBossek** [withastro/astro#11756] opened 2024-08-17 08:09 UTC
### Astro Info

```block
Astro                    v4.14.2
Node                     v18.17.1
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             set-prerender
```

### If this issue only occurs in one browser, which browser is a problem?

Not a browser problem

### Describe the Bug

While reading cookies in middleware function result in following warning:

> [WARN] `Astro.request.headers` is unavailable in "static" output mode, and in prerendered pages within "hybrid" and "server" output modes. If you need access to request headers, make sure that `output` is configured as either `"server"` or `output: "hybrid"` in your config file, and that the page accessing the headers is rendered on-demand.

### What's the expected result?

No warning message.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/RaphaelBossek/astro-auth-middleware-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by cielorz** [comment] 2024-08-18 10:50
I think this issue would be same to #11751

**Comment by ematipico** [comment] 2024-08-18 11:16
@RaphaelBossek can you provide more context or reasons about why this is a bug?

In particular, please provide:
- instructions on how to reproduce the warning 
- which pages you're rendering

**Comment by RaphaelBossek** [comment] 2024-08-18 12:31
The advice is to change to output mode "hybrid" but I'm in "hybrid" mode.
I've applied an "working" example at https://stackblitz.com/~/github.com/RaphaelBossek/astro-auth-middleware-test with this warning, so your questions are answered within the short "code".  Could you pleaes precise your questions based on the Minimal, Reproducible Example.

**Comment by cielorz** [comment] 2024-08-18 13:15
I think this warning might brought by recent changes in astro action. Before ver 4.13.2 there is no warning when build.
________________________________

**Comment by hkbertoson** [comment] 2024-08-18 15:57
Its the same as https://github.com/withastro/astro/issues/11751 The error message was fixed at one point. But then got reintroduced at some point.

**Comment by bholmesdev** [comment] 2024-08-20 17:32
Hey @RaphaelBossek! Thanks for reporting. It seems that middleware runs on prerendered routes in development, which trips that warning log when accessing headers or cookies.

We have some Astro maintainers discussing how to expose whether a route is prerendered or not so you can check this from middleware. You can [join the discord](https://astro.build/chat) to discussion in #feedback-ideas! For now, you can safely ignore the warning.

**Comment by florian-lefebvre** [comment] 2024-09-18 13:53
It's available in 5.0 beta, you can use `context.isPrererendered`

**Comment by bholmesdev** [comment] 2024-09-23 08:28
`context.isPrererendered` is now supported! @RaphaelBossek can you try this API on the 5.0 beta and give us your feedback?

**Comment by mlafeldt** [comment] 2024-09-25 23:26
Looks like it's still called `_isPrerendered` ...

https://github.com/withastro/astro/blob/1720c5b1d2bfd106ad065833823aed622bee09bc/packages/astro/src/core/render-context.ts#L242

... and not officially part of the context yet.

https://github.com/withastro/astro/blob/1720c5b1d2bfd106ad065833823aed622bee09bc/packages/astro/src/actions/runtime/middleware.ts#L23

Apart from that, it works fine!

**Comment by florian-lefebvre** [comment] 2024-09-26 06:03
That's because the change is on the next branch

**Comment by ematipico** [comment] 2024-10-02 10:43
I just tried the user's reproduction, and I can't see the warning anymore when using `ctx.isPrendered`. 

Closing as completed

**Closed by ematipico** 2024-10-02 10:43 UTC
Labels: - P2: has workaround, feat: middleware
