### ISSUE TITLE
Type union causes build errors

### ISSUE THREAD

**Issue by altano** [withastro/astro#7991] opened 2023-08-08 07:34 UTC
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

Using a simple union for the Props type:

```ts
export type Props = {
	type: "face"
} | {
	type: "hat"
}
```

Causes this error:
```
12:33:11 AM [astro] reload /src/pages/index.astro
 error   Unexpected "|"
  File:
    /home/projects/github-b6qvcs/src/pages/index.astro:27:1
```

Might be related to https://github.com/withastro/compiler/issues/517

### What's the expected result?

no build errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b6qvcs?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-08-08 18:14
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed** 2023-08-08 18:14 UTC
Labels: - P3: minor bug
