### ISSUE TITLE
🐛 BUG: UnoCSS broken on production build

### ISSUE THREAD

**Issue by XiNiHa** [withastro/astro#4099] opened 2022-07-30 08:32 UTC
### What version of `astro` are you using?

1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macOS & Linux, both confirmed

### Describe the Bug

- Directly importing `uno.css` in `.astro` file / Importing `uno.css` from static framework components (framework components that are not used as an island)
  - Astro doesn't invoke the UnoCSS Vite plugin with `generateBundle()` hook by itself. This becomes problematic since UnoCSS relies on that hook to replace the hash placeholder with generated CSS rules.
  - I was able to identify the hash placeholder in the built CSS that should've been replaced.
  - When trying with SolidJS integration, `generateBundle()` only receives JS code in the bundle. Therefore the UnoCSS Vite plugin crashes for not finding any hash placeholders.
- Importing `uno.css` in inline `<script>` / Importing `uno.css` from an island (tried with SolidJS integration)
  - Generates a correct CSS file. However it's not imported. only `empty css` comment is present in the hoisted JS file.

The reproduction takes the first approach - directly importing `uno.css` in `.astro` file.

### Link to Minimal Reproducible Example

https://github.com/XiNiHa/astro-unocss-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

(only when somewhat enough guides are provided)

**Comment by FredKSchott** [comment] 2022-08-02 22:52
> Astro doesn't invoke the UnoCSS Vite plugin with generateBundle() hook by itself. This becomes problematic since UnoCSS relies on that hook to replace the hash placeholder with generated CSS rules.

Can you say more about this? I don't think we block `generateBundle()` from being called inside of Astro. Would love to help traige this to find the root issue!

**Comment by XiNiHa** [comment] 2022-08-03 00:07
> I don't think we block generateBundle() from being called inside of Astro.

That's very weird. I've verified that `generateBundle()` hook doesn't get called in SSR build by injecting `console.log()` in the UnoCSS plugin's hook. I believe you can also reproduce this with the one I've attached. Could it be a new change/bug in Vite 3? 🤔

**Comment by matthewp** [comment] 2022-08-03 18:48
@XiNiHa can you link me to the UnoCSS plugin's `generateBundle`? I'm going to debug this myself.

**Comment by matthewp** [comment] 2022-08-03 20:45
@XiNiHa If you mean this generateBundle hook: https://github.com/unocss/unocss/blob/8f3cd7cd1405a8ae1d08164b5eed26d64443bd70/packages/vite/src/modes/global/build.ts#L148

The reason it doesn't run is because the `apply` hook returns `false`, so Vite does not add the plugin to run. https://github.com/unocss/unocss/blob/8f3cd7cd1405a8ae1d08164b5eed26d64443bd70/packages/vite/src/modes/global/build.ts#L144

It's false because of this `!options.build?.ssr`. Astro sets options.build.ssr to `true`. Hope this helps.

**Comment by matthewp** [comment] 2022-08-03 20:46
Happy to continue helping you here. Keeping open for now.

**Comment by XiNiHa** [comment] 2022-08-04 00:39
I just tested with a monkey-patched version of UnoCSS Vite plugin (to make it only run on SSR) and that works great!

However, that's a bit awkward behavior to work with, since it is normal that something related to CSS to be considered as a clientside job. I've tried UnoCSS many times with something like `vite-plugin-ssr` and didn't have any issue there (since I've imported the `uno.css` root file in the client entry).

Therefore I guess we should decide between adding a new option to UnoCSS Vite plugin to make it run on SSR, or fixing the case on importing `uno.css` in an inline `<script>` tag. I feel the latter makes more sense(since enabling an option is also a thing that can be missed easily). What do you think about it?

**Comment by matthewp** [comment] 2022-08-04 12:06
For server-rendered apps, the CSS should be included in a `<link>` tag. So if you made it part of the client JS bundle it wouldn't be and you'd get FOUC problems. So what I would recommend is having the uno.css import be placed in the .astro files.

I would recommend creating an Astro integration, similar to our Tailwind one. This would allow the user to use uno.css without having to import it into each page themselves. See how tailwind automatically injects it here: https://github.com/withastro/astro/blob/7300f094fd2dab7dbf631d69c1bb3e38e603e7bb/packages/integrations/tailwind/src/index.ts#L77

Then all the user would have to do is:

__astro.config.mjs__

```js
import unocss from '@example/unocss';

export default {
  integrations: [unocss()]
};
```

**Comment by XiNiHa** [comment] 2022-08-05 01:08
Okay that sounds reasonable. I'll make an issue on UnoCSS repo to create a new option for enabling CSS generation on SSR mode. Not sure about the integration - should I host it by myself? or are you guys open to accepting a PR for it?

**Comment by AllanChain** [comment] 2022-08-05 03:30
@XiNiHa Does this integration meet your needs? https://github.com/AllanChain/astro-uno

**Comment by XiNiHa** [comment] 2022-08-05 04:13
@AllanChain Oh that's right! I completely missed that your integration provides forced run of UnoCSS in SSR! I guess that's the one I need :D
I hope your extension gets promoted as an official recommendation.

**Comment by matthewp** [comment] 2022-08-05 13:51
Great to hear. @AllanChain I would recommend using the ` injectScript('page-ssr')` code snippet posted above which would prevent users from needing to import uno themselves in each page. Otherwise it looks great!

We have a page for integrations here: https://astro.build/integrations/

Here are the steps to get yours added: https://docs.astro.build/en/guides/publish-to-npm/#integrations-library

Glad to see that this issue is resolved. Going to close this issue, thanks everyone!

**Closed by matthewp** 2022-08-05 13:51 UTC
Labels: p4-important, s1-small

**Comment by aspiiire** [comment] 2022-10-31 16:15
I'm sorry to re-open this issue, but It doesn't seem to be solved. I also have a lot of issues and UnoCSS, after using @AllanChain's package things seems to work. But many times it seems that while building for production it is not able to find many classes or breakpoints. It's really weird and strange with no predictable behaviour. 

Do someone have any solution to that? I use SSR as well with node

**Comment by AllanChain** [comment] 2022-11-01 00:38
> But many times it seems that while building for production it is not able to find many classes or breakpoints. It's really weird and strange with no predictable behaviour.

Everything works well on my side with SSG. Do you have the same problem in SSG mode? Can you provide a minimal reproduction?

BTW UnoCSS also provides an official Astro integration. You may also try that in case I did something wrong in my integration. Although they should differ only in the way handling some atrributify-related stuff.

**Comment by aspiiire** [comment] 2022-11-02 08:57
I'll try to put up a minimal reproduction! 

I have already tried the UnoCSS integration, but it doesn't even build for production! that's why I have used your integration that works.

What I do is you astro build, and serve the files with express.static, first dist/client then the ssrHandler that's inside the dist/server folder.

Inside the .astro files I use Vue, and I found out that the problem I had was due to the fact that I was using client:only="vue" how I should handle it if I want to allow only the client to load the content in some components?
