### ISSUE TITLE
[astrojs/lit] web components don't adopt SSR'd DSD from view-transitions

### ISSUE THREAD

**Issue by hrmcdonald** [withastro/astro#9953] opened 2024-02-02 17:39 UTC
### Astro Info

```block
Astro                    v4.2.8
Node                     v18.19.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/lit
                         @astrojs/mdx
                         @astrojs/react
```

### Describe the Bug

Our design system is built with Lit web components. Our docs site is built with Astro. We use the `@astrojs/lit` plugin to SSR all our components on pages and it works great.

However, recently we have been testing out Astro's newer view-transition functionality and we noticed a major issue going on here that is blocking us from adopting this functionality right now.

While the initial page load works as expected, any SSR'd web components loaded in a view-transition do not adopt their SSR'd shadow root. I was pointed to the fact that the browser's declarative shadow DOM parsing [only runs during HTML parsing](https://developer.chrome.com/docs/css-ui/declarative-shadow-dom#parser-only). I don't know enough about view-transitions or how Astro handles them to be able to know if this is why these DSD roots are not getting adopted properly. Is this a browser bug? Should or could it be handled by Astro?

### What's the expected result?

In the example I have linked below, I have created a very simple Astro site with two pages, a web component on each, and view transitions enabled.

The first page you load (can be either one) everything parses and renders as expected. But once you click the link to transition in the other page, you will notice the second page's web component link does not render correctly. It is there, but it has not adopted its SSR'd shadow DOM and thus the link on the second page is not visible.

Initial load:
<img width="666" alt="image" src="https://github.com/withastro/astro/assets/39349270/695317df-828a-48ba-b935-84d9031115da">

Page when loaded via view-transition:
<img width="668" alt="image" src="https://github.com/withastro/astro/assets/39349270/e210ea05-bc1b-43c6-883e-4c9f255a2d10">

Ideally, we want web components loaded during a view transition to get parsed like normal so they adopt their DSD. Otherwise we can't really utilize view transitions with SSR'd web components.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/edit/withastro-astro-ytwbdv?file=src%2Fpages%2Findex.astro&title=Astro%20Starter%20Kit:%20Blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment] 2024-02-03 08:23
Hi @hrmcdonald, thank you for opening this issue!

It looks like we are not putting the template in the shadowRoot when we parse the new DOM from the file.

**Comment by martrapp** [comment] 2024-02-03 12:27
The problem only seems to occur in development mode. 
@hrmcdonald, could you please check/confirm if it works for you with build/preview?

**Comment by martrapp** [comment] 2024-02-06 16:36
Preliminary analysis: For view transitions, we load the DOM with `DOMParser.parseFromString()`. No special attention is paid to templates and we have no special handling for shadowRoots. At first I thought that DSD support was simply missing, but then I got confused by the fact that it works with `astro build`. Maybe it's just a matter of re-initializing after swap. To be continued ...

**Comment by augustjk** [comment] 2024-02-06 17:19
FYI declarative shadow DOM won't be parsed with `DOMParser.parseFromString()`. Chrome shipped the ability to do so with a `{includeShadowRoots: true}` option passed in but it was before the spec was finalized. The correct way to parse string to a document while also letting the browser parse and attach the declarative shadowroots would be to use `Document.parseHTMLUnsafe()` which was added to the spec here https://github.com/whatwg/html/pull/9538.

If you don't need an entire document and would like something similar to setting `.innerHTML` that also parses DSD, `Element.prototype.setHTMLUnsafe()` has also been added to the spec.
Here's an example of it in use with a feature detection and fallback to a ponyfill: https://github.com/lit/lit/blob/31c181a8a225b807719a3e52b980bf02dcb64255/packages/labs/testing/src/lib/fixtures/ssr-fixture.ts#L75-L86

Currently the unsafe HTML methods are available in the recently released Firefox 122, and soon to come Safari 17.4 (currently available in Safari Technology Preview). Chrome is in the process of implementing.

**Comment by martrapp** [comment] 2024-02-06 17:43
Hey @augustjk!

Thank you so much for your detailed explanation and advice! I really appreciate it!

**Comment by hrmcdonald** [comment] 2024-02-06 18:31
Actually, when inspecting the production build a bit closer, I don't think things are working as expected still. It seems that in a prod build for some reason the web components are just re-initializing themselves properly where they don't in dev. However, they still don't seem to be properly adopting their DSD template. 

The stackblitz example is simple enough that it looks OK on the surface, but for anything more complex this still leads to a lot of issues.

**Comment by hrmcdonald** [comment] 2024-02-11 19:56
I updated the repro stackblitz to use `link` instead of `href` as a prop. I'm not sure what to recommend as the best path forward though from here. We can hold off on utilizing view transitions until browser support is better here.

**Comment by martrapp** [comment] 2024-02-11 20:45
That at least changed the error message for href to link. ;-)
![image](https://github.com/withastro/astro/assets/94928215/02e30638-ba36-4e9e-a33e-608217e36c64)
I am afraid that as long as there are uncaught exceptions in the browser console, they will prevent the shadow root from initializing correctly. I have no experience with lit and can't really help with fixing the lit problem. To get rid of the original error, I simply deleted the `@property() href: string;` and hardcoded the href in the anchor. But then the issue disappeared for me too. 

Please help me with a reproduction that does not throw errors in the browser console during loading or view transitions.

**Comment by martrapp** [comment] 2024-02-11 21:06
Please note that the uncaught error also occurs independently of view transitions.
If `<ViewTransitions />` is removed from Base.astro, the error will show up on page load.   
So it's not so much a question of missing browser support for view transitions, but we should figure out how to fix the basic lit problem here.

**Comment by martrapp** [comment] 2024-02-14 17:46
@hrmcdonald here is the stackblitz for a minimal reproducible example that works for me.
https://stackblitz.com/c/edit/withastro-astro-wmttqt?file=src%2Fcomponents%2Fmy-custom-button.js&title=Astro%20Starter%20Kit:%20Blog
It doesn't throw errors, sets the shadow DOM, and shows working view transitions.
Testes on Chrome Version 121.0.6167.185 (Official Build) (64-bit).

Does that work for you, too?
Do you see any further issues?

**Comment by martrapp** [comment] 2024-02-19 15:20
@hrmcdonald I'm closing this issue now as there was no further response. Please feel free to reopen it at any time if you gain new insights.

**Closed by martrapp** 2024-02-19 15:20 UTC
Labels: needs response, feat: view transitions

**Comment by hrmcdonald** [comment] 2024-02-26 19:29
Sorry for the delayed response here @martrapp. I don't know why the error you called out is getting thrown with decorator properties in the example, but even in your fixed example, while it looks like things are working properly, the web component is not initializing properly. Its SSR template shadow root is not getting properly adopted:

<img width="517" alt="image" src="https://github.com/withastro/astro/assets/39349270/1065d42e-d6c7-4d56-841e-7f2be1821ecf">

See how the SSR'd declarative shadow dom template is still orphaned here. It looks like the web component is just initializing from scratch instead of adopting the SSR'd shadow dom template like it should.

We recently updated to Astro 4.x and are actually noticing this in production now even without view transitions at all on some initial loads:

<img width="417" alt="image" src="https://github.com/withastro/astro/assets/39349270/b8898170-2cb4-41ce-9fe0-6506f6867274">
<img width="417" alt="image" src="https://github.com/withastro/astro/assets/39349270/aa2198bb-ff76-41a0-93e4-cd01911b12ec">

Usually, when this occurs a refresh of the page fixes this so it almost seems like a timing issue? We cannot reproduce this locally in dev builds either. Here's what the same portion of the DOM looks like when the templates are properly adopted:

<img width="417" alt="image" src="https://github.com/withastro/astro/assets/39349270/c3bfc87f-1e0c-4ec8-8047-14c37892500b">

**Comment by hrmcdonald** [comment] 2024-02-26 19:34
I think the second half of that last comment is likely a different issue. I'll open up a separate issue for that.
