### ISSUE TITLE
🐛 BUG: Bundled JS generated from "@astrojs/lit/client-shim.js" is added in every build even if Lit is actually not used

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#3025] opened 2022-04-07 18:07 UTC
### What version of `astro` are you using?

1.0.0.beta-3

### What package manager are you using?

pnpm

### What operating system are you using?

Zorin OS (Ubuntu)

### Describe the Bug

I have installed all the six integrations for framework components but I'm not using any one of them. But a script tag is still added to every generated page both in dev and production. The `<script>` tag is adding a bundled shim from  `"@astrojs/lit/client-shim.js"`. I think the JS should only be added if I actually use any Lit components.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/condescending-sea-ublfn6

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment] 2022-04-11 05:00
This is a known limitation, since polyfills are applied regardless of usage.

This most likely won't get prioritized by core maintainers until post v1.0. If anyone would like to help implement, I'm happy to help point in the right direction.

**Comment by matthewp** [comment] 2022-10-06 21:03
We always bundle these things even if they are not used. However they are not actually added to the page unless you use a component that needs them. Closing as this is not a bug.

**Closed by matthewp** 2022-10-06 21:03 UTC
Labels: s2-medium, p2-nice-to-have
