### ISSUE TITLE
astro image with squoosh fails with `UnknownViteSSRError` when `quality` is not an integer

### ISSUE THREAD

**Issue by jeppe-smith** [withastro/astro#5276] opened 2022-11-02 08:33 UTC
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Build fails when you set `quality` as a string on `<Image />` when using Squoosh with a non descriptive error message. `yarn dev` works just fine so it's just `yarn build`. If you use sharp you get a useful error message.

Example:
```astro
<Image
  src="/hero.webp"
  alt="descriptive text"
  format="webp"
  width="1920"
  aspectRatio="4:3"
  quality="80"
/>
```

Using Squoosh on build: `UnknownViteSSRError`

Using sharp on build: `Expected integer between 1 and 100 for quality but received 80 of type string`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eom1wu?file=src%2Fpages%2Findex.astro,astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2022-11-02 10:53
Thank you for reporting this! I think this is caused by recent changes I made. I'll take a look!

**Comment by wulinsheng123** [comment] 2022-11-04 15:08
> Thank you for reporting this! I think this is caused by recent changes I made. I'll take a look!

Could u tell me what change you did ？

**Comment by wulinsheng123** [comment] 2022-11-04 15:08
> > Thank you for reporting this! I think this is caused by recent changes I made. I'll take a look!
> 
> Could u tell me what change you did ？

I want to try to fix this bug☺️

**Comment by Princesseuh** [comment] 2022-11-04 15:20
Hey, the fix for this will be included in the work I'm doing on improving errors this week. I should have a PR up for it today, so no need to tackle this! 

Nonetheless, thank you very much for contributing to Astro!

**Closed** 2022-11-09 15:53 UTC
Labels: p3-minor-bug, s1-small, error message
