### ISSUE TITLE
Styles are added to head in wrong order in prod

### ISSUE THREAD

**Issue by IanVS** [withastro/astro#5462] opened 2022-11-23 20:45 UTC
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I got bitten by a really strange error when trying to add a new page to our site.  The hamburger button in the top nav started showing up in desktop sizes, but only in production builds.  I traced it down to an issue in the order that styles were being added to the `head`, global styles were being added _after_ component styles.  I've created as minimal of a reproduction that I could, hopefully it's helpful.  

I've noticed a lot of times where the styles in dev don't match production, which is pretty concerning, so I'm hopeful that this reproduction can expose an issue that can be solved and might help bring dev and prod builds more into line.

### Link to Minimal Reproducible Example

https://github.com/IanVS/astro-style-order-reproduction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by prodkt** [comment] 2022-11-23 22:14
Happening to us as well! Watching in case we can provide additional detail as a discussion around this continues.

**Comment by wulinsheng123** [comment] 2022-11-25 02:16
![image](https://user-images.githubusercontent.com/27261522/203886718-90c48f31-7969-482c-9e6b-db23d0cb5a3a.png)
Help me check out

**Comment by IanVS** [comment] 2022-11-25 02:31
@wulinsheng123 thanks for taking a look, I just tested again in a fresh `git clone`, and the button is green for me.  What is the `Simple Browser` that you're opening this in?  The URL looks strange.  What happens if you open `http:localhost:3000` in firefox or chromium?

**Comment by wulinsheng123** [comment] 2022-11-25 06:07
I used `gitpod` that online editor, to open your project.
It runs on Chrome

**Comment by IanVS** [comment] 2022-11-25 14:03
Did you try cloning the project and building it locally, without gitpod?

**Comment by jasikpark** [comment] 2022-11-28 04:58
<img width="1624" alt="Screenshot 2022-11-27 at 10 57 41 PM" src="https://user-images.githubusercontent.com/10626596/204197274-e33a899f-aac4-4d9d-b27e-7b532a6f3023.png">
looks like it doesn't reproduce for me on gitpod either?

**Comment by IanVS** [comment] 2022-11-28 05:10
@wulinsheng123 @jasikpark can either of you reproduce in a standard environment?  Running in gitpod could be a confounding factor.

**Comment by wulinsheng123** [comment] 2022-11-28 06:24
I will try late. Recently I have had a little busy

**Comment by wulinsheng123** [comment] 2022-11-28 08:23
> @wulinsheng123 @jasikpark can either of you reproduce in a standard environment? Running in gitpod could be a confounding factor.

![image](https://user-images.githubusercontent.com/27261522/204228627-81aafb2c-d2d4-4423-a5fb-add453120086.png)

same

**Comment by IanVS** [comment] 2022-11-28 12:51
Thanks, there must be some tricky caching going on in my end.  Rats.  This is a tough one to reproduce.

**Comment by IanVS** [comment] 2022-11-28 15:39
OK, After some more work, I found that adding postcss/autoprefixer causes the issue to reproduce.

To break caching, it's necessary to change the project folder name, and rebuild.  And I've been using `npx http-server dist -p 8085` to launch in a fresh port, since it's not possible to specify the port when using `astro preview`.

Would y'all mind pulling the latest commit from my reproduction (maybe clone it into a new folder?) and trying again?

**Comment by jasikpark** [comment] 2022-11-28 16:45
> @wulinsheng123 @jasikpark can either of you reproduce in a standard environment?  Running in gitpod could be a confounding factor. 

i would expect gitpod to be amenable to a local linux build since it's a full remote box rather than something esoteric like stackblitz, tho ig it's always good to remove confounding variables

**Comment by jasikpark** [comment] 2022-11-28 18:14
![image](https://user-images.githubusercontent.com/10626596/204350508-200624fe-3f53-4b2f-b461-8d6bbb8fccc8.png)

was able to reproduce with the commit that contained autoprefixer and postcss

**Comment by wulinsheng123** [comment] 2022-11-29 06:40
> ![image](https://user-images.githubusercontent.com/10626596/204350508-200624fe-3f53-4b2f-b461-8d6bbb8fccc8.png)
> 
> was able to reproduce with the commit that contained autoprefixer and postcss
> 
> https://pr.new/https://github.com/IanVS/astro-style-order-reproduction

Do you copy his code directly into the Stackblitz?
My computer also can't replicate it.

**Comment by wulinsheng123** [comment] 2022-11-29 07:13
OK, I got it. Why happens in production

**Comment by wulinsheng123** [comment] 2022-12-02 07:12
I need some clarification.
The first picture was correct; we didn't change anything.
 ![image](https://media.discordapp.net/attachments/1042631983425126422/1048079367571521616/image.png)
The second picture was wrong; also, we kept everyone the same. 
 ![image](https://media.discordapp.net/attachments/1042631983425126422/1048079367919652864/image.png)

The primary reasons will cause this bug. I found it. 
Rollup's bundled result was in the wrong order because three pages(index, beta, admin files) build once, but the common file CSS `global.css` was used in a different `.astor` file, and then that would build late.
I haven't a better idea about this bug.
@matthewp Could you give me some suggestions?

**Comment by jasikpark** [comment] 2022-12-06 17:41
Thanks for the tip about global css too @matthewp - setting up import sorting to always throw the Layouts and MainHead at the top of our imports has mostly fixed the global css cascade problem

**Comment by matthewp** [comment] 2022-12-06 20:29
So the issue here is that the sort order only takes into account the order within the page component. I think what it should be is a sum of all sort orders from each module going all the way down. Will try and see if that can fix it.

**Comment by matthewp** [comment] 2022-12-06 20:34
That does indeed fix it, let me see if I can turn this example into a test.

**Comment by matthewp** [comment] 2022-12-06 20:54
Fix is in https://github.com/withastro/astro/pull/5549

**Closed** 2022-12-06 22:12 UTC
Labels: p4-important
