### ISSUE TITLE
Local Fonts for CJK Languages won't load

### ISSUE THREAD

**Issue by GoldenSoju** [withastro/astro#6308] opened 2023-02-19 08:33 UTC
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I have troubles loading local fonts for Chinese, Japanese or Korean, while local fonts for English work totally fine.

I thought this might be due to tailwindCSS, but it also happens in a Astro-only project.
I created a [Github Repo](https://github.com/GoldenSoju/astro-cjk-fonts),
it is also accessible via [StackBlitz](https://stackblitz.com/edit/github-vfi2us?file=src/pages/index.astro).

As seen below, the text should appear as in the image below each line.
So while this works fine for English, CJK languages always get loaded in their fallback fonts.
I tried with different formats (OTF/TTF) and different fonts but so far nothing worked.

![cjk-fonts-astro](https://user-images.githubusercontent.com/42365471/219937367-a14b07a4-0ac2-4f94-9081-29ffe632e8e2.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vfi2us?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment] 2023-02-19 16:41
Seeing in your reproduction that you didn't import the `global.css` file in your layout, that's very likely the issue. Let me know if doing that works

**Comment by GoldenSoju** [comment] 2023-02-20 02:14
@MoustaphaDev 
Oh...
Thanks, that indeed solved the problem for the astro-only example.
But I cannot get the tailwind example working.
Is there something missing in [the docs](https://docs.astro.build/en/guides/fonts/) maybe?

Example:
[StackBlitz](https://stackblitz.com/edit/github-12mvza?file=src/pages/index.astro)

**Comment by bluwy** [comment] 2023-02-20 08:40
The stackblitz example seems to be working for me. The text is correctly rendered with the custom font. Closing this for now as it seems Astro is working fine.

**Closed by bluwy** 2023-02-20 08:40 UTC

**Comment by bluwy** [comment] 2023-02-21 09:05
I'm using MacOS to test it.
