### ISSUE TITLE
`astro check` reports function as unused import when inside `return` statement of Astro file

### ISSUE THREAD

**Issue by omothm** [withastro/astro#7315] opened 2023-06-06 19:52 UTC
### What version of `astro` are you using?

2.6.0

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When an imported function is used within the `return` statement of an Astro file (for redirection), `astro check` reports that the imported symbol of that function is unused.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-55brpm?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-06-06 20:40
Duplicate of https://github.com/withastro/language-tools/issues/476

**Closed by Princesseuh** 2023-06-06 20:40 UTC

**Comment by omothm** [comment] 2023-06-07 17:56
Thanks for pointing out the duplicated issue. It looks like this issue was duplicated multiple times, probably because the existing one is under a different repository. I suggest keeping at least one duplicate open under this repository to prevent further duplicates from showing up again and again.
