### ISSUE TITLE
Chakra UI Causes Invalid Hook Call in Astro

### ISSUE THREAD

**Issue by JeffMusgrave** [withastro/astro#4396] opened 2022-08-19 22:25 UTC
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

NPM

### What operating system are you using?

Mac / Windows

### Describe the Bug

When using Chakra-UI (and the react renderer), Astro throws: 

`Warning: Invalid hook call. Hooks can only be called inside of the body of a function component.`

The page still renders, but none of the chakra components render correctly.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/inspiring-kalam-e58mx1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-09-04 08:47
I believe this is a duplicate of #4220. Closing in favor of it!

**Closed by bluwy** 2022-09-04 08:47 UTC
