### ISSUE TITLE
Diagnostic hints flag variable as unused incorrectly

### ISSUE THREAD

**Issue by Cherry** [withastro/astro#7239] opened 2023-05-29 16:49 UTC
### What version of `astro` are you using?

2.5.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

```js
const url = 'https://google.com';
return Response.redirect(url, 302);
```

A simple page like this will throw an invalid diagnostic hint like:
```
❯ astro check
05:46:42 PM [check] Checking files
05:46:43 PM [content] No content directory found. Skipping type generation.
✔  Getting diagnostics for Astro files in /home/projects/github-cxqzsf/…
05:46:44 PM [diagnostics] 
 /home/projects/github-cxqzsf/src/pages/example.astro:2:7 Hint: 'url' is declared but its value is never read.
01  ---
02  const url = 'https://google.com';
          ~~~
03  return Response.redirect(url, 302);

05:46:44 PM [diagnostics] Result (4 files): 
- 0 errors
- 0 warnings
- 1 hint

```

To reproduce:
- Visit stackblitz repro example
- Run `astro check`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cxqzsf?file=src%2Fpages%2Fexample.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-05-29 18:31
Duplicate of https://github.com/withastro/language-tools/issues/476

**Closed by Princesseuh** 2023-05-29 18:31 UTC
