### ISSUE TITLE
Assets Images not showing when running in Docker container with Node

### ISSUE THREAD

**Issue by xriter** [withastro/astro#7819] opened 2023-07-26 14:23 UTC
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS 13.4.1

### What browser are you using?

Safari

### Describe the Bug

So I am trying to run my Astro site inside a Docker container using node. Everything works fine, EXCEPT images using the Assets implementation.

(See the code in this repo: https://stackblitz.com/edit/github-ocszci)

✅ Images show up fine when in:
`npm run dev` mode
`npm run build && npm run preview` mode
(so not inside a docker container)

🔥 But _not_ when ran **inside a Docker container** (update: where the public Docker port (e.g. 8007) doesn't match the Astro port inside the container (e.g. 3000)).
Then the `_image?href=...&q=high&f=webp` path returns 404.
Build and run using: `sudo docker compose up -d --build`.

The error logs don't show anything. The files when build are all there. So why does `/_image` give 404?

What is going wrong here? Is this is a bug, or am I missing something?

<img src="https://github.com/withastro/astro/assets/70454441/afad4074-eba7-46d8-b45b-2107db789665">

### What's the expected result?

The images to work, also when the public Docker port and the internal Astro port don't match.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ocszci

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-07-27 10:28
Closing as duplicate of https://github.com/withastro/astro/issues/6128

The code in that endpoint is really annoying, but it kinda has to be this way due to SSR.. I'm not sure yet how we could make it more reliable. Probably by reading some parts from the Astro config, I'd assume..

**Closed by Princesseuh** 2023-07-27 10:28 UTC
Labels: - P4: important, feat: assets
