### ISSUE TITLE
onTouchStart not being attached to DOM elements when using jsx

### ISSUE THREAD

**Issue by bitobeats** [withastro/astro#10851] opened 2024-04-23 04:24 UTC
### Astro Info

```block
Astro                    v4.6.3
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

When creating a React or Solid component with jsx and writing:

```typescript
function MyComponent() {
  return <div onTouchStart={() => {console.log("foo")})> bar </div> 
}
```

The event handler is not added to the DOM both using `pnpm dev` and `pnpm build` + `pnpm preview`.

I can see in my dist folder that indeed the code for the event exists. But somehow it's not being added to the DOM.

### What's the expected result?

The event should be attached to the correct DOM element.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s1yqym?file=src%2Fcomponents%2FCounter.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-04-23 05:37
Where is `onTouchStart` coming from? Is it something about view transitions? I couldn't find anything in the documentation

**Comment by Princesseuh** [comment] 2024-04-23 08:10
`onTouchStart` is the React equivalent of `touchstart`

**Comment by matthewp** [comment] 2024-04-23 12:29
Seems to be working here, what am I missing?

https://github.com/withastro/astro/assets/361671/7406012f-d38e-4937-bf3c-c80a0d42b633

Also, this is very unlikely to have anything to do with Astro. Astro just renders the React component. Any unexpected behavior once that happens is probably either a misuse of their APIs or a React bug. In any case, this seems to be working as you'd like.

I think you probably want to use `useCallback` here to prevent adding/removing event listening every time that event fires. Maybe there's something going on where the event listener is removed too quickly causing the log not to occur and that's what you're experiencing, just a guess though.

**Comment by vitorrloureiro** [comment] 2024-04-24 00:37
After more research I realized React attaches event listeners to React root, not to the element themselves. 

So in Astro's case the events are attached to <astro-island>. By itself this is is not a problem since a setup with Vite + React works fine.

The mystery for me right now is why Astro React output + Safari isn't working.


Also, super easy to reproduce. Just spawn an Astro project, create a React component with an `onTouchStart` listener and use Safari's Simulator (Command + Control + R then select an iOS device) and you'll see.
Or if you have an iPhone just `pnpm dev --host` it check on the phone.

I have a workaround for my own case right now (adding event listeners directly using ref) so please don't consider this post a support post. I'll keep on eye on this issue and will report back if I have new findings...

**Comment by vitorrloureiro** [comment] 2024-04-24 00:53
Ok, I double checked everything in a real device and the issue **is** consistent. So again I'm tending to believe this is not on my side.

What I realized, though, is that after I add an event listener directly (via `ref.current.addEventListener()`) the `onTouchStart` event attached to the component starts to get passed as well. Super super weird.

It sounds to me like it could be related to the way hydration is happening... Is it possible?

**Comment by matthewp** [comment] 2024-04-24 12:33
I'm not sure. This just seems very unlikely to be related to Astro. Please keep investigating and let us know.

**Comment by vitorrloureiro** [comment] 2024-04-24 21:58
My argument for that being related to Astro comes from the fact that it doesn't happen when using Vite + React (without Astro). Also that it happens in every Astro template I tried (including "blank").


I'll understand if that's not enough and you rather close this issue (although in my opinion this is a rather serious bug). No worries. 

If you think it's valid to investigate more: 

Can you please check in your end (using Safari + simulator or an iOS device) if you have the same bug? (should be super quick to test. Like 3 minutes)

This way we can discard this is a problem on my end.


Thanks for the attention!

**Comment by matthewp** [comment] 2024-05-13 18:07
I'm not going to be able to investigate. If you can make a reproduction that removes React from the equation then please post a new issue with that. Thank you and good luck.

**Closed by matthewp** 2024-05-13 18:07 UTC
Labels: needs triage

**Comment by bitobeats** [comment] 2024-05-13 18:23
I can't understand how removing react from equation makes sense considering the problem is the react integration...

Anyway, I'd keep investigating if I could validate the problem is not only on my side. Since I can't, I'm giving up as well.

Thank you and good luck.

**Comment by 2wheeh** [comment] 2024-07-05 07:39
Now I'm facing same issue. `onTouchStart` is not hydrated on production, safari.

It works after refresh but on the first load, it doesn't.
