### ISSUE TITLE
CSS updates require a dev server restart in Starlight

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro#9794] opened 2024-01-23 19:24 UTC
### Astro Info

```block
Astro                    v4.2.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```
### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

When updating CSS inside Starlight components, the styles do not update until the dev server is restarted. Reloading the page does not fix the issue, only fully restarting the dev server does.

This has been going on in Starlight since Astro 4.0.0.

### What's the expected result?

For the CSS to update

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-trknvj?file=src%2Fcomponents%2FMyComponent.astro (change red to blue to see no changes)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by heycassidy** [comment] 2024-01-26 05:49
I am also seeing this same issue outside of Starlight with MDX components in a content collection. Here's a reproducible example: https://stackblitz.com/edit/github-1sy2xt?file=src%2Fcomponents%2FMyComponent.astro

**Comment by 0livare** [comment] 2024-01-28 18:10
I am also seeing this behavior with MDX components.  With CSS modules, SCSS, and SCSS modules.

The CLI does pick up that the file was changed, but doesn't update the CSS contents:
```bash
12:03:27 [watch] /src/foobar.scss
```

Interestingly, I noticed that if the component is included both in the MDX & directly in the `.astro` file, then the css **WILL** update.

**Comment by fisherfrontier** [comment] 2024-02-01 05:47
Seeing the same issue in MDX files (opened #9917).

**Comment by hippotastic** [comment] 2024-02-02 12:51
The issue also seems to happen when changing the styles inside of Vue components used on a regular `.astro` page. We just had a user on Discord report this.

**Comment by Princesseuh** [comment] 2024-02-02 13:21
Bumping this issue to a p5 since it seems to be affecting more and more people, unusually.

**Comment by spacedawwwg** [comment] 2024-02-02 13:22
> The issue also seems to happen when changing the styles inside of Vue components used on a regular `.astro` page. We just had a user on Discord report this.

It's worth noting that the Vue component in question is imported from an external package in my monorepo

**Comment by matthewp** [comment] 2024-02-02 22:20
This PR contains what I think is the fix: https://github.com/withastro/astro/pull/9956

I tested it against @heycassidy's reproduction. I haven't tested against Starlight projects but I think it is the same issue. 

There's a preview release you can try with `npm install astro@experimental--cc-hmr`. If a few people can try and report your findings in that PR I would appreciate it, thanks.

**Comment by matthewp** [comment] 2024-02-02 22:34
I tested it against the OP Starlight reproduction and it fixes that too.

**Comment by hippotastic** [comment] 2024-02-02 22:37
I tested it on Windows using PNPM, both in the Expressive Code monorepo, as well as in a freshly set up Starlight project, and everything worked flawlessly. I can even edit the Code component imported from my linked monorepo package live while viewing the site and any changed styles get picked up immediately. Great job!

**Comment by hippotastic** [comment] 2024-02-03 09:13
Please note that I did not test the Vue scenario reported by @spacedawwwg, which didn't even involve MDX if I understood it correctly. As the fix description seems to be focused on MDX, we might need another fix for this variant of the issue as well.

**Comment by matthewp** [comment] 2024-02-03 16:27
@hippotastic The key part of this bug is that your CSS is imported by content in a content collection. That's usually going to be MDX, but could also be Markdoc. If there's no content collections involved then it's likely a different bug (but possible the same underlying issue), so would want a separate issue for it.

**Comment by hippotastic** [comment] 2024-02-03 16:29
@spacedawwwg Is your Vue bug using Content Collections? If not, it would be great if you could create a new issue with a small reproduction for this.

**Comment by fisherfrontier** [comment] 2024-02-03 22:15
Tested https://github.com/withastro/astro/pull/9956 in my project and it fixed the problem for MDX content collections. Thanks, @matthewp.

**Closed** 2024-02-06 14:56 UTC
Labels: - P5: urgent, feat: hmr

**Comment by spacedawwwg** [comment] 2024-02-13 16:44
@hippotastic issue still persists with external vue package CSS, I will open a separate issue with a repro
