### ISSUE TITLE
Uses deprecated APIs - 1 Warning found

### ISSUE THREAD

**Issue by majkl-zumberi** [withastro/astro#5833] opened 2023-01-11 11:30 UTC
### What version of `astro` are you using?

^1.6.10

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

i have the same [issue](https://github.com/BuilderIO/partytown/issues/313) as this builderIo/partytown issue
which in the original repo @BuilderIo/partytown has been resolved and closed; but in this astro integration i'm still experiencing the same problem that consist of a lighthouse warning in the "best practice"  Uses deprecated APIs ruining the score

### Link to Minimal Reproducible Example

https://github.com/BuilderIO/partytown/issues/313

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-01-11 12:36
Duplicate of https://github.com/withastro/astro/issues/5819

**Closed by bluwy** 2023-01-11 12:36 UTC
