### ISSUE TITLE
🐛 BUG: Vue component HMR does not work

### ISSUE THREAD

**Issue by sdoerger** [withastro/astro#2707] opened 2022-03-03 09:11 UTC
### What version of `astro` are you using?

0.23.4

### What package manager are you using?

npm

### What operating system are you using?

Linux Manjaro

## STR
I added in the Blog Boilderplate of Astro a simple vue component (Test.vue, `<Test :client:load />`) and installed Tailwind.

When I save changes in the Vue-Component (either console, html or style) the changes are not refelcted in Browser nor console.
Only if I save the parent astro component, updates take place.

I could not find in the docs, how to fix that. Is it connected to `:client...` or settings/config or is it a real bug/feature request?

I use "@astrojs/renderer-vue": "^0.4.0" for vue components.

Thanks

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zv8xdl?file=src/pages/index.astro

**Comment by ckissi** [comment] 2022-03-26 17:56
It doesn't work. I'm on version 0.24.3 and facing the same issue. I have to manually refresh the page to see changes.

**Comment by natemoo-re** [comment] 2022-03-31 18:02
I can confirm that this is still an issue. Reopening.

HMR for files other than `.astro` are handled by their respective Vite plugins. I'm guessing we have an issue where we're not handling the HMR request coming from the Vue plugin properly. I'm going to take a look at this as soon as I can.

**Comment by tony-sull** [comment] 2022-04-15 10:45
I ran into this while looking into #3097 as well

With `client:` directives for other components the browser gets an update event from Vite including the component file that was updated.  For some reason, specifically with view we only get an update event for the `.astro` page and not the hydrated Vue component

**Comment by TheDutchCoder** [comment] 2022-04-15 17:39
I get the same issue with the default Vue template. Content updates to the page HMR fine, but the Vue component does not.

**Comment by natemoo-re** [comment] 2022-04-21 20:44
I made some HMR fixes in https://github.com/withastro/astro/pull/3138 but it looks like we're still having trouble with the HMR handling of Vue components. Not sure if it's coming from Vue's Vite plugin or from us.

**Comment by matthewp** [comment] 2022-05-27 15:20
This appears to have been fixed in the last 2 months:

https://stackblitz.com/edit/github-zv8xdl-s1vj7l?file=astro.config.mjs,package.json,src%2Fpages%2Findex.astro,src%2Fcomponents%2FElements%2FTest.vue

**Closed by matthewp** 2022-05-27 15:20 UTC
Labels: framework-vue, p4-important, s2-medium, hmr
