### ISSUE TITLE
🐛 BUG: Passing number as prop

### ISSUE THREAD

**Issue by jakobpevec** [withastro/astro#1878] opened 2021-11-18 09:34 UTC
### What version of `astro` are you using?

0.21.0.next7

### What package manager are you using?

npm

### What operating system are you using?

Windows + WSL2

### Describe the Bug

Example with Vue:

1. In a vue component define a prop with type Number.
2. In .astro file pass the value via prop
3.  This will result in the following error: Invalid prop: type check failed for prop "numberOfSlides". Expected Number with value 2, got String with value "2".

Is this a bug/not yet implemented or am I just not trying the right things?

I cannot get either stackblitz or codesandbox to start the container, that's why the example is empty. I'm available for extra info if needed.

### Link to Minimal Reproducible Example

https://test.eu

**Comment by jonathantneal** [comment] 2021-11-18 14:55
>  I'm available for extra info if needed.

Would you mind sharing the minimal contents for the `.vue` file, @jakobpevec? I’m happy to help work out the complete example.

**Comment by jakobpevec** [comment] 2021-11-18 15:29
Sure! The vue file is in the attachment. I'm passing the prop like this: 
```<ProjectsCarousel projectsData={projectsData} numberOfSlides="3.3" client:only/>```

There is also this dependency for the slider (probably not needed for reproducing the error):
```"swiper": "^7.2.0"````

And 
[ProjectsCarousel.zip](https://github.com/snowpackjs/astro/files/7563900/ProjectsCarousel.zip)

**Comment by Porges** [comment] 2021-11-22 20:20
> Sure! The vue file is in the attachment. I'm passing the prop like this: `<ProjectsCarousel projectsData={projectsData} numberOfSlides="3.3" client:only/>`

Try: `<ProjectsCarousel projectsData={projectsData} numberOfSlides={3.3} client:only/>`

**Comment by jasikpark** [comment] 2021-12-10 04:26
I believe the problem is that you need to pass a number via `numberOfSlides={3.3}` rather than `numberOfSlides="3.3"`:

I demonstrated it here in https://stackblitz.com/edit/github-dqew3h-vndugy?file=src/pages/index.astro

<img width="685" alt="image" src="https://user-images.githubusercontent.com/10626596/145517072-7096c8fa-4de0-4a4c-be8d-da031f397b96.png">

alt text:

```astro

<body>
	<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
	<ProjectsCarousel numberOfSlides="3" />
	<ProjectsCarousel numberOfSlides={3} />
</body>

</html>
```
```sh
~/projects/github-dqew3h-vndugy 48s
❯ npm run start
$ astro dev
10:23 PM [astro] Port 3000 in use. Trying a new one…
10:23 PM [astro] Server started                               10615ms
10:23 PM [astro] Local: http://localhost:3001/
10:23 PM [astro] 200 /                                        3334ms
10:23 PM [astro] 200 /                                        1085ms
[Vue warn]: Invalid prop: type check failed for prop "numberOfSlides". Expected Number with value 3, got String with value "3".
10:23 PM [astro] 200 /         
```

**Comment by jasikpark** [comment] 2021-12-10 04:27
I believe that should be the solution for you! I'll close this issue, but please comment and we'll re-open the issue if this doesn't solve your problem!

**Closed by jasikpark** 2021-12-10 04:27 UTC
Labels: needs response
