### ISSUE TITLE
Spaces in project path break Markdoc integration

### ISSUE THREAD

**Issue by suhaylmv** [withastro/astro#8164] opened 2023-08-20 09:34 UTC
### What version of `astro` are you using?

2.10.12

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Had a fully functional blog which uses .md files, but after installing markdoc and creating the config file, right when I rename a .md file to .mdoc  throws this error:

```
Failed to load url /mnt/D/Docs/Web%20projects/randomproject/markdoc.config.mjs (resolved id: /mnt/D/Docs/Web%20projects/randomproject/markdoc.config.mjs) in /mnt/D/Docs/Web projects/randomproject/src/content/blog/randomblogpost.mdoc. Does the file exist?
```

### What's the expected result?

It should keep working 

### Link to Minimal Reproducible Example

Link to my project repo: https://github.com/suhaylmv/minov-studio . Check the branch "test"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment] 2023-08-20 14:04
Thanks for bringing this up!

It's probably going to be difficult to diagnose it from your real project that you linked. Could you create a minimal reproduction?

**Comment by suhaylmv** [comment] 2023-08-20 17:54
I installed this markdoc template  https://github.com/withastro/astro/tree/latest/examples/with-markdoc , and when I run npm run dev it throws exactly the same error. Could you please try this template and see if it works for you? If it does, then it must be problem of my machine

**Comment by lilnasy** [comment] 2023-08-20 18:04
It seems to work fine, both in dev and build.

<img width="960" alt="image" src="https://github.com/withastro/astro/assets/69170106/5c616698-75f2-4909-95dc-124ee7641220">

**Comment by suhaylmv** [comment] 2023-08-20 20:04
That's odd. I think the problem is the OS. Now I'm on Elementary OS (debian based), but before when I used Arch I never had such issues. I had a fuckton of other problems too because of Elementary. Distro hopping is never going to end). Thank you for help!

**Comment by suhaylmv** [comment] 2023-08-21 09:53
I made a fresh install of pop os and I'm having the same problem. Idk what to do

**Comment by suhaylmv** [comment] 2023-08-21 10:13
Ok I found a solution. For some reason when the project folder is inside an external hdd drive and the project uses markdoc, gives this error. I would suggest trying the same on other machines to see if the same error occurs. If it does, then maybe it's worth adding the information to the troubleshooting page in the documentation.

**Comment by lilnasy** [comment] 2023-08-21 13:18
You also seem to have a space in your project path, could that be the issue?

**Comment by suhaylmv** [comment] 2023-08-22 16:45
> You also seem to have a space in your project path, could that be the issue?

Where?

**Comment by lilnasy** [comment] 2023-09-21 05:45
#### Good first issue!
This is an opportunity for astro users to learn about how astro works by fixing a small but real bug. You can expect to get help setting up the dev environment, and understanding the project structure in the #dev channel of our discord: https://astro.build/chat. If you have already been contributing for a while, consider guiding an enthusiastic newcomer.

#### What's the bug?
You can reproduce it by creating a new project using the `with-markdoc` template and renaming the created project to include a space. The project would fail to build.

#### What's going wrong here?
The cause of the issue is a space in the path. Astro config stores most paths as URL objects. Part of URL encoding is using `%20` in place of a space. This would need to be converted back so that vite can understand it. See [#8614](https://github.com/withastro/astro/pull/8614) for a similar fix.

#### Where do I start looking?
The markdoc integration uses the Astro config (with URLs) [here](https://github.com/withastro/astro/blob/main/packages/integrations/markdoc/src/index.ts#L29).

**Comment by lutaok** [comment] 2023-10-04 23:31
Hello @lilnasy,
I'd like to contribute on this.

I actually already have a fix for this thanks to your suggestions, but I also wanted to add a test case for this scenario. Do you think it could be valuable?

If yes, proper tests would be of "render", "render html" and "variables" categories, is that correct?

Thank you in advance!

**Comment by lilnasy** [comment] 2023-10-05 01:19
Thanks for looking into it!

And yes, those categories sound appropriate.

**Comment by natemoo-re** [comment] 2023-10-27 14:34
Just linked this issue to the next release so GitHub will display what release the fix is included in!

**Comment by bluwy** [comment] 2024-01-03 16:12
Looks like GitHub didn't automatically close this. Fixed in https://github.com/withastro/astro/pull/8759

**Closed by bluwy** 2024-01-03 16:12 UTC
Labels: - P2: has workaround, pkg: markdoc
