### ISSUE TITLE
🐛 BUG: astro 0.24 breaks tailwindcss

### ISSUE THREAD

**Issue by mq1** [withastro/astro#2777] opened 2022-03-12 18:34 UTC
### What version of `astro` are you using?

0.24

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

https://mq1.eu/en/

https://github.com/mq1/mq1.eu

The hover animation on the "download my cv" button (for example) is present only if using --legacy-build

---

Another website is this:

https://top-for-spotify.mq1.eu/

https://github.com/mq1/top-for-spotify

Without using --legacy-build it disrespects sm:whatever and only builds mobile styles

### Link to Minimal Reproducible Example

https://mq1.eu/en/

**Comment by FredKSchott** [comment] 2022-03-14 04:26
Another reproduction from @RafidMuhymin in #2780:


> Some of the complex Tailwind CSS classes are getting incorrectly escaped. For example, the class `2xl:w-[80%]` is getting changed to `\\32xl\\:w-\\[80\\%\\]`. Because of the unnecessary `3`, it's being treated as `32xl:w-[80%]`.
>
> ![image](https://user-images.githubusercontent.com/63650415/158069386-950132d7-cf51-4793-a935-09b2d22022ba.png)
>
>
> ### Link to Minimal Reproducible Example
>
> https://stackblitz.com/edit/github-dntvlc?file=src%2Fpages%2Findex.astro

**Comment by FredKSchott** [comment] 2022-03-14 04:38
@mq1 are you able to reproduce in a stackblitz? Your link to https://mq1.eu/en/ seems to be working correctly, and it is difficult for maintainers to check out large repros and reproduce.

**Comment by FredKSchott** [comment] 2022-03-14 04:42
Fixed in https://github.com/mq1/mq1.eu/pull/141

**Closed by FredKSchott** 2022-03-14 04:42 UTC
