### ISSUE TITLE
Over 10k `setTimeout()` on Route Rendering

### ISSUE THREAD

**Issue by itsmatteomanf** [withastro/astro#7460] opened 2023-06-23 13:38 UTC
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When publishing to Pages, which has a 10k `setTimeout()` limit, I'm hitting this limit when rendering ~3.5k components.

```json
 {
	"name": "QuotaExceededError",
	"message": "You have exceeded the number of timeouts you may set.10000",
	"timestamp": 1687523060530
}
```

The issue seems to be related to this function, which is from Astro's handling of components. None of these components handle any actual data fetching, just rendering HTML.

```js
function $a(e) {
	let t = e.map((n) => new $t(n));
	return (
		setTimeout(() => {
			t.forEach((n) => !n.isStarted() && n.buffer());
		}, 0),
		t
	);
}
```

I can't really provide a minimal example, it needs to be deployed on Pages and you need to look at their logs to see the error (apart from the page failing to render).

### What's the expected result?

The page to load.

### Link to Minimal Reproducible Example

null

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-06-23 13:42
The code comes from https://github.com/withastro/astro/blob/dfa70357d3ce936995e0dfaf4336a2bc1e9b8136/packages/astro/src/runtime/server/render/util.ts#L147-L157

This seems to be a really niche case though. Can you show how you're rendering 3.5k components? Are they scattered or rendered side-by-side? cc @johannesspohr

**Comment by itsmatteomanf** [comment] 2023-06-23 13:46
It's a grid of components.

```js
{data.map((item) => (
	<FilterItem
		href={`/page/${item.url}/`}
		string={item.name}
	/>
))}
```

Can I create them from within the main page? Sure. Is it ideal? No. This component is used in tons of pages.
I could make the component render multiple children itself, probably, but it would still be kind of the opposite of what you would expect the code to look like.

**Comment by johannesspohr** [comment] 2023-06-23 14:07
I guess a lot of the `setTimeout` are called in the same synchronous execution, so we could probably reduce the amount of setTimeouts a lot by batching those calls as well. I won't be able to try this before next week though (but of course anyone is welcome to give it a go). Other than that, I don't know if some replacement (like `setImmediate`) is available on workers, it seems like it's not.

**Comment by itsmatteomanf** [comment] 2023-06-23 14:25
> Other than that, I don't know if some replacement (like `setImmediate`) is available on workers, it seems like it's not.

I am being suggested from *sources* it's to be implemented, and that `queueMicrotask()` exists, which may help.
`queueMicrotask()` doesn't seem to have limits.

**Comment by bluwy** [comment] 2023-06-26 08:21
`queueMicrotask` sounds like a great alternative. Happy to get that in if you'd like to contribute.

**Comment by itsmatteomanf** [comment] 2023-06-26 14:56
> Happy to get that in if you'd like to contribute.

Not sure I'd be actually able myself to do that, but I'll take a look and who suggested that if he wants to help me out.

Thank you!

**Comment by itsmatteomanf** [comment] 2023-06-26 17:06
> `queueMicrotask`

Do I need to add a fallback to `setTimeout()` if it were to not be implemented? Not sure about support strategies you have.

**Comment by bluwy** [comment] 2023-06-27 07:38
Since that's runtime code, it runs in node, deno, cloudflare, vercel edge, etc.

We only support node16 and above:

https://github.com/withastro/astro/blob/57e603038fa51f5cf023c086705e2ced67434b38/packages/astro/package.json#L221-L224

Deno 1.0 (I think), and any latest versions of cloudflare and vercel edge.

From the respective runtime docs, `queueMicrotask` is [supported in node11, deno 1.0](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask#browser_compatibility), and the latest versions of cloudflare and vercel edge. So we should be good here without a fallback.

**Comment by itsmatteomanf** [comment] 2023-06-29 21:32
@bluwy there seems to be a very big performance regression here.

I'm gonna try and see if the slowdown is due to a Workers bug or it's expected.
We need to consider if it makes sense at that point.

**Comment by itsmatteomanf** [comment] 2023-06-29 22:01
Adding additional context, testing locally using Node v20 it seems to be slower across the board, nowhere near as badly as in Workers, but still slower.

**Comment by bluwy** [comment] 2023-06-30 08:13
Do you have some numbers on how slow it became? If it's huge, maybe we should go with Johannes' idea of batching it ourselves and use a single `setTimeout` to queue it.

**Comment by itsmatteomanf** [comment] 2023-06-30 08:19
> Do you have some numbers on how slow it became?

Locally it seems to be empirically (there is some variance in the numbers, but the averages...) ~50% slower, on Workers (but I'm pretty sure something is wrong on their end for this, or they need to enforce some limits here, too) at the limit which I haven't found yet goes from the 50% to like 800%.

> maybe we should go with Johannes' idea of batching it ourselves and use a single `setTimeout` to queue it.

That would probably be a good idea. I assume it would be even faster still, calling `setTimeout()` multiple times slows things down a lot. `queueMicrotask()` seems even slower, at this point. I guess it's due to how they behave, with the latter making the called function have priority on everything else.

**Comment by johannesspohr** [comment] 2023-06-30 17:57
I quickly drafted my ideas here: https://github.com/withastro/astro/pull/7544, but I haven't had time to test it thoroughly. Maybe somebody who currently has sophisticated benchmarks set up can give it a go to see if it improves anything?

**Comment by itsmatteomanf** [comment] 2023-06-30 23:32
The bench were run in the new PR, it might be nice to run these against my older PR, but not sure I have permissions.

**Comment by bluwy** [comment] 2023-07-03 13:14
Re-opening for the perf regressions.

**Comment by bluwy** [comment] 2023-07-04 09:32
Fixed in https://github.com/withastro/astro/pull/7544

**Closed by bluwy** 2023-07-04 09:32 UTC
Labels: good first issue, p3-minor-bug
