### ISSUE TITLE
Astro 3.0 breaks React client component

### ISSUE THREAD

**Issue by NotJorge** [withastro/astro#8314] opened 2023-08-31 09:49 UTC
### Astro info

```block
Astro version            v3.0.3
Package manager          pnpm
Platform                 win32
Architecture             x64
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind, @astrojs/react
```

### What browser are you using?

Chrome

### Describe the Bug

After upgrading to Astro 3.0 while using node adapter and hybrid output, it is adding `before-hydration-url=/` attribute to React client components. This makes `childrenConnectedCallback` try to import `/` and breaking the rendering causing the following error message in browser console when running `astro preview` (Works fine in dev mode)
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### What's the expected result?

I expected my component to render properly

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bmpb88

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by NotJorge** [comment] 2023-08-31 09:49
Link to Minimal Reproducible Example is not working because Node version is not supported. You can download the project to test locally.

**Comment by xesrevinu** [comment] 2023-08-31 13:56
https://github.com/xesrevinu/astro-react-prod-issue

I created a reproducible repository and deployed it to https://astro-react-prod-issue.pages.dev/

```
astro-react-prod-issue.pages.dev/:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
(index):3 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://astro-react-prod-issue.pages.dev/
```

**Comment by NotJorge** [comment] 2023-08-31 14:03
> I created a reproducible repository and deployed it to cloudflare pages :) 
> https://astro-react-prod-issue.pages.dev
> https://github.com/xesrevinu/astro-react-prod-issue
> 
> ```
> astro-react-prod-issue.pages.dev/:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
> (index):3 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://astro-react-prod-issue.pages.dev/
> ```

Thank you very much!

**Comment by natemoo-re** [comment] 2023-08-31 21:31
Thank you for the report! We'll look into this as soon as we can!

**Comment by JLarky** [comment] 2023-09-01 00:58
I was able to reproduce this with Vercel serveless adapter as well. You can see that in the last commit I'm changing `output` from `server` to `hybrid` and it stops hydrating it on the client.

I created a reproduction here https://github.com/JLarky/astro-examples/tree/main/astro-3-react-ssr-vercel-bug

[expected](https://pink-photon-8va4h665e-jlarky.vercel.app/):
<img width="498" alt="image" src="https://github.com/withastro/astro/assets/7026/ffbc173e-2003-4daf-96fb-8bc1e2a20573">

instead got [this](https://pink-photon.vercel.app/):
<img width="501" alt="image" src="https://github.com/withastro/astro/assets/7026/9253d0dc-560f-47d9-9316-27d666964f7b">

**Comment by pijusz** [comment] 2023-09-01 07:22
I get somewhat similar error:
I'm using React components with shadcn's navigation (Mobile and Desktop modals) with:
client:load and Mobile Nav also has: client:media="(max-width: 1024px)"
In preview I get 2 console errors (in dev mode it works):
"SES_UNHANDLED_REJECTION: TypeError: error loading dynamically imported module: URL"
And then "Loading module from “URL” was blocked because of a disallowed MIME type (“text/html”)."

**Comment by ajn404** [comment] 2023-09-01 07:42
same error

**Comment by jln13x** [comment] 2023-09-01 08:44
> I was able to reproduce this with Vercel serveless adapter as well. You can see that in the last commit I'm changing `output` from `server` to `hybrid` and it stops hydrating it on the client.
> 
> I created a reproduction here [JLarky/astro-examples@`main`/astro-3-react-ssr-vercel-bug](https://github.com/JLarky/astro-examples/tree/main/astro-3-react-ssr-vercel-bug?rgh-link-date=2023-09-01T00%3A58%3A26Z)
> 
> [expected](https://pink-photon-8va4h665e-jlarky.vercel.app/): <img alt="image" width="498" src="https://user-images.githubusercontent.com/7026/264823337-ffbc173e-2003-4daf-96fb-8bc1e2a20573.png">
> 
> instead got [this](https://pink-photon.vercel.app/): <img alt="image" width="501" src="https://user-images.githubusercontent.com/7026/264823425-9253d0dc-560f-47d9-9316-27d666964f7b.png">

did it work for you with the `output: server` ? Because neither works for me.

**Comment by degun** [comment] 2023-09-02 12:46
I get the same error with Svelte.

**Comment by vampaz** [comment] 2023-09-02 17:59
Same with Vue

**Comment by pijusz** [comment] 2023-09-04 12:46
Seems to have been fixed with #https://github.com/withastro/astro/pull/8388

**Closed** 2023-09-04 14:50 UTC
Labels: pkg: react, - P5: urgent

**Comment by benjamin-guibert** [comment] 2023-09-23 09:57
I get the same issue using `hybrid` mode with Vercel:
- Client components work fine on server rendered pages (`prerender = false`);
- Client components don't work on static pages;
- Everything works fine locally when running in dev mode.

**Comment by benjamin-guibert** [comment] 2023-09-23 10:40
Never mind, I was still using Astro version `3.0`. I can confirm that the issue is solved for version `3.1.2`. Thank you for the fix, you rock! 🚀
