### ISSUE TITLE
🐛 BUG: [0.21] Vite plugins (such as vite-imagetools) cannot build for production

### ISSUE THREAD

**Issue by Porges** [withastro/astro#1718] opened 2021-10-31 21:52 UTC
### What package manager are you using?

npm

### What operating system are you using?

Windows, Linux (under WSL)

### Describe the Bug

Vite plugins always seem to be in serve/development/watch mode (is there a real name for this? 😀). This is a problem because several plugin APIs such as `emitFile` are [disabled in this mode](https://github.com/vitejs/vite/blob/11409818d934f2b13ba7d5972647d31273fd3293/packages/vite/src/node/server/pluginContainer.ts#L236-L239). Generally the plugin will work fine with Astro’s `npm start`, but the site generated by `npm run build` will be incorrect.

### How vite-imagetools is broken

One example affected plugin is `vite-imagetools`. The affected region of the source can be seen here:

https://github.com/JonasKruckenberg/imagetools/blob/4253c96cad6a8c3bab7bda332fb8e7ece39a5c79/packages/vite/src/index.ts#L72-L84

If not in watch mode, the plugin will use the `emitFile` API, otherwise it will generate a URI (starting with `/@imagetools/`) that it can handle to serve the generated images from memory.

Since `watchMode` is always true, when building the static site with Astro, it doesn’t use `emitFile` and the generated HTML is something like:

```html
<html><head></head><body><p>Hi world! <img src="/@imagetools/218ccf129cc0b7b85f42cf7c6315930356e86c9e"></p>
</body></html>
```

Visible here is the fake URI, which obviously won’t work. No images are emitted.

### Other plugins 

I saw [a report](https://discord.com/channels/830184174198718474/845451724738265138/904034740791808040) of WindiCSS which looks at first glance like it is the same problem (magic URIs starting with `/@windicss` and no generated files). 

## Solution

I don’t know how to fix this, I tried looking at the source for both Astro & Vite but couldn’t figure out what needs to change.

### Steps to Reproduce

1. Clone my repro from: https://github.com/Porges/astro-repro
2. `npm start` should work
3. `npm run build` runs and generates the bad HTML from above

### Link to Minimal Reproducible Example (Optional)

https://github.com/Porges/astro-repro

**Comment by hans-d** [comment] 2021-11-01 12:44
Confirming that for WindiCSS no files are being produced

**Comment by mcfadyeni** [comment] 2021-11-01 14:01
May be a related issue to https://github.com/snowpackjs/astro/issues/1715 (Astro.resolve assets work with dev but are not copied to dist, similar to here).

**Comment by natemoo-re** [comment] 2021-11-02 03:05
Interesting! Thanks for the detailed breakdown. Definitely something we have to fix. 👍🏻

**Comment by drwpow** [comment] 2021-11-04 18:54
`astro@next` still has some known bugs with the build, and CSS and images missing from the build are all part of the same scope of work to be done. We‘ll have this fixed before the `0.21` stable release.

**Comment by mcfadyeni** [comment] 2021-11-12 16:39
This looks like it has been fixed with the change by @matthewp to add static assets (including images and CSS).

**Comment by Porges** [comment] 2021-11-18 07:53
> @mcfadyeni This looks like it has been fixed in `astro@next` with the change by @matthewp to add static assets (including images and CSS).

I just checked in `0.21.0-next.7` and `imagetools` is still not working in build mode.

**Comment by matthewp** [comment] 2021-11-18 15:45
Sounds like you know what the problem is, mind submitting a fix?

**Comment by mcfadyeni** [comment] 2021-11-18 16:06
Apologies, looks like it only works with hydrated components! (was using Svelte with `client:load` when I was testing it)

**Comment by YuukanOO** [comment] 2021-11-19 13:02
Yup, still not working in `0.21.0-next.8` :(

**Comment by matthewp** [comment] 2021-11-19 19:20
Oh interesting, thanks for the additional info @YuukanOO. So it seems like possibly a bug in Vite? It should be using the `watchMode` setting of the vite server and not defaulting to true. I guess they are not expecting people to use SSR as part of the actual build process like we do.

**Comment by matthewp** [comment] 2021-11-22 16:02
Taking a look today.

**Comment by matthewp** [comment] 2021-11-23 19:39
Ok, this is a tricky one. I think I have a solution though and testing it locally it works. However it requires us to fetch() the resource through Vite's dev server. The problem there is not doing the fetch, necessarily, but that we can't tell that a URL needs to be fetch (it could already be in public/, which works without fetching).

Taking this to discord to discuss the solution.

**Comment by matthewp** [comment] 2021-11-29 16:17
So fixing vite-imagetools specifically, and the class of plugins that work similarly (read a special import statement and create assets in the dist/ folder), is not really possible with the way Astro currently works in 0.21. I'll explain why and what I think we can do to get these types of plugins to work.

How Astro's build works is:

1. We generate the HTML for each page using same mechanism we use for dev. This is Vite's `ssrLoadModule` API that exists on the Vite dev server.
2. We can the generated HTML for scripts/styles/images and run them through `vite.build`.
3. Only the *client-side* JavaScript gets run through the build.

Due to **(3)**, these types of plugins don't work with Astro. The build only sees the client-side JS you are going to need and since .astro files are not run in the client, those will not be built.

How we can fix:

What I think we should be doing here is changing how the build fundamentally works. Instead of doing step (1) we should be running each .astro file as an entrypoint in `vite.build`. This *should* allow Vite plugins like vite-imagetools should behave as they expect to.

This is essentially doing an SSR build. Then for static generation we can run each of the built pages (which might be somewhere like `dist/index.js`) to generate the static HTML.

There might be some issues with doing this, but it feels like the right approach to me, and given that we are hoping to support SSR in the not too distant future, it feels aligned with that goal.

**Comment by matthewp** [comment] 2021-11-29 17:15
@RafidMuhymin if you mean changing the way we do the build, my expectation is that the build will be faster (and use less memory).

**Comment by matthewp** [comment] 2021-12-22 16:05
This plugin is now working with the `--experimental-static-build` flag, and there's an example here: https://github.com/withastro/astro/tree/main/examples/fast-build.  However this flag doesn't work with client-side components at the moment (PR coming soon) so I wouldn't recommend using it yet. But we are getting closer on this.

**Comment by moritzlaube** [comment] 2021-12-23 13:09
That is great! One quick question: Will it also be possible to not only use the sharp parameters like in your example (`import grayscaleUrl from '../images/random.jpg?grayscale=true';`) but also in the html directly like so?

```
<picture>
        <source
          srcset="/assets/images/random.jpg?w=400&webp 1x, /assets/images/random.jpg?w=800&webp 2x"
          type="image/webp"
        />
        <source
          srcset="/assets/images/random.jpg?w=400 1x, /assets/images/random.jpg?w=800&webp 2x"
          type="image/jpg"
        />
        <img
          src="/assets/images/random.jpg?w=200"
        />
      </picture>
```

Thanks for your awesome work and Merry Christmas!

**Comment by matthewp** [comment] 2021-12-23 13:15
@moritzlaube No, Astro doesn't include vite-imagetools by default. This issue is about compatibility and the ability for users to include the plugin themselves. So you have to use it as designed. We are going to add an Image component in the future that will hopefully account for all of these use-cases.

**Comment by tony-sull** [comment] 2022-02-08 12:59
@matthewp Is this issue still a `coming soon` feature or is it supported now with the latest magic you've been pulling off with static builds and perf updates?

**Comment by matthewp** [comment] 2022-02-14 21:28
Closing as vite-imagetools works with the `--experimental-static-build` flag. If there are other plugins which don't work please file specific issues for those, thanks!

**Closed by matthewp** 2022-02-14 21:28 UTC

**Comment by spacedawwwg** [comment] 2023-08-31 17:10
@matthewp has `--experimental-static-build` stopped working with astro v3?
