### ISSUE TITLE
Impossible to use SVG files in Markdown when `astro:assets` is enabled

### ISSUE THREAD

**Issue by alvinometric** [withastro/astro#7420] opened 2023-06-19 14:13 UTC
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

With Assets, it's not possible to use `svg` files in Markdown image tags (as in `![alt text](./image.svg)`)

This creates the following error
![Screenshot 2023-06-19 at 16 05 21](https://github.com/withastro/astro/assets/107407814/f7f448e5-15d9-4cf3-90e2-e07862e775da)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ife6nx?file=src%2Fcontent%2Fblog%2Ffirst-post.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-06-19 16:19
I am going to close this one. As you can see, that's not a bug but the intended behaviour. Feel free to open a discussion in the roadmap repository

**Comment by Princesseuh** [comment] 2023-06-19 16:59
This is a bug. SVGs are not supported on purpose, but in Markdown we shouldn't be trying to process them in the first place. This make it impossible for users to use `.svg` files at all.

**Comment by hfournier** [comment] 2023-06-21 16:50
I've run into the same issue. I tried converting the image in markdown from `![alt text](@assets/example.svg)` to an `<img src="../assets/example.svg" alt="alt text">` tag manually to avoid the issue, but then I also need to manually move the image from the assets folder to public. So although it's not completely impossible, it's very impractical.

Astro should process SVGs in markdown the same as any other image, but without the image optimization step.

**Comment by natemoo-re** [comment] 2023-06-22 18:11
I'm bumping this up to an important bug because this is a huge pain if you have SVG images! Hoping we can prioritize a fix for this soon, but PRs are also welcome!

**Closed** 2023-07-13 19:22 UTC
Labels: markdown, p4-important, assets, help wanted
