### ISSUE TITLE
Relative images in Markdown crashes build

### ISSUE THREAD

**Issue by phenomen** [withastro/astro#6492] opened 2023-03-09 19:54 UTC
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows / Netlify

### Describe the Bug

It works fine in dev, but crashes both local (Windows) and Netlify build.

Image is located in `public/images/111-jackson-blvd/exterior.webp`

```markdown
![Exterior photo of 111 Jackson Blvd](/images/111-jackson-blvd/exterior.webp)
```

```
[Error: Failed to parse Markdown file "D:\Github\project\src\content\properties\111-jackson-blvd.md":
ENOENT: no such file or directory, open 'D:\images\111-jackson-blvd\exterior.webp'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\images\\111-jackson-blvd\\exterior.webp'
}
[astro:markdown] Could not load D:/Github/project/src/content/properties/111-jackson-blvd.md (imported by src/content/properties/111-jackson-blvd.md?astroPropagatedAssets=true): Failed to parse Markdown file "D:\Github\project\src\content\properties\111-jackson-blvd.md":
```

Notice that path `D:\images\111-jackson-blvd\exterior.webp` is incorrect, it should be `D:\Github\project\public\images\111-jackson-blvd\exterior.webp`

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-03-09 19:55
Closing as a duplicate of https://github.com/withastro/astro/issues/6462

**Closed by Princesseuh** 2023-03-09 19:55 UTC
