### ISSUE TITLE
Vercel's Serverless Function crashes due to not being able to find the "image-size" module (and is also required for astro build for some reason..?)

### ISSUE THREAD

**Issue by solelychloe** [withastro/astro#6521] opened 2023-03-12 09:21 UTC
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

I'm using the Vercel SSR adapter.

### What package manager are you using?

yarn (version 3.3.1)

### What operating system are you using?

I'm using Ubuntu under WSL (Windows Subsystem for Linux) in this case.

### What browser are you using?

Microsoft Edge

### Describe the Bug

With the release of Astro 2.1(?), I have been getting an error when building my website with the `image-size` dependency, even though my workspace doesn't require it (as can be seen below, it's just `yarn.lock`):

![Code_MgKic2lHLs](https://user-images.githubusercontent.com/22654782/224535181-556c95b9-13ec-4f6d-810d-5ec24950e522.png)

I decided to install `image-size` and include it to my `package.json` file, and sure enough, `astro build` worked locally.
However when I go and deploy my site to Vercel, it says that a serverless function has crashed.

![msedge_KbuVK5M3uY](https://user-images.githubusercontent.com/22654782/224536130-9c4ec316-a7aa-48ef-be1e-974efee48abf.png)

It says that Vercel still requires the dependency, even after it is included in the `package.json` file.
![msedge_oJygakxzvj](https://user-images.githubusercontent.com/22654782/224535152-234aa7bf-7887-4b7b-9906-c5928ae9c131.png)

Any help is appreciated. Thank you!

### Link to Minimal Reproducible Example

None. I don't think I can use Stackblitz to reproduce this issue, since it is related to Vercel.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mfrachet** [comment] 2023-03-13 06:23
Probably related to https://github.com/withastro/astro/issues/6470 which seems to be fixed and closed 😊 . Waiting for a release 🚀

**Comment by Princesseuh** [comment] 2023-03-13 11:24
Closing as a duplicate of https://github.com/withastro/astro/issues/6470, seems to be exact same issue! `image-size` is a capricious package unfortunately 😓

**Closed by Princesseuh** 2023-03-13 11:24 UTC
Labels: assets
