### ISSUE TITLE
Context-based Radix UI primitives (React) crash on mount

### ISSUE THREAD

**Issue by sdnts** [withastro/astro#6139] opened 2023-02-05 17:06 UTC
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

Nope

### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

Radix primitives that require a `Provider`, like Tooltips, Toasts etc. crash on mount with the error: `TooltipTrigger must be used within Tooltip`, even though my usage is correct.

I'm building a pure client-side app, so there's no SSR at play, and I see this error even when I set the `client:only` directive.

I understand that this is a library compatibility issue, but unfortunately I'm not familiar enough with either Radix or Astro's internals to judge where the issue is. I created this issue here because the exact same setup works on a barebones Vite template (which does not do any kind of server-side / build-time rendering out of the box). Please let me know if Radix's repo would be a better place to raise this!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-p2row3?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment] 2023-02-05 18:01
Closing as duplicate of https://github.com/withastro/astro/issues/2016
The author didn't use Solid components but the same principles apply

**Closed by MoustaphaDev** 2023-02-05 18:01 UTC

**Comment by sdnts** [comment] 2023-02-05 20:48
Ah, I didn't know that, thanks for pointing me in the right direction!

For posterity, this is what I ended up doing, as suggested: https://stackblitz.com/edit/github-p2row3-evwryw?file=src/pages/index.astro

**Comment by RealKai42** [comment] 2024-01-09 18:09
> Ah, I didn't know that, thanks for pointing me in the right direction!
> 
> For posterity, this is what I ended up doing, as suggested: [stackblitz.com/edit/github-p2row3-evwryw?file=src/pages/index.astro](https://stackblitz.com/edit/github-p2row3-evwryw?file=src/pages/index.astro)

Bro! YOU ARE THE REAL HERO!!
