### ISSUE TITLE
define:vars causes a passed style object to become "[object Object];"

### ISSUE THREAD

**Issue by FelixSelter** [withastro/astro#12044] opened 2024-09-20 18:18 UTC
### Astro Info

```block
Astro                    v4.15.8
Node                     v22.9.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I am trying to pass some style down to my component.
I created a Prop style of type astroHTML.JSX.CSSProperties in my child Component.
Everything works great and as expected.

Now I forward some props as css variables to my style
```html
<style
  define:vars={{
    width,
    height,
    marginLeft,
    marginRight,
    marginBottom,
    marginTop,
  }}
>
 ...
</style>
```

The problem now is that the generated output style tried to convert my object to a string
`style="[object Object]; --width: 210mm;--height: 297mm;--marginLeft: 2.5cm;--marginRight: 2.5cm;--marginBottom: 2.5cm;--marginTop: 2.5cm;"`

### What's the expected result?

I would expect Astro to detect, that an object has been applied to the style and gracefully convert the object to a string

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pwy7vs?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-10-02 12:46
I investigated the issue, and this is by design. `define:vars` **must** be passed as an object, so you can't in line objects passed by props. 

So you **can't** do this:
```jsx
<style define:vars={someProp} ></style>
```

But you can do this
```jsx
<style define:vars={{ ...someProp }} ></style>
```

Basically, the compiler requires an opening `{{` and closing `}}`.

**Closed by ematipico** 2024-10-02 12:46 UTC
Labels: feat: styling, - P3: minor bug
