### ISSUE TITLE
Console outputs 404 on page reload with devtools

### ISSUE THREAD

**Issue by Zettexe** [withastro/astro#4230] opened 2022-08-10 09:23 UTC
### What version of `astro` are you using?

1.0.0-rc.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Console outputs `[serve]    404 /@id/astro/runtime/client/astro_runtime_client_hmr__js.js.map` on page reload when devtools are open. Does not appear to do it on Stackblitz.

Steps to reproduce:
1. npm create astro (I used recommended settings)
2. Load/reload webpage with devtools open

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-08-10 09:26
I think this is a duplicate of #4219

**Closed by bluwy** 2022-08-10 09:26 UTC
