### ISSUE TITLE
Page works as expected in dev, but not production build

### ISSUE THREAD

**Issue by thdoan** [withastro/astro#6888] opened 2023-04-22 00:41 UTC
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

After spending countless hours perfecting our site in dev mode (`astro dev`), we were dismayed to find that many things broke in production (`astro build`). Steps to reproduce:

1. See it working [as expected](https://stackblitz.com/edit/github-y5t9cq), with the text sliding up on page load.
2. Download the project, run `astro build` and view the same page in your browser.

ISSUE -- The page doesn't load the same as in dev mode (step 1):

https://www.loom.com/share/802aa43daf594ae9b3fc0b71fa444e97

The main reason for this bug report is to point out that the development and production output should be visibly identical so that developers can have confidence that whatever they're building in dev will be reflected accurately in production. I hope the build process can be improved such that either the dev environment also produces the "yoyo" glitch seen in the loom, or the prod environment no longer produces the glitch -- either way is fine as long as both environments produce a consistent output.

Note that I've verified that this issue can be resolved by inlining the CSS, a scenario in which PR #6659 would come in very handy.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-y5t9cq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by visrut7** [comment] 2023-04-22 15:51
I think it's also related to my issue #6892 I can try to resolve this problem but I need some guidance on where to start and what files should I look into.

**Comment by lilnasy** [comment] 2023-04-25 19:24
https://user-images.githubusercontent.com/69170106/234381336-3188b6a9-134d-4a25-9cea-83d82a24b38b.mov

The build output animates like it says.

**Comment by matthewp** [comment] 2023-04-28 18:49
I'm seeing the same as @lilnasy here. Maybe it was fixed in a patch? Please file a new issue if you have problems. Thanks.

**Closed by matthewp** 2023-04-28 18:49 UTC

**Comment by thdoan** [comment] 2023-04-28 19:52
Thanks for checking. I tried publishing the minimal test case on Netlify and was not able to reproduce the issue. It seems this issue is only reproducible in my local web server ([Mongoose](https://github.com/cesanta/mongoose) v4.1).

**Comment by hansfigo** [comment] 2023-04-29 14:54
I have similar problem but mine is the javascript is not working on certain pages in build production. but in dev mode its works perfectly.  I haven't found a solution yet. Perhaps anyone give me some suggestions?

**Comment by vasi26ro** [comment] 2023-06-08 01:26
> I have similar problem but mine is the javascript is not working on certain pages in build production. but in dev mode its works perfectly.  I haven't found a solution yet. Perhaps anyone give me some suggestions?
> 
> 
> 
> 

I have the same issue. Did you found a fix?

**Comment by Albertyhu** [comment] 2023-09-02 06:30
I am also experiencing the same problem where my site renders fine in development mode, but the css and javascript files could not be loaded in production mode. 

site: https://main--idyllic-crumble-facf8a.netlify.app/
Github repository: https://github.com/Albertyhu/uthan-template

**Comment by lilnasy** [comment] 2023-09-02 13:58
@Albertyhu This is not a bug. Astro does not process <link> tags, it leaves them as-is.

You may want to read the documentation for styling.
https://docs.astro.build/en/guides/styling/#import-a-local-stylesheet

**Comment by Albertyhu** [comment] 2023-09-06 03:06
@lilnasy Thanks for the suggestion.
