### ISSUE TITLE
define:vars not working in Safari

### ISSUE THREAD

**Issue by aleksa-codes** [withastro/astro#5064] opened 2022-10-13 07:39 UTC
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac, iOS

### Describe the Bug

The issue was closed but the problem is still there: https://github.com/withastro/astro/issues/4859

Check my footer in Safari on Mac/iOS for a reproduction of the problem.

code: https://github.com/aleksa-codes/astro-portfolio/blob/main/src/components/Footer.astro

### Link to Minimal Reproducible Example

https://aleksa.codes

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by rhizodigital** [comment] 2022-10-13 09:01
I have same issue, In scripts the value is available directly inside script tag, but not inside a function. Works in firefox and chrome.


<img width="470" alt="Screenshot 2022-10-13 at 10 00 25" src="https://user-images.githubusercontent.com/69630853/195552522-96040f08-737c-4981-946e-9b90d73d7ee7.png">

**Comment by rishi-raj-jain** [comment] 2022-10-14 06:08
@aleksa-codes @matthewp something is making <script> as <script>{ when being added as a HTML Parts before render takes place. Not able to find the place where this extra curly brace could've been added.

<img width="1512" alt="Screenshot 2022-10-14 at 11 37 32 AM" src="https://user-images.githubusercontent.com/46300090/195774336-bafe6c8f-76ba-4897-a0bc-6a72576689f7.png">

**Comment by rishi-raj-jain** [comment] 2022-10-17 07:00
@aleksa-codes I think it's more of a astro/compiler issue to detect? Those extra curly braces after the tag 👀

**Comment by janreges** [comment] 2022-10-25 20:03
+1 ... curly braces `{}` which Astro adds to `<script>` with `define:vars` also causes the Alpine JS scripts to malfunction in Safari.

@matthewp is there any chance a fix for this critical problem will be in the next release of Astro?

**Comment by janreges** [comment] 2022-10-25 22:16
@matthewp and @natemoo-re - all these problems in Safari are probably caused by changes in this PR https://github.com/withastro/astro/pull/3976

I understand that `{}` are used to avoid redeclaration errors (which can be encountered by some use-cases), but unfortunately it causes fatal problems in Safari.

Unless there is a better solution for this situation, I suggest that the addition of `{}` be controlled by some configuration parameter. What do you think about it?

At the same time, I think that if someone decides to use `define:vars` in a repeatedly inserted component, they should ensure that these global variables have unique names. Typically containing e.g. entity ID, so e.g. ```<script define:vars={{`name_${componentId}`: $name}}`> ... </script>``

**Comment by rishi-raj-jain** [comment] 2022-10-26 05:10
Why do we need those {} at all?
Reassigning won't be possible as the variable are defined with const (as
let fails with safari scoping methods)

**Comment by janreges** [comment] 2022-10-26 07:38
@rishi-raj-jain - it was a good intention from @natemoo-re and it solves a situation where a component with `<script define:vars>` is inserted more than once on the page. Thanks to that, wrapping it in `{}` will not cause reassignment, which would otherwise result in an error.

In my opinion, the addition of `{}` should not be automatic, but should be set by explicitly setting, for example, `is:scoped`. So `{}` would only be added in the case of a definition e.g. `<script is:scoped define:vars={{ ... }}>`.

At the same time, I would expect this behavior to be implemented in the `renderElement` method: https://github.com/withastro/astro/blob/37cb2fc02a03754d454b243579bc55e55cf72904/packages/astro/src/runtime/server/render/util.ts#L109

I was debugging this last night and it was very confusing to me that the logic isn't just inside the method.

**Comment by rishi-raj-jain** [comment] 2022-10-28 06:03
@matthewp @natemoo-re

**Comment by maxcountryman** [comment] 2022-10-28 18:11
Hi folks, are there any workarounds in the meantime? I can rewrite component with React, etc but that is truly an awful situation to be in. Safari is not a niche browser, so this feels like an incredibly important issue to address.

**Comment by matthewp** [comment] 2022-10-28 18:20
@janreges do you know the reason why the `{}` breaks in safari? Agree that this is more of a priority.

**Comment by matthewp** [comment] 2022-10-28 18:41
Pretty sure it's this bug: https://bugs.webkit.org/show_bug.cgi?id=179698

**Comment by matthewp** [comment] 2022-10-28 18:47
Got a fix in the works.

**Closed** 2022-10-28 20:13 UTC
Labels: p5-urgent, p4-important
