### ISSUE TITLE
Image component seems to be broken

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#7517] opened 2023-06-29 06:59 UTC
### What version of `astro` are you using?

2.7.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Sandbox / MacOS

### What browser are you using?

Chrome (but not relevantt)

### Describe the Bug

I have a project using the latest version of all astro packages and don't know when exactly some images are not being rendered at all.

I get errors like:

```
Buffer has an unsupported format
```

or

```
 Input buffer has the corrupt header: glib: XML parse error
```

You can find a post that renders a broken image: https://www.raulmelo.me/en/blog/learning-golang-as-javascript-dev-intro

Initially, I thought it was something related to the CDN of those images (I'm using Sanity) but when I created a sandbox in Stackblitz and tried that out, the same problem occurs with basic images.

### What's the expected result?

Render the images properly

### Link to Minimal Reproducible Example

- https://stackblitz.com/edit/github-flmzqu
- https://github.com/raulfdm/broken-img-component

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by raulfdm** [comment] 2023-06-29 09:13
Update:

1. When I switch from squoosh to sharp, the `<Image>` component worked out, but the `<Picture>` doesn't.
2. On stackblitz it seems to have a different problem, it might worth run it locally

**Comment by GrantBirki** [comment] 2023-06-30 02:57
I'm having an issue with the image component as well. When running `npm run dev` on version `0.17.0` I have no issues. When upgrading to `0.17.1` I get 500 errors and all images on my site fail to load.

**Comment by natemoo-re** [comment] 2023-08-17 00:03
Hello! I'm sorry for the delay. The `@astrojs/image` integration has been deprecated in favor of the built-in [`astro:assets`](https://docs.astro.build/en/guides/assets/) feature. 

Since I wasn't able to reproduce this issue using the recommended `astro:assets`, I think it's fair to close this. Please feel free to re-open if you run into the same problem there, though.

**Closed by natemoo-re** 2023-08-17 00:03 UTC
Labels: - P4: important, pkg: image
