### ISSUE TITLE
Redirects cause incoherent errors

### ISSUE THREAD

**Issue by jesper-bylund** [withastro/astro#8384] opened 2023-09-03 12:56 UTC
### Astro Info

```block
Astro                    v3.0.7
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari, Arc, Firefox

### Describe the Bug

I am moving a blog, and also changing route structure. This is causing issues in the build step, which seems to make incoherent errors pop out.

My blog has two old patterns of routes:
`domain.com/[year]/[month]/[day]/[slug]`
and 
`domain.com/[year]/[month]/[slug]`

while the new site uses
`domain.com/blog/[slug]`

I have added the following redirect:
```
  redirects: {
    "/[year]/[month]/[day]/[...slug]": {
      status: 301,
      destination: "/blog/[...slug]?y=[year]&m=[month]&d=[day]"
    },
    "/[year]/[month]/[...slug]": {
      status: 301,
      destination: "/blog/[...slug]?y=[year]&m=[month]"
    },
  }
```

Which gives the following error:
```
 error   `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
  Hint:
    See  https://docs.astro.build/en/core-concepts/routing/#dynamic-routes  for more information on dynamic routes.

    Alternatively, set `output: "server"` or `output: "hybrid"` in your Astro config file to switch to a non-static server build. This error can also occur if using `export const prerender = true;`.
    See  https://docs.astro.build/en/guides/server-side-rendering/  for more information on non-static rendering.
  Error reference:
    https://docs.astro.build/en/reference/errors/get-static-paths-required/
  File:
    /[year]/[month]/[day]/[...slug]
  Stacktrace:
GetStaticPathsRequired: `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
```

### What's the expected result?

I would expect redirects to execute first, never testing the route of the redirected URL. But it seems like that is happening?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1v2muo?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-09-05 19:16
Hey @jesper-bylund, this is intentional behavior. The reason is that redirects in Astro are not required to be to pages that are within your project. We actually never check if that route exists as it might not. Instead we just get all of the pages generated in the *from* field in the config and generate redirects from that. So I would recommend creating a page with a getStaticPaths. It's ok if it's a duplicate of what you have in the *to* page.

**Comment by matthewp** [comment] 2023-09-06 13:24
Going to go ahead and close this, please reach out in Discord if you have any trouble setting this up, thanks!

**Closed by matthewp** 2023-09-06 13:24 UTC
Labels: needs response
