### ISSUE TITLE
`client:only` is not working for React Sub Component.

### ISSUE THREAD

**Issue by faizananwerali** [withastro/astro#10545] opened 2024-03-24 19:54 UTC
### Astro Info

```block
Astro                    v4.5.8
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/sitemap
                         astro-robots-txt
                         astro-imagetools
                         astro-compress
```

### Describe the Bug

This is my Hero.tsx file

```react.js
import {
  Meteors,
  Section,
} from '@components/index.tsx';

const Hero = () => (
  <Section>
    {/* Meaty part - Meteor effect */}
    <Meteors number={20} client:only="react" />
  </Section>
);

export { Hero };
```

`client:only` is not working for React Sub Component.

I want to render sub component of react page only client side, in this case Meteor animation should only render in client side.

<img width="1277" alt="Screenshot 2024-03-25 at 12 56 04 AM" src="https://github.com/withastro/astro/assets/12691366/e31b19a4-10b7-4fc8-96a0-c62a63519e79">

### What's the expected result?

This should work or looking for a way to client render react sub component.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment] 2024-03-25 06:49
Hi @faizananwerali,

The minimal reproducible example you provided is Astro's main codebase. Could you provide another one that reproduces the problem you encountered?

**Comment by faizananwerali** [comment] 2024-03-25 12:51
This is just an example. Now I need to convert a lot of my .tsx files to .astro files and their syntaxes.

I thought I could use Astro with React very easily without changing much.

**Comment by lilnasy** [comment] 2024-03-25 15:41
> I can not use the client:only for React Sub Components.

That is correct. However, you can achieve the same effect by composing your components differently.

For example, if `Meteor` client-side only, and `Section` and the rest of `Hero` server-side only, you can slot `Meteor` as a child of `Hero`.

### `components/Hero.tsx`
```tsx
import {
  Section,
} from '@components/index.tsx';

const Hero = ({ children }) => (
  <Section>
    {children}
  </Section>
);

export { Hero };
```

### `pages/index.astro`
```astro
---
import { Hero } from "../components/Hero.tsx"
---
{/* No client directive. Therefore, renders only on the server */}
<Hero>
  {/* Meaty part - Meteor effect - renders only within the browser */}
  <Meteors number={20} client:only="react" />
</Hero>
```

**Comment by faizananwerali** [comment] 2024-03-25 16:31
Yeah this is what I've done also.

> What you have to remember using this pattern, is that context providers (createContext) in the Hero component will not be readable by context consumers (useContext) in Meteors.

Very important info indeed.

**Comment by lilnasy** [comment] 2024-03-25 17:40
Good luck!

Closing as `client:only` is not intended to have effect in non-`*.astro` files.

**Closed by lilnasy** 2024-03-25 17:40 UTC
Labels: needs repro
