### ISSUE TITLE
the slug property has disappeared from my collections

### ISSUE THREAD

**Issue by alberto-ln** [withastro/astro#12233] opened 2024-10-15 11:20 UTC
### Astro Info

```block
Astro                    v5.0.0-beta.4
Node                     v20.16.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  @astrojs/netlify
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         load-itcss
                         @sanity/astro
                         @astrojs/preact
```

### Describe the Bug

I use the slug property to create static pages and all pages have stopped mounting.

In v5.0.0-beta.1 this works perfectly, but when I switch to v5.0.0-beta.4 the slug property disappears, if I use another property of the collection to mount the pages it works. I have the property inside data.

![image](https://github.com/user-attachments/assets/14935194-48df-4d4d-9f8f-12c7488999b5)

### What's the expected result?

I hope to be able to use that property within data or to know if I have to find another name for the property.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/alberto-ln/astro-bug-slug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-10-15 11:38
Duplicate of https://github.com/withastro/astro/issues/12162

**Closed** 2024-10-15 11:38 UTC
Labels: needs triage
