### ISSUE TITLE
When a Svelte component is the only item on an Astro page Tailwind CSS does not get incorporated

### ISSUE THREAD

**Issue by squeezeboxhuf** [withastro/astro#7050] opened 2023-05-10 10:47 UTC
### What version of `astro` are you using?

2.4.3

### Are you using an SSR adapter? If so, which one?

node (but also tried none)

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I have TailwindCSS and Svelte integrations both added using the "astro add" method, and both working. I added an Astro page that all it has on it is a reference to a Svelte component. The Svelte component is rendered, but no Tailwind CSS is added to the page at all.  It appears completely processed.

If in my Astro page I add any other HTML element before or after the Svelte component then the Tailwind magic happens!

Here's my plain Astro file where the component appears unstyled...

```
---
import { getCollection } from "astro:content";
import Recipes from "../components/Recipes.svelte";
const recipes = await getCollection("recipe");
---
<Recipes client:load recipes={recipes} />
```

My Svelte component contains some Tailwind styling but gets rendered without any CSS added, using browser defaults.

```
script lang="ts">
  export let recipes;
//other logic here...
 
</script>


<section class="recgrid">
  <ul>
    {#each recipes as recipe}
      <li
        class="bg-sky-500 bg-cover bg-center rounded-lg"
        style="
          background-image:
            {recipe.data.image &&
          `url(/images/${recipe.data.image
            .split('.')
            .slice(0, -1)
            .join('.')}.webp)`}  "
      >
        <a href={`/recipe/${recipe.slug}`}>
          <div
            class="reclink px-4 py-2 h-40 sm:h-60 shadow-md rounded-lg bg-transparent"
          >
            <h3
              class="text-xl sm:text-3xl text-slate-50 font-semibold sm:font-bold"
            >
              {recipe.data.title}
            </h3>
          </div>
        </a>
      </li>
    {/each}
  </ul>
</section>
```

Just adding an H1 to the page sorts it out, the Tailwind gets incorporated for the Astro page and the Svelte component:

```
---
import { getCollection } from "astro:content";
import Recipes from "../components/Recipes.svelte";
const recipes = await getCollection("recipe");
---
<h1>{recipes.length} Recipes</h1>
<Recipes client:load recipes={recipes} />
```

I can always add some content before the component, but this sent me round in circles for a while...

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gapubm

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment] 2023-05-14 21:53
Closing as duplicate of #6225

**Closed by MoustaphaDev** 2023-05-14 21:53 UTC
