### ISSUE TITLE
Styling issues when `@chakra-ui/react` is used with `prerender`

### ISSUE THREAD

**Issue by kstulgys** [withastro/astro#5980] opened 2023-01-25 16:19 UTC
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a route `[slug].astro`
This route has `getStaticPaths` and `prerender=true`
When I `build` and `preview` a website I see that only the first dynamic route is prerendered. 
Minimal Reproducible Example is added.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ojbn1i?file=src/pages/products/[slug].astro 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-01-25 18:28
If you look in the `dist/` directory after running `npm run build`, you can see that every page under `products/` is prerendered to an `.html` file, so the issue is not that these routes are not prerendered. Maybe there's some issue going on with styles?

**Comment by kstulgys** [comment] 2023-01-25 18:54
Good point. Either way looks strange since all dynamic pages are same.

**Comment by natemoo-re** [comment] 2023-01-25 19:44
My initial guess is that this styling issue is because `@chakra-ui` uses emotion which is not fully supported. There's much more detail in https://github.com/withastro/astro/issues/4432

**Comment by kstulgys** [comment] 2023-01-26 20:37
I see this issue is tagged as "has workaround". What is a workaround then?

**Comment by bluwy** [comment] 2023-06-26 08:08
Closing this in favour of #4432.

**Closed by bluwy** 2023-06-26 08:08 UTC
Labels: p2-has-workaround
