### ISSUE TITLE
🐛 BUG: Svelte Component not hydrated when also importing Astro Component

### ISSUE THREAD

**Issue by adlichhammer** [withastro/astro#3197] opened 2022-04-24 16:44 UTC
### What version of `astro` are you using?

v1.0.0-beta.17 

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

See fork on stackblitz - maybe i dont understand some basic concepts?

**Observed**
1.  Create a simple page with a svelte counter button - counts clicks (index.astro)
2. Duplicate the page but move the (identical) html head into a seperate Astro component - does not count clicks (see bug.astro) 

**Expected**
Setup 2. works the sameway as Setup 1.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-a7r6oj-qfcwpu?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pyronaur** [comment] 2022-04-25 17:36
Uh, just ran into the same thing.

**Comment by natemoo-re** [comment] 2022-05-10 20:31
This should definitely work! Prioritizing this for an urgent fix—thanks for opening an issue.

**Comment by natemoo-re** [comment] 2022-05-12 17:16
I'm going to close this as a duplicate of https://github.com/withastro/astro/issues/3197, it's the same issue with having `<head>` delegated to a component.

**Closed by natemoo-re** 2022-05-12 17:16 UTC
Labels: p5-urgent, s1-small
