### ISSUE TITLE
Tailwind base styles not displaying correctly with dev server

### ISSUE THREAD

**Issue by jeffrimko** [withastro/astro#7743] opened 2023-07-21 04:01 UTC
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Create an empty template with `npm create astro@latest` followed by `npx astro add tailwind`. Create a `src/styles/main.css` with the some [base styles](https://tailwindcss.com/docs/adding-custom-styles#adding-base-styles) like the following:

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  h1 {
    @apply font-extrabold text-3xl text-red-500;
  }
}
```

Update `src/pages/index.astro` to import `main.css`. Note that when viewing with the dev server, h1 tags are red but the `font-extrabold text-3xl` styles do not apply. Exit the dev server and run `npm run build` then start a server for the `dist` directory, note that the `font-extrabold text-3xl` styles are now applied.

Noticed the above issue today but haven't investigated it much. Thought originally I might have been doing something wrong but seems odd that there are inconsistencies between the dev server and the built static page.

### What's the expected result?

The base styles should render as expected in both the dev server and the static output.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yyryod?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-08-11 15:42
I think you want to use this option: https://github.com/withastro/astro/tree/e1a886530f0c0077b5c94251ab2e9c428d761e7b/packages/integrations/tailwind#applybasestyles

Disabling the integration's base styles is what you want to do when you need to set your own.

**Comment by matthewp** [comment] 2023-08-11 16:27
Talked with people on the team and we're not confident on a way to warn this properly. Still open to do so in the future if we or anyone else can think of how to do so. Closing as this is not a bug, please use `applyBaseStyles: false`. Thank you!

**Closed by matthewp** 2023-08-11 16:27 UTC
Labels: - P4: important, pkg: tailwind
