### ISSUE TITLE
Top-level awaits are not working for imports in Astro components

### ISSUE THREAD

**Issue by kireerik** [withastro/astro#7284] opened 2023-06-03 05:46 UTC
### What version of `astro` are you using?

2.5.7

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

(Dynamic imports are not working in Astro components (not even a very simple one).)

(Simple ones work fine in Node.js modules.)

### Link to Minimal Reproducible Example

⠀

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-06-05 08:00
Please provide a repro. It works for me: https://stackblitz.com/edit/github-t3nmym?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by natemoo-re** [comment] 2023-07-05 13:24
Thanks for opening an issue! Unfortunately, without a proper reproduction, we're unable to help get this fixed. In an effort to keep all issues in this repository actionable, we've decided to close this issue for now.

If you're still having trouble and are able to provide a reproduction in the future, please let us know.

**Closed by natemoo-re** 2023-07-05 13:24 UTC
Labels: needs-repro
