### ISSUE TITLE
is:global not global and wrong filename

### ISSUE THREAD

**Issue by GuidanceZero** [withastro/astro#6337] opened 2023-02-23 05:37 UTC
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

When I ran `npm run build` with index.astro and contactus.astro, the dist produce 2's contactus.123456.css, confuse that Astro could not generate global CSS? 

index.astro
```
<style is:global>
...
</style>
```

contactus.astro
```
<style is:global>
...
</style>
```

When i have 404.astro with no CSS style in this file, I get 404.123456.css which supposely should be name as index.123456.css instead.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by GuidanceZero** [comment] 2023-02-23 07:16
Further seems that it use the name from lower character range. if a.astro which is lower than i in index.astro, Astro will generated a.css

**Comment by bluwy** [comment] 2023-02-23 11:36
Can you provide a repro where this happens?

**Comment by matthewp** [comment] 2023-02-23 17:58
Closing until we get an example. I think this might just be confusion about file names and not a bug. A file name is not a 1:1 match with the files it is derived from.

**Closed by matthewp** 2023-02-23 17:58 UTC
Labels: needs response
