### ISSUE TITLE
astro check reports issues in /dist/ and /node_modules 

### ISSUE THREAD

**Issue by gkatsanos** [withastro/astro#9072] opened 2023-11-12 09:40 UTC
### Astro Info

```block
I added an npm script to my package.json file: 

    "typecheck": "astro check",
```

Here's my tsconfig:
```json
{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "allowImportingTsExtensions": true,
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "@assets/*": ["src/assets/*"],
      "@components/*": ["src/components/*"],
      "@pages/*": ["src/pages/*"],
      "@helpers/*": ["src/helpers/*"],
      "@layouts/*": ["src/layouts/*"],
      "@constants/*": ["src/constants/*"],
      "@experiments/*": ["src/experiments/*"],
      "@middleware/*": ["src/middleware/*"],
      "@store/*": ["src/store/*"],
      "@i18n/*": ["src/i18n/*"],
      "@scripts/*": ["src/scripts/*"]
    },
    "jsx": "preserve",
    "plugins": [
      {
        "name": "@astrojs/ts-plugin"
      }
    ],
  }
}
```

### Describe the Bug

I'm getting errors from files in... `dist` :

```
1324 function _sfc_ssrRender$u(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                             ~~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:1283:73 - warning ts(6133): '$data' is declared but its value is never read.

1283 function _sfc_ssrRender$v(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                             ~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:1283:65 - warning ts(6133): '$setup' is declared but its value is never read.

1283 function _sfc_ssrRender$v(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                     ~~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:1156:73 - warning ts(6133): '$data' is declared but its value is never read.

1156 function _sfc_ssrRender$w(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                             ~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:1156:65 - warning ts(6133): '$setup' is declared but its value is never read.

1156 function _sfc_ssrRender$w(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                     ~~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:1045:73 - warning ts(6133): '$data' is declared but its value is never read.

1045 function _sfc_ssrRender$x(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                             ~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:1045:65 - warning ts(6133): '$setup' is declared but its value is never read.

1045 function _sfc_ssrRender$x(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                     ~~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:849:25 - warning ts(6385): 'escape' is deprecated.

849       .replace(/[()]/g, escape);
                            ~~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:778:80 - warning ts(6133): '$options' is declared but its value is never read.

778 function _sfc_ssrRender$y(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                                   ~~~~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:778:73 - warning ts(6133): '$data' is declared but its value is never read.

778 function _sfc_ssrRender$y(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
                                                                            ~~~~~
dist/server/chunks/pages/rfq_ce2fd3bc.mjs:778:65 - warning ts(6133): '$setup' is declared but its value is never read.

778 function _sfc_ssrRender$y(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
```

### What's the expected result?

no errors in dist? 

### Link to Minimal Reproducible Example

unable to provide

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-11-12 11:51
Duplicate of https://github.com/withastro/language-tools/issues/643

**Closed by Princesseuh** 2023-11-12 11:51 UTC
Labels: needs triage
