### ISSUE TITLE
*.mdx loaded from /content does not support CSS

### ISSUE THREAD

**Issue by jbebe** [withastro/astro#6434] opened 2023-03-06 18:19 UTC
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

If you define a collection and load mdx files from that collection, every *.astro component that is imported into that mdx file will lose its style.

The repro clearly shows that when I use mdx at page level (`/red` app url), the imported Astro component works fine and the text becomes red, but when I choose the defineCollection way and render the mdx file as a component, the style is gone (`/not-red` app url). It is the same behavior for when I import the css class in the inner Astro component. (`/not-red-2` app url)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-ujjlyg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-03-06 18:52
Thanks, taking a look.

**Comment by matthewp** [comment] 2023-03-06 20:36
With content collections you really do need to have a `<head>` element. That's how Astro knows to inject the CSS. See this fix: https://stackblitz.com/edit/astro-y2rbcq?file=src%2Fpages%2Fnot-red.astro

We might wind up creating a `Astro.injectHead()` or something like that, a utility you can use yourself, but until this adding a head in your document fixes it.

**Comment by jbebe** [comment] 2023-03-06 21:29
Sorry for missing the \<html> part, I fixed the stackblitz demo, now the issue might be clearer:
[https://stackblitz.com/edit/astro-ujjlyg](https://stackblitz.com/edit/astro-ujjlyg)

Apparently rendering in the root Astro component yields different output to rendering in a child Astro component.

**Comment by matthewp** [comment] 2023-03-06 21:38
That's helpful, thanks I'll dig into this, then.

**Comment by natemoo-re** [comment] 2023-08-16 20:45
This seems to be a duplicate of https://github.com/withastro/astro/issues/7761 so I'm going to track that there. Feel free to chime in on that conversation!

**Closed by natemoo-re** 2023-08-16 20:45 UTC
Labels: - P2: has workaround
