### ISSUE TITLE
Middleware isn't invoked before rendering the default `404` page

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/astro#8244] opened 2023-08-27 04:54 UTC
### Astro info

```block
Astro version            v2.10.14
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             None or couldn't determine.
```

### What browser are you using?

Chrome

### Describe the Bug

Middleware isn't invoked before rendering the default `404` page. 

NB: I'm uncertain if this is a bug or the intended behaviour 

1. Consider the basic middleware below: 

```ts
import { defineMiddleware } from "astro/middleware";

export const onRequest = defineMiddleware((context, next) => {
  console.log("in middleware");
  return next();
});
```

2. Visit a random page route: e.g., `/uhoihoijoijoijoijoi` 

Result: The middleware is never invoked. No logs. 

3. Add a custom 404.astro page 

```ts 
// src/pages/404.astro
---
console.log("404 page");
---
```

Now, the middleware will be invoked before rendering the custom `404.astro` page. 

```bash 
#logs 
in middleware
404 page
```

### What's the expected result?

Consistently invoke the middleware for both custom and default 404 pages. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-i9px2m?file=src%2Fmiddleware%2Findex.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by syahzuan** [comment] 2023-08-27 13:53
Similar to #8226 .

**Comment by ematipico** [comment] 2023-08-28 10:59
Duplicate of https://github.com/withastro/astro/issues/8226

The origin of the issue is the same.

**Comment by ematipico** [comment] 2023-08-28 11:00
Duplicate of https://github.com/withastro/astro/issues/8226

The origin of the issue is the same.

**Closed by ematipico** 2023-08-28 11:00 UTC
Labels: needs triage
