### ISSUE TITLE
Passed a `encoded url` to endpont as params, get a error

### ISSUE THREAD

**Issue by liruifengv** [withastro/astro#10659] opened 2024-04-03 05:21 UTC
### Astro Info

```block
Astro                    v4.5.12
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

- Create a endpoint `src/pages/test/[url].ts`
```ts
import type { APIRoute } from 'astro';

export const GET: APIRoute = async ({params}) => {

  const target = params.url
  if (!target) {
    return new Response('URL is required', { status: 400 });
  }

  return new Response(`Your url is ${target}`, { status: 200 });

};
```

- Access `http://localhost:4321/test/https%3A%2F%2Fliruifengv.com%2F`
- Throw a error:
![image](https://github.com/withastro/astro/assets/25167721/2c4240ba-96d2-4616-936f-76af7d912e81)

### What's the expected result?

The `encoded url` can be endpoint params.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xx2wzh

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-04-03 07:41
Duplicate of https://github.com/withastro/astro/issues/8516

**Closed by ematipico** 2024-04-03 07:41 UTC
Labels: needs triage
