### ISSUE TITLE
JS Class Props fail in UI Frameworks

### ISSUE THREAD

**Issue by Guergeiro** [withastro/astro#7652] opened 2023-07-14 14:52 UTC
### What version of `astro` are you using?

2.8.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Tested on npm and pnpm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

When instantiating a class in a UI Framework, the properties of the class are not defined.
```ts
// Does not work
export class Service {
  readonly #baseUrl = new URL('https://jsonplaceholder.typicode.com/posts');

  public async get() {
    const res = await fetch(this.#baseUrl);
    if (res.ok === false) {
      throw new Error(res.statusText);
    }
    return await res.json();
  }
}
```

```ts
// Does work
export class Service {
  public async get() {
    const res = await fetch(new URL('https://jsonplaceholder.typicode.com/posts'));
    if (res.ok === false) {
      throw new Error(res.statusText);
    }
    return await res.json();
  }
}
```

```ts
// In a Solid component
import {
  type Component,
  createResource,
  Suspense,
  For
} from "solid-js";
import {Service} from "../services/Service"

const service = new Service();

const TestComponent: Component = () => {
  const [foo] = createResource(service.get)
  return <Suspense fallback={<p>Error</p>}>
    <For each={foo()}>
      {(item) => {
        return <p>{item.title}</p>
      }}
    </For>
  </Suspense>
}
export default TestComponent;
```

### What's the expected result?

We should be able to use instantiated class properties normally.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tsijuz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-07-14 15:20
If one version works but not the other, maybe your compiler is transforming the TS class in some code unsupported by Solid?

**Comment by Guergeiro** [comment] 2023-07-14 16:01
Weird. In older versions of solid I was able to access properties of classes, but not in new versions.

**Comment by Princesseuh** [comment] 2023-07-17 09:07
Closing, since it seems like the issue is unrelated to Astro.

**Closed by Princesseuh** 2023-07-17 09:07 UTC
