### ISSUE TITLE
🐛 BUG: Dev Server not resetting automatically

### ISSUE THREAD

**Issue by Eloi-Perez** [withastro/astro#3263] opened 2022-05-03 09:02 UTC
### What version of `astro` are you using?

1.0.0-beta.20

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 10 21H2 - PowerShell 7.2.3

### Describe the Bug

Using the development server `astro dev`, when I do a mistake on my code giving me as a result a "500: Internal Error", once I fix the error the server is suppose to reset and show me the website if everything is fine with my code, but every time, I have to reset the server manually.

### Link to Minimal Reproducible Example

Can't reproduce it online

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Eloi-Perez** [comment] 2022-05-03 09:55
I also just tried the Dev Server with WSL2, and here the server is not even watching for changes. Is it something wrong with my computer?

**Comment by Jutanium** [comment] 2022-05-03 19:58
See https://github.com/withastro/astro/issues/3228 and others, this is important

**Comment by Jutanium** [comment] 2022-05-04 18:51
Related issues - I'm not sure which of these have the same root cause, but in all cases we can improve the end-user situation with error boundaries
https://github.com/withastro/astro/issues/3196
https://github.com/withastro/astro/issues/3180
https://github.com/withastro/astro/issues/2921

Panic mode - here there are two problems at hand: one is that there is a bug, and the other is that the compiler shifts into a very unfriendly `panic mode`:
https://github.com/withastro/astro/issues/3204
https://github.com/withastro/astro/issues/3253

We've actually had that named slot issue open for more than two weeks: https://github.com/withastro/astro/issues/3127

**Comment by matthewp** [comment] 2022-05-06 20:12
Upstream PR needs merging before we can fix this one: https://github.com/vitejs/vite/pull/8052

**Comment by matthewp** [comment] 2022-05-09 20:17
Upstream was merged, waiting on a release.

**Comment by matthewp** [comment] 2022-05-10 18:06
After Vite 2.9.9 is merged we can fix this. We need to update the Astro plugin to set `import.meta.hot` here: https://github.com/withastro/astro/blob/1acbcaba9e05ef376ba8f2e550a0ab5bbad35efe/packages/astro/src/vite-plugin-astro/index.ts#L185. Doing so will cause it to correctly invalidate .astro modules when dependencies go from broken to fixed.

**Comment by Jutanium** [comment] 2022-05-10 19:26
Thanks! Will this also fix the issue with `Astro.glob` (i.e., when you put an invalid string in there, and then fix it, the dev server should be good to go)

**Closed** 2022-05-11 19:38 UTC
Labels: upstream, p5-urgent, s1-small
