### ISSUE TITLE
context.cookies.set() can't be used multiple times.

### ISSUE THREAD

**Issue by eigood** [withastro/astro#7058] opened 2023-05-10 20:30 UTC
### What version of `astro` are you using?

2.2.2

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Line

### What browser are you using?

Chrome 109

### Describe the Bug

```javascript
export async function get(context) {
  const { cookies } = context
  cookies.set('A', '1')
  cookies.set('B', '2')
  cookies.set('C', '3')
  return {
    body: JSON.stringify({
      message: 'set 3 cookies',
    }),
  }
}
```

```shell
root@tooz:/var/lib# wget -O /dev/null --debug http://localhost:3333/api/multiple-cookies
DEBUG output created by Wget 1.21 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts
URI encoding = ‘UTF-8’
--2023-05-10 15:23:04--  http://localhost:3333/api/multiple-cookies
Resolving localhost (localhost)... ::1, 127.0.0.1
Caching localhost => ::1 127.0.0.1
Connecting to localhost (localhost)|::1|:3333... connected.
Created socket 4.
Releasing 0x000055d26cd5f590 (new refcount 1).

---request begin---
GET /api/multiple-cookies HTTP/1.1
User-Agent: Wget/1.21
Accept: */*
Accept-Encoding: identity
Host: localhost:3333
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
content-type: text/plain;charset=utf-8
set-cookie: A=1, B=2, C=3
Date: Wed, 10 May 2023 20:23:04 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

---response end---
200 OK

Stored cookie localhost 3333 /api/ <session> <insecure> [expiry none] A 1, B=2, C=3
Registered socket 4 for persistent reuse.
URI content encoding = ‘utf-8’
Length: unspecified [text/plain]
Saving to: ‘/dev/null’

/dev/null                                                 [ <=>                                                                                                                    ]      27  --.-KB/s    in 0s      

2023-05-10 15:23:04 (4.26 MB/s) - ‘/dev/null’ saved [27]
```

That single set-cookie header line is bad.  If I do this same call in chrome, then look at the Application tab of the debugger, I have a single cookie called "A", with a value of "1, B=2, C=3".

Fyi, this is running in node 18.9.0.

### Link to Minimal Reproducible Example

#

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-05-11 08:33
Seems like duplicate of https://github.com/withastro/astro/issues/6525, and is fixed in Astro v2.4

**Comment by eigood** [comment] 2023-05-16 18:12
```javascript
export async function get(context) {
  const { cookies } = context
  cookies.set('A', '1')
  cookies.set('B', '2')
  cookies.set('C', '3')
  return new Response({
    message: 'set 3 cookies',
  }, {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'set-cookie': 'foo',
    },
  })
}
```

It's still broken; if the response being returned has a set-cookie header already, then the 3 cookies.set() calls are not represented in the output.  This is breaking my integration with auth-astro/next-auth.  I'm using astrojs 2.4.4 this time.

**Comment by eigood** [comment] 2023-05-16 18:25
If I have '-set-cookie' as the name of the Response header, then the 3 cookies(A, B, C) end up getting set.  Astro is failing to merge the headers.

**Comment by matthewp** [comment] 2023-06-12 17:18
Astro does not merge Astro.cookies cookies with those manually set by Set-Cookie. The RFC describes this: https://github.com/withastro/roadmap/blob/main/proposals/0025-cookie-management.md#serializing-cookie-changes

Going to close. If you have a use-case for changing this please bring it up as a roadmap discussion item: https://github.com/withastro/roadmap/discussions

**Closed by matthewp** 2023-06-12 17:18 UTC
Labels: p4-important
