### ISSUE TITLE
Astro does not add Content-Length Response header for default

### ISSUE THREAD

**Issue by alexandregiordanelli** [withastro/astro#6518] opened 2023-03-12 00:34 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

anyone

### Describe the Bug

Astro does not add Content-Length Response header for default

### Link to Minimal Reproducible Example

Astro does not add Content-Length Response header for default

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment] 2023-03-13 09:28
@alexandregiordanelli Can you link a reproducible example for this? In case of a static project, it'd be upto the CDN provider.

**Comment by natemoo-re** [comment] 2023-03-13 14:45
Yes, a reproduction or more some more detail will be necessary to debug this. It looks like we are adding `Content-Length` in the default case, so maybe this is an edge case where that isn't handled? 
https://github.com/withastro/astro/blob/95164bfdd2c1cbe5f1fafeab9e998ee4c85df3e3/packages/astro/src/core/app/index.ts#L251

**Comment by matthewp** [comment] 2023-03-13 19:38
@natemoo-re That code is for SSR. According to the issue, this is not SSR, so I assume they mean in dev mode.

We likely don't have this header due to streaming, I assume it's not possible in a streaming context as you don't know what the content length will be.

**Comment by matthewp** [comment] 2023-03-28 18:10
Closing as I don't think this is solvable.

**Closed by matthewp** 2023-03-28 18:10 UTC
