### ISSUE TITLE
VSCode "Go To Definition/Implementations/.." in web-component,  opens "index.astro.0.mts" 

### ISSUE THREAD

**Issue by ambrt** [withastro/astro#11333] opened 2024-06-25 10:28 UTC
### Astro Info

```block
Astro                    v4.11.1
Node                     v20.4.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/svelte
                         astro-global
```

### Describe the Bug

I have a web component in `index.astro` file. When in VSCode i click any of "Go to Definition/Implementations/References" on a function inside this component, it  opens new empty file "index.astro.0.mts".
It happens both for functions in `constructor` and for methods.

### What's the expected result?

VSCode should go to function inside of web component.

### Link to Minimal Reproducible Example

not applicable

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-06-25 11:15
Duplicate of https://github.com/withastro/language-tools/issues/876

**Closed** 2024-06-25 11:16 UTC
Labels: needs triage
