### ISSUE TITLE
2.1.5 regression: `astro check` fails with “`astro sync` command failed to generate content collection types”

### ISSUE THREAD

**Issue by andersk** [withastro/astro#6629] opened 2023-03-22 20:37 UTC
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

`astro check` fails in a project using collections. It worked in 2.1.4.

This can be reproduced in the standard blog example (https://astro.new/blog).

```console
❯ astro check
01:33:17 PM [check] Checking files
 error   `astro sync` command failed to generate content collection types.
  Hint:
    Check your `src/content/config.*` file for typos.
  File:
    /home/projects/aonipylmz.github/node_modules/astro/dist/core/errors/errors.js:26:5
  Code:
    25 |   }
    > 26 |   setLocation(location) {
         |     ^
      27 |     this.loc = location;
      28 |   }
      29 |   setName(name) {
  Stacktrace:
Error
    at AstroError (file:///home/projects/aonipylmz.github/node_modules/astro/dist/core/errors/errors.js:26:5)
    at sync (file:///home/projects/aonipylmz.github/node_modules/astro/dist/core/sync/index.js:83:11)
```

### Link to Minimal Reproducible Example

https://astro.new/blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment] 2023-03-22 23:51
Confirmed this was introduced by #6617, which resolved a _different_ urgent issue 😓 

Tagging @bluwy and @MoustaphaDev in case they have context on this change. Seems to be an issue resolving the `astro:content` virtual module.

**Closed** 2023-03-23 13:30 UTC
Labels: p5-urgent
