### ISSUE TITLE
Getting frontmatter from custom remarkPlugins

### ISSUE THREAD

**Issue by rwwagner90** [withastro/astro#4581] opened 2022-09-01 00:07 UTC
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

It seems frontmatter is empty when defining `remarkPlugins`.

Setting arbitrary frontmatter is easy with remarkPlugins, but there seems to be no way to get existing frontmatter. For example, this will not work:

```js
import authorData from './data/authors.mjs';

export function addAuthorRemarkPlugin() {
  return function (tree, post) {
    const author = authorData[post.data.astro.frontmatter.author];
    post.data.astro.frontmatter.author = author;
  }
}
```

### Link to Minimal Reproducible Example

https://github.com/shipshapecode/website-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment] 2022-09-01 20:54
Ah, third request I've seen for this! Definitely think this is worth implementing. Will make a PR soon 👍

**Comment by bholmesdev** [comment] 2022-09-07 19:10
Marking as duplicate of this to track in one place #4429. Still on my todos!

**Closed by bholmesdev** 2022-09-07 19:10 UTC
Labels: p2-nice-to-have
