### ISSUE TITLE
SSR Rendering client:only component slow

### ISSUE THREAD

**Issue by do-web** [withastro/astro#5889] opened 2023-01-18 11:41 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Iam using SSR with node. If i the page renders my vue component is loading very slow. 

`<MyCom client:only="vue" />`

So if i run this with native vue it renders much faster and it does apear immediately.

### Link to Minimal Reproducible Example

https://imgur.com/a/37M6SQW

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by do-web** [comment] 2023-01-18 12:27
With <MyCom client:idle="vue" /> it works as expected. 

But i have also found another bug in Firefox with `<MyCom client:only="vue" />` iam using i18next in this client component, the translation is not always loaded in Firefox, it seams it does not refresh the component. If i click on the button where the translation is missing, the translation then apears.

**Comment by natemoo-re** [comment] 2023-01-25 22:51
[`client:only`](https://docs.astro.build/en/reference/directives-reference/#clientonly) components will not render a placeholder in the initial markup. Based on your video, I think that's all that is happening. The only reason to use `client:only` over `client:idle` is if the component **CAN'T** be rendered on the server because it needs access to DOM APIs like `window`.

**Comment by matthewp** [comment] 2023-02-02 22:10
Rereading, this seems like a misunderstanding of what client:only is for and not a bug. Closing.

**Closed by matthewp** 2023-02-02 22:10 UTC
Labels: needs response
