### ISSUE TITLE
Content-Type header is ignored in server.headers config option

### ISSUE THREAD

**Issue by sapegin** [withastro/astro#6593] opened 2023-03-19 10:12 UTC
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Edge, Firefox

### Describe the Bug

With this Astro config:

```ts
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';

export default defineConfig({
	output: 'server',
	server: {
		headers: { 'Content-Type': 'text/html;charset=utf-8', test: 'pizza' },
	},
	integrations: [react()],
	vite: {
		plugins: [vanillaExtractPlugin()],
	},
});
```

And after running `astro dev` and opening the homepage, the `Content-Type` is ignored and only `test` header is correctly sent to the browser:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/70067/226168446-65dfd292-9dbb-45bb-ac94-af81ba63c0b1.png">

This is causing an incorrect encoding in the browsers (even with the `<meta charset="utf-8" />` tag in the layout) in at least two browsers — Edge and Firefox. 

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/github/withastro/astro/tree/latest/examples/basics?on=codesandbox&file=%2FREADME.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment] 2023-03-22 07:16
mark

**Comment by darioguarascio** [comment] 2023-03-26 06:57
Same issue, running as middleware with expressjs

**Comment by doganalper** [comment] 2023-04-06 22:22
Same issue. Could this be happening because `createResult` function in `packages/astro/src/core/render/result.ts`. By checking source code briefly found only that place where `Content-Type` is being set as `text/html` directly.

**Comment by bholmesdev** [comment] 2023-04-07 20:31
Thanks for filing @sapegin! First, I'll say that setting a `'Content-Type'` from your `server.headers` probably isn't what you want. This will set the content type for _every_ file in your project, including images and stylesheets. We'd definitely suggest sticking with `<meta>` tags for this, or [setting via `Astro.response.headers()`](https://docs.astro.build/en/guides/server-side-rendering/#astrorequestheaders) in your templates.

We're also [working on a middleware API](https://github.com/orgs/withastro/projects/11/views/1?filterQuery=middlewa&pane=issue&itemId=23655544) that should negate the need for `server.headers`. To avoid short term breaking changes, we plan to leave this `server.headers` override behavior as-is.

I'm also surprised to here including that `<meta charset="utf-8">` doesn't resolve your issue. That's the intended solution. Can you share a reproduction (ideally with Stackblitz) to see if I can replicate? I tried visiting the basics template you sent but everything looks correct there.

**Comment by bholmesdev** [comment] 2023-04-10 15:38
Polite bump to @sapegin and others running into a charset issue!

**Comment by bholmesdev** [comment] 2023-04-25 17:39
Since we have a recommended fix with action items, I'm going to close this issue. Report new repros below in case we missed anything!

**Closed by bholmesdev** 2023-04-25 17:39 UTC
Labels: p3-minor-bug, needs-repro
