### ISSUE TITLE
Component Template errors after running

### ISSUE THREAD

**Issue by MrAmericanMike** [withastro/astro#8786] opened 2023-10-09 19:07 UTC
So I was following the guide here as to how to create a component to publish to NPMJS: https://docs.astro.build/en/reference/publish-to-npm/

(Apart from the guide been a bit confusing) one of the first steps mentions to run:

```
pnpm create astro@latest my-new-component-directory -- --template component
```

After doing this and opening the index.ts file an error shows in `'./src/MyComponent.astro'` that says:

>Cannot find module './src/MyComponent.astro' or its corresponding type declarations.(2307)

Here is an stackblitz illustrating the problem: https://stackblitz.com/edit/github-gg5qiw?file=my-new-component-directory%2Findex.ts
```


### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Errors out of the box when using provided template.

### What's the expected result?

To not see any error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gg5qiw?file=my-new-component-directory%2Findex.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-10-10 09:42
The error in your message isn't a runtime error, it's because Stackblitz does not run our tooling and so cannot get the types from `.astro` files.

**Comment by MrAmericanMike** [comment] 2023-10-11 18:49
> The error in your message isn't a runtime error, it's because Stackblitz does not run our tooling and so cannot get the types from `.astro` files. Are you encountering the same error (or another error) outside Stackblitz?

Yes, exact same error when working locally inside Visual Studio Code

**Comment by lilnasy** [comment] 2023-10-25 00:20
I am getting a different error.
![image](https://github.com/withastro/astro/assets/69170106/60b2c140-6fc7-40c8-a214-df7a977eda3b)

Fixed by setting `jsx: preserve` in tsconfig.json.

**Comment by bluwy** [comment] 2024-01-03 16:10
It seems to also be the case for starlight: 
<img width="710" alt="image" src="https://github.com/withastro/astro/assets/34116392/13e90c47-1ab5-4194-9860-86825c6bbbcd">

@Princesseuh would the fix for this be on the language tools side, or is there a `jsx` misconfiguration, or is it an expected behaviour for now?

**Comment by Princesseuh** [comment] 2024-01-03 16:58
Hmm, the best way would be to add `jsx: 'preserve'` to our `tsconfig.json` templates, but I'm not sure if this could potentially cause issues with compilation? If it doesn't cause issues, then that would be my suggestion.

**Comment by bluwy** [comment] 2024-01-04 07:50
`jsx: 'preserve'` seems to work fine after a few tests that also mixes React stuff. I could try adding that to the templates then as the solution for now.

**Closed** 2024-01-04 11:06 UTC
Labels: - P2: nice to have, feat: typescript
