### ISSUE TITLE
Wildcard routes can have the wrong priority order in `@astrojs/netlify` _redirects config

### ISSUE THREAD

**Issue by tony-sull** [withastro/astro#8121] opened 2023-08-17 19:17 UTC
### What version of `astro` are you using?

2.10.9

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

Looks like there's a corner case in routing priority order, specifically with the sort order of wildcard routes when building for Netlify.  This was introduced sometime after `@astrojs/netlify@2.1.3`, upgrading to latest ran into this bug

With the file structure below,

```
pages
├─ [slug].astro
├─ themes
       ├─ [...page].astro
```

the build `dist/_redirects` file ends up with redirects in the wrong order (below)

```
/:slug                    /:slug/index.html                   200
/themes/*             /.netlify/functions/entry           200
```

With this order, Netlify will match a request to `/themes` with the static `/:slug` fallback instead of the more specific `/themes/*` route.

### What's the expected result?

The redirects should be order should be flipped so that the `/themes/[...page]` takes priority

```
/themes/*             /.netlify/functions/entry           200
/:slug                    /:slug/index.html                   200
```

### Link to Minimal Reproducible Example

na

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-17 19:31
I fairly sure this is a duplicate of https://github.com/withastro/astro/issues/8121 so I'm going to move this convo over there.

**Closed by natemoo-re** 2023-08-17 19:31 UTC
Labels: needs triage
