### ISSUE TITLE
Cookies from middleware don't get set on custom 404 page

### ISSUE THREAD

**Issue by xriter** [withastro/astro#7880] opened 2023-07-31 15:06 UTC
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When cookies are being set in middleware (using `Astro.cookies.set`), but the page request resolves to a (custom) 404 page, the cookies don't get set/send.

### What's the expected result?

Even when a page resolves to 404, cookies must be able to be set from middleware.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bpkd5t?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-07-31 16:13
> When cookies are being set in middleware (using Astro.cookies.set), but the page request resolves to a (custom) 404 page, the cookies don't get set/send.

You shared a reproduction, but you didn't specify how we can reproduce the issue. I opened the link but I am really sure what I am supposed to.

**Comment by ematipico** [comment] 2023-07-31 16:14
FYI, when calling `next()`, you **must `return`**. Not doing so will cause issues.

**Comment by ematipico** [comment] 2023-07-31 16:17
I just tried to read the cookie from the 404, and it's correctly set.

**Comment by natemoo-re** [comment] 2023-08-01 20:54
Looks like this has been fixed in [Astro 2.9.7](https://github.com/withastro/astro/releases/tag/astro%402.9.7) by #7754. Please upgrade `astro` and any integrations to the latest version.

Please see [minimal reproduction](https://stackblitz.com/edit/github-bpkd5t-jruzzh?file=src%2Fpages%2F404.astro).

**Closed by natemoo-re** 2023-08-01 20:54 UTC
Labels: needs response, - P3: minor bug
