### ISSUE TITLE
Module CSS is not loaded when a react/solidjs component is the only element on a page

### ISSUE THREAD

**Issue by DenisStad** [withastro/astro#6374] opened 2023-02-26 13:32 UTC
### What version of `astro` are you using?

2.0.15

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

If using a single react or solid-js component in a page, and the component uses a module.css, that css is only loaded if you have a html element on the page.

Example:

The react component `Test.tsx`:
```
import s from './test.module.css' // Import a module css here!

export function Test() {
  return (<div className={s.test}>This should be red. If it isn't, something's not working.</div>);
}
```

And the index page, `index.astro`:

```
---
import { Test } from '../components/Test'
---

<Test />
```

The component's module.css is not loaded. If you add an empty `<div>` to `index.astro`, the css module is loaded and styles are applied.

I tested with react and solid-js, both have that bug.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-5clnso?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment] 2023-02-26 16:57
@DenisStad 

I think it's very important to appreciate the HTML syntax. If you atleast add html and body tag to this, it works. I don't think that shall be an issue.

**Comment by DenisStad** [comment] 2023-02-26 21:02
@rishi-raj-jain very true, that works if you add the tags in the astro component. If however you add the `html` and `body` tags in the react component, it still doesn't work. I updated the example accordingly.

Is that for some reason not supported?

**Comment by MoustaphaDev** [comment] 2023-02-28 00:16
Closing as duplicate of https://github.com/withastro/astro/issues/6225
As @rishi-raj-jain said, you could wrap your component with html/body or just have another other element in the astro page itself

About your second issue, [this comment](https://github.com/withastro/astro/issues/6144#issuecomment-1419116556)  explains why you can't have `html` inside component islands

**Closed by MoustaphaDev** 2023-02-28 00:16 UTC
