### ISSUE TITLE
Astro file parsing and including strings with angle brackets

### ISSUE THREAD

**Issue by readonlychild** [withastro/astro#2717] opened 2022-03-04 01:52 UTC
### What version of `astro` are you using?

0.23.5

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I am bringing some content from an API, and some strings contain like "<script>" in them and it breaks when doing a map loop like in the stackblitz repro.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b84cdd?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by natemoo-re** [comment] 2022-03-04 22:59
Ah interesting. This is actually being caused by Vite stepping in and trying to parse the HTML after Astro generates it... Not sure how we can fix this but we definitely need to. See also https://github.com/withastro/astro/issues/2583

**Comment by FredKSchott** [comment] 2022-03-12 00:45
Confirmed fixed in v0.24.0!

**Closed by FredKSchott** 2022-03-12 00:45 UTC
Labels: upstream
