### ISSUE TITLE
Dev server becomes unusably slow as content collection grows

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#10269] opened 2024-02-28 17:37 UTC
### Astro Info

```block
Astro                    v4.4.6
Node                     v21.6.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
                         @astrojs/sitemap
```

### Describe the Bug

The dev server becomes unresponsive for several seconds after each edit to a content entry. This duration becomes longer the larger the content folder grows.

The astro docs project (~1850 MDX files)
<img width="293" alt="image" src="https://github.com/withastro/astro/assets/69170106/e62b3bb8-6eba-4ee5-9f8d-53b2aac307bf">

After deleting 1000 content entries
<img width="293" alt="image" src="https://github.com/withastro/astro/assets/69170106/22e64abf-2935-4e64-a552-3f1f7d21d83b">

After the period of unresponsiveness, the rendering itself remains fast (~100ms).
<img width="374" alt="image" src="https://github.com/withastro/astro/assets/69170106/00924961-829d-47f4-a334-aae6b0aa2acb">

### What's the expected result?

The dev server remains responsive.

### Link to Minimal Reproducible Example

https://github.com/withastro/docs/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment] 2024-02-28 17:40
Funnily enough, deleting the content entries made it unresponsive for much longer, suggesting that astro is invalidating and loading _all_ content entries on _every_ chokidar event.

<img width="374" alt="image" src="https://github.com/withastro/astro/assets/69170106/60f91913-b165-49ee-8c4b-6459ef78c8aa">
<br/>
<img width="374" alt="image" src="https://github.com/withastro/astro/assets/69170106/f80d64df-7753-4236-a4d3-d5c781bf7751">

**Comment by matthewp** [comment] 2024-03-04 16:43
I guess we can keep this as the definitive "collections doesn't scale" issue. It will be fixed by *that other thing* I suppose. But nothing we can likely do about it in the meantime.

**Comment by ascorbic** [comment] 2024-10-03 11:27
I'm closing this as a duplicate of #7241

**Closed by ascorbic** 2024-10-03 11:27 UTC
Labels: needs response, - P2: nice to have, feat: content collections, requires refactor

**Comment by lilnasy** [comment] 2025-01-18 18:41
This is still true of the astro v5 with content layer
