### ISSUE TITLE
Template could not be found! with astro@latest -- --template

### ISSUE THREAD

**Issue by Keshav-writes-code** [withastro/astro#12507] opened 2024-11-22 15:01 UTC
### Astro Info

```block
Astro                    v4.16.14
Node                     v20.17.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             unocss
                         @astrojs/svelte
                         astro-icon
```

### Describe the Bug

So astro allows you create new Projects by giving it a github repo in this syntax as mentioned in the docs
```
# create a new project based on a GitHub repository’s main branch
npm create astro@latest -- --template <github-username>/<github-repo>

```
i wanted to create a project using my own git repo so i ran this
`bun create astro@latest -- --template keshavWebDev-personal/astroUnocssDaisyui-template`
but i got this error
```
 astro  Launch sequence aborted.


      ▲  error
         Template keshavWebDev-personal/astroUnocssDaisyui-template could not be found!
      ◼  check
         https://astro.build/examples
```
tried with npm

```
 astro  Launch sequence aborted.

      ▲  error
         Template keshavWebDev-personal/astroUnocssDaisyui-template could not be found!
      ◼  check
         https://astro.build/examples
npm error code 1
npm error path /home/keshav/Programming Stuff/Projects/temp/astroUnocssDaisyui-template
npm error command failed
npm error command sh -c create-astro --template keshavWebDev-personal/astroUnocssDaisyui-template
npm error A complete log of this run can be found in: /home/keshav/.npm/_logs/2024-11-22T14_47_11_076Z-debug-0.log
```
the log it generated :-
[2024-11-22T14_47_11_076Z-debug-0.log](https://github.com/user-attachments/files/17871866/2024-11-22T14_47_11_076Z-debug-0.log)

Tried with my Other Repos, they all worked but not this specific one

### What's the expected result?

It should See the Github Repo as other repos are recognized no problems

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2024-11-22 15:25
Duplicate of https://github.com/withastro/astro/issues/12453

**Closed by bluwy** 2024-11-22 15:25 UTC
Labels: needs triage
