### ISSUE TITLE
i18n experimental routing creates a redirect page in the root

### ISSUE THREAD

**Issue by dallyh** [withastro/astro#9300] opened 2023-12-05 07:50 UTC
### Astro Info

```block
Astro                    v3.6.4
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/sitemap
```

### Describe the Bug

This may be more of a question, than an issue, However I'm not sure if it's the case,

So im fiddling with the new i18n router in SSG mode. 

I have my pages setup with 2 locales, and pages arranged into folders with dynamic routes for `[lang]`, using `getStaticPaths() `function. One of my pages in the root of pages is not in the [lang] folder, and it does not get generated,instead, a page with redirect (with meta refresh tag) to `defaultLocale` in the config is generated - that is when i access http://localhost:4321/ I get redirected to http://localhost:4321/cs/.  This happens only when the `prefixDefaultLocale` is set to `true`.

![image](https://github.com/withastro/astro/assets/6968534/65456276-6702-438a-bd46-2855501b5322)

Is this intended? Does and should the i18n router work well with `getStaticPaths()` dynamic routes? 

 If this is intended, then this should probably be mentioned in the docs. There is a mention that when `prefixDefaultLocale` is set to `true` all routes should be in the `/locale/` folders, but nowhere (maybe i missed it) it says, that the root page is generated as a redirect. The structure even shows this page in the root, so I would assume that it does not get tempered with and it is generated as-is.

![image](https://github.com/withastro/astro/assets/6968534/eba17d06-cc8f-45aa-964c-44ec5674b269)

I had plans to use this page to detect user's prefered language from browser/storage and redirect the user myself, now it is not possible to do so.

If it is not intended and routing should not behave like this, then please tell me and I'll create a reproducible example.

Thanks!

### What's the expected result?

When using i18n routing with `prefixDefaultLocale` is set to `true` the root page should be generated, and not altered to redirect to the `defaultLocale`.

### Link to Minimal Reproducible Example

None for now, please see the description.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-12-05 09:50
Hey @dallyh , thank you for filing the issue.

> but nowhere (maybe i missed it) it says, that the root page is generated as a redirect.

You didn't miss anything, that's on us that we forgot to mention this behaviour in the documentation. I already made sure to mention it. We will deploy the change soon. 

The RFC mentions this behaviour though: https://github.com/withastro/roadmap/blob/main/proposals/0045-i18n-routing.md#routing-strategy

> Is this intended? Does and should the i18n router work well with getStaticPaths() dynamic routes?

Probably yes, although I can't give you proper directions because the original RFC doesn't touch `getStaticPaths`. The feature is about routing, so theoretically, you shouldn't encounter any issue, as long as the generated URL match the expectations set by the i18n routing.

**Comment by dallyh** [comment] 2023-12-05 10:00
@ematipico 

Thanks for the response! Would it be possible to take this as a feature request then? Where if there is a page in the root, it is then generated normally? This would be handy in cases like mine, when I want to control how to redirect the user client side, according to language preferences and such. Now it is also possible, but there would be multiple redirects.

**Comment by ematipico** [comment] 2023-12-05 10:26
That's something that was requested in the RFC. We should be able to implement it, but not now because we are about to release v4.0.

**Comment by ematipico** [comment] 2023-12-06 10:31
Closing for now because that's not a bug and it works as expected

**Closed by ematipico** 2023-12-06 10:31 UTC
Labels: needs triage

**Comment by viniciusdeliz** [comment] 2025-06-30 23:57
@dallyh how did you solve that? maybe configuring redirects for your static hosting provider such as vercel/netlify or else?

**Comment by dallyh** [comment] 2025-07-01 06:00
@viniciusdeliz I don't remember exactly, but I think it was a combination of manual i18n routing and a middleware.
