### ISSUE TITLE
Unable to use %23 (#) in dynamic url

### ISSUE THREAD

**Issue by Elias-Chairi** [withastro/astro#10983] opened 2024-05-09 11:43 UTC
### Astro Info

```block
Astro                    v4.8.0
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
```

### Describe the Bug

When trying to load a dynamic url like `alphabet/:letter.astro` if the `letter` includes or is equal to `%23` i get the error: 
```
Expected "letter" to match "[^\/#\?]+?", but got "#"
```

### What's the expected result?

I expect the page to load with the param resolving to either `#` or `%23`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-x6hzgp?file=astro.config.mjs,src/pages/%5Bdynamic%5D.astro,src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Elias-Chairi** [comment] 2024-05-09 11:43
I am not a expert of any kind :) 
https://github.com/withastro/astro/pull/10965

**Comment by ematipico** [comment] 2024-05-10 14:48
I think this is a duplicate of https://github.com/withastro/astro/issues/8516

**Comment by Elias-Chairi** [comment] 2024-05-10 21:03
I am sorry, i might have explained it poorly. The example in #8516 is with paths generated with the `getStaticPaths` method in static or hybrid mode. My problem is with a path in ssr mode. The example path used in the other issue seems to work fine in a dynamic path in ssr mode.

**Closed** 2024-05-16 08:26 UTC
Labels: - P2: has workaround
