### ISSUE TITLE
JS `//` comments inside JSX-like component template error

### ISSUE THREAD

**Issue by junaga** [withastro/astro#9120] opened 2023-11-17 00:39 UTC
### Astro Info

```block
Astro                    v3.5.5
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### Describe the Bug

given `src/pages/index.astro`

```jsx
{
  // Hello, World!
}
```

errors

### What's the expected result?

I use the VS Code shortcut `CTRL`+`/`. Which comments out selected code in JSX-like expressions with multiple `//` statements. This is inconsistent from Stackblitz, where `CTRL`+`/` comments out JSX-like expressions with HTML comments.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-chqyza?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment] 2023-11-17 02:29
How is this an Astro problem?

**Comment by jacobthesheep** [comment] 2023-11-17 02:33
Sounds like a VSCode or extension issue.

**Comment by junaga** [comment] 2023-11-17 03:23
> Sounds like a VSCode or extension issue.

there is a link to the repro ^^

**Comment by junaga** [comment] 2023-11-17 03:27
from `vite dev`

```  
 error   Unexpected "}"
  File:
    /home/projects/github-chqyza/src/pages/index.astro
  Stacktrace:
Error: Transform failed with 1 error:
/home/projects/github-chqyza/src/pages/index.astro:29:0: ERROR: Unexpected "}"
    at failureErrorWithLog (/home/projects/github-chqyza/node_modules/vite/node_modules/esbuild/lib/main.js:1639:15)
    at eval (/home/projects/github-chqyza/node_modules/vite/node_modules/esbuild/lib/main.js:837:29)
    at responseCallbacks.<computed> (/home/projects/github-chqyza/node_modules/vite/node_modules/esbuild/lib/main.js:693:9)
    at handleIncomingPacket (/home/projects/github-chqyza/node_modules/vite/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/home/projects/github-chqyza/node_modules/vite/node_modules/esbuild/lib/main.js:669:7)
    at EventEmitter.emit (node:events:42:9202)
    at addChunk (node:internal/streams/readable:105:4109)
    at readableAddChunk (node:internal/streams/readable:105:3808)
    at Readable.push (node:internal/streams/readable:105:2679)
    at _0x2c4d79.onStreamRead (node:internal/stream_base_commons:158:2341)
```

**Comment by jacobthesheep** [comment] 2023-11-17 04:32
I'm confused, do js comments not work inside the brackets but html comments do work?
If so, this is not an issue with Astro itself unless you think it should work.

**Comment by junaga** [comment] 2023-11-17 05:56
I think it should work. JS `//` comments don't but JS `/* */` comments do. the [astro docs mention](https://docs.astro.build/en/core-concepts/astro-syntax/#comments) `/* */` comments. I want the other comments too. because VS Code sets them on the commenting hotkey.

**Comment by florian-lefebvre** [comment] 2023-11-17 08:28
https://github.com/withastro/compiler/issues/609#issuecomment-1300432846 seems related

**Comment by matthewp** [comment] 2023-11-17 13:15
Yeah looks like a duplicate of 609, thanks for reporting though!

**Closed by matthewp** 2023-11-17 13:15 UTC
Labels: needs triage

**Comment by MoustaphaDev** [comment] 2023-11-20 15:51
Yeah as @florian-lefebvre pointed, this is a compiler bug. Moving this issue to the compiler repo
