### ISSUE TITLE
🐛 BUG: Tailwind Classes are getting incorrectly escaped

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2780] opened 2022-03-13 16:35 UTC
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu

### Describe the Bug

Some of the complex Tailwind CSS classes are getting incorrectly escaped. For example, the class `2xl:w-[80%]` is getting changed to `\\32xl\\:w-\\[80\\%\\]`. Because of the unnecessary `3`, it's being treated as `32xl:w-[80%]`.

![image](https://user-images.githubusercontent.com/63650415/158069386-950132d7-cf51-4793-a935-09b2d22022ba.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dntvlc?file=src%2Fpages%2Findex.astro

**Comment by FredKSchott** [comment] 2022-03-14 04:25
Thanks for filing! Closing as a duplicate of #2777, but I'll copy/merge the relevant new info from this issue into that one. Looking forward to fixing this

**Closed by FredKSchott** 2022-03-14 04:25 UTC

**Comment by FredKSchott** [comment] 2022-03-14 04:37
Update: @RafidMuhymin this may not be an issue, see: https://github.com/tailwindlabs/tailwindcss/issues/3069. I actually see the class apply to the element in your stackblitz once I make a change to the site, triggering HMR for tailwind. the `\3` seems to be a valid CSS workaround if the class name starts with a number.
