### ISSUE TITLE
🐛 BUG: script tags in components are missing if the component is imported from a JS re-export

### ISSUE THREAD

**Issue by delucis** [withastro/astro#3053] opened 2022-04-10 08:31 UTC
### What version of `astro` are you using?
- [v1.0.0-beta.19](https://stackblitz.com/edit/github-53maw1?file=demo/src/pages/index.astro)

#### Also confirmed in
- v1.0.0-beta.12
- v1.0.0-beta.10
- v1.0.0-beta.7
- v1.0.0-beta.5
- [v0.25.4 (using `hoist`)](https://stackblitz.com/edit/github-53maw1-vjmcf7?file=demo/src/pages/index.astro)
- [v0.24.3 (using `hoist`)](https://stackblitz.com/edit/github-53maw1-sz6dvb?file=demo/src/pages/index.astro)
- [v0.24.0 (using `hoist`)](https://stackblitz.com/edit/github-53maw1-eykfbi?file=demo/src/pages/index.astro)

#### Not present in

- [v0.23.7](https://stackblitz.com/edit/github-53maw1-vkucij?file=demo/src/pages/index.astro)
- [v0.23.7 with `--experimental-static-build`](https://stackblitz.com/edit/github-53maw1-jpa4y5?file=demo/src/pages/index.astro)

☝️ This suggests the bug was introduced between v0.23.7 and v0.24.0 although a lot has changed since then so how helpful it is to know that, I don’t know.

### What package manager are you using?

npm

### What operating system are you using?

macOS 12.2.1 / Stackblitz

### Describe the Bug

If a component includes a `<script>` tag and is re-exported by a JS file (common for packages to expose multiple components from a single entry point), the script is not included when the component is used.

This is the re-export style I mean:

```js
export { default as MyComponent } from './MyComponent.astro';
```

The minimal reproduction shows this by using two components with identical source code, one local, one in a different workspace. Only the script for the local component is included.

The two packages structure is because I initially thought this was due to importing from another package, not specifically importing from an intermediary JS file. Here’s a simpler reproduction without the multi-repo setup: https://stackblitz.com/edit/github-53maw1-uqxxci?file=src/pages/index.astro

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-53maw1?file=demo/src/pages/index.astro

Astro fork with failing test for this bug here: https://github.com/delucis/astro/tree/delucis/3053

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aFuzzyBear** [comment] 2022-04-14 11:36
This would explain why I was having my project fail last night,

**Comment by RafidMuhymin** [comment] 2022-04-14 12:03
I'm facing the same issue when for the `<BackgroundImage />` component of `astro-imagetools`.

**Comment by zk-g** [comment] 2022-04-16 08:55
I have attached another example on discord about this few days ago, I ll copy here:

Attachment: https://discord.com/channels/830184174198718474/960968296520359966/960976630728261696

Seem that happen when you import your package from an `index.js` file.

I ll report the message as well:

^0.26.1 / astro ^1.0.0-beta.2

If I import astro components from a js file, script tags doesn't seem to work (they don't get added to the head)

```js
// import Tour from '../components/Tour.astro'; // <-- Script works
import { Tour } from '../index.js'; // <-- Script doesn't works
```

index.js:

```js
export { default as Tour } from "./components/Tour.astro";
```

script inside Tour.astro:

```html
<script>
alert(':rocket:');
</script>
```

**Comment by hippotastic** [comment] 2022-04-20 14:18
I'm experiencing this issue as well. You can solve it by changing the way you import the component though:
1. Add an entry for each .astro file exported by your component package to its `exports` property in `package.json`.
2. In your project, import the component like this:
  ```js
  ---
  import PackageComponent from '@example/my-component/PackageComponent.astro';
  ---
  ```

## Example package.json:
```js
{
  "name": "@example/my-component",
  "version": "0.0.1",
  "private": true,
  "type": "module",
  "exports": {
    "./PackageComponent.astro": "./PackageComponent.astro"
  }
}
```

## Usage in your project (e.g. `index.astro`):
```html
---
import PackageComponent from '@example/my-component/PackageComponent.astro';
---

<html lang="en">
	<body>
		<div class="wrapper">
			<main class="content">
				<PackageComponent />
			</main>
		</div>
	</body>
</html>
```

**Comment by hippotastic** [comment] 2022-04-20 14:34
I've forked your Stackblitz example and modified it according to my explanation to get it to work:
https://stackblitz.com/edit/github-53maw1-viyrdh

**Comment by tony-sull** [comment] 2022-05-10 22:29
There a few issues related to re-exporting components through a JS file.  Closing this as a duplicate of [#3217](https://github.com/withastro/astro/issues/3217) which we're using as the primary high priority issue to track fixing this :+1:

**Closed by tony-sull** 2022-05-10 22:29 UTC
