### ISSUE TITLE
🐛 BUG: Adding new tailwind classes does not affect in the ui

### ISSUE THREAD

**Issue by mukhtharcm** [withastro/astro#2410] opened 2022-01-17 17:17 UTC
### What version of `astro` are you using?

0.22.13

### What package manager are you using?

pnpm ,npm

### What operating system are you using?

Windows, Stackblitz

### Describe the Bug

Because of the recent migration from `Astro.resolve` ( see #2402  ) , I started to use 
```html
<style global>
  /* @import "../styles/global.css"; */
</style>
```
for importing tailwind CSS.

After this change, whenever I add a new style, I have to restart the Astro server for it to notice the change.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/mukhtharcm/astro-tw-sample?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by RafidMuhymin** [comment] 2022-01-17 17:31
@mukhtharcm It's a cache invalidation issue. The problem is Astro/Vite doesn't know that the `styles/global.css` file has to be updated when you add a class to any pages or components. So, you'll have to update/resave the `BaseHead.astro` (or, the file which contains the `<style>` tag that imports the `.css` file where the tailwind directives have been included) file manually every time you add any tailwind class.

**Comment by mukhtharcm** [comment] 2022-01-17 18:19
After digging is the discord, A workaround for this is to use the old `Astro.resolve` method and add an empty `<style>` tag.

```html
<link rel="stylesheet" href={Astro.resolve("../styles/global.css")} />

<style global>

</style>
```

Don't know why this works, but it works 😃 

@RafidMuhymin Thank you for helping us out!

**Comment by p13rnd** [comment] 2022-01-18 07:48
I stumbled upon the same issue today. While assets are beeing generated fine, the <link ...> to the stylesheet is not included into the header until I add

```html
<style global>

</style>
```

while it works for the time beeing the root cause if this seems to sits deeper as it shouldn't be required at all to have an empty style tag somewhere on the page.

**Comment by jonathantneal** [comment] 2022-01-21 19:47
Yea, this seems like a bug, where something is not being brought into the dependency graph properly.

**Comment by prastoin** [comment] 2022-01-27 09:31
> After digging is the discord, A workaround for this is to use the old `Astro.resolve` method and add an empty `<style>` tag.
> 
> ```
> <link rel="stylesheet" href={Astro.resolve("../styles/global.css")} />
> 
> <style global>
> 
> </style>
> ```
> 
> Don't know why this works, but it works smiley
> 
> @RafidMuhymin Thank you for helping us out!

Thanks :smiley:, Worked for me !

**Comment by n7trd** [comment] 2022-01-28 18:33
Looks like the issue is not only tied to tailwind.
If i add this to my index page:
```
<style global>
  @import "../styles/global.css";
 /* the style is in the src dir*/ 
</style>
```
The page loads the styles but edits don't have an impact. Refreshing the page doesn't work either. I have to restart the dev astro server to see the results. 

This works without an issue:
`<link rel="stylesheet" href={Astro.resolve("../styles/global.css")} />`

**Comment by frankstallone** [comment] 2022-01-28 19:01
I had this issue upgrading from `0.22.1` [on my site](https://stallone.dev)☨ that uses Tailwind. I did not check HMR but publishing to Netlify produced a site without any CSS files. Here is how I am importing CSS:

```html
<link rel="stylesheet" type="text/css" href={Astro.resolve("../styles/global.css")}>
<link rel="stylesheet" type="text/css" href={Astro.resolve("../styles/cartridge.css")}>
<link rel="stylesheet" type="text/css" href={Astro.resolve("../styles/facundo.css")}>
```

I cannot tell from this conversation if we're advocating this odd  empty `style` tag. That looks like an odd workaround that I don't want to have to remember later down the road so for now I reverted back to `0.22.1`.

☨ [GitHub like to my site](https://github.com/frankstallone/frankstallone-portfolio)

**Comment by amir-al-razin** [comment] 2022-01-31 13:22
```html
<link rel="stylesheet" href={Astro.resolve("../styles/global.css")} />

<style global>

</style>
```
this solution worked for me as well. But the css modules are still not loading.

**Comment by tottello** [comment] 2022-02-02 22:53
Having same issue.

**Comment by pyronaur** [comment] 2022-02-15 10:41
It took me way too long to find how to fix this 😂 😬

**Comment by tony-sull** [comment] 2022-02-16 13:19
One other work around I just came across for now is to drop the `@tailwind` imports right into the `<style global>` instead of importing from `global.css`

```astro
<style global>
	@tailwind base;
	@tailwind components;
	@tailwind utilities;
</style>
```

This could be a bit annoying if you include a lot of inline styles for above the fold content, but HMR ends up working since Vite will catch the `.astro` file updates

**Comment by ooliver1** [comment] 2022-02-26 19:35
this does also happen with me

**Comment by frankstallone** [comment] 2022-02-26 22:32
> It works in 0.23.0 with the ESM import in the frontmatter:
> 
> ```
> ---
> import '../styles/global.css'
> ---
> ```
> 
> With this approach, you need to trigger a HMR reload by saving any file when you start the dev server so Astro can pick up the import and inject the link style into the DOM, otherwise you will see an unstyled page. Next reloads will work as expected, it will trigger HMR reload when you make changes to your Tailwind classes.
> 
> In 0.23.1+ you have to save the Tailwind CSS file every time you make changes, i think it's an issue with the [new fine-grained HMR](https://github.com/withastro/astro/pull/2649).

Still sounds like a regression from prior versions of Astro. I am waiting to upgrade until we're at least in the same place we were before the alleged 'cache invalidation issue' or 'something is not being brought into the dependency graph properly'.

**Comment by tony-sull** [comment] 2022-03-01 09:51
Thanks for re-opening and reporting all the details here everyone!  There was a regression in 0.23.1 that specifically impacted Tailwind, causing the issues mentioned above where the `global.css` file itself had to be saved before the dev server would serve the compiled styles

This was fixed in [PR 2681](https://github.com/withastro/astro/pull/2681) and released in `astro@0.23.3` 👍  Sorry for the extra churn here!

**Closed by tony-sull** 2022-03-01 09:51 UTC

**Comment by kelvin-zhao** [comment] 2022-03-10 06:51
```
---
import '../styles/global.css'
---
```

Works for inner pages, but doesn't load any css for the main index file. Not sure if it's because there is no JS used in my index file but it doesn't trigger the injecting of the css.

**Comment by pyronaur** [comment] 2022-03-10 09:15
@kelvin-zhao Is your import in your main index file at the top of the file? I've found that the order of imports is significant at the moment.

**Comment by kelvin-zhao** [comment] 2022-03-10 09:50
@pyronaur, yup it is at the very top. Actually all my pages are using the same Base.Astro layout. All loaded the css except for the index file. But only the index file is just plain html without JS, not sure if that's the reason, or if it's because it's the index and somehow it got missed during the build?

Even during dev, sometimes the css doesn't load for the index, sometimes it does, not sure what triggers or causes it to skip.

**Comment by pyronaur** [comment] 2022-03-10 11:05
Huh, oh well, I have no idea what's going on then. I'd open a new GitHub issue with a reduced test case to demo the issue to get more eyeballs on it.

**Comment by schlichtanders** [comment] 2022-11-11 16:19
I have the same regression - tailwind classes are not updating on the fly...
