### ISSUE TITLE
Images not correctly rotated when using experimental asset service

### ISSUE THREAD

**Issue by eyrewiut** [withastro/astro#7387] opened 2023-06-13 23:14 UTC
### What version of `astro` are you using?

2.6.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

After migrating from the `@astro/image` integration to the experimental asset service, many of my images are not correctly oriented (eg, a 3:4 image becomes 4:3).

Looking at the exif metadata for my images I suspect this might be due to the dimensions in exif and actual pixel dimensions being switched.

one of the incorrectly oriented images is available in the minimal reproduction

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/quiet-leaf-6vvxpd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-06-14 09:14
Just realized this is a duplicate of https://github.com/withastro/astro/issues/7304

**Closed by bluwy** 2023-06-14 09:14 UTC
Labels: p3-minor-bug, assets
