### ISSUE TITLE
Strange CSS generation with Tailwind CSS custom `base.css`

### ISSUE THREAD

**Issue by Tosainu** [withastro/astro#7085] opened 2023-05-14 07:19 UTC
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

My site has the Markdown file that has the following code fragment:
```markdown
---
layout: '../layouts/Layout.astro'
---

[-1:6]
```

With the latest Tailwind integration and custom `base.css`, Astro generates strange CSS.

```
$ npx astro build
04:16:37 PM [content] No content directory found. Skipping type generation.
04:16:37 PM [build] output target: static
04:16:37 PM [build] Collecting build info...
04:16:37 PM [build] Completed in 71ms.
04:16:37 PM [build] Building static entrypoints...
warnings when minifying css:
▲ [WARNING] Expected identifier but found "-1" [css-syntax-error]

    <stdin>:480:2:
      480 │   -1: 6;
          ╵   ~~


04:16:39 PM [build] Completed in 1.22s.

 generating static routes
▶ src/pages/index.md
  └─ /index.html (+10ms)
Completed in 16ms.

04:16:39 PM [build] 1 page(s) built in 1.31s
04:16:39 PM [build] Complete!
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nf8wib?file=src/pages/index.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-05-15 06:05
Duplicate of https://github.com/withastro/astro/issues/6663. Unfortunately it's one of the limitations of Tailwind's JIT implementation itself that's unrelated to Astro.

**Closed by bluwy** 2023-05-15 06:05 UTC
