### ISSUE TITLE
🐛 BUG: Spreading an object with a class key to an element generates two class attributes.

### ISSUE THREAD

**Issue by edazpotato** [withastro/astro#2051] opened 2021-11-29 22:30 UTC
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Spreading an object with a `class` key to an element (an `<a>` in this example) throws an error.
Looking at the error message, it seems that Astro is adding an extra `class` attribute for Astro-generated classes in addition to the one supplied by the object being spread.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/crazy-zhukovsky-7gygz?file=/src/pages/broken.astro

**Comment by natemoo-re** [comment] 2021-11-30 03:26
Going to close as a duplicate of https://github.com/withastro/astro/issues/1978

**Closed by natemoo-re** 2021-11-30 03:26 UTC
