### ISSUE TITLE
Fragment shorthand error when using <= condition

### ISSUE THREAD

**Issue by MKlblangenois** [withastro/astro#7810] opened 2023-07-26 08:49 UTC
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Brave

### Describe the Bug

Got the error `Unable to assign attributes when using <> Fragment shorthand syntax` when I try to use "Less than or Equal to" (<=) syntax to render DOM element. When I invert condition with >=, this work. Adding parentheses doesn't change result

VSCode view :
![Capture d’écran 2023-07-26 à 10 39 21](https://github.com/withastro/astro/assets/42929225/02815dfe-0cf2-4346-b656-41b021c98ca3)

### What's the expected result?

Get my condition working in both ways

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rtgen9?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-07-27 10:32
Duplicate of https://github.com/withastro/compiler/issues/723

**Closed by Princesseuh** 2023-07-27 10:32 UTC
Labels: needs triage
