### ISSUE TITLE
Server-Side Rendering blockers

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#1855] opened 2021-11-17 14:26 UTC
This issue contains blockers for supporting server-side rendering. We need to make decisions on these things before it can be implemented. Since these would be breaking changes it would be good to get these things in before [1.0](https://github.com/snowpackjs/astro/issues/1222).

These are the *potentially* breaking changes that we need to decide on:

# Building without rendering pages

A server-rendered page is not intended to be built in the traditional SSG-sense, even if only to scan the page. Therefore we need a way to know, *without rendering*, the dependencies of a page including:

* Hydrated components
* Hoisted scripts
* Scoped styles
* External stylesheets (in src)
* External images / video, etc (in src)

We need to make a decision on how we can statically build this dependency graph to feed into the SSR build step.

# Statically optimized prerendered pages

Even in an SSR scenario, some pages can be statically rendered at build-time if they never change at (server) run-time. Some other frameworks like Next.js have this feature.

If we want to support this, we need a way to distinguish pages that can be statically prerendered from those that cannot.

This is related to how we are going to pass in request information into a render. With Next.js they use `getServerSideProps`. We currently have `Astro.request`. One option is to remove `Astro.request` and force users to opt-in to reading from the request. Another is to make static-prerendering pages be special in some way, for example by using a filename convention like `$terms-of-service.astro`.

# Use of Node.js APIs

We want Astro server builds to be compatible with any JavaScript runtime, not just Node.js. But with Vite, users can use any Node.js builtin like `import path from 'path';`.

We need to decide to either:

* Disallow using these APIs (and provide alternatives perhaps)
* Build them so that they work on any runtime (might be hard for some)
* Something else.

# Blocking `<head>` rendering (streaming)

Currently we wait for the page to be fully rendered before adding scripts and styles to the head. This allows us to hoist all of a page's subcomponent hydrated scripts/styles.

In an SSR context this effectively means no streaming HTML. If we want to support streaming SSR we need to not do this.

For styles, those will be discovered and built at build-time. For hydrated components (and hoisted scripts), if we allow those to be dynamic then we need some other solution. One possibility is to *not* hoist them into the head, but let the script tags get added where they are used in the body (like we did in 0.20).

# Async Astro components prevents effective out-of-order streaming

Frameworks like Marko have a concept called out-of-order streaming. That is components that need to block on data requests will not be server-rendered, but rather a placeholder is added and they are later rendered through script-tag DOM manipulation.

If we wanted to support a similar feature we would have trouble doing so because *all* of Astro components are async. What this means is that a typical Astro page like:

```astro
<Layout>
  <BlogPost id={id} />
</Layout>
```

Would be rendered as:

```html
<script>/* Layout rendering */</script>
```

That is, a completely blank page with a script that starts building DOM. Ideally want you want rendered is *most* of the static page up front, and script tags only for any blocking components.

If Astro components were not always async we could support the above.

**Comment by natemoo-re** [comment] 2021-11-17 20:05
Thanks for putting this together, it's amazing! Still reading through everything.

One thought on the last point (_Async Astro components prevents effective out-of-order streaming_)... We could theoretically `await` top-level components before kicking into out-of-order mode. Since these would likely always be Layout components, that might make sense.

**Comment by FredKSchott** [comment] 2021-11-24 05:25
Thanks for putting this together! Closing this issue since it's a future-looking investigation and not a bug, but please repost in the RFC repo as a discussion!

https://github.com/withastro/rfcs/discussions

**Closed by FredKSchott** 2021-11-24 05:25 UTC
