### ISSUE TITLE
fail to use antd when build

### ISSUE THREAD

**Issue by ijntvwh** [withastro/astro#6919] opened 2023-04-27 05:46 UTC
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

when i use antd button, fail to build(npm run build)

but it was success in astro@2.2.3

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bjlru4-ygpbih

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-04-27 09:05
Duplicate of https://github.com/withastro/astro/issues/6901

**Closed by bluwy** 2023-04-27 09:05 UTC
