### ISSUE TITLE
Dynamic tags do not pass along style `define:vars`

### ISSUE THREAD

**Issue by Thodor12** [withastro/astro#10683] opened 2024-04-04 20:32 UTC
### Astro Info

```block
Astro                    v4.5.13
Node                     v18.17.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         astro-icon
                         @astrojs/markdoc
                         @astrojs/sitemap
                         minecolonies-submodule
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When you have `define:vars` on a style tag, it's supposed to include the vars in the style of your root element.

Astro does this properly, unless you are using a dynamic tag name:
```html
<div>
  My beautiful content
</div>

<style define:vars={{ path: "test" }}>
</style>
```

Will output:
```html
<div data-astro-cid-r2trt5ig="" style="--path: 'test'"></div>
```

With a dynamic tag name:
```ts
---
const Tag = "div";
---
<Tag>
  My beautiful content
</Tag>

<style define:vars={{ path: "test" }}>
</style>
```

Will output:
```html
<div data-astro-cid-r2trt5ig=""></div>
```

This can be worked around by wrapping the dynamic tag into a parenting div, but realistically that shouldn't be necessary and creates unnecessary clutter in the DOM.

### What's the expected result?

In both instances (with or without a dynamic tag name) should the variables be applied to the root element.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ftigdc-vr9g59

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment] 2024-04-05 08:06
```astro
---
const Tag = "div";
---
<Tag>
  My beautiful content
</Tag>
```

Curious, does that work as is? I mean without styles.

**Comment by Thodor12** [comment] 2024-04-05 14:47
That works @rishi-raj-jain, it's listed in the documentation that you can do this.

**Comment by lilnasy** [comment] 2024-04-05 14:49
This is one of the oddities of scoped styles - it only applies the class or attribute to literal html tags.

When you create a dynamic tag, it behaves the same as a component and the compiler can no longer consider it safe to insert the class or attribute onto a component.

`define:vars` is not a factor in this unexpected behavior.

**Comment by lilnasy** [comment] 2024-04-11 22:00
Closing as this is a design limitation.

**Closed by lilnasy** 2024-04-11 22:00 UTC
Labels: needs response

**Comment by ericc-ch** [comment] 2024-04-15 07:53
Is this going to be mentioned in the docs? Because I checked just now and it's not mentioned yet in these pages [Dynamic Tags](https://docs.astro.build/en/basics/astro-syntax/#dynamic-tags), [Template Directives](https://docs.astro.build/en/reference/directives-reference/#definevars)
