### ISSUE TITLE
Form element contents will be rendered outside of the Form

### ISSUE THREAD

**Issue by daraHK88** [withastro/astro#8765] opened 2023-10-06 14:57 UTC
### Astro Info

```block
Astro                    v3.2.3
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             unocss
                         @astrojs/sitemap
                         astro-compress
                         @vite-pwa/astro-integration
```

### Describe the Bug

The Form element contents will render outside of the form and form element is empty on the browser. the only way to solve it is to remove the map. I don't know if it's me that I'm making a mistake or a bug in the compiler.

run the code and you will see in the inspect of the browser that Form element is empty and whatever that must be inside it is next to it

please check the Form with ID "addApiForm" in the code and browser

### What's the expected result?

the elements that I put inside the form must stay inside the form not be relocated to any other place

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ngr3mk-j76ht7?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-10-09 09:23
Seems like a duplicate of https://github.com/withastro/compiler/issues/870. The table bug is affecting the enclosing of the form.  Also looks like the `{title}` triggers the issue. I'll close this in favour of that.

**Closed by bluwy** 2023-10-09 09:23 UTC
Labels: needs triage
