### ISSUE TITLE
Problem when building with yarn

### ISSUE THREAD

**Issue by rxtsel** [withastro/astro#5981] opened 2023-01-25 18:19 UTC
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

WSL with Debian

### Describe the Bug

I am trying to build the project but I get this error. In development mode everything works perfect, but I need the yarn build command to work because I use github pages.

![image](https://user-images.githubusercontent.com/85462420/214648737-8a05092a-cfb7-484d-84fb-69e318a62de3.png)

### Link to Minimal Reproducible Example

https://github.com/abouthernan/rappicerrajeria

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-01-25 18:28
There's not much we can do to help without seeing your actual code, would you mind sharing a minimal reproducible example?

**Comment by rxtsel** [comment] 2023-01-25 18:32
> There's not much we can do to help without seeing your actual code, would you mind sharing a minimal reproducible example?

I have updated Link to Minimum Reproducible Example

**Comment by natemoo-re** [comment] 2023-01-25 19:39
Thanks! I can reproduce this on the latest version (2.0.1). It looks like some sort of bundling issue based on the structure of the project? I'm very confused why it's referencing a file that doesn't exist.

Will have to dig into this more!

**Comment by natemoo-re** [comment] 2023-01-25 19:46
Marking this as `p4-important` because this repro has a very basic project structure that just doesn't build properly.

**Comment by rxtsel** [comment] 2023-01-27 14:49
Should I go back and redo the project?

**Comment by HiDeoo** [comment] 2023-01-28 10:38
The issue seems to be related to the `src/styles/gallery.modules.css` that should be renamed to `src/styles/gallery.module.css` (extra **s** at `.module.`). 

After doing so and fixing the import in `src/components/Gallery.tsx` to `import styles from '../styles/gallery.module.css'` instead of `import styles from '../styles/gallery.modules.css'`, the project is building fine on my end.

**Comment by rxtsel** [comment] 2023-01-28 16:07
> El problema parece estar relacionado con el `src/styles/gallery.modules.css` que debe ser renombrado a `src/styles/gallery.module.css` ( extra **`s`** a `.module.`).
> 
> Después de hacerlo y fijar la importación en `src/components/Gallery.tsx` a `import styles from '../styles/gallery.module.css'` en lugar de `import styles from '../styles/gallery.modules.css'`, el proyecto está funcionando bien de mi parte.

Wow bro, thank you so much! you saved my life!

**Comment by rxtsel** [comment] 2023-01-28 16:08
> The issue seems to be related to the `src/styles/gallery.modules.css` that should be renamed to `src/styles/gallery.module.css` (extra **`s`** at `.module.`).
> 
> After doing so and fixing the import in `src/components/Gallery.tsx` to `import styles from '../styles/gallery.module.css'` instead of `import styles from '../styles/gallery.modules.css'`, the project is building fine on my end.

Wow bro, thank you so much! you saved my life! Now it works

**Comment by matthewp** [comment] 2023-01-30 20:07
So it looks like it was a code error. Closing, thanks for the assist @HiDeoo

**Closed by matthewp** 2023-01-30 20:08 UTC
Labels: p4-important
