### ISSUE TITLE
Astro Image component appears to be overoptimizing remote URLs

### ISSUE THREAD

**Issue by eastcoasting** [withastro/astro#4276] opened 2022-08-11 21:17 UTC
### What version of `astro` are you using?

1.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When using an image component with the following two urls:

```
`https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3486,37.8169,9,0/500x500@2x?access_token=${ACCESS_TOKEN}`

`https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-0.4006,42.0879,5.01,0/500x500@2x?access_token=${ACCESS_TOKEN}`
```
Astro appears to generate only one of the two images in `dist/_image`. In dev this issue does not exist, and the image component generates two different images/maps. The following code can reproduce the difference between dev/prod. I looked into the shorthash function [here](https://github.com/withastro/astro/commit/299b4afcab090bbe014d4eaf2a5ea439e8436bcc), and found that it generated two different hashes for the set of URLs as expected (when including the full access token).

```
---
import Layout from '../layouts/Layout.astro';
import { Image } from '@astrojs/image/components';
// Removing the key for the issue; does not seem unique to mapbox to get an access token: https://account.mapbox.com/auth/signup/
const ACCESS_TOKEN = "TOKEN"
---

<Layout title="MRE">
  <main>
    <Image
      format={"webp"}
      width={500}
      height={500}
      class="relative top-1/2 left-1/2 transform -translate-x-1/2 z-10 rounded-md"
      src={`https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3486,37.8169,9,0/500x500@2x?access_token=${ACCESS_TOKEN}`}
    />

    <Image
      format={"webp"}
      width={500}
      height={500}
      class="relative top-1/2 left-1/2 transform -translate-x-1/2 z-10 rounded-md"
      src={`https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-0.4006,42.0879,5.01,0/500x500@2x?access_token=${ACCESS_TOKEN}`}
    />
  </main>
</Layout>
```

**Dev**:
![image](https://user-images.githubusercontent.com/62911962/184243153-29a3ac56-6725-4ba8-b585-16802136be22.png)

**Prod**:
![image](https://user-images.githubusercontent.com/62911962/184243068-47ad4728-24f6-4adf-a767-104fa652b383.png)

### Link to Minimal Reproducible Example

https://github.com/eastcoasting/astro-overoptimized-images

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment] 2022-08-11 21:56
I've assigned @tony-sull to help take a look when he gets back, but if anyone else can dig into why this might be happening that would be great. The fact that shorthash is working properly is very curious.

**Comment by tony-sull** [comment] 2022-08-25 22:12
@eastcoasting Looks like this should be fixed in the latest release, would you mind updating your local reproduction to the latest `@astrojs/image` release to confirm?

A recent release updated how remote URLs are handled, in SSG builds the optimized image filename now includes a hash of the full original URL :+1:

**Comment by eastcoasting** [comment] 2022-08-29 20:50
Can confirm this is fixed in prod - glad to see the keys at the end are also hashed. Thanks!

**Closed** 2022-08-29 20:50 UTC
Labels: p3-minor-bug
