### ISSUE TITLE
Astro v5.0.4 - [astro:db] [vite] cannot find entry point module 'astro:db'

### ISSUE THREAD

**Issue by cameronapak** [withastro/astro#12699] opened 2024-12-09 16:24 UTC
### Astro Info

```block
Astro                    v5.0.4
Node                     v22.5.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             astro:db
                         @astrojs/db/file-url
                         @astrojs/tailwind
                         @astrojs/alpinejs
```

### Describe the Bug

When running `npm run dev`, I encounter an error message in the console that says:

```bash
[ERROR] [astro:db] [vite] cannot find entry point module 'astro:db'.
```

This has been referenced in https://github.com/withastro/astro/issues/12474, but I find that it was not fully fixed. 

### What's the expected result?

I expect it to not product and print that Vite error for Astro DB.

### Link to Minimal Reproducible Example

https://github.com/cameronapak/freedom-stack/pull/45

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JeremyPittard** [comment] 2024-12-10 00:51
If it's any help for evidence I am also seeing this on windows 11 running node 22.12 and WSL. I am also finding the db does not seed with seed.ts.

**Comment by jackmcpickle** [comment] 2024-12-10 09:08
getting same issue on new install 

```
Astro                    v5.0.4
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         astro:db
                         @astrojs/db/file-url
```

**Comment by jackmcpickle** [comment] 2024-12-10 09:10
NOTE - working when I use `pnpm dev --remote`

**Comment by PaiiNKiilleRD** [comment] 2024-12-10 21:55
Same here

 "dependencies": {
    "@astrojs/check": "^0.9.4",
    "@astrojs/cloudflare": "^12.0.1",
    "@astrojs/db": "^0.14.3",
    "@astrojs/rss": "^4.0.10",
    "@astrojs/sitemap": "^3.2.1",
    "astro": "^5.0.4",
    "typescript": "^5.7.2"
  }

**Comment by ngdangtu-vn** [comment] 2024-12-11 04:48
Me too,

```
$ bun -v
1.1.37
```

```json
"dependencies": {
  "@astrojs/cloudflare": "^12.0.1",
  "@astrojs/db": "^0.14.3",
  "@astrojs/sitemap": "^3.2.1",
  "@astrojs/solid-js": "^5.0.0",
  "@astrojs/tailwind": "^5.1.3",
  "astro": "^5.0.4",
  "astro-icon": "^1.1.4",
  "solid-devtools": "^0.30.1",
  "solid-js": "^1.9.3",
  "tailwindcss": "^3.4.16"
}
```

It seems like everyone in here have a problem with this integration in Astro 5 right?

**Comment by mckoda09** [comment] 2024-12-12 18:42
```
Astro                    v5.0.5
Node                     v23.3.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
                         ```
the same issue

**Comment by ascorbic** [comment] 2024-12-13 07:15
I'll try and get a patch release out today with the fixes: https://github.com/withastro/astro/pull/12716

**Comment by mckoda09** [comment] 2024-12-13 08:56
@ascorbic so the patch will be soon?

**Comment by ascorbic** [comment] 2024-12-13 10:49
I'll try to get it out today.

**Comment by jeffscottward** [comment] 2024-12-15 20:27
Is this possibly related to my issue with a very basic form request?

`TypeError: Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded".`

Using this example basically verbatim:
https://docs.astro.build/en/guides/astro-db/#insert

**Comment by mckoda09** [comment] 2024-12-15 20:46
@jeffscottward i guess no, because db works, just a little error in console.

**Comment by jeffscottward** [comment] 2024-12-15 20:59
> @jeffscottward i guess no, because db works, just a little error in console.

Upon inspecting, its `POST`ing as `text/html` even if I put `enctype="multipart/form-data"` in the `<Form>`

I verified it's 
- pulling from remote Turso. (test data record in remote db)
- `.env` config
- Seed / Config / FormData / Insert / Schema all align
- Busted cache
- Checked `dev --remote` flag. 

Im totally stumped even with AI help.
This code is the only thing that could possibly be causing it. 
I've commented it out and this is culprit

```js
---
import { db, cashOfferRequests } from "astro:db";

if (Astro.request.method === "POST") {
  try {
    const formData = await Astro.request.formData();

    const firstName = formData.get("firstName")?.toString() ?? "";
    const lastName = formData.get("lastName")?.toString() ?? "";
    const email = formData.get("email")?.toString() ?? "";

    if (
      firstName &&
      lastName &&
      email
    ) {
      await db.insert(cashOfferRequests).values({
        firstName,
        lastName,
        email,
      });
    }
  } catch (error) {
    console.error("Error processing form submission:", error);
  }
} 

---

<form
  id="sellForm"
  method="POST"
  enctype="multipart/form-data"
  class="bg-[#F5F5DC] p-8 rounded-lg shadow-lg space-y-12"
>
```

Theres something here and its not me almost for sure.

**Comment by jeffscottward** [comment] 2024-12-15 22:11
Confirmed bug in isolated repo:
See https://github.com/withastro/astro/issues/12741

**Comment by ascorbic** [comment] 2024-12-16 11:33
Thanks everybody. There's no need for any more details. The fix for this is already merged. To be clear: you can safely ignore the warning. Your sites will still work. The error will disappear once we put out a release.

**Closed by ascorbic** 2024-12-16 11:33 UTC
Labels: - P2: nice to have, pkg: db

**Comment by cameronapak** [comment] 2024-12-16 16:09
Wonderful. Thanks so much @ascorbic !

**Comment by LLLisa** [comment] 2024-12-17 01:22
So glad the Astro team is on the ball like this. I ran into this bug Saturday, found this issue and decided to wait to see if it would be fixed on Monday, and it was. Big kudos

**Comment by JeremyPittard** [comment] 2024-12-17 01:49
Thankyou muchly, has also resolved my issue.

**Comment by Keshav-writes-code** [comment] 2025-04-04 13:46
>  To be clear: you can safely ignore the warning. Your sites will still work. The error will disappear once we put out a release.

Is the release out now?
