### ISSUE TITLE
After build, package is not defined

### ISSUE THREAD

**Issue by lalagis** [withastro/astro#8728] opened 2023-10-02 17:02 UTC
### Astro Info

```block
Astro                    v3.2.1
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         unocss
```

### Describe the Bug

astro dev runs normally, but when I use build and then preview, I encounter an error: Uncaught (in promise) ReferenceError: Cesium is not defined.
![image](https://github.com/withastro/astro/assets/62090328/1f59cbf5-a445-47ca-a775-e932f3177ea3)
In _astro js:
![image](https://github.com/withastro/astro/assets/62090328/41855b2c-7e40-4802-8439-0b2583c3f0fc)

### What's the expected result?

show as in astro dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9z3dkb

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-10-03 14:27
The issue is that `vite-plugin-cesium` uses [transformIndexHtml](https://github.com/nshen/vite-plugin-cesium/blob/3fb46a510d3c90a7f2c0b9533bdb02f3b45dae4e/src/index.ts#L106-L113) to link the build output of Cesium global runtime. Astro doesn't run the `transformIndexHtml` hook as it doesn't work for us, and it only applies to Vite-handled HTML pages.

As a workaround, you can add that script yourself by placing this in the `<head>` of `Layout.astro`:

```jsx
{import.meta.env.PROD && <script src={`${import.meta.env.BASE_URL}cesium/Cesium.js`}></script>}
```

As this isn't something Astro supports by default, I'll close this as expected behaviour.

**Closed by bluwy** 2023-10-03 14:27 UTC
Labels: needs triage
