### ISSUE TITLE
npm create astro --yes should skip all questions

### ISSUE THREAD

**Issue by totalhack** [withastro/astro#8543] opened 2023-09-13 16:12 UTC
### Astro Info

```block
N/A, this happens during install using the `npm create astro` helper. It's the "v3.0.13 launch sequence."
```

### Describe the Bug

The `--yes` option doesn't seem to skip all questions as the help string suggests. You can get by this by specifying a template but I believe `--yes` should use the recommended template and not prompt the user. As a new user it's unclear to me what templates would be equivalent to the options below (perhaps the template name should be in that output?).

```
$ npm create astro newdir -- --skip-houston --yes

 astro   v3.0.13 Launch sequence initiated.

      ◼  dir Using newdir as project directory

  tmpl   How would you like to start your new project?
         ● Include sample files (recommended)
         ○ Use blog template 
         ○ Empty 
```

```
create-astro [dir] [...flags]

             --help (-h)  See all available flags.
       --template <name>  Specify your template.
--install / --no-install  Install dependencies (or not).
        --git / --no-git  Initialize git repo (or not).
              --yes (-y)  Skip all prompt by accepting defaults.
               --no (-n)  Skip all prompt by declining defaults.
               --dry-run  Walk through steps without executing.
          --skip-houston  Skip Houston animation.
                   --ref  Choose astro branch (default: latest).
                 --fancy  Enable full unicode support for Windows.
   --typescript <option>  TypeScript option: strict | strictest | relaxed.
```

### What's the expected result?

Astro gets setup with the recommended starter defaults.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment] 2023-09-13 17:47
Looking at the code, `--yes` does behave as expected.

**Comment by jacobthesheep** [comment] 2023-09-13 18:22
I guess since it displays `Include sample files (recommended)`, it should choose that option when running `--yes`

**Comment by lilnasy** [comment] 2023-09-14 22:35
`--yes` is working as intended, all the yes-or-no questions are skipped. The part that doesn't get skipped is template selection, which is not a yes or no question. You can explicitly add a template to skip that part as well, for example `--template blog`.

**Comment by jacobthesheep** [comment] 2023-09-19 22:03
This issue can be closed. PR has been merged.

**Closed** 2023-09-20 07:42 UTC
Labels: needs discussion
