### ISSUE TITLE
Netlify Not rendering 404 page , but npm run dev rendering correctly.

### ISSUE THREAD

**Issue by MuntasirSZN** [withastro/astro#12099] opened 2024-10-01 15:07 UTC
### Astro Info

```block
Astro                    v4.15.9
Node                     v22.6.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             astro-robots-txt
                         @astrojs/react
                         @astrojs/tailwind
                         @astrojs/partytown
```

### Describe the Bug

Running npm run dev shows the 404 custom status page, but not in production, In Netlify. 

### What's the expected result?

Everything Should Work Correctly.

### Link to Minimal Reproducible Example

https://github.com/STEAMer-Academy/steamer-academy.me

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-10-02 10:37
I am going to close the issue because the reproduction is no longer valid.

**Closed by ematipico** 2024-10-02 10:37 UTC
Labels: needs response
