### ISSUE TITLE
`vite.build.cssCodeSplit = false` breaks all CSS in Astro prod build

### ISSUE THREAD

**Issue by soluml** [withastro/astro#4413] opened 2022-08-21 18:34 UTC
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows (WSL)

### Describe the Bug

When attempting to disable [CSS Code splitting in Vite](https://vitejs.dev/config/build-options.html#build-csscodesplit), I noticed that CSS when running `astro build` completely breaks.  

In the attached stackblitz, everything works well but if you kill the server and run `npm run build && npm run preview` You'll see attached screenshot below. 

![image](https://user-images.githubusercontent.com/589571/185805704-ea39a8dd-4869-40ca-b062-172db6bacec0.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kx19h2?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Ernxst** [comment] 2022-08-21 20:40
I've been trying to get code splitting working as well. You get no styling because the `<link />` tag to the final stylesheet `style.[hash].css` is not injected into the page and I have no clue why this occurs. 

I've published an integration to do this (`npm i --save-dev @ernxst/astro-cssbundle` - not on GitHub yet, but is a default export) while this issue gets resolved. It works by globbing the output directory for a css file and then creates an AST for each HTML page, adding a new `<link />` AST element (linking to the css file) as a child of the `<head />` AST element.

**Comment by matthewp** [comment] 2022-08-22 20:12
Thanks, I think we probably need to add support for this config option in our CSS build plugin.

**Comment by matthewp** [comment] 2022-08-22 20:13
@bluwy going to assign to you. I would assume the problem is happening in this plugin: https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/vite-plugin-css.ts

If this becomes a rabbit hole don't spend too much time, we can discuss.

**Closed** 2022-08-25 08:34 UTC
Labels: p3-minor-bug
