### ISSUE TITLE
🐛 BUG: CSS Module styles do not update upon saving file in development

### ISSUE THREAD

**Issue by Merri** [withastro/astro#3654] opened 2022-06-20 20:43 UTC
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

When changing and saving CSS Module file the style change does not get reflected to current open page in development. This can be so bad that the only way to get the styles to latest changes is to restart the local dev server.

Additionally at least on Vercel SSR adapter the CSS Modules seem not to work at all:

```
1:28:33 PM [vite] Error when evaluating SSR module /src/components/CheckPick.tsx:
--
16:28:33.523 | Error: failed to load module for ssr: ./Checkpick.module.css
16:28:33.523 | at instantiateModule (/vercel/path0/node_modules/vite/dist/node/chunks/dep-97cb3622.js:50206:15)
```

---

## To replicate issue

1. Import a CSS Module file to Astro page that is open in your browser.
2. Change a property in the CSS file.
3. Save the file.
4. Nothing changes.

The changes may only get updated when something else is changed, such as edit some other aspect of the page, visit another page, restart dev, or in the case of CodeSandbox an auto-refresh (not caused by editing the CSS module file) updates the page.

## Expected behavior

Changed style is reflected on the page.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/cool-mahavira-0dkrgc?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment] 2022-06-21 15:32
Thanks for reporting @Merri! Unfortunately, I couldn't replicate this behavior on my end (either importing CSS modules into jSX or importing CSS modules into `.astro` files). I assume this is a Windows-specific issue _or_ a browser issue. Would you mind sharing the browser you're using to debug?

**Comment by NapperJLG** [comment] 2022-06-21 21:31
I'm having the same issue on macOS and Chrome

**Comment by bholmesdev** [comment] 2022-06-22 19:04
Interesting! @NapperJLG to confirm, are you seeing this issue when importing CSS modules into Astro files, React / Preact components, or both?

**Comment by NapperJLG** [comment] 2022-06-22 19:35
@bholmesdev Importing CSS modules into React components. I have since given up with it though and converted my React components into Astro ones with `<style>` tags 😅

**Comment by bholmesdev** [comment] 2022-06-22 19:52
@NapperJLG  Oh no, you shouldn't have to do that! I'll bump the priority on this one, since CSS modules is our recommended React styling solution right now 👍

**Comment by bholmesdev** [comment] 2022-07-06 18:56
Confirmed this issue definitely happens for non-hydrated JSX components. Unable to reproduce for CSS modules in `.astro` files or CSS modules in `client:` components. For that first problem alone, I'm bumping this to urgent 👍

**Comment by matthewp** [comment] 2022-07-07 15:39
@sHoskens can you provide an example? I feel like we might be talking about several different problems in this issue.

**Comment by natemoo-re** [comment] 2022-07-19 21:57
I was able to look into this while working on https://github.com/withastro/astro/pull/3932. AFAICT, this will be fixed by https://github.com/withastro/astro/pull/3932 since we're scaling back our custom HMR handling and using what Vite gives us out of the box.

@sHoskens would you mind searching for other `styled-components` issues, and if you don't see a relevant one, opening a new issue? The original issue here is unrelated to `styled-components`.

**Comment by sHoskens** [comment] 2022-07-21 18:40
Sure thing, I'll look into this as soon as I'm able. My astro project is temporarily on hold, but I'll test out a few different approaches and, if I still encounter these issues, provide you with examples.

**Comment by pikeas** [comment] 2022-07-22 17:02
Same issue, seems to only happen for imports:

```
// Layout.astro

---
[some props handling]
---

<html>
[...]
</html>

<style>
    @import "styles/preflight.css";
    @import "styles/vars.css";

    [...]
</style>
```

CSS edits in the `<style>` block are immediately reflected in the browser, edits to `vars.css` are never HMR-ed despite the dev server's file watching seeing the change.

**Closed** 2022-07-22 18:37 UTC
Labels: p4-important, s2-medium, hmr

**Comment by diegoALCE95** [comment] 2023-06-08 04:59
I'm having the same error when using React on Astro.

I'm using CSS Modules on Windows / Chrome. 

Seems like a class issue. When I style for example an h2, it works just fine, but if I try to style a class, let's say .calculator, it doesn't work. 

I'll see if I can replicate it on a new project.
