### ISSUE TITLE
vite.build.assetsInlineLimit is invalid

### ISSUE THREAD

**Issue by peipei818** [withastro/astro#11540] opened 2024-07-24 08:04 UTC
### Astro Info

```block
Astro                    V4.8.7
Node                     v18.17.1
Package Manager          pnpm
```

### Describe the Bug

vite.build.assetsInlineLimit configuration is invalid.

When i use background image url to import img in css, it was valid. Imported or referenced assets that are smaller than this threshold will be inlined as base64 URLs.
```
  div {
    background-image: url('../assets/check.svg');
  }
```

But when i use import img in javascript, it was invalid.
```
---
import checkImg from '../assets/check.svg';
---

<img src={checkImg.src} alt="" />

```

### What's the expected result?

I want to use  base64 image.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-07-24 08:36
Duplicate of https://github.com/withastro/astro/issues/11361

**Closed by Princesseuh** 2024-07-24 08:36 UTC
Labels: needs triage
