### ISSUE TITLE
@astrojs/image@0.17.1 Picture component double encoded srcset value

### ISSUE THREAD

**Issue by fracsi** [withastro/astro#7481] opened 2023-06-26 11:17 UTC
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

chrome, firefox

### Describe the Bug

Passing `GetImageResult` to `<Picture/>` component results in image 404 error (image not shown) if any of the `<source>` are loaded instead of the original `img` src attribute. The URL-s in the srcset attributes are double encoded.

### What's the expected result?

Picture HTML tag is rendered with desired sources (formats and sizes).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cvzpwg-hrfg8c?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Tanguy-Magnaudet** [comment] 2023-06-26 12:53
Hello,

I'm facing the same issue.

I have some context, in the picture tag, the <img> tag don't result in a 404.
The problem is in how Astro encode the href parameter of <source> tags: 

```html
<picture>
	<source type="image/avif" srcset="/_image?f=avif&amp;w=160&amp;h=90&amp;ar=1.7777777777777777&amp;href=http%253A%252F%252Fexemple.com%252Fcontent%252Fuploads%252Fexemple.png 160w"><source type="image/webp" srcset="/_image?f=webp&amp;w=160&amp;h=90&amp;ar=1.7777777777777777&amp;href=http%253A%252F%252Fexemple.com%252Fcontent%252Fuploads%252Fexemple.png 160w"><source type="image/png" srcset="/_image?f=png&amp;w=160&amp;h=90&amp;ar=1.7777777777777777&amp;href=http%253A%252F%252Fexemple.com%252Fcontent%252Fuploads%252Fexemple.png 160w">
	<img alt="Logo du groupe Rivelec" src="/_image?f=png&amp;w=160&amp;h=90&amp;ar=1.7777777777777777&amp;href=http%3A%2F%2Fexemple.com%2Fcontent%2Fuploads%2Fexemple.png" loading="eager" decoding="async">
</picture>
```

`%3A%2F%2F` Becomes `%253A%252F%252F` in `<source>` tags. Looks like `25` is being added somehow.

**Comment by wooseopkim** [comment] 2023-06-27 03:37
@fracsi @Tanguy-Magnaudet This does not seem to happen on prod builds. At the first version of the change made at `0.17.1` I encoded spaces only (https://github.com/withastro/astro/pull/7340#discussion_r1223320341), but reviewers suggested `encodeURI`ing the entire `src`. I did that, mostly because I wanted the PR to be merged fast, but it turns out not to have been fully tested. My bad! I'll open another PR to handle this.

**Comment by Tanguy-Magnaudet** [comment] 2023-06-27 09:59
@wooseopkim I just found an other side effect of this commit.

Reproduction : [https://stackblitz.com/edit/github-cvzpwg-rtzje7?file=src%2Fpages%2Findex.astro](https://stackblitz.com/edit/github-cvzpwg-rtzje7?file=src%2Fpages%2Findex.astro)

In SSR mode, the Picture tag makes an internal HTTP Request from the server to the value sets to `src`. If you use a remote `src` it will makes a relative request with the remote image src as URI, triggering Astro 404 instead of looking for the remote image content.

Happens with sharp also.

It is probably related to encodeURI but you get the information.

**Closed** 2023-07-03 08:09 UTC
