### ISSUE TITLE
🐛 BUG: `client:only` errors @ React, Vue, & Solid

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#3362] opened 2022-05-13 11:22 UTC
### What version of `astro` are you using?

1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

Yarn

### What operating system are you using?

Windows

### Describe the Bug

**Steps to reproduce:**
- Clone the `Kitchen Sink (Multiple Frameworks)` template.
- Change all instances of `client:visible` to `client:only="..."` @ `src/pages/index.astro`.

**React Errors**
```log
• Warning: Expected server HTML to contain a matching <div> in <astro-root>.
• Warning: An error occurred during hydration. The server HTML was replaced with client content in <astro-root>.
```
**Vue Errors**
```log
• [Vue warn]: Attempting to hydrate existing markup but container is empty. Performing full mount instead. 
```

**Solid Errors**
- Counter value is not rendered initially:  
![image](https://user-images.githubusercontent.com/10906415/167962969-c0a75021-b821-46c1-8c5d-f6b9a8b614c5.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-client-directive-issues-82bu8s?file=/src/pages/index.astro:769-1214

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-05-13 14:46
Ah dang, sorry this still isn't fixed! We'll take a look at this again.

**Comment by JLarky** [comment] 2022-05-16 16:21
I had the same issue with React 17 and both `client:only` and `client:idle` that you can see here https://youtu.be/_y5hbSvVVAs?t=2282 and my workaround https://youtu.be/_y5hbSvVVAs?t=2555 was to just remove this check :) but I think the issue was that `hyrdate` function inside `idle.js` or `only.js` was not passing the third argument

**Comment by joeldsouzax** [comment] 2022-05-16 16:39
I have this error for client:* in solid-js. astro in dev mode is not able to find the component by path but works okay when built.

**Comment by matthewp** [comment] 2022-06-01 12:19
Thanks for the new reproduction.

**Comment by tony-sull** [comment] 2022-06-27 20:19
Looks like this is fixed in the latest beta release, [Stackblitz demo](https://stackblitz.com/edit/github-oqoznb?file=src%2Fpages%2Findex.astro&on=stackblitz) 🥳 

We've made some huge strides the last few weeks in component hydration, both in performance improvements and in adding support for nested slots.  Closing this as fixed but please open a fresh issue run into any related bugs!

**Closed by tony-sull** 2022-06-27 20:19 UTC
Labels: p4-important, s2-medium
