### ISSUE TITLE
incorrect `astro check` warning message

### ISSUE THREAD

**Issue by stefanprobst** [withastro/astro#10722] opened 2024-04-09 05:25 UTC
### Astro Info

```block
Astro                    v4.5.16
Node                     v20.12.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

with the following [`src/pages/index.astro`](https://github.com/stefanprobst/issue-astro-ts/blob/main/src/pages/index.astro), i get an incorrect warning message when running `astro check`:

```astro
---
const locale = "en";
return Astro.redirect(`/${locale}`, 307);
---
```

running `astro check` prints:

```
src/pages/index.astro:2:7 - warning ts(6133): 'locale' is declared but its value is never read.

2 const locale = "en"
        ~~~~~~
```

### What's the expected result?

see above

### Link to Minimal Reproducible Example

https://github.com/stefanprobst/issue-astro-ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-04-09 07:33
Duplicate of https://github.com/withastro/language-tools/issues/476

**Closed by Princesseuh** 2024-04-09 07:33 UTC
Labels: needs triage
