### ISSUE TITLE
When I use npx to add Tailwind, the installer uses Yarn instead of npm

### ISSUE THREAD

**Issue by jorgeluissanchez** [withastro/astro#9697] opened 2024-01-15 05:58 UTC
### Astro Info

```block
Astro                    v4.1.2
Node                     v18.18.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/tailwind
```

### Describe the Bug

npx astro add tailwind
✔ Resolving packages...
24:54:53 
  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭───────────────────────────────────────────────────────╮
 │ yarn add @astrojs/tailwind@^5.1.0 tailwindcss@^3.4.1  │

### What's the expected result?

npm i @astrojs/tailwind@^5.1.0 tailwindcss@^3.4.1

### Link to Minimal Reproducible Example

npx astro info

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2024-01-15 08:09
Might be a duplicate of https://github.com/withastro/astro/issues/7925

**Closed** 2024-01-19 00:20 UTC
Labels: needs repro
