### ISSUE TITLE
🐛 BUG: Custom Integration Doesn't Run on Build / Preview

### ISSUE THREAD

**Issue by roblevintennis** [withastro/astro#3246] opened 2022-04-30 15:43 UTC
### What version of `astro` are you using?

^1.0.0-beta.20

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Repro:

1. Have a small project with a custom integration
2. Run the app with `npm run dev --experimental-integrations`

Result: I see my app with the styles loaded (my integration does one thing and that's import a CSS file). For example, see the following blue and red colors; they come from `common.min.css` which the integration loads:

![image](https://user-images.githubusercontent.com/142403/166112917-00212343-87a9-44df-99db-e04a4cf59afb.png)

3. Now try to build and preview the project with

```sh
npm run build && npm run preview # and I had to use --experimental-integrations from CLI for these to not throw error
```

4. Visit the localhost page

Expected: Should still see styled buttons
Actual: The CSS is no longer being loaded and thus the integration did not run or is somehow not still working after build

![Screen Shot 2022-04-30 at 10 55 23 AM](https://user-images.githubusercontent.com/142403/166112936-e4af38cf-586c-464e-8eec-e2167b1478ba.png)

___

This may be related to:
https://github.com/withastro/astro/issues/3015

But I've already added following (also on stackblitz) with no success:

```js
  experimental: {
    integrations: true
  }
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jkhska-7pkdme?file=package.json&on=stackblitz

Again, you will need to stop the terminal and run `npm run build && npm run preview` to repro this as the integration appears to work fine for `npm run dev` (just not when building)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aFuzzyBear** [comment] 2022-05-02 19:23
Hey @roblevintennis thanks for raising this, I checked the build output, it is appearing to pull the styles and bundle them but its not applying them properly, Ill ping @tony-navillus  too see if he could see whats what,

**Comment by tony-sull** [comment] 2022-05-03 14:48
Strange, most of the styles are including in the build but the CSS variables are missing?  🤔

**Comment by tony-sull** [comment] 2022-05-03 15:00
@roblevintennis My initial thought here is that it might actually make sense for the `.astro` components in `agnostic-astro` to import the common CSS file along with the component-specific ones

We still need to circle back to the `injectElement` or `injectHTML` integration hook which would be useful for importing global CSS, but having the Astro components do it directly would actually make sure it's always run through the usual Astro pipeline of bundling per-page

Thoughts?  I'm just kind of brainstorming here, the use of `injectScript` to actually import styles feels a little off but I 💯 understand why that's used here (and is probably a limitation of the integrations API that we could/should fix)

**Comment by roblevintennis** [comment] 2022-05-03 16:02
@tony-sull I got the idea of injecting the common styles looking at the tailwind integration which injects some sort of base.scss or something and so I figured I would have the integration import the common.min.css as a convenience.

That said, if it's not supported yet, I can instead go back to having the user import the global css from a top-level script. In fact, that's how I had it before. I don't want them to import the common.min.css at the component level though. That should be done once only as it's a global and if I had 20 components all loading them it feels wasteful.

So I guess for a component set as I have here, an integration is really unrealistic then? 🤔

I guess in terms of the hackathon which is about to have its deadline, I will submit this as a theme 🤷‍♂️

**Comment by roblevintennis** [comment] 2022-05-03 16:03
Still feels like a bug to me but I suppose that falls for you and the team to decide :)

**Comment by FredKSchott** [comment] 2022-05-10 20:58
We believe that this is a duplicate of #3298! Closing this one in favor of #3298, since that issue includes an investigation into the cause and potential fix.

**Closed by FredKSchott** 2022-05-10 20:58 UTC
Labels: bb:investigate

**Comment by roblevintennis** [comment] 2022-05-10 22:51
Makes sense thanks for the update 👍🏽
