### ISSUE TITLE
Hot load of component CSS fails in MDX files

### ISSUE THREAD

**Issue by fisherfrontier** [withastro/astro#9917] opened 2024-02-01 04:15 UTC
### Astro Info

```block
Astro                    v4.2.8
Node                     v20.8.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Astro component, when used in an MDX file, fails to render updated CSS during hot load.

### What's the expected result?

Editing an Astro component should cause hot load of updated CSS when rendering `.mdx` file.

To reproduce the problem, try navigating in the demo app to the "Using MDX" blog post. While viewing that page, edit the `./src/components/StrongText.astro` component, where you can choose your favorite color (`blue`, no `yellow`).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-p2lpzn?file=src%2Fcomponents%2FStrongText.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-02-01 15:25
Duplicate of https://github.com/withastro/astro/issues/9794

**Closed by ematipico** 2024-02-01 15:25 UTC
Labels: needs triage
