### ISSUE TITLE
🐛 BUG: SolidJS Components cannot receive render props from spread object

### ISSUE THREAD

**Issue by samijaber** [withastro/astro#3366] opened 2022-05-13 22:26 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using SolidJS, spreading props into a child component behaves oddly. If one of those props is inlined into the JSX as string content, then nothing will appear.

Example:
```jsx
import { createMutable } from 'solid-js/store';

function SpreadComp(props) {
  return (
    <div data-test-xyz={props.foo}>
      <div>this should say bar: {props.bar}</div>
      <div>this should say baz: {props.baz}</div>
    </div>
  );
}

function App() {
  const state = createMutable({
    spreadProps: {
      foo: 'foo',
      bar: 'bar',
    },
  });
  return <SpreadComp {...state.spreadProps} baz={'baz'} />;
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jecp67?file=src%2Fcomponents%2FCounter.jsx&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-05-19 23:42
Thanks for the clear reproduction! This is an odd one, we'll have to dig into what's going on here.  I suspect this _could_ be an upstream issue with Solid's hydration logic, but it's equally likely to be an issue with Astro's Solid integration.

Can you confirm if this same behavior occurs using [Solid Start](https://github.com/solidjs/solid-start) to rule that this is an upstream problem?

**Comment by samijaber** [comment] 2022-05-21 00:05
@natemoo-re I'm afraid this issue is specific to Astro, and not upstream to SolidJS. here is a SolidJS playground working fine: [link](https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAFl6uKCbVwps+YoA5HQa2nr6ZLjccIGWEFYy9BDMuGi0ELwAyoROIgDCCoQAFDm0hGSIvFAQ+ACU-Fa8gnC4TBlFjU28ADwiaABuvCLOUFoukVoU+ABeALwgpeUAdDK0tJIAfJ1dPX39G7gAFmhkvGSHDGoiZ1D4vCZQjJUL8ssPjJLd+ntbGTu7AwOx1O50u1zIt3uUGmz0WZCWD2mn2+gO2PRR+06tTikisVjgFFsfDEMig9DUfESyVS6V4BSSLkYRXqIE6zHSkTOnhcvFmDicLncnm8cCKrL+TTIOTgUBEAAVXhUGhKuqtaJVAmrAlg0U13hr3tq0ZIdX9JNjOkJWowMt1srkCpx+EsXZFnHAllLcgqymRpIj5oFEYFpPoNji8fEIEJROIiszeRsevSIIzeGGsENaMx6PBU0sAOYtACiPjzuAAQvgAJIiDpgKCEQgqWoAQgtmEkAF0gA)

**Comment by tony-sull** [comment] 2022-05-24 16:18
Looks like it's specific to using nested objects as well, both of the examples below work but when spreading `{...state.spreadProps}` the object is lost in the props 🤔 

```js
// This works, spreadProps is available to the component
<SpreadComp {...state} baz={'baz'} />
```

```js
// this also works, foo and bar are available to the component
const state = createMutable({
      foo: 'foo',
      bar: 'bar',
  });
  
return <SpreadComp {...state} baz={'baz'} />
```

**Comment by natemoo-re** [comment] 2022-05-25 19:26
While this does work with Solid + Vite when using pure client-side rendering, looks like this is failing in the same way when using SolidStart + Vite SSR with Solid's hydration.

So this looks like an upstream bug! Here's a reproduction [repo](https://github.com/natemoo-re/solid-spread-repro) using SolidStart and a [live example on StackBlitz](https://stackblitz.com/github/natemoo-re/solid-spread-repro?file=src%2Fcomponents%2FCounter.tsx).

**Comment by natemoo-re** [comment] 2022-05-25 19:36
Awesome! Sorry for the duplicate, I was already in the process of sharing this with them. Going to close this since it's being tracked upstream.

Thanks for debugging this with us!

**Closed by natemoo-re** 2022-05-25 19:36 UTC
Labels: upstream, framework-solid

**Comment by samijaber** [comment] 2022-05-25 19:50
Awesome @natemoo-re , thank you for diving into this even though it ended up being an issue outside of Astro. Appreciate you & your team's help!
