### ISSUE TITLE
🐛 BUG: Warn when unsupported vite config is used

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#2782] opened 2022-03-14 04:00 UTC
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

See https://github.com/withastro/astro/issues/2776

Astro only partially supports Vite's `vite` configuration object. Some properties work, but others are overwritten by Astro, and others are effectively ignored due to how we use Vite internally.

It would be good to report warnings when we see you using a Vite configuration property incorrectly.

### Link to Minimal Reproducible Example

See https://github.com/withastro/astro/issues/2776

**Comment by matthewp** [comment] 2022-05-10 22:19
Duplicate of https://github.com/withastro/astro/issues/3046, we're going to fix it there.

**Closed by matthewp** 2022-05-10 22:19 UTC
