### ISSUE TITLE
Duplicate stylesheets and scripts in build

### ISSUE THREAD

**Issue by JakobMick** [withastro/astro#4969] opened 2022-10-03 23:36 UTC
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Related to [#4757](https://github.com/withastro/astro/issues/4757)

Stylesheets and scripts are still getting injected twice in build when using `head` in an astro component in a layout. 

Stylesheets and scripts are injected once in `head` and once in `body`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-c5xvms?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2022-10-04 13:23
I don't think this is likely solvable. I recommend changing how you build layouts. The problem is this:

```astro
<!DOCTYPE html>
<html lang="en">
	<Head></Head>
	<body>
		<slot />
	</body>
</html>
```

This looks fine on its surface but consider an example like this:

```astro
<meta charset="utf8">
<Component />
```

`Component` maybe contain `<head>` content, it may contain body content, or even both. The parser doesn't know, it just knows that the `<meta>` tag is the last valid head tag. So it inserts an insertion point that looks like this:

```astro
<meta charset="utf8">
${renderHead()}
<Component />
```

The same thing is happening in your example. Since the parser doesn't know that `<Head>` contains head content; it might or it might have body content, it has to add an insertion point before it.

You can easily fix this by doing it another way:

```astro
<!DOCTYPE html>
<html lang="en">
	<head>
	  <Head />
	</head>
	<body>
		<slot />
	</body>
</html>
```

closing as there is an easy workaround and the original issue can't be fixed.

**Closed by matthewp** 2022-10-04 13:23 UTC
