### ISSUE TITLE
`@astrojs/solid-js@2.1.1` breaks build on `@astrojs/vercel/edge`

### ISSUE THREAD

**Issue by alexvuka1** [withastro/astro#7098] opened 2023-05-16 01:11 UTC
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

@astrojs/vercel/edge

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

When I updated from `@astrojs/solid-js@2.1.0` to `@astrojs/solid-js@2.1.1` I got the following 2 errors in Vercel logs when visiting a page that has a `client:load` solid-js component. It works fine locally and since `@astrojs/vercel/edge` doesn't support `astro preview` I can't show reproduce the error in StackBlitz, but if the provided code is deployed to Vercel it should result in the errors.

![image](https://github.com/withastro/astro/assets/23139322/71cbc4e1-a780-43b7-9bee-8dda64d6ad52)
```
Error: __ is not supported in the browser, returning undefined
    at (entry.mjs:166:40709)
    at (entry.mjs:166:40819)
    at (entry.mjs:767:1185)
    at (entry.mjs:152:1042)
```
```
Error: Unable to render Upload!

This component likely uses @astrojs/react, @astrojs/preact, @astrojs/solid-js, @astrojs/vue, @astrojs/svelte or @astrojs/lit,
but Astro encountered an error during server-side rendering.

Please ensure that Upload:
1. Does not unconditionally access browser-specific globals like `window` or `document`.
   If this is unavoidable, use the `client:only` hydration directive.
2. Does not conditionally return `null` or `undefined` when rendered on the server.

If you're still stuck, please open an issue on GitHub or join us at https://astro.build/chat.
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/solid-js-vercel-edge?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-05-16 06:53
Duplicate of https://github.com/withastro/astro/issues/6989. Sorry for the unintentional breaking change, I'll try to look into the issue this week.

**Closed by bluwy** 2023-05-16 06:53 UTC
