### ISSUE TITLE
Language switcher not working in "docs" example

### ISSUE THREAD

**Issue by pReya** [withastro/astro#4749] opened 2022-09-14 11:21 UTC
### What version of `astro` are you using?

v1.2.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When creating a new page according to the `readme.md` of the [`docs` example](https://github.com/withastro/astro/tree/main/examples/docs), the language switcher won't work.

To recreate:

1. Create new project with the `docs` template
2. Add a new language to `config.ts`, e.g.
```
export const KNOWN_LANGUAGES = {
  English: "en",
  German: "de",
} as const;
```
3. Create localized content file, e.g. `pages/de/introduction.md`
4. Open the english `introduction` page
5. Click on "German" in the language switcher -> nothing happens

I'm getting a Preact hydration error in the console:
```
Uncaught (in promise) TypeError: can't define property "__": Object is not extensible
```

Not sure if this is related to the language switcher problem.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-buwkrs?file=src/pages/de/introduction.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by xstevenyung** [comment] 2022-09-14 16:19
It seems like the issue is coming from the sidebar config.

I had the same issue until I added the following code:
```ts
export const SIDEBAR: Sidebar = {
	en: {
		'Section Header': [
			{ text: 'Introduction', link: 'en/introduction' },
			{ text: 'Page 2', link: 'en/page-2' },
			{ text: 'Page 3', link: 'en/page-3' },
		],
		'Another Section': [{ text: 'Page 4', link: 'en/page-4' }],
	},
    // This will config the sidebar for the language switch
	de: {
		'Section Header': [
			{ text: 'Introduction', link: 'de/introduction' },
			{ text: 'Page 2', link: 'de/page-2' },
			{ text: 'Page 3', link: 'de/page-3' },
		],
		'Another Section': [{ text: 'Page 4', link: 'de/page-4' }],
	},
};
```

**Comment by matthewp** [comment] 2022-09-14 17:58
@xstevenyung can you update the code?

ccing @delucis

**Comment by xstevenyung** [comment] 2022-09-14 19:34
It seems quite well documented already, do you want me to add an example?

**Comment by pReya** [comment] 2022-09-14 20:29
@xstevenyung Changing the Sidebar object does not change anything for me. Even with the changed Sidebar, the Language Switcher doesn't do anything. I've added debug output to the `onChange` handler in the `<select>` of the LanguageSwitcher – it's never being called at all.

**Comment by xstevenyung** [comment] 2022-09-14 21:49
Do you have some code I can look into ?

**Comment by delucis** [comment] 2022-09-14 22:03
@matthewp There seems to be a Preact hydration error but I’m not 100% sure why it’s breaking `LanguageSelect.tsx`, because that’s actually a React component. Is it possible we broke combining React + Preact in one project somehow?

**Comment by matthewp** [comment] 2022-10-06 19:51
This usually comes down to a preact version issue.

**Comment by delucis** [comment] 2022-10-06 21:40
I’m not able to reproduce this with a minimally updated copy of the docs example. Adding a language to `KNOWN_LANGUAGES` and corresponding entries to `SIDEBAR` seems to make the language switcher work as expected: https://stackblitz.com/edit/github-fpa7iz?file=src/config.ts

I’ll close this for now, but please re-open if you can still provide steps to trigger this issue.

**Closed by delucis** 2022-10-06 21:40 UTC
Labels: p3-minor-bug
