### ISSUE TITLE
Error messages wrong and for wrong file

### ISSUE THREAD

**Issue by LukaHarambasic** [withastro/astro#5333] opened 2022-11-08 21:41 UTC
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The following bug thrown for `harambasic.de/src/pages/posts/[slug].astro:4:27` gets fixed when I remove the function from `harambasic.de/src/util/api/categories.ts` (see https://github.com/LukaHarambasic/harambasic.de/pull/84/commits/2b1ab7e3288f01ce2df076e05bcaf2192859bb26 (ignore the formatting noise).

So a bug in `harambasic.de/src/util/api/categories.ts` exists but it shows that a type import is the problem.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/22857823/200680307-df028f90-dda2-41cc-bb94-85af8f990e57.png">

Is this maybe a vite bug?

I just find it very confusing and it took me some time to figure it out. 

### Link to Minimal Reproducible Example

https://github.com/LukaHarambasic/harambasic.de/pull/84/commits/0458b1bc1af40e3c0b5c01d6f9071aefd221a246

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by LukaHarambasic** [comment] 2022-11-08 21:50
Found the error, a type import wasn't explicit - https://github.com/LukaHarambasic/harambasic.de/pull/84/commits/37f51b074d88675ec2adbec83e5ce6737200af5f
But I still think the error message is kind of strange.

**Comment by Princesseuh** [comment] 2022-11-08 22:19
https://github.com/withastro/astro/pull/5316 will slightly improve the message, by adding the nuance that this is often caused by a typo, but might not be the case

But, unfortunately the fix in that PR isn't super informative either - Vite gives a super generic error whenever it fails to import a file (which in a lot of cases, it simply a typo) so we don't have much information to go on apart that, well, the import failed

Thank you for reporting this issue!

**Comment by Princesseuh** [comment] 2022-11-09 16:02
Here's the upstream issue to track for this: https://github.com/withastro/astro/issues/5333

**Comment by bluwy** [comment] 2022-11-22 03:52
Closing as https://github.com/vitejs/vite/issues/10002 is fixed. It's merged into Vite 4 and will provide a similar error message to what Astro provides now.

**Closed by bluwy** 2022-11-22 03:52 UTC
Labels: upstream, error message

**Comment by LukaHarambasic** [comment] 2022-11-22 18:53
@Princesseuh & @bluwy, thanks for being so nice and quick. You and the whole team(s) are doing an amazing job!

**Comment by Princesseuh** [comment] 2022-11-22 19:10
No problems, always happy to help!
