### ISSUE TITLE
🐛 BUG: Shiki not exported with MDX

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#4129] opened 2022-08-03 10:51 UTC
### What version of `astro` are you using?

rc-04

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

User reported on [Discord](https://discord.com/channels/830184174198718474/1002949789001977867)  a problem with shiki within their project with vite not being able to locate the export location for shiki, 
Having tested `astro.new/with-mdx` the shiki plugin seems to operational, however upon inspection of the users project I am suspecting there might be something at play with the way the plugins are being applied, was just a feeling from the poking about in the reproduction. 
I would like another set of eyes on this issue to see what can be done to help unblock the user with their project. As this is `borking` deployment of his site,

### Link to Minimal Reproducible Example

https://github.com/brycewray/astro-site

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by brycewray** [comment] 2022-08-07 20:18
A little more info...

I, the user @aFuzzyBear mentioned, am getting the same error messages when trying to deploy in Cloudflare Pages that I got, and continue to get, in Vercel. This is even after I considerably pared down the repo config — including deleting and then reinstalling all packages, plus the `package-lock.json` file just to be safe — based on his comment re “there might be something at play with the way the plugins are being applied.” This is now using Astro 1.0.0-rc.7.

```plaintext
15:12:43.208 | file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34410
-- | --
15:12:43.209 | throw new Error(`Failed to resolve entry for package "${id}". ` +
15:12:43.209 | ^
15:12:43.209 |  
15:12:43.209 | Error: Failed to resolve entry for package "shiki". The package may have incorrect main/module/exports specified in its package.json.
15:12:43.209 | at packageEntryFailure (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34410:11)
15:12:43.210 | at resolvePackageEntry (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34407:5)
15:12:43.210 | at tryNodeResolve (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34161:20)
15:12:43.210 | at Context.resolveId (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:33963:28)
15:12:43.210 | at Object.resolveId (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:35216:55)
15:12:43.210 | at async Object.<anonymous> (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62552:21)
```

**Comment by bholmesdev** [comment] 2022-08-07 20:27
@brycewray Thanks for reporting! We pushed a fix in the latest minor release for the MDX integration, but I haven't tested on cloudflare pages deployment. Try bumping to `@astrojs/mdx@latest` and run a fresh `npm install`. Let me know if you're still running into issues and I'll re-open!

**Comment by brycewray** [comment] 2022-08-07 20:34
> Try bumping to `@astrojs/mdx@latest` and run a fresh `npm install`. Let me know if you're still running into issues and I'll re-open!

@bholmesdev Actually am already running that latest version of `@astrojs/mdx`, 0.7.0, which gave me that error on both Vercel and CFP. Would you like me to try `@astrojs/mdx@next--rc`?

**Comment by bholmesdev** [comment] 2022-08-07 21:15
Hm, must mean we _didn't_ resolve the issue then! Reopening to prioritize next week.

**Comment by bholmesdev** [comment] 2022-08-08 15:51
@brycewray  Okay, I can confirm that our `with-mdx` example is deployable to vercel (both static and as serverless functions), so it's definitely something specific in your setup. I'm walking through the pages now to figure out the source.

**Comment by brycewray** [comment] 2022-08-08 15:53
> @brycewray Okay, I can confirm that our `with-mdx` example is deployable to vercel (both static and as serverless functions), so it's definitely something specific in your setup. I'm walking through the pages now to figure out the source.

@bholmesdev OK. I think only https://github.com/brycewray/astro-site/tree/main/src/pages/posts/2022/07/test006 has an actual code block within it, if that helps. Most of the pages were just boilerplate for testing MDX.

**Comment by bholmesdev** [comment] 2022-08-08 17:24
@brycewray Ah ha! It looks like it's our `@styles/index.scss` causing issues. Just [removed this from the `Head.astro` component](https://github.com/brycewray/astro-site/blob/main/src/components/Head.astro#L2) and builds seem to succeed. I'll let you confirm on your end, but I have a feeling that `shiki` _the npm package_ is resolving fine; just some funky imports in the scss perhaps?

**Comment by bholmesdev** [comment] 2022-08-08 17:33
Found it, just need to capitalize the `shiki` [style import in index.scss](https://github.com/brycewray/astro-site/blob/main/src/styles/index.scss#L4) 🤦 

`@use 'Shiki';`

Update that `@use` statement and let me know if it works!

**Comment by brycewray** [comment] 2022-08-08 17:42
> @brycewray Ah ha! It looks like it's our `@styles/index.scss` causing issues. Just [removed this from the `Head.astro` component](https://github.com/brycewray/astro-site/blob/main/src/components/Head.astro#L2) and builds seem to succeed. I'll let you confirm on your end, but I have a feeling that `shiki` _the npm package_ is resolving fine; just some funky imports in the scss perhaps?

@bholmesdev Yes, and then found some other SCSS `@use` issues within other files, so — entirely my bad. 😞 

Thanks so much, and I apologize for wasting your time, especially at this stage of Rollout Week. Best wishes as always to all the Astro team!

**Comment by bholmesdev** [comment] 2022-08-08 18:05
@brycewray Ah no problem! It's a pretty confusing error message, to be fair 😄 I'll close this out but let us know if anything else comes up in your migration!

**Closed by bholmesdev** 2022-08-08 18:05 UTC
Labels: markdown, p3-minor-bug, s1-small, MDX
