### ISSUE TITLE
URL/Raw SCSS imports work in `dev`, but not `build`

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#4791] opened 2022-09-18 01:37 UTC
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

The linked repro has this implementation:
- dark theme @ `astro dev`
- light theme @ `astro build`
- 2 pages, one which loads the theme via CSS and the other via SCSS

&nbsp;  
## ✔️ `astro dev` @ [CSS, SCSS]
![Dev--CSS-SCSS](https://user-images.githubusercontent.com/10906415/190881817-12d03b8c-4f09-45a2-815b-ebf61c4168b6.png)

&nbsp;  
### Styles are broken for all pages, not just the ones that loaded `SCSS`.
![Build--CSS-SCSS](https://user-images.githubusercontent.com/10906415/190881815-7ec302de-10d4-4a45-ac33-ece27d0caaf8.png)
**Update:**  
I was just exploring this a bit more and now can't reproduce the `CSS` page being broken when other pages have `SCSS`...  
Also ran into that several times yesterday, so `CSS` being affected in the presence of `SCSS` seems intermittent.  
The `SCSS` issue is consistent.  

&nbsp;  
### (*SCSS page renamed to `SCSS.astro.disabled`*)
![Build--CSS](https://user-images.githubusercontent.com/10906415/190881818-3e3228e5-8fe2-41df-9b34-7ef48020fad7.png)

&nbsp;  
### Link to Minimal Reproducible Example

https://github.com/enteleform-codesandbox/0017--Astro--ConditionalSCSS

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by songololo** [comment] 2022-09-18 07:18
Is this maybe a wider issue? I'm having the same problem with tailwind / css - works fine in dev but CSS goes missing in the build process...

**Comment by bluwy** [comment] 2022-09-18 09:14
Duplicate of https://github.com/withastro/astro/issues/4395 and https://github.com/vitejs/vite/issues/2522

**Closed by bluwy** 2022-09-18 09:14 UTC
