### ISSUE TITLE
Context will be `Undefined` when getting  from svelte context

### ISSUE THREAD

**Issue by harrytran998** [withastro/astro#5674] opened 2022-12-26 10:40 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

NodeSSR standalone

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When I create a svelte context component to pass the child context globally --> I cannot get the context in the child component, it always returns undefined. 😅.

Hopefully, anyone can check it, please 🥹.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5z58um?file=src/components/OkOk.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by predaytor** [comment] 2022-12-26 19:57
I asked a similar question, but unfortunately, it's not possible now.
https://discord.com/channels/830184174198718474/1056926240289849444/1056926240289849444

**Comment by harrytran998** [comment] 2022-12-27 05:41
@predaytor Thank you for sharing this 🥹 the concept `Inject` something globally was popular. I think I need to change the way I think about it.

**Comment by predaytor** [comment] 2022-12-27 10:26
> @predaytor Thank you for sharing this 🥹 the concept `Inject` something globally was popular. I think I need to change the way I think about it.

yeah, in this way the islands architecture is quite limited for building complex APIs. I'm going to switch to native web components and vanilla javascript for a moment. Although I don't quite understand how to implement such a declarative way of creating complex components unlike what modern frameworks offer..

**Comment by MoustaphaDev** [comment] 2023-02-05 18:01
Closing as duplicate of https://github.com/withastro/astro/issues/2016
The author didn't use Svelte components but the same principles apply

**Closed by MoustaphaDev** 2023-02-05 18:01 UTC
