### ISSUE TITLE
🐛 BUG: <link rel="stylesheet"> inside Svelte component breaks client:visible

### ISSUE THREAD

**Issue by isaac-mcfadyen** [withastro/astro#4191] opened 2022-08-07 15:21 UTC
### What version of `astro` are you using?

v1.0.0-rc.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macOS Ventura (don't think it's related)

### Describe the Bug

When using a `<link rel="stylesheet" ...>` inside a Svelte component, `client:visible` seems to break.

Any component with a stylesheet anywhere inside it and using `client:visible` will no longer be hydrated, no matter where on the page you scroll and even if it's directly visible. Removing the stylesheet causes things to immediately work again.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fv7dts?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-08-08 15:23
Thanks for opening an issue! This is a strange one, we'll have to investigate what's going on here.

**Comment by pilcrowOnPaper** [comment] 2022-10-29 14:26
I think this issue is resolved? 

Reproduction: https://github.com/pilcrowOnPaper/astro-svelte-visible-hydrate

**Comment by PuruVJ** [comment] 2022-11-04 06:06
Not resolved for me yet, getting the same problem

**Comment by pilcrowOnPaper** [comment] 2022-11-04 08:27
@isaac-mcfadyen @PuruVJ  @natemoo-re 

2 things:
- The reproduction works fine on my local machine
- The reproduction on StackBlitz works fine when the stylesheet `href` is pointing to a local file (not external like `https://unpkg.com/swiper/swiper-bundle.min.css`)

From this, I think this is an issue with StackBlitz and network requests, and not Astro/Svelte.

**Comment by PuruVJ** [comment] 2022-11-04 09:47
The reproduction is fine, but my local version with many MDX and Svelte files combined isn't working.

Update: It's not because of style. It's just not working at all 😅

**Comment by wulinsheng123** [comment] 2022-11-06 09:32
@natemoo-re what's the latest news for this bug？ I  want to found it

**Comment by bluwy** [comment] 2022-11-17 06:50
Looks like this is working fine, but StackBlitz is blocking the unpkg request somehow causing it fail. If I run this locally, specify another external link that 404s, it renders fine too. Closing as fixed.

**Closed by bluwy** 2022-11-17 06:50 UTC
Labels: framework-svelte, p3-minor-bug, s1-small
