### ISSUE TITLE
Astro experimental assets does not work with Node.js SSR adapter

### ISSUE THREAD

**Issue by YonicDev** [withastro/astro#7974] opened 2023-08-06 12:05 UTC
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Windows 10, Linux (Debian)

### What browser are you using?

Chrome, Firefox

### Describe the Bug

While using `astro:assets` with the Node SSR adapter, optimized images don't work properly on not prerendered pages when running via `node ./dist/server/entry.mjs`, on both Squoosh and sharp image services. This doesn't seem to be the case when executing `npm run preview` or `npm run dev`, however.

When requesting the images directly, the only error printed is a 404 "Not found" error in the client.
Stackblitz seems to deliver corrupt images with "unexpected end of JPEG file", but this may be a different issue altogether, so I'm linking the repository to a minimal code example directly.
CodeSandbox seems to be the only environment where it does seem to work for some reason.

### What's the expected result?

The optimized images should be delivered correctly from the server on non-prerendered pages.

### Link to Minimal Reproducible Example

https://github.com/YonicDev/astro-bug-assets-node

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by deeprobin** [comment] 2023-08-06 19:38
I have this problem too. I solved it locally by upgrading from node 18 to node 20.

@Princesseuh any update on this?

**Comment by Princesseuh** [comment] 2023-08-29 13:41
The repro you shared works for me on both Node 18 and Node 20. Does it still happen for you on the latest versions of Astro?

**Comment by YonicDev** [comment] 2023-09-01 08:43
This still does not work on Astro v3 and @astrojs/node 6. I'm using Node 19.

**Comment by doidor** [comment] 2023-09-21 17:23
This issue is still reproducing in Astro v3.1.1

**Comment by matthewp** [comment] 2023-09-27 21:36
Works fine for me too. Can someone who's experiencing this issue debug it and see what is going on? Thanks.

<img width="1659" alt="Screen Shot 2023-09-27 at 5 36 15 PM" src="https://github.com/withastro/astro/assets/361671/9cd27ed5-d610-49ff-9efc-bdc135aa0682">

**Comment by Princesseuh** [comment] 2023-10-09 20:31
I believe the only remaining issue related to this is this one: https://github.com/withastro/astro/issues/8735 that is specific to Windows. Otherwise, recent patches should've fixed everything, so I'll close this issue

**Closed by Princesseuh** 2023-10-09 20:31 UTC
Labels: feat: ssr, pkg: node, feat: assets
