### ISSUE TITLE
Custom HTTP status pages (404, 403) have different build output

### ISSUE THREAD

**Issue by cvh23** [withastro/astro#4418] opened 2022-08-22 10:30 UTC
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a `404.md` and a `403.md` in `src/pages` directory. If I execute `astro build`, I get a `404.html` but a `403/index.html` in `dist` directory. Although `astro build`-output says, that a `403.html` was generated (which would be the intended behavior):
```
▶ src/pages/403.md
  └─ /403.html (+3ms)
▶ src/pages/404.md
  └─ /404.html (+2ms)
```
```
❯ ls -la dist
total 7
drwxr-xr-x  1  1  staff     5  Aug  22  12:27  ./            
drwxr-xr-x  1  1  staff    14  Aug  22  12:27  ../           
drwxrwxrwx  1  1  staff     1  Aug  22  12:27  403/          
-rw-rw-rw-  1  1  staff    35  Aug  22  12:27  404.html      
drwxrwxrwx  1  1  staff     1  Aug  22  12:27  assets/       
-rw-r--r--  1  1  staff  4286  Aug  22  12:27  favicon.ico   
-rw-rw-rw-  1  1  staff  2114  Aug  22  12:27  index.html 
```

On local development web server `403.md` is actually available under `/403.html`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vyyavy-7kwypv

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment] 2022-08-22 22:26
Thanks for reporting @cvh23! Double checking if this is special-cased for 404 pages, or if we should properly handle all status codes this way. I'll let @matthewp confirm!

**Comment by bholmesdev** [comment] 2022-08-24 15:55
Just touched base with @matthewp on this, and it sounds like this is intentional. Popular providers like Netlify support `404` handling via a `404.html`, but not other status codes. So, we special-cased 404 routes specifically to avoid an `index.html`.

Today, you can change `route/index.html` -> `route.html` across the board by [setting `build.format: 'file'` in our Astro config](https://docs.astro.build/en/reference/configuration-reference/#buildformat). Doing this route-by-route is a good idea though! Feel free to [open a discussion here](https://github.com/withastro/rfcs) if you want that sort of feature.

Since this is expected behavior, I'll close this issue for now. Feel free to reply with thoughts though

**Comment by cvh23** [comment] 2022-08-24 16:58
Thanks for your answer. But build process output is still stating, that `403.html` was generated, which is not the case. Also local development server serves `403.html` instead of generated `403/index.html`. So there are still some issues, even if this is intentional.

Yes, would be good to have a common solution for HTTP status pages, not just 404.

**Comment by bholmesdev** [comment] 2022-08-26 14:04
Ah sorry, I forgot about that misleading console message. I'll reopen to work on a fix 👍

**Closed** 2022-08-26 15:35 UTC
Labels: p3-minor-bug
