### ISSUE TITLE
🐛 BUG: custom element with client:only adds weird import

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3179] opened 2022-04-22 11:12 UTC
### What version of `astro` are you using?

1.0.0-beta.11

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

In my page `settings.astro` I import a custom element, that I'd like to only render on the client:
`settings.astro`:

```astro
---
import '../components/mollie-subscription.js';
---
<mollie-subscription client:only></mollie-subscription>
```

Where `components/mollie-subscription.js` looks like:

```js
class MollieSubscription extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({mode: 'open'});
  }
  
  connectedCallback() {
    this.render();
  }
  
  render() {
    this.shadowRoot.innerHTML = `Loading...`;
  }
}

export const tagName = 'mollie-subscription';
customElements.define(tagName, MollieSubscription);
```

When I load this in the browser, my element is not rendered on the page, only an empty astro-root:
<img width="292" alt="Screenshot 2022-04-22 at 13 06 08" src="https://user-images.githubusercontent.com/17054057/164703261-e12843ea-f43c-4568-aeda-f1419552ac3e.png">

And it looks like the script thats supposed to load the component has a weird import:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/17054057/164703577-01947632-9c66-4842-8162-60adfd25a1d7.png">

which also leads to an error in the browser: 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/17054057/164703668-d0eb39ee-e374-4922-8b1e-5b9c79c11c70.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hcspcv?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thepassle** [comment] 2022-04-23 13:35
Aha. Just found this while reading the docs: 
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/17054057/164896857-78132a8e-455f-402a-bd46-218a65084cb4.png">

What should the value of it be if the file I want to load is just standard js (im not using any libraries/frameworks), though?

**Comment by thepassle** [comment] 2022-04-24 07:34
Did some more debugging on this. It seems that if I give the element any other directive, for example `client:load`, the components `metadata` in the `renderComponent` function looks like:
```js
{
    displayName: 'my-el',
    hydrate: 'load',
    hydrateArgs: 'foo',
    componentExport: { value: 'tagName' },
    componentUrl: '/src/components/my-el.js'
  }
```

However, if I give it the `client:only="foo"` (or even `client:only="react"`) directive, the `metadata` looks like:
```js
{
    displayName: 'my-el',
    hydrate: 'only',
    hydrateArgs: 'react',
    componentExport: { value: '' },
    componentUrl: ''
  }
```
and it doesnt seem to pick up the `componentExport` and `componentUrl` anymore, which leads it to be unable to create the correct import in the `generateHydrateScript` function. This is weird, because my component file exports a `tagName` variable, so I'd expect the `componentExport` to be `{value:'tagName'}` and the `componentUrl` to be `/src/components/my-el.js`.

Im unable to debug why the `componentExport` and `componentUrl` arent being picked up when using the `client:only` directive, because I can't find where `renderComponent` is actually being called, but this is making me think it might be a bug in the compiler? Tagging in @natemoo-re 😄

**Comment by matthewp** [comment] 2022-05-10 19:01
How client:only works is that an import statement is matched up to component usage. So if you have:

```astro
---
import Foo from '../components/Foo.jsx';
---

<Foo client:only />
```

Internally the compiler keeps metadata on this connection so that we know to import `'../components/Foo.jsx'` for this island.

For a custom element tag name, there really is no way to make that connection. If you had something like:

```astro
---
import '../components/mollie-subscription.js';
import './another';
import ./yet-another';
---
<mollie-subscription client:only></mollie-subscription>
```

The compiler doesn't know that `'../components/mollie-subscription.js'` is the thing to load. Given this, I don't think `client:only` is something we can support with custom tag name usage. However, if you were to do it this way:

```astro
---
import  Subscription from '../components/mollie-subscription.js';
import './another';
import ./yet-another';
---
<Subscription client:only></Subscription>
```

That should work regardless of what renderer you are using.

There's a similar issue open here: https://github.com/withastro/astro/issues/2526 in which the conclusion is to add a better error message around this.

Going to close as a duplicate of that. Happy to reopen if you can think of a way to make this connection, but I don't see how it would be possible.

**Closed by matthewp** 2022-05-10 19:01 UTC

**Comment by thepassle** [comment] 2022-05-10 20:56
Maybe client:only could take a module specifier?

`<mollie-subscription client:only=“../components/mollie-subscription.js”>`?
