### ISSUE TITLE
Astro Error highlights Component Template when the bug is in the Component Script

### ISSUE THREAD

**Issue by dsomel21** [withastro/astro#6372] opened 2023-02-25 23:49 UTC
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### Describe the Bug

Take a look here:

<img width="644" alt="Astro bug" src="https://user-images.githubusercontent.com/17516559/221384529-7d8557f5-4b11-41c1-a925-1cf2ffc518c5.png">

The error message in red is correct, but the stack trace is not. 

## What I Can Do:

It's probably harder than it looks, but if you can point me to the code, I can take a look :) 

### Link to Minimal Reproducible Example

> **Note**: This is **NOT** a reproducable example, because it's a DEV ONLY problem. I cannot deploy a known bug, else Netlify will complain. 

https://github.com/dsomel21/wireframes-astro/blob/main/src/pages/books/index.astro#L2-L6

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-02-27 14:33
Closing as a duplicate of https://github.com/withastro/astro/issues/5465. Our error positions in general needs work and I suspect there's a few "big issues" that would solve most of the issues.

In the future, please create a Stackblitz or CodeSandbox reproduction for this kind of issue, you do not need to give a deployed page.

**Closed by Princesseuh** 2023-02-27 14:33 UTC

**Comment by dsomel21** [comment] 2023-03-02 00:33
Thank you, I will take a look there :)
