### ISSUE TITLE
npm create astro@latest fails when creating a new project

### ISSUE THREAD

**Issue by snimavat** [withastro/astro#6860] opened 2023-04-16 16:17 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

firefox

### Describe the Bug

Ran the 1st command 

`npm create astro@latest`

and it failed with below output

```
Need to install the following packages:
  create-astro@3.1.3
Ok to proceed? (y) y

╭─────╮  Houston:
│ ◠ ◡ ◠  Time to build a new website.
╰─────╯

 astro   v2.3.0 Launch sequence initiated.

   dir   Where should we create your new project?
         .

  tmpl   How would you like to start your new project?
         Use blog template
      ✔  Template copied

  deps   Install dependencies?
         Yes
 ██████  Dependencies installing with npm...
      ▲  error Request timed out after one minute
npm ERR! code 1
npm ERR! path /Users/xxx/work/xxx/playground/astro-blog
npm ERR! command failed
npm ERR! command sh -c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXX/.npm/_logs/2023-04-16T15_56_31_603Z-debug-0.log
sudhir@macpro astro-blog % npm create astro@latest
```

Nothing to reproduce, so no link to codesandbox

### Link to Minimal Reproducible Example

https://codesandbox.com/doesnotexist

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snimavat** [comment] 2023-04-16 16:24
It fails if i choose "blog" template option during project creation steps.

**Comment by bluwy** [comment] 2023-04-17 06:45
Duplicate of https://github.com/withastro/astro/issues/6600

**Closed by bluwy** 2023-04-17 06:45 UTC

**Comment by sArVwaN666** [comment] 2023-09-22 23:14
It is happening to me with the recommended option and also with the empty project
