### ISSUE TITLE
Lit nested components results in error

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#6743] opened 2023-04-03 15:50 UTC
### What version of `astro` are you using?

2.1.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When rendering 2 lit components inside of each other an error is thrown: `elementRenderers is not iterable`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-x8wcke?file=index.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by augustjk** [comment] 2023-04-04 21:27
I think the issue is this line

https://github.com/withastro/astro/blob/4cc1bf61b832dba9aab1916b56f5260ceac2d97d/packages/integrations/lit/server.js#L62

Providing an empty object for the render info option there so it's not able to handle nested custom elements without any element renderers to handle. I can work on a fix for this.

**Closed** 2023-04-05 13:05 UTC
