### ISSUE TITLE
JS shows when using Tailwind + DaisyUI + client:only

### ISSUE THREAD

**Issue by Srlion** [withastro/astro#9957] opened 2024-02-03 01:33 UTC
### Astro Info

```block
Astro                    v4.3.2
Node                     v20.11.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

When integrating Tailwind CSS and DaisyUI in a project, embedding a framework-specific component within a div element assigned the "navbar" class—utilizing the client:only directive—results in an unexpected outcome where raw JavaScript code is displayed. This issue appears to be specifically triggered by the presence of the "navbar" class

### What's the expected result?

Not show JS code

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/daisyui-astro-us2kgv?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2024-02-06 09:39
Duplicate of https://github.com/withastro/astro/issues/8377. However, the issue can't be fixed because of https://github.com/withastro/astro/issues/8618. You need to make sure the styles don't make the injected scripts visible

**Closed by bluwy** 2024-02-06 09:39 UTC
Labels: needs triage

**Comment by kaytwo** [comment] 2024-02-09 02:57
I had the same exact issue and was able to workaround it using 

```css
.navbar > script {
  display: none;
}
.navbar > style {
  display: none;
}
```
This should work either in `global.css` or a `<style is:global></style>`.

[Stackblitz](https://stackblitz.com/edit/daisyui-astro-fmyw1d?file=src%2Fglobal.css)

**Comment by kaytwo** [comment] 2024-02-13 05:36
fixed by https://github.com/saadeghi/daisyui/commit/8b1cfedcc25b775c8e1290766fb4234e558c0bd5
