### ISSUE TITLE
Unable to `return` from SSR dynamic page

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#4631] opened 2022-09-05 17:51 UTC
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I have code like this inside my SSR (vercel adapter) page:

```typescript
const { slug } = Astro.params;

const found = data.find((o) => o.slug === slug);

if (!found) {
  Astro.response.status = 404;
  Astro.response.statusText = "Not found";
  return;
}

const obj = found;
```

When I run it (`astro dev`) I get:

```
ERROR: Top-level return cannot be used inside an ECMAScript module
```

The error seems to stem from `esbuild`. If I remove `return` from the `if` clause it works, but I need for two reasons:

1. In TypeScript `found` is `Obj | undefined` but `obj` can't be `undefined` after the `if` check. So it can be safely used and type-checked inside the template.
2. I want to early-return with 404 if the object is not found and not execute any further SSR code that might depend on the data object available.

Maybe I missed anything and there is another way to handle SSR. I also couldn't use `getStaticPaths`'s `props` because they are ignored in server mode, which I understand is required for Vercel adapter.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1ajmmy?file=src/pages/[slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zicklag** [comment] 2022-09-05 18:05
@shishkin I've run into this before, and I think the issue is that if you `return` you have to return a `Response`. Maybe you can `return Astro.response;` instead of just `return;`.

**Comment by shishkin** [comment] 2022-09-06 06:13
Thanks @zicklag! Indeed returning a new Response as described in https://docs.astro.build/en/guides/server-side-rendering/#response solved the issue!

I'll leave this issue open as I believe the error message can be improved here.

**Comment by shishkin** [comment] 2022-09-06 07:14
Also found a related bug in https://github.com/withastro/astro/issues/4635

**Comment by matthewp** [comment] 2022-09-06 14:44
Better error message would be good here for sure!

**Comment by rishi-raj-jain** [comment] 2022-09-23 02:16
I think now the logging shows the errors with this code.

**Comment by matthewp** [comment] 2022-09-23 16:28
@rishi-raj-jain can you post the logging that happens? If so we can close this issue.

**Comment by xstevenyung** [comment] 2022-09-23 20:07
Personally when running`return;`, I got the issue:

<img width="1624" alt="Screenshot 2022-09-23 at 21 55 52" src="https://user-images.githubusercontent.com/7261258/192048672-885b7716-c1c3-4013-b08d-9b0e3b6735d1.png">

**Comment by matthewp** [comment] 2022-09-23 20:15
Thank you @xstevenyung can you provide a code sample?

**Comment by xstevenyung** [comment] 2022-09-23 20:19
https://stackblitz.com/edit/github-qhds18?file=src%2Fpages%2Findex.astro%3AL10-L10

**Comment by matthewp** [comment] 2022-09-26 18:13
Closed by https://github.com/withastro/astro/pull/4857, thanks @xstevenyung !

**Closed by matthewp** 2022-09-26 18:13 UTC
Labels: p5-urgent
