### ISSUE TITLE
Tailwind class has no css on browser

### ISSUE THREAD

**Issue by Xavier-Pisco** [withastro/astro#6272] opened 2023-02-17 01:27 UTC
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

In a component of my project, I have a js variable `width` which is used as the class `w-${width}`. The CSS that is on the site has no effect, when I inspect the element, the class is as expected `w-4,` but there is no CSS associated with it. If I change and use `w-4` instead of width, everything works fine.

I think this might be due to optimizations because in no part of the project, do I use the class `w-4` so it may be marked as not needed by Tailwind and, so, it removes it to reduce the CSS size. This is just a guess, I might be completely wrong.

In the stackblitz example try to change the width value to see the difference between the 2 "blocks".

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tgltra-dhelwp?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment] 2023-02-17 05:09
This is actually normal behaviour by Tailwind and is caused by the JIT engine. You can put your classes on Tailwinds 'safelist' configuration, or completely opt-out the JIT.

**Comment by Princesseuh** [comment] 2023-02-17 07:26
Here's more information on the subject: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

Closing since this is not an Astro issue.

**Closed by Princesseuh** 2023-02-17 07:26 UTC
