### ISSUE TITLE
🐛 BUG: data astro injected before the <!DOCTYPE html>

### ISSUE THREAD

**Issue by rnwolf** [withastro/astro#3014] opened 2022-04-07 06:33 UTC
### What version of `astro` are you using?

1.0.0-beta.4

### What package manager are you using?

npm

### What operating system are you using?

Windows & Linux

### Describe the Bug

Wirth `npm run dev` and look at the source code I see

```
<link rel="[stylesheet]()" href="[/src/styles/global.css](view-source:http://localhost:3000/src/styles/global.css)" data-astro-injected></link>
<link rel="[stylesheet]()" href="[/src/styles/blog.css](view-source:http://localhost:3000/src/styles/blog.css)" data-astro-injected></link>
<link rel="[stylesheet]()" href="[/src/components/BlogHeader.astro?astro&type=style&index=0&lang.css](view-source:http://localhost:3000/src/components/BlogHeader.astro?astro&type=style&index=0&lang.css)" data-astro-injected></link>
<link rel="[stylesheet]()" href="[/src/components/BlogPostPreview.astro?astro&type=style&index=0&lang.css](view-source:http://localhost:3000/src/components/BlogPostPreview.astro?astro&type=style&index=0&lang.css)" data-astro-injected></link>
<link rel="[stylesheet]()" href="[/node_modules/@astrojs/tailwind/base.css](view-source:http://localhost:3000/node_modules/@astrojs/tailwind/base.css)" data-astro-injected></link><script type="[module]()" src="[/@vite/client](view-source:http://localhost:3000/@vite/client)" astro-script="[/test/script-0]()"></script>
<script type="[module]()" src="[/C:/Users/rnwol/workspace/astro-v1b3-tw/node_modules/astro/dist/runtime/client/hmr.js](view-source:http://localhost:3000/C:/Users/rnwol/workspace/astro-v1b3-tw/node_modules/astro/dist/runtime/client/hmr.js)" astro-script="[/test/script-1]()"></script>
<!DOCTYPE html><html dir="[ltr]()" lang="[en]()">
<meta charset="[UTF-8]()">
<meta name="[viewport]()" content="[width=device-width, initial-scale=1.0]()">

  <link rel="[apple-touch-icon]()" sizes="[180x180]()" href="[/apple-touch-icon.png](view-source:http://localhost:3000/apple-touch-icon.png)">
  <link rel="[icon]()" type="[image/png]()" sizes="[32x32]()" href="[/favicon-32x32.png](view-source:http://localhost:3000/favicon-32x32.png)">
  <link rel="[icon]()" type="[image/png]()" sizes="[16x16]()" href="[/favicon-16x16.png](view-source:http://localhost:3000/favicon-16x16.png)">
  <link rel="[manifest]()" href="[/site.webmanifest](view-source:http://localhost:3000/site.webmanifest)">
	<title>Throughput Focus home page</title>
...
```

And with `npm run build` the index.html page starts with

```
<link rel="stylesheet" href="/assets/asset.5f3f1e3c.css"></link>
<!DOCTYPE html><html dir="ltr" lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">
	<title>Throughput Focus home page</title>
```

I previously had the link to the style sheets injected after the docype and opening html tag.

I noticed this after running a Google Lighthouse report on the page.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/rnwolf/astro-v1b3-tw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by michaelfig** [comment] 2022-04-11 04:07
I'd happily submit a PR for this issue if somebody can point me at where the `<script...astro-script=` and `<link` are being injected.

My similar problem is with 1.0.0-beta.5's dev server, where my `.astro` page begins with `<?xml version="1.0"?><!DOCTYPE...` but is rendered as the following:

```html
<script type="module" src="/@vite/client" astro-script="//script-0"></script>
<script type="module" src="/Users/michael/src/self/fig-org/node_modules/astro/dist/runtime/client/hmr.js" astro-script="//script-1"></script>
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
[... rest of page follows]
```

**Comment by michaelfig** [comment] 2022-04-11 05:27
I found what's causing this for me: my `src/pages/index.astro` renders an entire page string, roughly equivalent to:

```astro
---
const html = `\
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
[... rest of page follows]`;
---
<Fragment set:html={html} />
```

The absence of a `<head>` tag within the page body defeats the compiler's insertion of `<!--astro:head-->`.

**Comment by rnwolf** [comment] 2022-04-11 08:51
Ok so what is did I move the meta tags inside the head tag and now it seems to work.

This did not work and resulted in the problem described above.
```
<!DOCTYPE html>
<html dir="ltr" lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />  
<head>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
  <link rel="manifest" href="/site.webmanifest" />
	<title>{title}</title>
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
</head>
<body>
```

I also needed to move the import for the global styles to the top of the frontmatter.

```
---
import "../styles/global.css";
etc...
```



This works

```
---
import "../styles/global.css";
import Navbar from '../components/Navbar.astro';
import NavbarSpacer from '../components/NavbarSpacer.astro';
import SiteBanner from '../components/SiteBanner.astro';
import Footer from '../components/Footer.astro';
const currentyear = new Date().getFullYear();
const { title, description } = Astro.props;

---
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
  <link rel="manifest" href="/site.webmanifest" />
	<title>{title}</title>
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
</head>
<body>
```

**Comment by tony-sull** [comment] 2022-04-13 13:17
Glad you found a fix!  Just tested locally and confirmed the issue will hit when there's no `<head>` or when `<meta>` tags are outside the head

Closing this out since it turned out not to be an issue in Astro, but it'd be cool to see an RFC down the road to add HTML validation warnings whenever we have a chance to revisit built-in accessibility and performance audit warnings :+1:

**Comment by aFuzzyBear** [comment] 2022-08-11 23:14
I have noticed this behaviour reappearing with the most recent releases with users in the support threads reporting similar issues where the link tag is being inserted before the `<html>` tag, see the following for further info, Ill append more threads to this in due course
https://discord.com/channels/830184174198718474/1007409697969688587

**Comment by matthewp** [comment] 2022-09-07 12:32
This was fixed in a patch release!

**Closed by matthewp** 2022-09-07 12:32 UTC
