### ISSUE TITLE
import.meta.glob with path aliases

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#10701] opened 2024-04-05 23:42 UTC
### Astro Info

```block
Astro                    v4.5.13
```

### Describe the Bug

import.meta.glob should be object like this

```
'/src/resolved/dir/1.png': [Function: /src/resolved/dir/1.png],
'/src/resolved/dir/2.png': [Function: /src/resolved/dir/2.png],
```

### What's the expected result?

```
'@dir/1.png': [Function: /src/resolved/dir/1.png],
'@dir/2.png': [Function: /src/resolved/dir/2.png],
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/flamboyant-parm-hmhud7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment] 2024-04-06 16:38
Duplicate of #9258 but needs to be addressed after triage if reproducible.

Fix made for the same issue earlier at https://github.com/withastro/astro/pull/9560/files.

**Comment by cdtut** [comment] 2024-04-06 19:35
That issue was about error when using path alias but this is about unexpected result. If output use `/src/resolved/dir/1.png` instead of `@dir/1.png` then you need to know actual path to get the object so no point in using alias.

**Comment by rishi-raj-jain** [comment] 2024-04-07 00:33
@cdtut 

https://github.com/withastro/astro/pull/9560/files#diff-fab61a0ffbc9d08d4f7bcecfea9cdabbd61a98cab6b521920b3b3ad944ebdd64R10 is what you're looking for to have implemented, correct?

**Comment by cdtut** [comment] 2024-04-07 17:23
I don't know what that mean but bug description shows the output and what it should be.

**Comment by bluwy** [comment] 2024-04-08 07:04
It's a Vite issue: https://github.com/vitejs/vite/issues/12180

**Closed by bluwy** 2024-04-08 07:04 UTC
Labels: needs triage
