### ISSUE TITLE
🐛 BUG: dynamic route params as numbers break findPathItemByKey search

### ISSUE THREAD

**Issue by amatiasq** [withastro/astro#3082] opened 2022-04-11 22:57 UTC
### What version of `astro` are you using?

1.0.0-beta.7

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I had `export function getStaticPaths()` returning `[{ year, month, slug }, ...]` for a blog and got hit by this error:

```
 error   [getStaticPath] route pattern matched, but no matching static path found. (/blog/2014/04/asincron-a-y-el-eventloop/)
```

After some navigating astro's code I found the issue comes from [`findPathItemByKey()`](https://github.com/withastro/astro/blob/main/packages/astro/src/core/render/route-cache.ts#L114) not being able to find a page with such params so I added this line to astro's code:

```diff
   if (matchedStaticPath) {
     return matchedStaticPath;
   }

+ debug('test', Array.from(staticPaths.keyed.keys()))
   debug("findPathItemByKey", `Unexpected cache miss looking for ${paramsKey}`);
```

and a logger in my config file

```ts
globalThis._astroGlobalDebug = (...args) => console.log(...args);
```

And got this printed out:

```
test [
  '{"month":"04","slug":"asincron-a-y-el-eventloop","year":2014}',
  ...
]
findPathItemByKey Unexpected cache miss looking for {"month":"04","slug":"asincron-a-y-el-eventloop","year":"2014"}
```

Took me a while to find out the only difference is that `year` is a number in the cache while it's a string in the key we're looking for it's a string.

**IMPORTANT**: this is only visible with `astro build`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-afsa7x?file=src/pages/[year].astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment] 2022-04-12 10:06
Thanks for all the investigation and clear reproduction here!

Looks like we have a couple issues related to numeric route params - I'll take a look and track down a fix for this and [#3058](https://github.com/withastro/astro/issues/3058) which looks very related

**Closed** 2022-04-15 19:16 UTC
