### ISSUE TITLE
404.astro in dynamic routes does not create a 404.html

### ISSUE THREAD

**Issue by stavros-k** [withastro/astro#10423] opened 2024-03-13 15:05 UTC
### Astro Info

```block
Astro                    v4.5.2
Node                     v20.11.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

build-time

### Describe the Bug

When doing an static astro build, the nested 404.astro (in dynamic routes) does not produce a 404.html file, but a 404 dir with and index.html file inside.

### What's the expected result?

The 404.astro should produce 404.html file always.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dxwnhj?file=src%2Fpages%2F%5Blang%5D%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by stavros-k** [comment] 2024-03-13 15:05
![image](https://github.com/withastro/astro/assets/47820033/68a51ffb-5941-4264-995c-832035e674d4)
![image](https://github.com/withastro/astro/assets/47820033/feb0759b-df15-48ba-9bde-75babb166006)

**Comment by lilnasy** [comment] 2024-03-13 16:55
Only `pages/404.astro` and `pages/500.astro` are given the special treatment of being output as `[code].html`.

You can enable configure [`build.output`](https://docs.astro.build/en/reference/configuration-reference/#buildformat) to get the behavior you want, but it will apply to all routes.

Doing it for deeply nested routes is not an obvious decision since there is no convention for localized error html files that static web servers follow.

**Comment by stavros-k** [comment] 2024-03-13 22:17
Thanks for pointing the build output option, I remember there was something about that!
This should solve my issue on cloudflare.

While the example is hinting to localized error page, it could be used also to have a custom page when a blog post is missing eg `/blog/[post].html` (with error at `/blog/404.html` and also have different error page for `/guides/[guide].html` or even `/[lang]/[post]/404.html` 

The same logic applies in any case.

Imho, the 404.astro and 500.astro should be treated consistently both on the top level and on any nested route.
I'm sure that this is probably not a simple "switch" to toggle, so this is probably a feature request rather than a bug.

**Comment by ematipico** [comment] 2024-03-15 10:20
Hey @lilnasy, if you don't mind, I will remove the label and open it to discussion. 

Is it something we need it? 

@stavros-k Can you explain your use case? Why does a deeply nested `404.astro` need to be treated differently?

**Comment by stavros-k** [comment] 2024-03-15 12:33
I said the opposite actually. 
I said that 404.Astro should be treated the same on any nest level.
Sorry if that wasn't clear 

Use case is both localised error pages and also different error pages per route. Eg missing product can have a "this product wasn't found"
Where on the parent level you can say the language wasn't found"

**Comment by stavros-k** [comment] 2024-03-15 12:34
I said the opposite actually. 
I said that 404.Astro should be treated the same on any nest level.
Sorry if that wasn't clear 

Use case is both localised error pages and also different error pages per route. Eg missing product can have a "this product wasn't found"
Where on the parent level you can say the language wasn't found"

**Comment by ematipico** [comment] 2024-03-15 16:39
If the nested `**/404.astro` will be treated as the root `404.astro`, how does Astro know when to render the nested 404 instead of the one of the root? 

At the end, 404 pages don't have an actual URL.

**Comment by stavros-k** [comment] 2024-03-16 10:55
> If the nested `**/404.astro` will be treated as the root `404.astro`, how does Astro know when to render the nested 404 instead of the one of the root?

Do you mean how to known which 404 to render during the build process? 
The same way it knows that the `index.astro` would be `/` for this nested route, with the difference that 404.astro will be 404.html instead of 404/index.html

If you mean in an SSR context, where a user tries to access a  [slug] that does not exist, you strip the [slug] check if a 404 exists, if it does, display that, if not trim one more segment, check again.

This is exactly how [Cloudflare works](https://developers.cloudflare.com/pages/configuration/serving-pages/#not-found-behavior)

I've learned since my original post that there are some alternative ways to do that.
1. build.output => file - That will work fine for some hosts, but others might need configuration to work with non-index.html files (eg apache, but apache)
2. build.output => directory + `404.html.ts` file as an [endpoint](https://docs.astro.build/en/guides/endpoints/#static-file-endpoints) and will keep the normal `slug/index.html` format + 404.html where you want it. 
In case of apache for example You 'd probably also want a `[htaccess].ts` and dynamic params inside due to leading dot) too to also create the appropriate `ErrorDocument` line for nested 404 serving.


And by making the above 2 points, realizing that in either way you'd have to do some extra work depending on your host, so going the `2.` way might be the best, as you get the full freedom to "hack" around.

PS. Apache is not a host of my taste/choice, but I have to support a stuborn client that prefers a single/non HA host over any other cloud :D (/rant)

!!!! Note !!!
I'm using **SSG** only, so some behaviors will not work as expected on SSR!

**Comment by iivvaannxx** [comment] 2024-07-13 15:40
I've found myself with the same problem @stavros-k mentioned. My use case is the same, to display localized 404 pages. I don't know how other cloud or hosting providers work, but in the case of [Cloudflare](https://developers.cloudflare.com/pages/configuration/serving-pages/#not-found-behavior) and like @stavros-k said, is just try to find the nearest 404 page. 

Consider this example, you have a default route at `/` which is `index.html` file, and a custom `404` page under two different folders that have different translated content. You may want to display a translated 404 error message depending on where the request failed. The request `/fourohfour` would fail and display the `/404.html` page, and the same request but with the `es` locale prefix would match the `/es/404.html` error.

```
404.html
index.html
├── es
│   ├── 404.html
│   └── index.html
```

If, for some reason, a 404 page is not found in the nearest location where the request failed, you start to crawl up the source tree until you find another 404. If none is found then you could display a fallback or something, like Astro does when you don't define a custom 404 page. 

I can't think of any other practical use cases outside of showing translated 404 pages or custom messages depending on the route where the request failed (as @stavros-k said),  like showing if it's a `blog` that is missing under a `/blogs` pathname, or if it's an `author` under an `/authors` pathname. It's not a super necessary feature, but it would be nice to have.

In my case, I'm also using SSG, and I tried manually creating a `404.astro` in my `[locale]` dynamic folder, but it doesn't match during `dev`, although this is probably expected behavior as how error handling works as of today in Astro. You can't see any content if you try to request the page `/[locale]/404`. Redirecting via `middleware` doesn't work either. It gets pre-rendered on build, but completely ignored during development. Then you have the problem this issue refers to, depending on the output strategy you may end with a `/404/index.html` which I don't think would ever work (didn't try tho). 

The solution number 2 provided by @stavros-k worked for me, I didn't want to change the output format so I manually created a `404.html.ts` endpoint with a GET request, and leveraged the current experimental `AstroContainer` API to render a custom page to an HTML string. It's a bit inconvenient, but it works. Here's the code in case anyone ever has to face a similar solution.

`[locale]/404.html.ts` file:
```ts
import type { APIRoute } from "astro";
import { experimental_AstroContainer as AstroContainer } from "astro/container";

// The page is prefixed with a _ in order to tell Astro that it should not output the page in the build.
import { default as _404 } from "./_404.astro";

// Used to dynamically render an Astro page.
const container = await AstroContainer.create();

export const GET: APIRoute = async ({ params, request }) => {
  const content = await container.renderToString(Test, {
    request,
    params,

    routeType: "page",
    locals: {
      locale: params.locale,
    },
  });

  return new Response(content, {
    status: 200,
    headers: {
      "Content-Type": "text/html",
    },
  });
};

// Your getStaticPaths for the [locale] parameter.
export const getStaticPaths = createStaticPathsHandler();
```
With this you can pre-render a nested 404 page wherever you want, and it will output a `404.html` with the contents of your Astro file.

@ematipico If you would consider this feature, we could move this to a discussion, as it would be a better place for it.

**Comment by ematipico** [comment] 2024-07-13 16:28
That's definitely a new feature worth discussing, and not a bug

**Comment by ematipico** [comment] 2024-07-19 13:15
I am going to close this for now, because Astro doesn't support nested 404 out of the box

**Closed by ematipico** 2024-07-19 13:15 UTC
Labels: needs discussion, feat: error pages
