### ISSUE TITLE
🐛 BUG: Vue component styles not included

### ISSUE THREAD

**Issue by dwaynobaggins** [withastro/astro#2644] opened 2022-02-23 10:03 UTC
### What version of `astro` are you using?

^0.22.20

### What package manager are you using?

Yarn

### What operating system are you using?

Windows

### Describe the Bug

When using a single .css/.scss file for multiple Vue components within an Astro file the css is not being rendered.
For example: 
I have a folder ...components/inputs, which contains separate instances of input Vue components such as Textfield, Checkbox and Radio. They share the same .scss import, as below, but this css is not being rendered.
```<style lang="sass" src="./input.scss" scoped></style```
If I duplicate the .scss file, and create a separate css file for each component, it works.
```<style lang="sass" src="./textfield.scss" scoped></style>
<style lang="sass" src="./checkbox.scss" scoped></style>
<style lang="sass" src="./radio.scss" scoped></style>
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/cocky-morning-u4pjxy?file=/src/components/inputs/textarea.vue

**Comment by matthewp** [comment] 2022-02-23 16:16
Pretty sure this is not a bug, so closing, happy to continue discussion here though.

**Comment by dwaynobaggins** [comment] 2022-02-23 16:36
> You don't add the src to the `src` attribute. Instead do this:
> 
> ```
> <style lang="sass">
>   @import "./checkbox.scss";
> </style>
> ```

Hi Matthewp
Reading through my BUG report I realize I didnt mention that the code in question is inside external .vue files, rather than .astro files.
Will this make a difference?
Ill try your suggestion in the meantime

**Comment by matthewp** [comment] 2022-02-23 19:31
Oh interesting, I didn't realize this was a Vue bug, will update the title.

**Comment by dwaynobaggins** [comment] 2022-02-28 10:40
I've found a work-around to this BUG.
If I create one .scss file per Vue component, and then inside that .scss file I then import the .scss file that contains all my shared code

```
// textfield.vue
<style lang="sass" src="./textfield.scss" scoped></style>
```

I then repeat this process over each Vue component sharing the code in 'inputs.scss'.

```
// textfield.scss
@use './inputs.scss'
```

This is by no means optimal, but it seems to be working

**Closed** 2022-05-10 22:05 UTC
