### ISSUE TITLE
Vitest is broken in Astro v5

### ISSUE THREAD

**Issue by sarthikg** [withastro/astro#12723] opened 2024-12-12 08:34 UTC
### Astro Info

```block
Astro                    v5.0.4
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/sitemap
                         @astrojs/react
```

### Describe the Bug

As per the (docs)[https://docs.astro.build/en/guides/testing/#vitest], configuring Vitest in Astro can be done by creating a `vitest.config.ts` file, with the following contents:
```ts
/// <reference types="vitest" />
import { getViteConfig } from "astro/config";

export default getViteConfig({
  test: {
     // Config Variables
  },
});
```

Though, after upgrading to Astro v5, this doesn't seem to be working anymore. The build is failing, as well as execution of tests are failing.

Error is as follows:
```
vitest.config.ts:5:3 - error ts(2353): Object literal may only specify known properties, and 'test' does not exist in type 'UserConfig'.
```

### What's the expected result?

The tests & build should be run.

### Link to Minimal Reproducible Example

https://github.com/sarthikg/portfolio/pull/255

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-12-12 10:24
Please provide a minimal reproduction, a project isn't acceptable

**Comment by ArmandPhilippot** [comment] 2024-12-12 10:57
Hi @sarthikg, I think this is similar to #12662.

To resume: Vitest is not yet(/longer) compatible with Vite v6, so there are conflicts right now. In the meantime, I think the workaround in #12662 should work for you too.

**Comment by ascorbic** [comment] 2024-12-12 10:59
Closing as a duplicate of #12662. It's correct that this is related to Vitest not working properly with Vite 6. There is more info in this issue: https://github.com/vitest-dev/vitest/issues/6992

**Closed by ascorbic** 2024-12-12 10:59 UTC
Labels: needs repro
