### ISSUE TITLE
Having multiple slots and loop, makes list content disappear

### ISSUE THREAD

**Issue by minht11** [withastro/astro#9860] opened 2024-01-29 09:16 UTC
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/vue
```

### Describe the Bug

Have code below:
```astro
// Base.astro
<slot name="start" />

<slot />
```

```astro
---
  import Base from './Base.astro'

  const items = [1, 2, 3]
---

<Base>
{
  true && <div slot="start">Start</div>
}

{items.map((i) => <div>{i}</div>)}
</Base>
```
Observe that only one list item remains instead of 3.
<img width="331" alt="image" src="https://github.com/withastro/astro/assets/8914032/14696adb-853f-461c-a178-b50594a89a68">

### What's the expected result?

List content does not disappear.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kb5pc3?file=src%2Fcomponents%2FList.astro,src%2Fpages%2Findex.astro,src%2Flayouts%2FLayout.astro,src%2Fcomponents%2FBase.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment] 2024-01-29 10:31
I think this is a duplicate of https://github.com/withastro/compiler/issues/950, @MoustaphaDev what do you think?

**Comment by MoustaphaDev** [comment] 2024-01-29 11:15
Yep that's the same issue, I'll have a PR out to fix this today.
In the meantime, you can wrap the second loop around fragments @minht11 
```tsx
---
  import Base from './Base.astro'

  const items = [1, 2, 3]
---

<Base>
{
  true && <div slot="start">Start</div>
}
<>
  {items.map((i) => <div>{i}</div>)}
</>
</Base>
```
Sorry for the trouble!

**Closed by MoustaphaDev** 2024-01-29 11:15 UTC
Labels: needs triage
