### ISSUE TITLE
🐛 BUG: Astro.glob always omits trailing slash, even if trailingSlash is set to always

### ISSUE THREAD

**Issue by NotWoods** [withastro/astro#3314] opened 2022-05-07 03:23 UTC
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I want to use `Astro.glob()` to get a collection of my pages, and I expect `page.url` to correspond to the URL that the server will be sending. Not doing so causes unwanted redirects, and the dev server often doesn't even redirect me.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/hopeful-panini-5rpj4y?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-05-10 22:01
Seems like this should have been fixed in https://github.com/withastro/astro/pull/3198, but maybe we're still missing something.

Mind taking a look @JuanM04?

**Comment by JuanM04** [comment] 2022-05-11 23:55
I can't reproduce the error :thinking:. The example button points to `/projects/`, right? Do you expect `/projects`?

**Comment by tatethurston** [comment] 2022-07-29 03:47
I'm seeing this behavior as well on  1.0.0-beta.73

**Closed** 2022-08-03 20:28 UTC
Labels: s1-small, p2-nice-to-have
