### ISSUE TITLE
🐛 BUG: links.map(link) doesn't recognize link

### ISSUE THREAD

**Issue by j-delisle** [withastro/astro#2111] opened 2021-12-03 15:33 UTC
### What version of `astro` are you using?

0.21.5, 0.21.6, 0.21.8

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Getting a 500 server error due to the map

Error: link is not defined
ReferenceError: link is not defined

```
{links.map((link) => (
                <a class="btn btn-link btn-sm rounded-btn text-secondary" href={link.url}>{link.text}</a>
 ))}
 ```
The link item is not recognized. If just link.url is there and no link.text it works and vice versa, if link.url is taken out and link.text is left it works. 

This could possibly be related to https://github.com/withastro/astro/issues/2104 but rolling back to both 0.21.6 and 0.21.5 didn't fix it

### Link to Minimal Reproducible Example

https://astro.build/play#EQegDghg5gpgziACtGA6CcAuAnA9sALmABkBFAC1IHEBZACTgBE4qBjAIVYEEBRLgFS7kAbgDUAlgGEAHOMYwwAMT4AjLgGUATFCqYAmlwCuAJS4rSxAAzGA8sdw8DAdS5UA1gA0oiml0QxGUkY3LlZRYx5xYV4AFnZEPQATAHdJQ0tccQBJRktQ5IAbdQBWZIAPLkUAThtGDx4yiAApF1EAW2Kq9iyoLKyuACt1LOEoYh4ATwBGPTbFbABVfgKAZjgAOQGFgC8Ddba4bvVpLj1jKBpWRVYCxQ8F3AhGAY8uKa4uD1F2KoXFLjATUUWQA0k4qMkFolFKQuDZxMQQQt2OwoAsPjAAFrdLjrZJcADU7DcWSoADYYU4ynQuOJRIpyHpiB9xHRIHRRFQCjwXFxiJzjP06IlelApjx2MkplB2JY6MlWG4VpgJh8OTT1DBFAUoLEuOxyDEsjEGVqyMUIlAnG1YdssuQvCCYphIslIgB2DziAaMACOPBBVCyTV9mAAZr7GHpMQMbCoaJiZBBJFk9O7pAYuE03LDFHA4CpxE0CuswDRJVRxATGDRpOoymHellMVNcPxGG0AHZTNq0JpwLjSJwDRQg9YxBY0Yy+9YQMPJNry6RqTvCdhgYhlGI2LjFYT8KhhkHSdaiPTsBbSCDkAa6kGJL5cSQLTSMCCs0SMLKiAZZCBtVww2IKhGE7KAyRBTBLEYJxMThTBfRgGAaFISw2lYSxFGMCZ2E0VsYCgcQYE3KAVCmNxEGINo3EMAknEUKVSF9OhO0sFQFh9XAZzAgkoAgRA3HIMpfXITRDCmQwnHWRDMTJGByBgRIIHYa84GIMlijgYwYimMkmh3CAbFIVhcE-YziDAmgeFIJwmigURXCaOhND0CY9AHQc4AwiB0SyQRcESXBOzcUQAFo2k0bYVCcMAYi4YxLAWSwphiaR3UwKYPDKYDsKwvIVCoTFyCclR+G2NoQW2KgeAJOgCSqYoChgAlUNIRICUHbpOyaEEBgJMomP4ULMBgSxXxUUR+CaLgCmwA4uEwdg4CcYhthsGBcG2AZcBsURUuEZIYCaHgNWIZJEC4MoygWKhHgGYgGUUfhmS4bYLzcRh1HYO69GwVhMUUX1JHYKgoGkTBpCaSR1CoCYaEYKBcCgUhjxoAd2EkD7pFoKpthWdZxHdFNN0sI1hAmbFFDOmwylCxA4CkbBJEidhtl8GgSXJYp2CIrgJnEdRfTcYRsGSdZeIgULYCoPR1hBVhpFZ4grN9UgaDAKpsFIJMwAGclxFgAZ+YKNpbNwEJFAgahSHWTtDGEWyCjBJoJjZnhMT0XYjZwgYPjgTsyiyYxthBZIslIYwYD0TRiGMFRFDDKgPLoLJuRBMBcExVgKmjxRQeWDxpxoTQQR4ZJGAKOPMD5xh0-IehlicSxYWAIA

**Comment by natemoo-re** [comment] 2021-12-03 16:49
Thanks for opening an issue! I'm on it.

Closing this as a duplicate of #2104.

**Closed by natemoo-re** 2021-12-03 16:49 UTC
