### ISSUE TITLE
Astro+Lit works only on initial load (CustomElementRegistry)

### ISSUE THREAD

**Issue by logindejavu27** [withastro/astro#6826] opened 2023-04-12 16:00 UTC
### What version of `astro` are you using?

2.2.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Astro+Lit works ONLY on initial load, but when you do any modification breaks with following error:
`
**Failed to execute 'define' on 'CustomElementRegistry': the name "xxxxx" has already been used with this registry**
`

1) open following example:  https://astro.new/framework-lit?on=stackblitz
2) add something new into html of component `src/components/calc-add.js` or `src/components/my-counter.js`
3) observe the error `Failed to execute 'define' on 'CustomElementRegistry'`

### Link to Minimal Reproducible Example

https://astro.new/framework-lit?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-04-12 16:17
Closing as a duplicate of https://github.com/withastro/astro/issues/6734

**Closed by Princesseuh** 2023-04-12 16:17 UTC
