### ISSUE TITLE
Regression: Pagination with `[...page]` doesn't work at the "root level" (src/pages)

### ISSUE THREAD

**Issue by castarco** [withastro/astro#4306] opened 2022-08-13 17:29 UTC
### What version of `astro` are you using?

1.0.4, 1.0.5

### Are you using an SSR adapter? If so, which one?

---

### What package manager are you using?

yarn

### What operating system are you using?

Linux (Ubuntu, x86_64)

### Describe the Bug

When using the pattern `[...page].astro` inside the "root" directory (`src/pages`), only the 2nd and following pages are generated, while the first one is discarded.

**Notes:**
- The bug was not present in 1.0.3
- It can be mitigated by setting `trailingSlash: 'always'` in `astro.config.mjs`
- This can't be seen when running `yarn dev`, only when looking at generated code via `yarn build`.
- This doesn't happen when done inside other nested directories.

While we could use `index.astro` as a workaround, it can be quite cumbersome at the time of keeping track of pages.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/castarco/astro_pagination_bug_example

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by castarco** [comment] 2022-08-13 18:42
It was probably introduced in this PR: https://github.com/withastro/astro/pull/4265/files , checking now...

**Comment by phocks** [comment] 2022-08-15 12:34
I just noticed this is happening for me too ...

**Comment by natemoo-re** [comment] 2022-08-15 14:09
Thanks! I'm going to assign this to @matthewp since his PR seemed to cause the regression.

**Comment by phocks** [comment] 2022-08-15 20:30
Reverting to [astro@1.0.3](https://github.com/withastro/astro/releases/tag/astro%401.0.3) fixed this for me.

**Comment by phocks** [comment] 2022-08-20 01:24
> Thanks! I'm going to assign this to @matthewp since his PR seemed to cause the regression.

Also, my guess it that this was already maybe broken before the PR that made no trailing slashes the default. So we might have to go back to the original [...page] code.

**Comment by matthewp** [comment] 2022-08-22 15:09
Thanks for your patience, I'm looking into this issue now.

**Closed** 2022-08-23 12:47 UTC
Labels: p5-urgent
