### ISSUE TITLE
astro.config.js should make it possible for the `_image` endpoint to remove the `base`

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [withastro/astro#8952] opened 2023-10-30 17:18 UTC
### Astro Info

```block
/var/www/public_html $ npx astro info
Astro                    v3.4.0
Node                     v21.0.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
                         @astrojs/tailwind
                         @astrojs/prefetch
                         @swup/astro
 error   Command failed: which xclip
  File:
    /var/www/public_html/node_modules/.pnpm/astro@3.4.0_typescript@5.2.2/node_modules/astro/dist/cli/info/index.js:38:20
  Code:
    37 |   } else {
    > 38 |     const output = execSync("which xclip", { encoding: "utf8" });
         |                    ^
      39 |     if (output[0] !== "/") {
      40 |       return;
      41 |     }
  Stacktrace:
Error: Command failed: which xclip
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at copyToClipboard (file:///var/www/public_html/node_modules/.pnpm/astro@3.4.0_typescript@5.2.2/node_modules/astro/dist/cli/info/index.js:38:20)
    at printInfo (file:///var/www/public_html/node_modules/.pnpm/astro@3.4.0_typescript@5.2.2/node_modules/astro/dist/cli/info/index.js:28:9)
    at async runCommand (file:///var/www/public_html/node_modules/.pnpm/astro@3.4.0_typescript@5.2.2/node_modules/astro/dist/cli/index.js:69:7)
    at async cli (file:///var/www/public_html/node_modules/.pnpm/astro@3.4.0_typescript@5.2.2/node_modules/astro/dist/cli/index.js:144:5)
```

### Describe the Bug

I don't know if it's a bug or an intended feature, but this issue wasn't present with the previous `@astrojs/image` integration.

When you set a base in the Astro config, it gets prepended to `_image`, resulting in `/base/base2/_image`. 

In the older `@astrojs/image` integration, the `_image` endpoint worked as expected, even with a base set. 

It would be great if the new image support could allow the `_image` endpoint to respond at both `_image` and `/base/_image`, or at least make this behavior configurable.

### What's the expected result?

`_image` endpoint should respond to the Image requests when a base is set in the config.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-xqjwat?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-10-30 19:02
Your reproduction doesn't work because `image.endpoint` is set to `_image`, when it's supposed to be the entrypoint of the module to use as the endpoint.

For the rest, I'm not sure I understand... Your website is hosted at that base, so presumably your endpoint would too?

**Comment by Tanguy-Magnaudet** [comment] 2023-10-31 07:57
`For the rest, I'm not sure I understand... Your website is hosted at that base, so presumably your endpoint would too?`

This is true if astro is handling the routes.

We already had a backend and we used Astro to replace the old react SSR express server that was rendering the pages in an isolated container.

Now that the base is prepended to `/_image`, we have to edit that endpoint in the Caddyfile everytime it changes.
As it is easy to forget it and waste time wondering what is the problem, we would like to force the image endpoint to be at `/_image`, nothing else (like it was before with the integration).

**Comment by ematipico** [comment] 2023-10-31 08:07
> This is true if astro is handling the routes.

Then, wouldn't it be easier to let your backend/webserver handle the base using a reverse proxy?

**Comment by Princesseuh** [comment] 2023-10-31 08:54
Yeah, this is honestly out of scope to have in Astro itself. `base` is already hard enough to manage without having niche opt-out like this.

I'd suggest making your own image service that wraps ours, like such:

```ts
import sharpService from "astro/assets/services/sharp";

export default {
	...sharpService,
	async getURL(options, imageConfig) {
		const originalURL = await sharpService.getURL(options, imageConfig);
		
		return originalURL.replace(import.meta.env.BASE_URL, '');
	}
}
```

**Closed by Princesseuh** 2023-10-31 08:54 UTC
Labels: needs response
