### ISSUE TITLE
Tailwind added after my style block clearing all styles

### ISSUE THREAD

**Issue by kubre** [withastro/astro#8044] opened 2023-08-11 20:11 UTC
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

I'm using the tailwind plugin for Astro, after updating Astro to the latest version it started adding a tailwind at the end of the head tag(as shown in the image). This causes any style added above to be reset on tags like `h1 { @apply bg-black } ` etc won't work. Downgrading back to the old version 2.0.15 and styles apply fine. Please check stackblitz

![image](https://github.com/withastro/astro/assets/20380094/8e76833c-c672-477c-8a3d-b314544ac610)

### What's the expected result?

Custom styles should be added after the base styles of the tailwind. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vbv2yk

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kubre** [comment] 2023-08-12 07:20
If anyone wants a quick fix for now I'm using it `.parent` class for general tags like h2, p etc. to override the base styles from a tailwind.

```csss
/* So rather than using */
h1 { <styles> }

/* Use */
.parent h1 { <styles> }
```

in HTML you will need

<div class="parent">
<slot/>
</div>

**Comment by natemoo-re** [comment] 2023-08-14 13:39
Sorry for the frustration! This behavior has switched back and forth and we really need to stabilize this.

I'm guessing that this regression was caused by https://github.com/withastro/astro/pull/8011 which switches how we crawl imports to find which styles need to be injected. This likely reverted the crawling order and messed up how styles were being injected during `dev`.

**Comment by Dunqing** [comment] 2023-08-15 17:25
`UnoCSS` has the same issue, https://github.com/unocss/unocss/issues/2821

**Comment by bluwy** [comment] 2023-09-25 09:17
I traced this to a Vite bug. The import order was not preserved by Vite dev module graph which caused the CSS to be out of order too. https://github.com/vitejs/vite/pull/14465

**Comment by bluwy** [comment] 2023-09-26 08:28
Going to close this for now as the work is done, and the fix is upstream. I'll look into backporting and releasing a patch for Vite 4 perhaps around this week or so.

**Closed by bluwy** 2023-09-26 08:28 UTC
Labels: - P4: important, pkg: tailwind
