### ISSUE TITLE
Astro check everything inside `dist` folder

### ISSUE THREAD

**Issue by teinett** [withastro/astro#11375] opened 2024-06-29 16:44 UTC
### Astro Info

```block
Astro                    v4.11.3
Node                     v18.20.2
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/mdx
                         @astrojs/sitemap
                         astro-meta-tags
                         astro-robots-txt
```

## Preconditions

I use npm workspaces

```
{
  "name": "learn-monorepo",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
  }
}

```

With the file structure:

```
/
├── node_modules/*
├── packages/
│   ├── design-system/
│   └── astrojs-project/
├── README.md
└── package.json
```
   
## Problem 

I go to astro project folder: `cd packages/astrojs-project`.

I want to check files: `npm run check`

AstroJS starts to checks files.

Actual result: AstroJS check files in `dist` folder too and finds many errros.

```
dist/server/chunks/astro_CtLE2bzG.mjs:3:24 - warning ts(7016): Could not find a declaration file for module 'html-escaper'. '/Users/teine/Development/learn-monorepo/node_modules/html-escaper/esm/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/html-escaper` if it exists or add a new declaration (.d.ts) file containing `declare module 'html-escaper';`

3 import { escape } from 'html-escaper';
                         ~~~~~~~~~~~~~~

dist/server/chunks/astro/assets-service_0V-cghdH.mjs:51:39 - warning ts(6133): 'allowWildcard' is declared but its value is never read.

51 function matchPathname(url, pathname, allowWildcard) {
                                         ~~~~~~~~~~~~~

dist/server/chunks/pages/node_BZ4OhT3s.mjs:1066:23 - warning ts(80007): 'await' has no effect on the type of this expression.

1066     const transform = await imageService.parseURL(url, imageConfig);
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/pages/404.astro:6:2 - error ts(2322): Type '{ children: any; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Type '{ children: any; }' is missing the following properties from type 'Props': metaSearch, metaSocial

6 <Layout>
```

<img width="1444" alt="2024-06-29 13-42-46" src="https://github.com/withastro/astro/assets/1038168/033b904f-1157-4bde-bca9-9f09ae7a8bea">

### What's the expected result?

Expected: only files in `src` folder will be checked.

### Link to Minimal Reproducible Example

no code

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-06-29 17:03
Duplicate of https://github.com/withastro/language-tools/issues/643

`astro check` follows the same include and exclude patterns as `tsc`, as such, you can add the dist folder to your `tsconfig.json`'s `exclude` array.

**Closed by Princesseuh** 2024-06-29 17:03 UTC
Labels: needs triage

**Comment by teinett** [comment] 2024-06-30 01:08
@Princesseuh Do you documentation about this behavior and rules, how to exclude this unwanted thing?

**Comment by Princesseuh** [comment] 2024-06-30 02:35
https://www.typescriptlang.org/tsconfig/#exclude
