### ISSUE TITLE
React children are being rendered as though they are markdown in mdx files

### ISSUE THREAD

**Issue by nasainsbury** [withastro/astro#4998] opened 2022-10-06 12:50 UTC
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

We have a page,

```
---
title: Buttons
description: Buttons, how and when to use them.
created: "09 Aug 2022"
lastUpdated: "10 Aug 2022"
image:
  alt: "Buttons at TES!"
  src: "./button-og.png"
layout: ../../layouts/MainLayout.astro
---

import CodeRenderer from "./../../components/CodeRenderer";

<CodeRenderer>
  <button className="text-green-50 px-2 py-1 bg-emerald-800 rounded-none">
    Continue
  </button>
</CodeRenderer>
```

Where `CodeRenderer` is simply:

```
import type { ReactNode } from "react";

type Props = {
  children: ReactNode;
};

const CodeRenderer = (props: Props) => {
  return props.children;
};

export default CodeRenderer;
```

When this is rendered, it is rendered as:

```
<button>
  <p>Continue</p>
</button>
```

I suspect the children are being formatted with the markdown formatter before being passed in as children, i.e:

```
<CodeRenderer>
  <button className="text-green-50 px-2 py-1 bg-emerald-800 rounded-none">
    Continue **bold**
  </button>
</CodeRenderer>
```

Renders

```
<button>
  <p>Continue <strong>bold</strong></p>
</button>
```

When, what I would want is

```
<button>Continue **bold**</button>
```

I cannot be sure if this is a bug, or this is the desired behaviour. Can you advise on whether this is something we should be handling, or whether this is a bug?

### Link to Minimal Reproducible Example

https://codesandbox.io/s/eager-hamilton-8cznb3?file=/src/pages/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-10-07 14:43
I would recommend debugging this in a plain MDX project (or using the [MDX Playground](https://mdxjs.com/playground/)) to confirm if the behavior in Astro differs from what MDX gives you out of the box.

I'm pretty sure this is an intentional feature of MDX, but it'd be good to confirm.

**Comment by bholmesdev** [comment] 2022-11-01 17:58
@nasainsbury Ah yes, parsing component children as Markdown (rather than raw text) follows the MDX spec, so this is expected. I'd suggest embedding as a string if you want to pass "raw" Markdown as children:

```ts
<Component>
{`**Raw** content`}
</Component>

I still want to clarify from your example though: you show your Tailwind classes being removed in the compiled `button` output, which I could not replicate in a Stackblitz. Is this also an issue for you?

**Comment by bholmesdev** [comment] 2022-11-04 14:47
@nasainsbury Since this is expected behavior, I plan to close this issue by end-of-day. Let me know your thoughts to the question above and I'm happy to reopen if needed!

**Closed** 2022-11-11 20:02 UTC
Labels: p4-important, MDX
