### ISSUE TITLE
[Bug]: WordPress Rest Api does not optimize images - set:html

### ISSUE THREAD

**Issue by javix64** [withastro/astro#10824] opened 2024-04-19 18:38 UTC
### Astro Info

```block
Astro                    v4.6.3
Node                     v21.6.2
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

1. When you fetch a page/post in WordPress Rest Api and you get the json, all the images inside the key:`content.rendered` (which is a string of the content of HTML) you are not able to optimize this images as usually happens when you use <Image />.
![screenshot1](https://github.com/withastro/astro/assets/58471170/7131eb21-7bbb-4392-8ebe-d98fb62578d0)
3. I am using the guide in [Headless Wordpress and Astro](https://docs.astro.build/es/guides/cms/wordpress/).
4. The code is:
```javascript
---
import { Image } from "astro:assets";
const res = await fetch("http://localhost:32768/wp-json/wp/v2/pages/23");
const page = await res.json();
---
<h2 set:html={page.title.rendered} />
<p set:html={page.content.rendered} />
```
5. My config in `astro.config.mjs` is (note that I am using an example images from wikimedia.org):
```javascript
export default defineConfig({
  image: {
    domains: ["localhost:32768", "**.wikimedia.org"],
    remotePatterns: [
        {
            protocol: "https",
            hostname: "**.wikimedia.org",
            pathName: "/**",
          },
          {
            protocol: "http",
            hostname: "localhost:32768",
            pathName: "/**",
          }
    ],
  },
});
```
6. When you build the Astro App, the app does not optimize the images. Refer to `screenshot2.png`. 
![screenshot2](https://github.com/withastro/astro/assets/58471170/33bef840-e789-408d-9720-012b0b29124a)
Also when you open the index.html from dist folder, you see:
![screenshot3](https://github.com/withastro/astro/assets/58471170/d9fd04aa-a68f-4c27-8e04-eec3ed909047)

7. I wrote a simple javascript function (that I do not have) that get the stringify text, replace the <img> tag for a text like: `<Image src="${src}" alt="${alt}" height="${height}" />`. But doing this does not render it properly.
8. I did not found any interesting data related with this issue in the documentation neither in the issues in the github.
9. I would like to collaborate but I do not know if I am good enought to do something like this because I do not know where to start :smile: 

### What's the expected result?

You are able to optimize any image from any CMS. Probably this is an issue with the directive `set:html`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ttupuv?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-04-22 09:05
Its `pathname`, not `pathName`: https://docs.astro.build/en/reference/configuration-reference/#imageremotepatterns

**Comment by Princesseuh** [comment] 2024-04-22 09:43
We don't process random `img` tags automatically, especially not from strings. Typically what you would do when rendering from a CMS is that when you render an image block, you pass the image src to `getImage`. If your CMS just returns a big string, there's not much we can do.

In the case of Wordpress, you may also want to look at getting the images from the `_embed` property when relevant.

Closing because this is not a bug, if you would like to see this as a feature, please open a discussion here: https://github.com/withastro/roadmap/discussions

**Closed by Princesseuh** 2024-04-22 09:43 UTC
Labels: needs response
