### ISSUE TITLE
Markdown pages aren't included in the build when they reference a local image

### ISSUE THREAD

**Issue by vadimdemedes** [withastro/astro#8485] opened 2023-09-10 08:43 UTC
### Astro Info

```block
Astro                    v3.0.8
Node                     v20.5.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

1. Store any image inside `src` folder (e.g. `src/assets/image.jpg`)
2. Create a Markdown page (e.g. `src/pages/example.md`)
3. Show that image on this page (e.g. `![](../assets/image.jpg)`)
4. In development mode (`astro dev`), `/example` page loads as expected and shows that image
5. When running `astro build`, `/example` page doesn't show up in "generating static routes" section nor does it exist in the `dist` folder.
6. As soon as you remove `![](../assets/image.jpg)` from Markdown and run `astro build` again, `/example` page is generated and exists in the `dist` folder as `/example/index.html`, as expected.

### What's the expected result?

Generate the Markdown page with or without local images in `astro build` or show the error that prevents that page from being built.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/epic-resonance-qfsyl4

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by vadimdemedes** [comment] 2023-09-10 08:45
I deploy my website on Vercel and I found out that if I use a `@astrojs/vercel/serverless` adapter with `output: "hybrid"`, this problem goes away. Maybe this is useful information for figuring out the root cause of this.

**Comment by ematipico** [comment] 2023-09-11 10:39
@vadimdemedes your `astro info` says that you don't use any adapter. Could you please update that information please? That's really important to us

**Comment by vadimdemedes** [comment] 2023-09-13 06:20
Yep, that is correct, I don't use any adapter when that bug happens. If I use `@astrojs/vercel/serverless` with `output: "hybrid"`, the bug goes away.

**Comment by Princesseuh** [comment] 2023-09-15 13:41
Duplicate of https://github.com/withastro/astro/issues/8547. The message looks slightly different because of a coincidence, but it's the same issue

**Closed by Princesseuh** 2023-09-15 13:41 UTC
Labels: - P4: important, feat: assets
