### ISSUE TITLE
Astro.locals, set in middleware, available on 404 page in dev mode but not in production mode

### ISSUE THREAD

**Issue by xriter** [withastro/astro#8154] opened 2023-08-18 23:43 UTC
### What version of `astro` are you using?

2.10.12

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

After some previous bugs around the 404 page have been solved, I still experienced problems with my 404 page not rendering. I now found the reason: another bug.

When using `middleware.ts` to set `Astro.locals`, you can then use those values in the `404.astro` page when it's in dev mode. But when in production mode, those values are undefined. (This caused the page to crash without me knowing, resulting in a blank 404 page).

👉 **So in short: the behaviour of `Astro.locals` availability in `404.astro` between dev and production mode is inconsistent.**

This problem started from Astro 2.9.7. Before that it worked as expected.

To repro and see the difference between the 2 modes, go to the stackblitz link.
Then first run `npm run dev` and then `npm run build && npm run preview`

Dev mode (the expected result):
<img width="1481" alt="Scherm­afbeelding 2023-08-19 om 01 37 38" src="https://github.com/withastro/astro/assets/70454441/87e24e26-9063-4522-bec1-aaf766b93afb">

Production mode:
<img width="1493" alt="Scherm­afbeelding 2023-08-19 om 01 38 03" src="https://github.com/withastro/astro/assets/70454441/34254afd-4c26-4dd5-8160-3e63ac615647">

(This is a continuation of the problem I first described in issue #8054, but turns out to be a separate bug.)

### What's the expected result?

I expect `Astro.locals`, set in `middleware.ts` to be available in `404.astro` in production mode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-trfvka-twqzu5?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment] 2023-08-19 14:17
Might be related #7881

**Comment by lilnasy** [comment] 2023-08-19 14:19
@xriter Does middleware work at all for 404?

If not, this is the same issue I brought up in #7881.

**Comment by lilnasy** [comment] 2023-08-19 14:55
Thanks for opening this issue and confirming!

To clarify, this issue is **not** a duplicate of 7881. When I reported it in that issue, I should've created another issue instead.

**Comment by lilnasy** [comment] 2023-08-19 15:12
Is the [workaround](https://github.com/withastro/astro/issues/7881#issuecomment-1664540900) possible in your case?

**Comment by lilnasy** [comment] 2023-08-19 15:29
I don't think there is.

You may already be using a slug route, but in that case, I think 404.astro never gets matched anyway.

**Comment by ematipico** [comment] 2023-08-25 11:24
This fix will be released as part of Astro 3.0

**Closed** 2023-08-25 11:24 UTC
Labels: - P4: important, feat: ssr, feat: 404
