### ISSUE TITLE
preact + node adapter: hydration issues

### ISSUE THREAD

**Issue by rburgst** [withastro/astro#11366] opened 2024-06-27 17:48 UTC
### Astro Info

```block
❯ npx astro info
Astro                    v4.11.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/preact
```

### If this issue only occurs in one browser, which browser is a problem?

All Browsers

### Describe the Bug

I have a preact component with `client:idle`. When rendering it I have the following problems

1. it gets rendered 4x on the server
2. it seems that the component gets re-created and looses its previous state

My Component looks as follows: 
```typescript
export const PreactComponent: FunctionComponent<PreactComponentProps> = ({id}) => {
    const [mapId] = useState(generateRandomHtmlId(id));

    console.log("render preact comp", {mapId})
    return (
          <div id={mapId}>
               <h1>Hello, World!</h1>
               <pre>ID: {mapId}</pre>
          </div>
     );
}

 function generateRandomHtmlId(id?: string) {
    return id || `html-id-${Math.random().toString(36).substring(2, 9)}`;
  }
  ```
So the idea is to create a random id in case it is not provided by the outside.

If you load a page that contains this component, then 
a) I see the server side printout "render preact comp xxx" 4 times, with 4 different random ids
b) on the client it gets rendered again (which is obvious) with a **completely new id**. 

So the question is why does it get rerendered multiple times on the server and why does not it re-hydrate with one of the ids from the server.

<img width="1187" alt="image" src="https://github.com/withastro/astro/assets/22971/1089ba75-e612-4ab0-a498-0bdb605bebd3">

### What's the expected result?

it should only render once on the server and the generated state from the server should be rehydrated on the client.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5bt3je?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by rburgst** [comment] 2024-06-27 17:50
as a side note, when I try to use `useId()` I get 
```
Cannot read properties of undefined (reading '__m')
```

**Comment by Princesseuh** [comment] 2024-07-17 13:53
It's expected for the state to be lost between the server and the client, not many frameworks support this (you might see this called resumability). The multiple render are expected at this time for Preact due to how the checking step works, it requires rendering the component twice. In local, when I download your reproduction I get two calls, as expected.

The usage of `useId` has been fixed in the latest version of the preact integration, which would be the proper way to share the id between the server and the client

**Closed by Princesseuh** 2024-07-17 13:53 UTC
Labels: needs triage
