### ISSUE TITLE
Body can't be set outside of layout

### ISSUE THREAD

**Issue by reggi** [withastro/astro#11031] opened 2024-05-13 19:24 UTC
### Astro Info

```block
✗ npx astro info
Astro                    v4.7.0
Node                     v21.7.3
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

I have a series of nested layouts and I didn't want the `<body>` tag included in the root layout because I wanted to be able to add custom tailwind. But I realized that astro will ignore a `<body>` if it's as a `<slot>` to a layout. I think the dom is adding a body when you view the tree, but view source shows no body.

### What's the expected result?

That I'd be able to set a body from outside the root layout.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hfbtiv?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2024-05-13 20:15
This has never worked very well and I would suggest not doing this. Instead make your layout include the body but pass the props you want to be attached to it.

There is a compiler bug for this already, so going to close this one as a duplicate of https://github.com/withastro/compiler/issues/982

**Closed by matthewp** 2024-05-13 20:15 UTC
Labels: needs triage
