### ISSUE TITLE
Local Image -"width" and "height" cannot both be undefined

### ISSUE THREAD

**Issue by DanyJack** [withastro/astro#5202] opened 2022-10-26 15:13 UTC
### What version of `astro` are you using?

1.5.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Hi,

With this code:
`<Image src="/assets/images/myimage.webp" alt="my image" />`

I get this error: "width" and "height" cannot both be undefined.

The issue is using local images...

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ayqcdg?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DanyJack** [comment] 2022-10-26 15:52
The problem is when the path to the image is used.
`<Image src="/assets/images/myimage.webp" alt="my image" />`
(in this way the image is not find also...)

In this way I do not get error and the image is visible:
`import myImage from "../images/my-image.webp"`
`<Image src={myImage} />`

**Comment by tony-sull** [comment] 2022-10-26 20:14
We're working on improved image docs this sprint, sorry for any confusion there!

If `<Image />` is given a string instead of an imported image it treats it like a remote image and requires image that you pass in image dimensions.

Importing the image in frontmatter similar to `import myImage from "../images/my-image.webp"` is the usual way to pull an image file into the build

You can actually inline the import as well if you want to avoid the frontmatter import, `<Image src={import("../images/my-image.webp")} />`

**Comment by tony-sull** [comment] 2022-10-26 20:14
Meant to keep this open to track in case we can improve the error message along with docs updates :+1:

**Comment by DanyJack** [comment] 2022-10-27 08:54
Hi Tony, thank you for all your info!

And thanks for the work you do :)

**Comment by wulinsheng123** [comment] 2022-11-08 03:28
> Meant to keep this open to track in case we can improve the error message along with docs updates 👍



> We're working on improved image docs this sprint, sorry for any confusion there!
> 
> If `<Image />` is given a string instead of an imported image it treats it like a remote image and requires image that you pass in image dimensions.
> 
> Importing the image in frontmatter similar to `import myImage from "../images/my-image.webp"` is the usual way to pull an image file into the build
> 
> You can actually inline the import as well if you want to avoid the frontmatter import, `<Image src={import("../images/my-image.webp")} />`

there is some confused here.
if the file `myimage.webp` is in the public folder.
looks like `<Image src="./myimage.webp" alt="my image" />`
it works well

**Comment by wulinsheng123** [comment] 2022-11-08 07:52
> We're working on improved image docs this sprint, sorry for any confusion there!
> 
> If `<Image />` is given a string instead of an imported image it treats it like a remote image and requires image that you pass in image dimensions.
> 
> Importing the image in frontmatter similar to `import myImage from "../images/my-image.webp"` is the usual way to pull an image file into the build
> 
> You can actually inline the import as well if you want to avoid the frontmatter import, `<Image src={import("../images/my-image.webp")} />`

 I have a little confused about how to resolve "width" and "height" both be undefined ?

**Comment by enricogallesio** [comment] 2022-11-16 09:48
Hey there
I'm having the same issue. I tried all the options to keep the image file in /src, in /public, I tried to import the image as per the examples, I tried with and without sharpt, but I always get:
`error   "width" and "height" cannot both be undefined`
with local images.
I think this error deserves further investigation. I've found people even in the Discord channel asking for the same problem with local images.

**Comment by saadatfar** [comment] 2022-11-29 09:31
> Hey there I'm having the same issue. I tried all the options to keep the image file in /src, in /public, I tried to import the image as per the examples, I tried with and without sharpt, but I always get: `error "width" and "height" cannot both be undefined` with local images. I think this error deserves further investigation. I've found people even in the Discord channel asking for the same problem with local images.

The Same here

**Comment by enricogallesio** [comment] 2022-11-30 08:12
> The Same here

Are you by any chance using both @astrojs/image and astro-imagetools integrations? In that case, try disabling astro-imagetools or invert their order in astro.config.mjs. I finally solved this that way.
Hope this helps

**Comment by matthewp** [comment] 2023-01-12 18:23
@Princesseuh this would be an error message we could hopefully improve on. https://github.com/withastro/astro/issues/5202#issuecomment-1292602782

**Comment by rishi-raj-jain** [comment] 2023-01-15 13:36
@tony-sull

But why does import(join(somepath)) doesn't work? I've had no problem with optimising remote images but with local images, optimising a list of images in a loop that I can't import manually seems like a tough task.

**Comment by rishi-raj-jain** [comment] 2023-01-15 13:40
Can't we just make it like, URL path to load a local image? Something like <Image src={join(process.cwd())} or anything that doesn't start with https to be resolved via relative fn, and rest treated as remote images. What do you think? Happy to do a PR

**Comment by bytrangle** [comment] 2023-02-01 16:36
@tony-sull 
What would be the recommended way to use `<Image />` with images stored in the `/public` folder?

I've found that the only way to use `<Image />` to render those images without specifying both "width" and "height" is to import them using relative paths.

For example:
```
---
import coverImg1 from "../../public/cover-img-1.jpeg"
---
<Img src={coverImg1} alt="" />
```

If I have a collection of blog posts, and their frontmatters contain a field that points to a cover image for each pos, I need to do this:

```
---
const allPosts = await getCollection("blog-posts")
---
{allPosts.map(post => (
  <Img src={import(post.data.coverImage)} alt="" />
))}
```
The above works, but ti will result in a warning like:

> Instead of /public/cover-img-1.jpeg, use /cover-img-1.jpeg

I think we can improve the warning message in addition to docs update.

**Comment by wassfila** [comment] 2023-02-18 16:08
- I'm not using image tools
- I'm using the example exactly like described in the doc https://docs.astro.build/en/guides/integrations-guide/image/#getimage
- I'm not using node 18, tested with 16
- reproduction example (third page getImage) : https://stackblitz.com/github/MicroWebStacks/astro-examples/tree/main/19_images-integration

Getting the error
```cmd
 error   "width" and "height" cannot both be undefined
  File:
    /home/projects/zzmigpnzj.github/node_modules/.pnpm/@astrojs+image@0.15.0_astro@2.0.14/node_modules/@astrojs/image/dist/lib/get-image.js:12:11
  Code:
    11 |     throw new Error(
    > 12 |       `"aspectRatio" must be included if only "${transform.width ? "width" : "height"}" is provided`
         |           ^
      13 |     );
      14 |   }
      15 |   let aspectRatio;
```

**Comment by Princesseuh** [comment] 2023-04-09 18:30
Hello! We are entering maintenance mode for `@astrojs/image` will now only fix issues that are major. This issue is an amalgamation of multiple problems, sometimes user-related, sometimes documentation related. In general, the new `astro:assets` feature has much better setup in place to avoid this kind of user confusion and we hope it'll solve many of the issues presented here. Thank you!

**Closed by Princesseuh** 2023-04-09 18:30 UTC
Labels: p2-nice-to-have, @astrojs/image
