### ISSUE TITLE
`Missing alt property.` error should contain the image without `alt`

### ISSUE THREAD

**Issue by Akxe** [withastro/astro#8969] opened 2023-10-31 23:08 UTC
### Astro Info

```block
Astro                    v3.4.0
Node                     v18.16.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

CLI

### Describe the Bug

When missing alt on an `<Image>` tag, the error `Missing alt property` is not helpful. 

### What's the expected result?

I would like to know where the tag missing the `alt` is. What file, what line?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1a7ypz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-11-01 07:52
From your reproduction, it does show the file, just not the position. Showing the exact line is unfortunately quite complicated, because the error is thrown quite far from the actual line where the component is called.

An alternative, easy, solution specific to this error would be to show the image path in the error. That should help narrow it down a fair amount

**Comment by jacobthesheep** [comment] 2023-12-05 19:50
This is a duplicate of https://github.com/withastro/astro/issues/8248

**Closed** 2023-12-05 21:27 UTC
Labels: - P2: nice to have, feat: errors, feat: assets
