### ISSUE TITLE
Incorrect line numbers reported in errors for JSX syntax in .astro body

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [withastro/astro#6786] opened 2023-04-08 06:00 UTC
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

n/a

### What operating system are you using?

MacOS Ventura 13.2

### What browser are you using?

n/a

### Describe the Bug

Suppose you forget your Astro fundamentals and put provide JSX as a prop in a `.astro` file body:

```astro
12  <body>
13    <h1 aria-label={<span />}>Astro</h1>
14  </body>
```

_(those are line numbers 12-14)_

Expected: you should be told by Astro that you were wrong to do so, with an error pointing to the correct line.

Actual: Astro does report an error, but it's got a vague message and wrong line:

```plaintext
 error   Expected ">" but found "/"
  File:
    /home/projects/github-dqpwvb/src/pages/index.astro:34:28
```

I think this demonstrates two problems:

* The error message should be made more specific
* The line number reported is much larger than the line count in the file

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dqpwvb?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment] 2023-04-08 06:31
Thanks for providing such good and detailed issues!

**Comment by Princesseuh** [comment] 2023-04-08 08:43
Thank you for the detailed information, unfortunately our error line numbers are currently wrong in so many cases, we don't yet accept issues about precise causes until we make a first step at improving it in general.

So I'll be closing this as a duplicate of https://github.com/withastro/astro/issues/5465

**Closed** 2023-04-08 08:44 UTC

**Comment by JoshuaKGoldberg** [comment] 2023-04-08 12:38
🤔 thanks for the quick triage @Princesseuh. Do you have a maintenance opinion on the other half of the issue, that the error message should be made more specific?

**Comment by Princesseuh** [comment] 2023-04-08 12:57
For that specific case, I'm sure we could provide something more detailed. Though those kind of messages (expected x and found y, etc) are generally coming either directly from JavaScript or ESBuild so they're a bit hard to improve usually on our end usually.

**Comment by openmindculture** [comment] 2025-09-03 13:57
What's the best practice to make Astro show the root cause line number in stack trace?
