### ISSUE TITLE
Module 'xxx/pale-pulsar/src/components/HelloWorld.vue"' has no default export

### ISSUE THREAD

**Issue by phk422** [withastro/astro#10243] opened 2024-02-27 08:58 UTC
### Astro Info

```block
no
```

### Describe the Bug

Importing vue components into vscode prompts a ts type error
![image](https://github.com/withastro/astro/assets/59734322/8e5bd6cd-2a98-47f0-9456-f040722c6b7e)

### What's the expected result?

vscode does not have this error

### Link to Minimal Reproducible Example

https://github.com/phk422/astro-issue-demo

### Participation

- [x] I am willing to submit a pull request for this issue.
```[tasklist]
### Tasks
```

**Comment by phk422** [comment] 2024-02-27 09:27
https://github.com/phk422/astro-issue-demo

**Comment by Princesseuh** [comment] 2024-02-27 09:36
Duplicate of https://github.com/withastro/language-tools/issues/758 (the cause is slightly different, but it's the same underlying result and bug)

**Closed by Princesseuh** 2024-02-27 09:36 UTC
Labels: needs repro
