### ISSUE TITLE
Sitemap integration: trailing slash in the home URL.

### ISSUE THREAD

**Issue by dmitriy-savranskiy-igotanoffer** [withastro/astro#8517] opened 2023-09-12 06:35 UTC
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.16.0
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/vue
                         @astrojs/sitemap
                         astro-critters
```

### Describe the Bug

The home page URL in the generated sitemap has a trailing slash regardless of the `trailingSlash` setting.
I also tried to find a workaround for this using the `filter` and `customPages` settings, but it seems like the integration always adds the trailing slash to the home URL regardless of where it comes from. 

### What's the expected result?

The home page URL in the sitemap respects the `trailingSlash` setting.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lkgxbh?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by andremralves** [comment] 2023-09-13 23:20
Home page URLs with or without a trailing slash are treated as the same. But I think it may be a good idea to remove the trailing slash in that case. Idk if there is any downside but will submit a PR.

**Comment by andremralves** [comment] 2023-09-14 02:03
Apparently, it's not possible. Astro uses this package [sitemap](https://www.npmjs.com/package/sitemap) to generate the sitemap and they always add the trailing slash to root URLs because of the URL constructor. https://github.com/ekalinin/sitemap.js/issues/345

But that is the intended behavior and doesn't harm SEO. As I said before, root URLs with or without trailing slash are treated as the same URL :)

**Comment by malachaifrazier** [comment] 2023-09-16 13:46
not a bug, then?

**Comment by andremralves** [comment] 2023-09-16 18:21
For me it's not a bug.

**Comment by rishi-raj-jain** [comment] 2023-09-18 09:49
@bluwy

I do find what @andremralves has said is correct (tried stripping the urls before they are sent to sitemap function).

Do we want to close this out for now?

**Comment by rishi-raj-jain** [comment] 2023-11-10 04:34
@bluwy @matthewp

I do find what @andremralves has said is correct (tried stripping the urls before they are sent to sitemap function).

Do we want to close this out for now?

**Comment by bluwy** [comment] 2023-11-10 13:53
Let's close this for now 👍

**Closed by bluwy** 2023-11-10 13:53 UTC
Labels: - P3: minor bug
