### ISSUE TITLE
i18n: disable redirect from / to /fr/ (or /en/ or any language).

### ISSUE THREAD

**Issue by millette** [withastro/astro#9395] opened 2023-12-10 20:19 UTC
### Astro Info

```block
$ pnpm astro info

> robin.millette.info@0.5.4 astro /home/millette/travail/robin/robin.millette.info
> astro "info"

Astro                    v4.0.3
Node                     v18.19.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Any browser (server-side issue).

### Describe the Bug

I upgraded a multilingual site to v4 and wanted to give the i18n feature a try. My original site has a bilingual front page (/) because it's very simple. When I added the i18n feature after the upgrade, I noticed my front page was always redirected to /fr/ or /en/.

Can I keep the old behavior with my original bilingual front page at / with no language prefix and also enable the i18n feature?

### What's the expected result?

I want to land on / page and not be redirector to either /fr/ nor /en/.

### Link to Minimal Reproducible Example

- https://githubv5zdyj-2hj2--4321--d3416dfd.local-credentialless.webcontainer.io/
- https://stackblitz.com/edit/github-v5zdyj?file=README.md
- https://github.com/millette/github-v5zdyj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by millette** [comment] 2023-12-10 20:37
https://githubv5zdyj-2hj2--4321--d3416dfd.local-credentialless.webcontainer.io/

On github: https://github.com/millette/github-v5zdyj

**Comment by ematipico** [comment] 2023-12-10 23:06
I am going to close this, since it's not a bug and it works as intended.

I suggest opening a discussion or upvoting this discussion https://github.com/withastro/roadmap/discussions/789, another user requested the same feature

**Closed** 2023-12-10 23:07 UTC
Labels: needs triage
