### ISSUE TITLE
Custom MDX components get tangled

### ISSUE THREAD

**Issue by hasparus** [withastro/astro#5868] opened 2023-01-15 21:13 UTC
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

no, I'm doing SSG

### What package manager are you using?

pnpm and whatever CodeSandbox uses (npm?)

### What operating system are you using?

Mac, CodeSandbox

### Describe the Bug

I've noticed an interesting problem in MDX custom components.

I have a `Link` written in Solid, and `Image` written Astro that I provide as `a` and `img` to my MDX posts.

Funnily, when the `Image` uses a `div` as its root element, the resulting markup gets interweaved, and I end up with two anchor elements for one link in Markdown, one before the Image and one inside of it, not just one as a parent as I'd expect.

As you check on [the CodeSandbox reproduction](https://codesandbox.io/s/astro-mdx-components-repro-pxquxy), changing `div`s into `span`s "fixes" the issue...

So, to reiterate with some simplified examples: the following MDX

```mdx
[![a cat](https://placekitten.com/200/200)](https://example.com)
```

and components looking more or less like this:

```astro
---
import { getImage } from "@astrojs/image";
const attrs = await getImage(Astro.props)
---

<div this-is-image>
  <img {...attrs} />
  <div this-is-placeholder />
</div>
---
```

```tsx
export const Link = (props) => <a {...props}>custom link {props.children}</a>
```

give me this HTML

```html
<p>
  <a href="https://example.com">custom link</a>
</p>
<div this-is-image>
  <a href="https://example.com">
    <img src="https://placekitten.com/200/200" alt="a cat"/>
    <div this-is-placeholder />
  </a>
</div>
```

🤷‍♂️ 😄 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-mdx-components-repro-pxquxy

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-01-16 08:05
It seems like Astro is serving the HTML right:

```html
<!DOCTYPE html>
<p>
    <a data-hk="0-0" style="display:inline-block;padding:1rem;border:2px solid black" href="https://placekitten.com/200/200">
        custom Link: <!--#-->
        <script type="module" src="/@vite/client"></script>
        <script type="module" src="/@fs/sandbox/node_modules/astro/dist/runtime/client/hmr.js?v=e40706f2"></script>
<div awesome-image style="display: inline-block; position: relative; overflow: hidden;">
    <img alt="Placeholder Cat" width="200" height="200" src="/_image?w=200&#38;h=200&#38;ar=1&#38;href=https%3A%2F%2Fplacekitten.com%2F200%2F200" loading="lazy" decoding="async">
    <div style="position: absolute; inset: 0; background: #ddd; z-index: -1;"></div>
</div>
<!--/-->
</a>

x
Notice that you can see the gray background, which is supposed to be the placeholder of the image,
and we end up with TWO anchor elements, as if the Image closed his parent Link, became its sibling and then used the Link inside of itself.</p>
```

The issue is likely that you're nesting block-level elements inside inline-level elements that's causing the browser to "fix" it and results to the incorrect display, as you've noticed with the `div` and `span` behaviour. Closing as this isn't an issue in Astro.

**Closed by bluwy** 2023-01-16 08:05 UTC
Labels: MDX

**Comment by hasparus** [comment] 2023-01-16 10:01
Thanks!
