### ISSUE TITLE
 \ is escaped in the style sheet

### ISSUE THREAD

**Issue by woodcoal** [withastro/astro#4392] opened 2022-08-19 17:34 UTC
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None and Node

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

if style include \ when dev/build  is escaped.

eg.
```
.fa-id:before {
	content: "\e64b";
}
```
when dev or after build, change to

```
.fa-id:before {
	content: "\\e64b";
}
```

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-08-20 12:46
Looks like this is a duplicate of https://github.com/withastro/compiler/issues/502. It should be resolved when we release and use https://github.com/withastro/compiler/issues/503

**Closed by bluwy** 2022-08-20 12:46 UTC
