### ISSUE TITLE
Small scripts not inlined across pages

### ISSUE THREAD

**Issue by ZebraFlesh** [withastro/astro#6247] opened 2023-02-15 02:03 UTC
### What version of `astro` are you using?

2.0.11 (also present in 1.9.2)

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Given:
* two Astro components, each of which has a trivially small `<script>` tag
* two pages where:
  * first page includes both components
  * second page includes only one component

Then Astro will produce external scripts when running `astro build`. If the set of included scripts has less than 100% overlap between the files, external scripts are output; changing the overlap to 100% causes the scripts to be inlined.

**Expected behavior:** If all scripts included on a page are below the `vite.build.assetsInlineLimit` value, then they are inlined in that page.

To reproduce using the linked stackblitz:
1. `npm run build`
2. Observe that the `dist` folder contains an `_astro` folder with `hoisted.js` files.
3. Edit `src/pages/other.astro` to uncomment lines 2 and 16. The two pages now have 100% overlap of included scripts.
4. `npm run build`
5. Observe that the trivial scripts are now inlined into the html files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gcs2xa?file=src/pages/other.astro&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-02-23 18:02
Scripts are not assets, they are not built in isolation. What is happening here is that 2 pages have a common dependency which causes that to be code-split. This is how Rollup works. So we don't attempt to inline modules that depend on other modules. Inlining only occurs if the bundle is without dependencies. The size is only considered if that is true.

Closing as this is not a bug. Not sure what we could even do to fix this.

**Closed by matthewp** 2023-02-23 18:02 UTC
