### ISSUE TITLE
Astro DB - when using --remote flag I get "Invalid URL"

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#10511] opened 2024-03-20 21:10 UTC
### Astro Info

```block
Astro                    v4.5.8
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
                         auto-import
                         @astrojs/code-snippets
                         @astrojs/mdx
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

When I run "astro dev --remote", I get the following error:

22:06:14 [ERROR] Invalid URL
  Stack trace:
    at /Users/thomasledoux/Documents/website-thomas-astro/node_modules/@astrojs/db/dist/runtime/db-client.js:31:15
    [...] See full stack trace in the browser, or rerun with --verbose.

This seems to be coming from `createRemoteDatabaseClient()` where the `remoteDbURL` that's passed to it is not valid apparently. 

### What's the expected result?

Connecting to the remote Astro DB

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by santiagoavilez** [comment] 2024-03-21 12:27
Sure, here's a suggested comment:

Hey there,

I've managed to replicate the issue in my development environment, and I've identified a workaround that might provide a temporary solution until the root cause is addressed.

It appears that the problem lies in the runtime handling of environment variables, specifically when retrieving credentials using the getRemoteDatabaseUrl() function. Although environment variables set at build time seem to work fine, runtime variables are causing issues.

To circumvent this, I've made a temporary adjustment in the createRemoteDatabaseClient function to hardcode my credentials. This ensures that the function operates correctly in my local setup. However, this is not a sustainable solution for production environments.

The issue seems to stem from discrepancies in how environment variables are handled between build time and runtime. For instance, while the command npx astro db shell --query 'select "*" from Courses' --remote works as expected, npx astro db execute db/seed.ts --remote fails due to the same problem.

In terms of code, I've made modifications in two files:

In @astrojs/db/dist/core/utils.js, I've observed that the getRemoteDatabaseUrl() function is where the issue originates, particularly in fetching environment variables. I've included a console.log statement to track the ASTRO_STUDIO_APP_TOKEN variable.
In @astrojs/db/dist/runtime/db-client.js, I've made changes to ensure that the getRemoteDatabaseUrl() function fetches the correct environment variables. Additionally, I've modified the createRemoteDatabaseClient function to accept hardcoded credentials temporarily.

`import { loadEnv } from "vite";
function getAstroStudioEnv(envMode = "") {
  const env = loadEnv(envMode, process.cwd(), "ASTRO_STUDIO_");
  return env;
}
function getRemoteDatabaseUrl() {
  const env = getAstroStudioEnv();
  return env.ASTRO_STUDIO_REMOTE_DB_URL || "https://db.services.astro.build";
}

function getAppToken() {
  const env = getAstroStudioEnv();
  return env.ASTRO_STUDIO_APP_TOKEN;
}

function createRemoteDatabaseClient(appToken , remoteDbURL) {
  remoteDbURL = getRemoteDatabaseUrl();
  appToken = getAppToken();
  const url = new URL("/db/query", remoteDbURL);
 const db = drizzleProxy(...
//  rest of the drizzle proxy function
..);
  applyTransactionNotSupported(db);
  return db;
`
While this workaround helps me locally, it's crucial to address the underlying problem with runtime environment variables. I'm willing to contribute a pull request to implement a more robust solution if needed.

Looking forward to hearing your thoughts on this and finding a permanent fix.

Best regards,
Santiago Avilez

**Comment by santiagoavilez** [comment] 2024-03-21 13:07
Is there a way to replicate the hardcoded functionality I've implemented in my local development environment for production? I'm nearing completion on an MVP for a client project, and switching to another database provider like Turso would be quite inconvenient. I've found Astro DB integration incredibly seamless and would prefer to stick with it if possible.

**Comment by matthewp** [comment] 2024-03-21 14:36
Should be fixed by https://github.com/withastro/astro/pull/10520 in `@astrojs/db@0.9.3`! So sorry about this one, let me know if you still have any issues.

**Closed by matthewp** 2024-03-21 14:36 UTC
Labels: - P5: urgent, pkg: db
