### ISSUE TITLE
[Netlify and Shiki problem] Error - Cannot find module 'vscode-oniguruma'

### ISSUE THREAD

**Issue by renoob21** [withastro/astro#7142] opened 2023-05-19 16:49 UTC
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I deployed my site to Netlify, everything went great, but when I clicked to the content containing a Syntax Highlighter, it crashes and gives this error

![image](https://github.com/withastro/astro/assets/98941290/647c5314-7a7e-4f39-bf72-18143acc5bf5)

You can check the error happening [here](https://main--preeminent-alfajores-c150fe.netlify.app/tutorials/dasar-dasar-python/python-string-concatenate-dan-format)

I'm really sure that the error was caused by the Shiki \<Code/> component since it uses the "vscode-oniguruma" extension.

I tried to install it using npm but the bug still happening

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gbqrrl?file=src/env.d.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by renoob21** [comment] 2023-05-20 03:33
I created a new project and migrated all my codes here : https://github.com/renoob21/senengoding and it still happens

**Comment by matthewp** [comment] 2023-06-12 14:52
@renoob21 This reproduction doesn't currently build. Can you update it? Thank you.

**Comment by gamebox** [comment] 2023-07-05 13:43
I am having a similar issue with the same error but the module not being found is `better-sqlite3` which is brought in transitively from `@libsql/client`.  This is only used in my endpoints / functions.  Though I wonder if a usage of it directly in one of my page frontmatter scripts is causing it?

**Comment by natemoo-re** [comment] 2023-08-10 19:28
Usually the solution here is to ensure that packages with native and/or wasm dependencies are not bundled by setting `vite: { ssr: { external: ['pkg-name'] }}}` in your Vite config. Netlify additionally bundles the build output, so you might need to also configure Netlify to also externalize the relevant packages.

Since there hasn't been any activity on this issue in a while and we can't do much about dependencies that can't be bundled, I'm going to close this issue.

**Closed by natemoo-re** 2023-08-10 19:28 UTC
Labels: needs response, feat: ssr, pkg: netlify
