### ISSUE TITLE
unused values in build JS

### ISSUE THREAD

**Issue by allaboutstrategy** [withastro/astro#10465] opened 2024-03-17 01:11 UTC
### Astro Info

```block
> celestial-chasm@0.0.1 astro
> astro info

Astro                    v4.5.5
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
```

### Describe the Bug

Hello,

I get 8 warning for unsued values in the build _astro/xxxxxx.js
dist/_astro/web.DDAQtEf1.js:1:287 - warning ts(6133): 'oe' is declared but its value is never read.
dist/_astro/web.DDAQtEf1.js:1:734 - warning ts(6133): 't' is declared but its value is never read.

its is from the solidjs in the ingegrations

import { defineConfig } from 'astro/config';

 import solid from "@astrojs/solid-js";

// https://astro.build/config
export default defineConfig({
  integrations: [solid()],
});

how to fix this?

### What's the expected result?

no warnings^^

### Link to Minimal Reproducible Example

http://google.de

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-03-17 07:45
Duplicate of https://github.com/withastro/language-tools/issues/643

The output is intended, the checking isn't

**Closed** 2024-03-17 07:45 UTC
Labels: needs triage
