### ISSUE TITLE
Customer Error Handler 500.astro does not always work

### ISSUE THREAD

**Issue by don41382** [withastro/astro#7953] opened 2023-08-04 09:33 UTC
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Custom `500.astro` only works, if you not including astro components. Here is the example:

**500.astro**
```
---
Astro.response.status = 500
---
<h1>Sorry</h1>
```

**error.astro**
```
---
import Boom from "./boom.astro"
---
<div>
    <Boom/>
</div>
````

**boom.astro**
```
---
throw new Error("boom")
---
<h1>Content</h1>
```

When I request `/error` I'll get a `Internal Server Error` message with a 200. I was expecting the custom `500` with status code 500.

If I request `./boom` directly, I'll get the `500` custom error as expected.

### What's the expected result?

I would expect to get always get the custom 500.astro, no matter were the error is thrown.

Note: Please run the example with `astro build && astro preview`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wyix4j?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-04 15:01
This is happening because we begin streaming the response from `/error` (the initial `<div>` before attempting to render `<Boom />` where the error gets thrown. Since the headers and `200` status have already been sent to the browser, we can't modify the status code anymore.

That said, this is definitely annoying. We should have a good answer for this, but I don't know that any streaming framework has figured one out.

**Comment by don41382** [comment] 2023-08-07 10:14
@natemoo-re yes, that would be lovely.

But what you are saying is, that right here in `entry.mjs`:
```
  if (webResponse.body) {
    try {
      for await (const chunk of responseIterator(webResponse)) {
        res.write(chunk);
      }
    } catch (err) {
      console.error((err == null ? void 0 : err.stack) || (err == null ? void 0 : err.message) || String(err));
      res.write("Internal server error");
    }
  }
```
... the request has already been sent to the client, so you can only add items to the response, right?

**Comment by natemoo-re** [comment] 2023-08-07 19:12
Correct, the response status and headers have already been sent to the client at this point. The iterator is writing chunks to the browser so it can render the content as soon as possible. If we encounter an error, our only option to to write some representation of the error to the in-progress Response.

**Comment by natemoo-re** [comment] 2023-08-07 19:14
I'm going to close this since it's not a bug, but a limitation of our architectural decision to embrace streaming responses.

If you'd like to propose a new feature that would allow users to opt-out of this behavior or handle it another way, I invite you to [open a discussion on our roadmap](https://github.com/withastro/roadmap/discussions).

**Closed by natemoo-re** 2023-08-07 19:14 UTC
Labels: needs triage
