### ISSUE TITLE
`hydrate(...)` is not available on the server Error using Svelte and Astro 5

### ISSUE THREAD

**Issue by flayks** [withastro/astro#12608] opened 2024-12-03 18:01 UTC
### Astro Info

```block
Astro                    v5.0.1
Node                     v22.11.0
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @sanity/astro
                         @astrojs/svelte
                         astro-critters
```

### Describe the Bug

Upgrading to the stable Astro 5 version + all other Astro related plugins and adapters, I get this error when hosting a build on Cloudflare:

```
Uncaught (in promise) Svelte error: lifecycle_function_unavailable
`hydrate(...)` is not available on the server
    at d (https://303408c0.daily-delights.pages.dev/_astro/client.svelte.B-Sw0lPZ.js:1:68)
    at m (https://303408c0.daily-delights.pages.dev/_astro/client.svelte.B-Sw0lPZ.js:2:200)
    at b (https://303408c0.daily-delights.pages.dev/_astro/client.svelte.B-Sw0lPZ.js:2:910)
    at https://303408c0.daily-delights.pages.dev/_astro/client.svelte.B-Sw0lPZ.js:2:771
    at https://303408c0.daily-delights.pages.dev/:13:2911
    at i (https://303408c0.daily-delights.pages.dev/:13:1049)
```

It works fine when building locally and using the node adapter. For some context, I haven't changed any code from Astro 4 to 5, just updated dependencies.

This issue already happened on the betas of Astro 5. It seems to come from the Svelte client on Astro side?

- Working setup on latest Astro 4: https://35c1cd91.daily-delights.pages.dev
- Broken setup on latest Astro 5: https://87703d69.daily-delights.pages.dev

### What's the expected result?

It should work properly 🤷

### Link to Minimal Reproducible Example

I cannot reproduce it as I have no idea where the issue is coming from

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Mravuri96** [comment] 2024-12-04 06:09
Temporary fix: Added the following to `astro.config`
```js
vite: {
  resolve: {
    conditions: ['browser'],
  },
}
```

**Comment by bluwy** [comment] 2024-12-04 15:18
This is an effect of the breaking change in Vite: https://vite.dev/guide/migration.html#default-value-for-resolve-conditions

Some Vite plugins may be updating `resolve.conditions` but removes the default conditions, which causes issues in resolving certain Svelte entrypoints. I'd suggest going through each plugins to see what's causing it.

Or maybe this is the same as https://github.com/withastro/adapters/issues/461 if you're using cloudflare.

**Comment by uwemaurer** [comment] 2024-12-05 07:38
> Or maybe this is the same as [withastro/adapters#461](https://github.com/withastro/adapters/issues/461) if you're using cloudflare.

I have the same problem with using the node adapter, so I think it is not caused by the cloudflare adapter then

**Comment by flayks** [comment] 2024-12-08 17:47
> Temporary fix: Added the following to `astro.config`
> 
> ```js
> vite: {
>   resolve: {
>     conditions: ['browser'],
>   },
> }
> ```

This indeed works, thanks! But what explains that? Is it on Astro side or is it my code? I only use a few Svelte components that are quite simple.



> > Or maybe this is the same as [withastro/adapters#461](https://github.com/withastro/adapters/issues/461) if you're using cloudflare.
> 
> I have the same problem with using the node adapter, so I think it is not caused by the cloudflare adapter then

Ha, interesting! Looks like it's more on the Astro side then 🤔

**Closed** 2024-12-12 00:27 UTC
Labels: needs repro
