### ISSUE TITLE
Content Collection in hybrid mode doesn't work

### ISSUE THREAD

**Issue by teinett** [withastro/astro#8009] opened 2023-08-09 05:34 UTC
### What version of `astro` are you using?

2.10.3

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

any

### Describe the Bug

I would like to use Astro Content Collection for my blog.

I want: 
- page example.com/posts - list of all posts
- page example.com/posts/:postID - one post

In future I would like to try Keystatic from Thinkmill, so I would like to use **markdoc**.

I will install packages: 
- @astrojs/markdoc - for markdoc support
- @astrojs/react, @keystatic/core and @keystatic/astro - for future Keystatic (from https://keystatic.com/docs/installation-astro)

Keystatic needs **output** **server** or **hybrid** for Astro, so my file `astro.config.mjs` will be:

```
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import markdoc from "@astrojs/markdoc";

export default defineConfig({
    output: "hybrid",
    integrations: [react(), markdoc()],
});

```

I create my astro pages:`/src/pages/posts/index.astro` - **there is no errors**:
```
---
import { getCollection } from "astro:content";
async function fetchPosts() {
    const allPosts = await getCollection("posts", (post) => {
        return !post.data.isDraft 
    });
    return allPosts;
}

const allPosts = await fetchPosts();

---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Astro</title>
	</head>
	<body>
    <main>
        <h1>Posts</h1>
        <ul>
            {
                allPosts.map((post) => (
                    <li>
                        <a
        href={`/posts/${post.slug}`}>{post.data.title}</a
    >
                    </li>
                ))
            }
        </ul>
    </main>
	</body>
</html>

```

Next I create astro page for each post: `/src/pages/posts/[…slug].astro` - **here I get error about output mode**:

```
---
import Layout from "@/layouts/Layout.astro";

import { getEntry } from "astro:content";

const { slug } = Astro.params;

if (slug === undefined) {
    throw new Error("Slug is required");
}
// // 2. Query for the entry directly using the request slug
const entry = await getEntry("posts", slug);

// 3. Redirect if the entry does not exist
if (
    entry === undefined ||
    entry.data.isDraft === true
) {
    return Astro.redirect("/404");
}
// 4. (Optional) Render the entry to HTML in the template
const { Content } = await entry.render();
---

<Layout title="Post page">
    <main>
        <h1>Post one</h1>
    </main>
</Layout>

```

**Console error:**
```
 error   `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
  Hint:
    See https://docs.astro.build/en/core-concepts/routing/#dynamic-routes for more information on dynamic routes.

    Alternatively, set `output: "server"` in your Astro config file to switch to a non-static server build. This error can also occur if using `export const prerender = true;`.
    See https://docs.astro.build/en/guides/server-side-rendering/ for more information on non-static rendering.
  File:
    /Users/teine/Development/learn-astro-keystatic/src/pages/posts/[...slug].astro
  Stacktrace:
GetStaticPathsRequired: `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
    at validateDynamicRouteModule (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/core/routing/validation.js:20:11)
    at callGetStaticPaths (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/core/render/route-cache.js:17:3)
    at getParamsAndProps (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/core/render/params-and-props.js:11:29)
    at matchRoute (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/vite-plugin-astro-server/route.js:35:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/vite-plugin-astro-server/request.js:52:28)
    at async runWithErrorHandling (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///Users/teine/Development/learn-astro-keystatic/node_modules/astro/dist/vite-plugin-astro-server/request.js:48:3)
```

### What's the expected result?

I read error message and I don't understand my mistake. 

`getStaticPaths() function is required for dynamic routes. Make sure that you export a getStaticPaths function from your dynamic route.`

Yes, I don't have getStaticPaths() function.

`Alternatively, set output: "server" in your Astro config file to switch to a non-static server build. This error can also occur if using export const prerender = true;.`

My Astro site is not in `output: "server"` - yes. 
It's `output: "hybrid"`, which is almost the same: https://docs.astro.build/en/guides/server-side-rendering/#enabling-ssr-in-your-project:

"To enable SSR features for production deployments, update your output configuration to 'server' or 'hybrid' (introduced in v2.6.0). Both of these modes control which [pages](https://docs.astro.build/en/core-concepts/astro-pages/) or [server endpoints](https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes) should be server-rendered."

**So it should be no error.**

One post page doesn't have `export const prerender = true;`. **So it should be no error.**

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nmtmiz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by teinett** [comment] 2023-08-09 05:46
It works, if I change output mode from 'hybrid' to 'server' in `astro.config.mjs`:


```
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import markdoc from "@astrojs/markdoc";

export default defineConfig({
    output: "server",
    integrations: [react(), markdoc()],
});
```

**Comment by natemoo-re** [comment] 2023-08-09 13:50
The error is correct, but the wording might be a bit confusing. The `/src/pages/posts/[…slug].astro` page needs a `getStaticPaths()` function in order to be prerendered (since we wouldn't know which pages to generate for `[...slug]` otherwise). Prerendering is the default for `hybrid` mode.

If you want `[...slug]` to be handled the same as `server` mode, you need to add an `export const prerender = false` statement.

**Comment by natemoo-re** [comment] 2023-08-09 13:51
I'm going to close this as it's not a bug. If you need further help, please hop into our `#support` channel [on Discord](https://astro.build/chat) so we can assist you!

**Closed by natemoo-re** 2023-08-09 13:51 UTC
Labels: needs triage
