### ISSUE TITLE
bun:sqlite - ESM loader error. Received protocol 'bun:'

### ISSUE THREAD

**Issue by fabriziogiordano** [withastro/astro#8481] opened 2023-09-10 06:00 UTC
### Astro Info

```block
Astro                    v3.0.12
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I am using Bun JS to build Astro. I also use SQLite to store some content.
When I use `bun:sqlite` to read the db I get an error during both dev and build.

This is the error I received in dev:

```bash
# bun run dev                 
$ astro dev
  🚀  astro  v3.0.12 started in 202ms
  
  ┃ Local    http://localhost:4000/
  ┃ Network  use --host to expose
  
Error: The following dependencies are imported but could not be resolved:

  bun:sqlite (imported by /root/astro-bun-sqlite/src/libs/db.ts)

Are they installed?
    at file:///root/astro-bun-sqlite/node_modules/vite/dist/node/chunks/dep-df561101.js:45705:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///root/astro-bun-sqlite/node_modules/vite/dist/node/chunks/dep-df561101.js:45114:38
```

Ref: https://github.com/oven-sh/bun/issues/4761

### What's the expected result?

bun:sqlite is supported

### Link to Minimal Reproducible Example

https://github.com/fabriziogiordano/astro-bun-sqlite

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by xiBread** [comment] 2023-09-10 06:58
Duplicate of #8476

**Closed** 2023-09-10 07:57 UTC
Labels: needs triage

**Comment by fabriziogiordano** [comment] 2023-09-11 01:37
It appears the Vite use case is handled by Bun.

By adding `--bun`: The --bun flag tells Bun to run Vite's CLI using bun instead of node.

```
bun --bun run astro build
```

Here the info from the doc: https://bun.sh/guides/ecosystem/vite
