### ISSUE TITLE
Usage of Astro.glob leads to scripts of components in mdx files being bundled

### ISSUE THREAD

**Issue by peterhijma** [withastro/astro#5445] opened 2022-11-20 18:20 UTC
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

It feels like a bug. Or is this expected behavior?

Open the example, then open the console. You'll see that although I only called `Astro.glob`, there is still an error about an element being `null`, which is inside the `Foo.astro` component.

```
Cannot read properties of null (reading 'addEventListener')
```

So the scripts from the component which are imported in the `mdx` file are somehow included in the page, where the component itself is not included. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yln4lc?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2022-11-21 02:32
Related to https://github.com/withastro/astro/issues/3816

**Comment by peterhijma** [comment] 2022-11-21 14:20
For that issue is no workaround. Is there for this one a workaround maybe?

**Comment by matthewp** [comment] 2022-11-21 17:33
There isn't a workaround other than being careful about your scripts, not using them if you don't want them on the Astro.glob-using page.

This RFC is meant to fix the issue with a new API: https://github.com/withastro/rfcs/pull/373

Closing as a duplicate of #3816

**Closed by matthewp** 2022-11-21 17:33 UTC
