### ISSUE TITLE
AstroJS collections are not accessible inside `tailwind.config` file

### ISSUE THREAD

**Issue by willpinha** [withastro/astro#11831] opened 2024-08-24 12:42 UTC
### Astro Info

```block
Astro                    v4.14.5
Node                     v21.7.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I cannot use Astro collections inside the `tailwind.config` file, since the module "astro:content" is not defined

```
[postcss] Cannot find module 'astro:content'
```

### What's the expected result?

Use a collection inside the `tailwind.config` file, since I have a collection with colors definitions and want to build custom Tailwind colors dynamically based on them

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-1yjmkk?file=tailwind.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2024-08-24 12:59
Collections weren't designed to be imported in a tailwind configuration file.

Also, I don't think we have a documentation page where we show how you can do that. 

Closing as it's not a bug

**Closed by ematipico** 2024-08-24 12:59 UTC
Labels: needs triage

**Comment by willpinha** [comment] 2024-08-24 13:21
Thanks for the answer! I'll think of an alternative solution. I will also pay attention to the right place to ask my questions.
