### ISSUE TITLE
Astro with Tailwind imports CSS from 404.astro

### ISSUE THREAD

**Issue by LefanTan** [withastro/astro#8549] opened 2023-09-13 21:28 UTC
### Astro Info

```block
Astro                    v3.0.13
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

When tailwind is installed and a `404.astro` page is present, the build version of the project will always include the CSS files from the 404 page in all the pages. Depending on the file size of `404`'s CSS, this can have a downstream effect on load performance

When visiting `/`, I don't think stylesheets related to `404.css` should be imported.
![Screen Shot 2023-09-13 at 3 24 04 PM](https://github.com/withastro/astro/assets/12474777/5d3f78b2-d0d6-4480-a086-4d9468ea85ec)

I've noticed that this could also happened to nested 404 pages, though i'm unable to replicate it in the sandbox

### What's the expected result?

Stylesheet related to 404 shouldn't be imported when visiting normal pages.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/withered-snowflake-zmv8rm?file=/src/pages/nested/404.astro:9,1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by BryceRussell** [comment] 2023-09-14 01:01
This is expected behavior, CSS is bundled into a file named after the first page it is used on and the tailwind integration injects styles onto every page by default so `404` is the first page alphabetically.

If you want more control over the naming of the output files you can configure rollup inside the Astro config:

[Customising Output Filenames](https://docs.astro.build/en/guides/configuring-astro/#customising-output-filenames)

```js
import { defineConfig } from 'astro/config'

export default defineConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          entryFileNames: 'entry.[hash].mjs',
          chunkFileNames: 'chunks/chunk.[hash].mjs',
          assetFileNames: 'assets/asset.[hash][extname]',
        },
      },
    },
  },
})
```

If you need more control over the importing of your tailwind styles you can disable the default style sheet and import your own: 

[`applyBaseStyles`](https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles)

```js
import { defineConfig } from 'astro/config';

export default defineConfig({
  integrations: [
    tailwind({
      applyBaseStyles: false,
    }),
  ],
});
``` 

```css
/* /src/styles/base.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

```jsx
// /src/pages/index.astro
---
import '../styles/base.css'
---
```

**Comment by Princesseuh** [comment] 2023-09-14 06:39
Closing as a duplicate of https://github.com/withastro/astro/issues/7469

**Closed by Princesseuh** 2023-09-14 06:39 UTC
Labels: needs triage
