### ISSUE TITLE
Ampersand in query string gets transformed after build

### ISSUE THREAD

**Issue by aprestmo** [withastro/astro#5567] opened 2022-12-09 09:08 UTC
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macOS Ventura 13.0.1

### Describe the Bug

When running astro build ampersands (and possibly other special characters) gets transformed to something else in the dist code.

In the case of using `&` to build a query string in the Astro frontmatter the output gets transformed to `&#38;` in the output html file.

In my specific case I need to build a query string for analytics that would look like this: `https://www.example.com/?id=1&size=large&style=dark` but I get `https://www.example.com/?id=1&#38;size=large&#38;style=dark` and the analytics system does not understand how to get the correct parts of the string.

Run `astro build` and have a look at the `index.html` in `dist` to see what I mean. It would be great to have a option to opt-in or out of this transformation for these purposes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rwhad5?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2022-12-10 22:35
I can confirm the unexpected behaviour in that StackBlitz — thanks for the report.

While waiting for a fix, looks like you can workaround this using [the `set:html` directive](https://docs.astro.build/en/reference/directives-reference/#sethtml). This will render the `<iframe>` and `src` URL as expected:

```astro
<Fragment set:html={`<iframe src="${source}" seamless frameborder="0"></iframe>`} />
```

**Comment by aprestmo** [comment] 2022-12-11 09:54
I can also confirm that a workaround like that was what I ended up with for now in my projects.

**Comment by andersk** [comment] 2022-12-17 23:12
This is not a bug. Correct HTML output requires ampersands to be escaped, *including in attributes* such as `src`, and `&#38;` is one correct way to escape an ampersand (along with the more common `&amp;`).

Your browser interprets `&#38;` as `&` during HTML parsing, and requests the URL with `&` to populate the iframe. Your analytics system will only see `&`, not `&#38;`.

**Comment by delucis** [comment] 2022-12-18 10:37
Ah yes! @andersk is correct. I will close this — thanks for commenting 🙌

**Closed by delucis** 2022-12-18 10:37 UTC
Labels: p2-has-workaround
