### ISSUE TITLE
 viewTransitions : transition:animate="morph" traget page have same scroll position as source page

### ISSUE THREAD

**Issue by FrenchTechLead** [withastro/astro#7913] opened 2023-08-01 21:45 UTC
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm testing the new viewTransitions API and I created a morph effect from one page to another.
When the navigation is done the target page is on the same scroll position as the source page was.

### What's the expected result?

Give the possibility to keep the same scroll position or to reset the scroll to the default position.

You can find an example of the undesired behaviour on my website:
1- Open page : https://frenchtechlead.com/blog/_index/
2- Scroll to the bottom of the page.
3- Click on one of the last elements of the list.

### Link to Minimal Reproducible Example

https://frenchtechlead.com/blog/_index/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-01 22:09
Closing as a duplicate of #7882.

**Closed by natemoo-re** 2023-08-01 22:09 UTC
Labels: needs triage, feat: view transitions
