### ISSUE TITLE
`#\#` being improperly escaped in CSS

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#4339] opened 2022-08-15 22:15 UTC
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows / Stackblitz

### Describe the Bug

I'm trying to use [`@csstools/postcss-cascade-layers`](https://www.npmjs.com/package/@csstools/postcss-cascade-layers) which works by generating selectors that look like this: `:not(#\#)`. Astro incorrectly converts these to `:not(#\\#)` which is not the same thing (the selector no longer matches).

The same thing happens in both `dev` server as well as prod `build`.

Compare with vite which can handle it correctly: https://stackblitz.com/edit/vitejs-vite-7cdd3b?file=style.css,vite.config.js,index.html

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ja8xka?file=src%2Fpages%2F_style.css,src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-08-16 07:55
I believe this is a duplicate of https://github.com/withastro/compiler/issues/502

**Closed by bluwy** 2022-08-16 07:55 UTC
