### ISSUE TITLE
inconsistent CSS behavior in dynamic routes

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#5251] opened 2022-10-29 18:32 UTC
```yaml
Astro Version:    1.6.1
SSR Adapter:      No
Package Manager:  NPM
Operating System: Windows
Reproduction:     https://github.com/enteleform-codesandbox/0022--Astro--DynamicRoutes-CSS
```

&nbsp;  
When generating routes dynamically, it seems that there are cases where styles from multiple routes are applied at the same time.

After narrowing it down to a minimal repro, the cause seems to be pages having the same HTML output, but different CSS.

This was also the case in the actual project where I initially ran into the issue: a PDF generator that reuses HTML for multiple routes, with changes to the CSS for different print sizes.

It seems like this could potentially be related to #3816. However, this example is using `import.meta.glob`, while the other issue is using `Astro.glob`.
&nbsp;  

-----

## Different HTML
Styles are applied as expected:

![HTML-Different](https://user-images.githubusercontent.com/10906415/198847113-60abdac1-bb55-4f61-957f-db8656f1f4da.png)

![CSS-Different](https://user-images.githubusercontent.com/10906415/198847110-da2c3fbb-9056-4bd4-bc8a-d8a80cf367cf.png)
&nbsp;  

-----

## Same HTML
Styles from both routes are applied:
![HTML-Same](https://user-images.githubusercontent.com/10906415/198847109-74b572e5-b102-419e-86bd-2c8a36719d9a.png)

![CSS-Same](https://user-images.githubusercontent.com/10906415/198847112-fa2491e2-2fa5-45cf-b7d8-e0b21aeef755.png)
&nbsp;

**Comment by bholmesdev** [comment] 2022-11-01 20:58
Hey @Enteleform! Yes, this is a _very_ well known issue that effects both `import.meta.glob` and `Astro.glob` (since `Astro.glob` is a thin wrapper around Vite's API). I'm drafting a pair of RFCs to address this problem at a fundamental level, so be on the lookout this coming week. I'll keep this issue open as well.

**Comment by matthewp** [comment] 2022-11-04 13:24
This appears to be a duplicate of https://github.com/withastro/astro/issues/3816, so closing this one.

**Closed by matthewp** 2022-11-04 13:24 UTC
Labels: p4-important
