### ISSUE TITLE
Astro Partytown not resolved correctly with base path config

### ISSUE THREAD

**Issue by harrytran998** [withastro/astro#5423] opened 2022-11-17 03:30 UTC
### What version of `astro` are you using?

lastest

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

yarn 3

### What operating system are you using?

Mac

### Describe the Bug

```js
export default defineConfig({
  output: 'server',
  base: '/ok',
  server: {
    port: 3000,
    host: '0.0.0.0',
  },
  adapter: node({
    mode: 'standalone',
  }),
  integrations: [
     ...,
    AstroPartytown({ 
      config: { debug: true, forward: ['dataLayer.push'] }
    }),
],
})
```

`[serve]    404        /~partytown/debug/partytown-sw.js`

### Link to Minimal Reproducible Example

This link stackblitz https://stackblitz.com/edit/js-rh7ooy https://github.com/harrytran998/reproduction-astro-base-path

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by brenelz** [comment] 2022-11-17 03:50
I believe this is a duplicate of https://github.com/withastro/astro/issues/5424?

**Comment by bholmesdev** [comment] 2022-11-17 03:53
Yep, closing as a duplicate!

**Closed by bholmesdev** 2022-11-17 03:53 UTC
