### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by BeetrootShoulders** [withastro/astro#3145] opened 2022-04-19 10:54 UTC
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

WIndows 11

### Describe the Bug

Attempting to add Tailwind to a fresh Astro project with `npx astro add tailwind` results in an error:

```
 error   Astro could not update your astro.config.js file safely.
  Reason: t.identifier is not a function

  You will need to add these integration(s) manually.
  Documentation: https://docs.astro.build/en/guides/integrations-guide/
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/gqaiqnkmm

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2022-04-19 12:20
Sounds like a duplicate of #3071

**Comment by bholmesdev** [comment] 2022-04-19 14:54
Ack, looks like that example link is private! Mind sharing a public link @BeetrootShoulders ?

**Comment by matthewp** [comment] 2022-04-20 13:53
Closing as a duplicate, can reopen if you can provide an example and better description.

**Closed as completed by matthewp** 2022-04-20 13:53 UTC
