### ISSUE TITLE
file.arrayBuffer is not a function

### ISSUE THREAD

**Issue by Altair-Bueno** [withastro/astro#5532] opened 2022-12-05 13:55 UTC
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Function `arrayBuffer` on files does not exist

```ts
export async function post({ redirect, request }: APIContext) {
  const formData = await request.formData();
  const file = formData.get("file") as File;
  console.log(file);
  const result = Array.from(new Int8Array(await file.arrayBuffer()).values());
  console.warn(result);
  return redirect("/");
}
```

This handler crashes with the following message

```text
 error   file.arrayBuffer is not a function
  File:
    /Users/compux72/Developer/texample/src/pages/handler.ts:6:54
  Code:
      5 |   const file = formData.get("file") as File;
    > 6 |   const result = Array.from(new Int8Array(await file.arrayBuffer()).values());
        |                                                      ^
      8 |   console.log(result);
    
  Stacktrace:
TypeError: file.arrayBuffer is not a function
    at Module.post (/Users/compux72/Developer/texample/src/pages/handler.ts:6:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async call (file:///Users/compux72/Developer/texample/node_modules/astro/dist/core/endpoint/index.js:70:20)
    at async call (file:///Users/compux72/Developer/texample/node_modules/astro/dist/core/endpoint/dev/index.js:15:10)
    at async handleRoute (file:///Users/compux72/Developer/texample/node_modules/astro/dist/vite-plugin-astro-server/route.js:113:20)
    at async run (file:///Users/compux72/Developer/texample/node_modules/astro/dist/vite-plugin-astro-server/request.js:45:14)
    at async runWithErrorHandling (file:///Users/compux72/Developer/texample/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///Users/compux72/Developer/texample/node_modules/astro/dist/vite-plugin-astro-server/request.js:39:3)
```

# Additional info

- Probably relates to https://github.com/withastro/astro/issues/4737

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-aqsqxb?file=src/pages/handler.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment] 2023-02-24 23:48
I do know which node version is. could you tell me

**Comment by Altair-Bueno** [comment] 2023-02-25 10:47
As noted by the MRE I provided, Astro v1.6.12 and Node v16.14.2

**Comment by Altair-Bueno** [comment] 2023-02-25 11:02
For the record, the MRE I provided still shows that forms are broken no matter to the Nodejs version. This has been an ongoing issue since Astro v1.6.12

### Node 19.3.0

![image](https://user-images.githubusercontent.com/67512202/221353208-b48ece9c-50aa-4731-ad31-b40f2997ddc6.png)

### Node 18.14.2

![image](https://user-images.githubusercontent.com/67512202/221353226-6c7970c7-985d-48ab-b9d5-1e973244e52c.png)

### Node 17.9.1

![image](https://user-images.githubusercontent.com/67512202/221353234-84b952e6-58b6-4fb4-af97-b99cce73b0c3.png)

**Comment by matthewp** [comment] 2023-04-12 12:37
Closed https://github.com/withastro/astro/issues/6297 as it's a duplicate of this. It includes a test that shows the problem.

**Comment by andremralves** [comment] 2023-04-18 16:08
I think you should add `enctype="multipart/form-data"` to your form. Without this attribute, the request will send a `string` and not a `File`.

```html
<form action="/handler" method="post" enctype="multipart/form-data">
	<input type="file" name="file" />
	<input type="submit" />
</form>
```

![image](https://user-images.githubusercontent.com/71379045/232837330-f8905e57-96d5-4576-8a37-6c88411d99d9.png)

**Comment by Arttii** [comment] 2023-05-09 13:02
@andremralves, do you by chance have a reproducible example? On Astro 2.4.3 I am getting multipart/form-data not supported with node 18.6.0

**Comment by lilnasy** [comment] 2023-06-17 20:49
@andremralves is absolutely correct. The size of the request payload is barely longer than the name of the file uploaded tothe reproduction. Without the enctype attribute, formdata.get('file') returns a `string`, and with it, a `File`. MDN: [Sending files using a FormData object](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#sending_files_using_a_formdata_object).

@Arttii The change suggested by andremralves is sufficient to get the example to work on Node 16.20 and 18.16. Could you check again?

**Comment by lilnasy** [comment] 2023-07-18 20:01
Closing as this issue was not related to astro

**Closed by lilnasy** 2023-07-18 20:01 UTC
Labels: - P2: nice to have
