### ISSUE TITLE
Duplicate stylesheet injection in production build

### ISSUE THREAD

**Issue by kiley-mitti** [withastro/astro#5834] opened 2023-01-11 16:05 UTC
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac, Linux

### Describe the Bug

When using a layout which extends another layout, CSS stylesheets get injected twice in the production build of the site. This occurs on any page using the extended layout.

The first injection occurs in the `<head>` of the page.

The second injection occurs at the beginning of the `<body>` of the page.

Thank you so much for your attention to this issue! If you need any further information let me know.

### Link to Minimal Reproducible Example

[https://stackblitz.com/edit/github-2ugymh-oqddw9](https://stackblitz.com/edit/github-2ugymh-oqddw9)

**UPDATE (1/19/23):** We've found that this also extends to `injectScript` as well, so built a second example to account for that too. Hopefully this is useful to you!
 
[https://stackblitz.com/edit/github-2ugymh-e6stgx](https://stackblitz.com/edit/github-2ugymh-e6stgx)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nicholasray** [comment] 2023-01-12 03:14
I think this issue and https://github.com/withastro/astro/issues/5715 might be related

**Comment by z336** [comment] 2023-01-24 17:20
Adding a +1 to this bug, I'm seeing link and script tags injected twice on pages using one of the layouts. Thanks! 

### What version of astro are you using?
1.9.0

### Are you using an SSR adapter? If so, which one?
No

### What package manager are you using?
npm

### What operating system are you using?
Mac

### Describe the Bug
Stylesheet and script tags are being injected into the body with one layout but not both. The layout it's happening to is PageLayout.astro in my repo. 

### Link to Minimal Reproducible Example
https://astro-docs-prototype.netlify.app/
https://github.com/z336/astro-docs-prototype

**Comment by matthewp** [comment] 2023-01-24 18:14
Thanks for the repro! I'll be working on this soon.

**Comment by marcfilleul** [comment] 2023-01-28 09:43
I had this issue with nested layouts so I reverted back to a unique layout for now.

Now I have the same issue in a component with a <slot /> so it looks like the imported js and css are duplicated as soon as we use a <slot /> (in a layout or in a component).

**Comment by matthewp** [comment] 2023-01-28 12:54
I have a fix for this, just working out some details to avoid breaking some corner case layouts. Should have this in a patch next week.

**Closed** 2023-01-30 16:55 UTC
Labels: p4-important

**Comment by z336** [comment] 2023-01-31 20:08
No more duplicate script/link tags for me, but on one of my layouts (the opposite this time) it's injecting them into the body. Can see that behavior on this page: https://astro-docs-prototype.netlify.app/docs/en/tutorial/a-tutorial/

I updated to 2.0.4 and this time it's my ArticleLayout.astro pages (so, flipped from my original comment above).

**Comment by nicholasray** [comment] 2023-01-31 20:22
fwiw, I also experienced the flash of unstyled content now with 2.0.4. I reverted back to 2.0.2 as a result

**Comment by z336** [comment] 2023-01-31 22:50
I'm only see the tags injected into the body on pages that have MDX components, so it looks like it may have more to do with the MDX integration than layouts at this point. I'll check for any other filed issues and create a new one if need be.

**Comment by matthewp** [comment] 2023-02-01 01:36
Thanks, ping me if you file a new issue.

**Comment by z336** [comment] 2023-02-01 02:14
@matthewp Hi, thank you for the attention on this. I added my details here: https://github.com/withastro/astro/issues/6057#issuecomment-1411192135

**Comment by jamaluddinrumi** [comment] 2023-07-07 00:06
![Screen Shot 2023-07-07 at 7 00 10 AM](https://github.com/withastro/astro/assets/446780/7460067c-ae14-4ff0-936b-a65ea6858f17)

i have something similar happen to me

i don't know how to reproduce this because it's quite large codebase for me 

→ [live website](https://www.indomascot.com/en/terms-and-conditions/)

**Comment by jamaluddinrumi** [comment] 2023-07-07 00:30
> fwiw, I also experienced the flash of unstyled content with 2.0.4. I reverted back to 2.0.2 as a result

me too

https://github.com/withastro/astro/assets/446780/e8e707d6-4628-45e7-9520-58152d253a39

**Comment by jamaluddinrumi** [comment] 2023-07-07 11:50
i remove [@astrojs/prefetch ](https://github.com/withastro/astro/tree/main/packages/integrations/prefetch/) and it's resolved
