### ISSUE TITLE
Hoisting of global styles

### ISSUE THREAD

**Issue by yakir-reznik** [withastro/astro#4410] opened 2022-08-21 14:37 UTC
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

No SSR

### What package manager are you using?

npm

### What operating system are you using?

Mac OS

### Describe the Bug

We need a way to include global styles in such a way that they are generated at the top of the <head> tag.
For years CSS was authored in a way that styles declared later in the document are meant to overwrite previous styles with the same specificity.

Assuming a project is supposed to be built using this paradigm: Layout > Page > Components
The logical place to include global styles is in the layout files.

So lets assume we have a global.sass file that contains this content:

button {
	color: red
}

If we import this file into a layout file (by writing import "../sass/global.sass") the generated css would not be scoped.
Up until now this is expected behavior as far as I'm concered.

Now if we create a page that uses that layout and add scoped style tag in that page, such as:

<style lang="sass">
	button { /* this is scoped */
		color: green
	}
</style>

The generated css would be scoped **but not of higher specificity than the selector in global.sass**, for example:
button:where(.astro-AFLCCVED) {
	color: green;
}

Since astro outputs the Page's style tag **before** the Layout's imported style -> the rendered button would have a text color of red.

In other frameworks (Vue for instance) scoped styles are not handled by a ":where" statement, So scoped selectors have higher specificity and they automatically overwrite the same unscoped selectors.

This could be fixed by hoisting global styles to the top of the <head> tag.
Or by allowing for a way to transform scoped styles to something like:
button.astro-AFLCCVED {...}
instead of
button:where(.astro-AFLCCVED) {...}

Hope i made myself clear...

### Link to Minimal Reproducible Example

git clone https://YakirReznik@bitbucket.org/YakirReznik/astro-global-styles-issue.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment] 2022-08-21 17:38
Thanks @yakir-reznik ! Moving to https://github.com/withastro/rfcs/discussions/265 since this is a new feature discussion and not a bug or unexpected behavior.

**Closed by FredKSchott** 2022-08-21 17:38 UTC

**Comment by pikeas** [comment] 2022-09-13 21:18
> not a bug or unexpected behavior.

This is very unexpected! The "C" in CSS is for "cascading" - component styles should override global styles. Specifically, any Astro transforms (eg, adding a class or `:where()`) should maintain the property that equal specificity ties are won by the latest definition.

Eg:

```
# global.css
button {
    color: red;
}
```

```
# components/Button.astro
<button>
</button>

<style>
button {
    color: green;
</style>
```

```
# Layout.astro
---
import "./global.css"
import Button from "./components/Button.astro"

<Button></Button>
```

The green declaration should win, because the Button component is imported after the global style. Any other behavior is against the CSS spec.

**Comment by samclaus** [comment] 2023-08-13 17:13
I agree with @pikeas: it is extremely annoying that component styles do not override global CSS styles. If I have an `h3` selector in my global `app.css` file, it should most definitely be lower precedence than `h3` rules in my `pages/blog.astro` file! I am trying to _override_ the generic `h3` styles and give them a custom look on _that_ page in particular.
