### ISSUE TITLE
🐛 BUG: Cannot find module 'postcss-load-config` using Portfolio-Svelte template

### ISSUE THREAD

**Issue by SkepticMystic** [withastro/astro#2778] opened 2022-03-12 18:43 UTC
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I followed the start guide on the docs as follows:

1. `npm i astro`
2. `npm init astro`
3. Choose Portfolio-Svelte template from the cli list
4. `npm i`
5. `npm run dev`
6. Get this error:

```
07:56:15 PM [serve] 404    /service-worker.js
19:56:15 [vite] Error when evaluating SSR module .\src\pages\404.astro:
Error: failed to load module for ssr: ./node_modules/astro/dist/runtime/server/index.js
    at instantiateModule (.\node_modules\vite\dist\node\chunks\dep-9c153816.js:56113:15)
07:56:15 PM [serve] 500    /service-worker.js
07:56:15 PM [error] Error: failed to load module for ssr: ./node_modules/astro/dist/runtime/server/index.js
    at instantiateModule (.\node_modules\vite\dist\node\chunks\dep-9c153816.js:56113:15)
[svelte-preprocess] PostCSS configuration was not passed or is invalid. If you expect to load it from a file make sure to install "postcss-load-config" and try again.
Error: No PostCSS Config found in: .
[svelte-preprocess] PostCSS configuration was not passed or is invalid. If you expect to load it from a file make sure to install "postcss-load-config" and try again
```

7. `npm i postcss-load-config`
8. `npm run dev`, same error, as well as this:

```
08:08:57 PM [serve] 404    /service-worker.js
08:08:57 PM [error] Error: Expected an exported Astro component but received typeof undefined
08:08:57 PM [serve] 500    /service-worker.js
```

**Note**: The Stackblitz example used in the docs reproduces this error, as shown in the console:

![](https://imgur.com/2bBrAFW.png)

However, the site still previews correctly.
The issue is that, when running the same example locally, the error occurs, but the site doesn't preview on localhost:

![](https://imgur.com/Iv3xLNQ.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/portfolio-svelte

**Comment by SkepticMystic** [comment] 2022-03-12 18:53
From the help of one of the maintainers of the Discord, downgrading to `astro@0.24-next.0` doesn't make the error go away, but the site now previews correctly!

**Comment by FredKSchott** [comment] 2022-03-14 03:54
Duplicate of https://github.com/withastro/astro/issues/2273

FYI the short term fix to silence these warnings is:
1. `npm install postcss-load-config`
2. `echo "module.exports = {}" > postcss.config.js`

Hoping to get this fixed ASAP! You can follow #2273 for more updates

**Closed by FredKSchott** 2022-03-14 03:54 UTC

**Comment by RafidMuhymin** [comment] 2022-04-27 10:07
@SkepticMystic there's another problem with this code. Astro is again falling to load modules if the path contains a space. If you remove the space (from `Astro Test` to `Astro-Test`) the problem will get partially solved.

**Comment by FredKSchott** [comment] 2022-04-28 21:00
@RafidMuhymin Can you give a more detailed example, or file a new issue for this? I could have sworn that we already fixed this issue a few months ago!
