### ISSUE TITLE
Build fails after adding rss.xml.js

### ISSUE THREAD

**Issue by Snaylaker** [withastro/astro#7627] opened 2023-07-11 22:13 UTC
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Hi, 
While following the official tutorial  Unit 5 ⁠-⁠ Astro API / Add an RSS feed.
 I added the dependency `pnpm install @astrojs/rss`
then created the file  rss.xml.js with the following content : 
```
`import rss, { pagesGlobToRssItems } from '@astrojs/rss';

export async function get() {
  return rss({
    title: 'Astro Learner | Blog',
    description: 'My journey learning Astro',
    site: 'https://my-blog-site.netlify.app',
    items: await pagesGlobToRssItems(import.meta.glob('./**/*.md')),
    customData: `<language>en-us</language>`,
  });
}`
```
When i ran `pnpm run build` ,i got the following : 
```
 error   z.number(...).positive(...).int(...).finite is not a function
  File:
    /home/mehdi/dev/blog-tutorial-demo/node_modules/.pnpm/@astrojs+rss@2.4.3/node_modules/@astrojs/rss/dist/schema.js:14:41
  Code:
    13 |     url: z.string(),
    > 14 |     length: z.number().positive().int().finite(),
         |                                         ^
      15 |     type: z.string()
      16 |   }).optional()
      17 | });

```

### What's the expected result?

That the application build without errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-usa6tw

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Snaylaker** [comment] 2023-07-11 22:20
I checked the dependency in the node module, weirdly enough vs code doesn't recognize the function` finite()` in number.

![Screenshot from 2023-07-12 00-15-38](https://github.com/withastro/astro/assets/43219077/39c3536d-8241-4b58-bc2e-051d79de6ad4)

But when i cloned  Astro , went to source file  and checked in the RSS package in can properly see the function 
![Screenshot from 2023-07-12 00-17-45](https://github.com/withastro/astro/assets/43219077/54ce0a5d-4698-4f66-a3ef-94f04bfbf40f)

I would be glad to take any clues or guess to go further with the investigation !

**Comment by bluwy** [comment] 2023-07-12 09:20
You need to bump Astro to v2, it's currently v1 in your stackblitz. v2 updates the zod dependency which supports `.finite()`. Another way is to run `pnpm update zod` in your project to force bump the dep.

We should probably set a peer dep of `astro` in `@astrojs/rss` to fix this so leaving it open for now. Or maybe have `@astrojs/rss` depend on `zod` directly instead of through `astro/zod`.

**Comment by natemoo-re** [comment] 2023-08-15 21:49
I'm actually going to close this since the issue is fixed by upgrading `astro` and `@astrojs/rss` to latest! Peer dependencies on `astro` are something we'll have to chat about as a team.

**Closed by natemoo-re** 2023-08-15 21:49 UTC
Labels: - P2: nice to have, pkg: rss
