### ISSUE TITLE
404 page doesn't render in production mode

### ISSUE THREAD

**Issue by xriter** [withastro/astro#8054] opened 2023-08-13 14:02 UTC
### What version of `astro` are you using?

2.10.7

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

In SSR mode, when going to a page that doesn't exist, the 404 page should be rendered (the default or custom one). It does this correctly in dev mode, but **in production mode it only renders a blank page**.

Using @astrojs/node `5.3.3` with node `v18.16.1`

Also see the repro.
Run `npm run build && npm run preview` and go to `/doesntexist`.

### What's the expected result?

The 404 page should be rendered correctly in SSR production mode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-trfvka?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-14 13:44
Guessing that this will be closed by https://github.com/withastro/astro/pull/8070 which fixes a few edge cases introduced in https://github.com/withastro/astro/pull/7754

**Comment by lilnasy** [comment] 2023-08-15 20:11
Is there a difference when you run `node dist/server/entry.mjs` instead of `npm run preview`?

**Comment by lilnasy** [comment] 2023-08-15 20:17
> Although, I run a website in production in a Docker container, (that is using node dist/server/entry.mjs), and there it does not work...

If the 404 page was prerender, it may have been an issue introduced recently.

**Comment by lilnasy** [comment] 2023-08-15 20:19
It should, unless the output config is "hybrid".

**Comment by lilnasy** [comment] 2023-08-15 20:44
Couldn't reproduce it with docker either.

Temporary link to running project with [`docker run --rm -it -p 8001:8001 7b80`](https://8001-lilnasy-astro-qrg8ohn9zpl.ws-us103.gitpod.io/)

**Comment by lilnasy** [comment] 2023-08-15 20:52
Yes, I could reproduce the issue when running `npm run preview`.

**Closed** 2023-08-18 20:51 UTC
Labels: - P2: has workaround, pkg: node, feat: 404
