### ISSUE TITLE
Elements don't render as expected.

### ISSUE THREAD

**Issue by noClaps** [withastro/astro#10682] opened 2024-04-04 19:32 UTC
### Astro Info

```block
Astro                    v4.5.15
Node                     v21.7.2
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

I have a component that looks like this:

```astro
<a href={`https://discuit.net/${name}`}>
    <li>
        <h3>{name}</h3>
        {about && <p set:html={marked.parse(about)} />}
        <p>{noMembers} members</p>
    </li>
</a>
```

When `about` is text that does not contain any Markdown syntax, the element renders correctly as:

```html
<a href="https://discuit.net/100YearsAgo" data-astro-cid-x6ewki5y="">
    <li data-astro-cid-x6ewki5y="">
        <h3 data-astro-cid-x6ewki5y="">100YearsAgo</h3>
        <p data-astro-cid-x6ewki5y=""></p>
        <p>What was happening 100 years ago today ( or another day :) )</p>
        <p></p>
        <p data-astro-cid-x6ewki5y="">114 members</p>
    </li>
</a>
```

However, when `about` contains text with Markdown syntax, the element renders as:

```html
<a href="https://discuit.net/Adenium" data-astro-cid-x6ewki5y=""> </a>
<li data-astro-cid-x6ewki5y="">
    <a href="https://discuit.net/Adenium" data-astro-cid-x6ewki5y="">
        <h3 data-astro-cid-x6ewki5y="">Adenium</h3>
        <p data-astro-cid-x6ewki5y=""></p>
        <p>A community for those who love and grow desert roses. </p>
    </a>
    <p>
        <a href="https://discuit.net/Adenium" data-astro-cid-x6ewki5y="">A good guide for starting seeds is </a>
        <a href="https://www.adenium.com.tw/adeniumseeds/Seed%20Sowing.htm">here</a>
    </p>
    <p></p>
    <p data-astro-cid-x6ewki5y="">39 members</p>
</li>
```

The `<a>` tag no longer wraps the `<li>` tag, even though according to the component structure, it should. All of the `about`s are getting parsed by `marked`, so I'm not sure why only some of them are structured differently.

### What's the expected result?

The component should be rendered the same way in both cases, as:

```html
<a href="https://discuit.net/Adenium">
    <li>
        <h3>Adenium</h3>
        <p>
            <p>A community for those who love and grow desert roses. </p>
            <p>A good guide for starting seeds is <a href="https://www.adenium.com.tw/adeniumseeds/Seed%20Sowing.htm">here</a></p>
            <p></p>
        </p>
        <p>39 members</p>
    </li>
</a>
```

### Link to Minimal Reproducible Example

https://github.com/noClaps/discuit-community-search

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by noClaps** [comment] 2024-04-04 19:33
I've linked my repository because it's fairly minimal, and StackBlitz wasn't allowing me to add new dependencies for some reason.

**Comment by matthewp** [comment] 2024-04-04 20:23
Hi @noClaps, we will indeed need a more minimal reproduction. You should be able to debug this further and find what what `about` syntax is causing this. But really we need to know what the output of `marked.parse(about)` is to help. That's the important part. So please create a reproduction that contains only the code snippet you provided in the description, and the HTML string required to see it not work. Then we can help from there.  Use this template: https://astro.new/latest **Empty Project**.

**Comment by noClaps** [comment] 2024-04-04 20:44
I got StackBlitz working, here's a minimal reproduction with the two examples I gave above: https://stackblitz.com/edit/github-3wwnsh.

**Comment by rishi-raj-jain** [comment] 2024-04-05 08:00
Even a minimal reproduction would be the following:

- Community.astro

```astro
---
import { marked } from "marked";

interface Props {
  about: string | null;
}

const { about } = Astro.props;

const output = marked.parse(about);
---

<li>
  <a href={`https://discuit.net/`}>
    <div set:html={output} />
  </a>
</li>
```

- index.astro

---
import Community from "../components/Community.astro";
---

```astro
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width" />
    <meta name="generator" content={Astro.generator} />
  </head>
  <body>
    <ul>
      <Community
        about={`[here](https://www.adenium.com.tw/adeniumseeds/Seed%20Sowing.htm)`}
      />
    </ul>
  </body>
</html>
```

**Comment by rishi-raj-jain** [comment] 2024-04-05 08:01
This is basically a case where
the rendered markdown consists of an `<a>` element 
AND
the parent element (of any higher order) enclosing the rendered markdown is an `<a>` element itself.

**Comment by lilnasy** [comment] 2024-04-05 14:54
The reproduction project does not include a `package.json`. Does it need to be updated?

**Comment by matthewp** [comment] 2024-04-08 20:20
@rishi-raj-jain thanks for triaging. So this is an `<a>` inside another `<a>` and that's not allowed, right?

**Comment by rishi-raj-jain** [comment] 2024-04-08 20:21
@matthewp 

Yup, the browser automatically "unfolds" them.

**Comment by matthewp** [comment] 2024-04-08 20:23
Well the reproduction is not an `<a>` inside a `<a>` but I think it's maybe a `<p>` inside a `<p>` which I think has the same problem.

**Comment by rishi-raj-jain** [comment] 2024-04-08 20:23
and per the spec nested links are illegal.

<img width="878" alt="Screenshot 2024-04-09 at 1 53 18 AM" src="https://github.com/withastro/astro/assets/46300090/eb23cdcc-d2af-4412-b51a-8e118f7a4cf0">

**Comment by rishi-raj-jain** [comment] 2024-04-08 20:25
> Well the reproduction is not an `<a>` inside a `<a>` but I think it's maybe a `<p>` inside a `<p>` which I think has the same problem.

Oh alright.

**Comment by matthewp** [comment] 2024-04-08 20:26
@noClaps if you run the build in your example you'll see that Astro is outputing exactly what you told it to. But the issue is that it's not valid HTML and the browser unfolds it (as @rishi-raj-jain explained) so it looks different from what you expected.

My recommendation is that if you're rendering markdown not to nest inside of `<a>` or `<p>`. Your example has another issue where a `<li>` is inside of an `<a>` where it should directly nest `<ul>`.

Closing as not an Astro bug.

**Closed by matthewp** 2024-04-08 20:26 UTC
Labels: needs triage

**Comment by noClaps** [comment] 2024-04-08 20:47
Yeah, I figured that out after some more testing. Thanks for your help!
