### ISSUE TITLE
Hoisted scripts missing for content collection entry with MDX

### ISSUE THREAD

**Issue by noidwasavailable** [withastro/astro#8034] opened 2023-08-11 02:05 UTC
### What version of `astro` are you using?

2.10.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Similar to issue #5991 as seen in [this comment in the issue](https://github.com/withastro/astro/issues/5991#issuecomment-1672573443), when using Astro components in MDX with Content Collections, hoisted scripts are ignored. Inline scripts are still present (on a theme), both on dev server and on build.

### Steps to reproduce
1. Install [stanaing/astro-paper](https://github.com/satnaing/astro-paper)
2. Install mdx via `npx astro add mdx`
3. Create an astro component with hoisted script
4. Import above astro component in an mdx document in `content/blog`
5. Run `npm run dev`
6. Navigate to the mdx document created

I created [a repository which goes through these steps](https://github.com/noidwasavailable/astropaper-mdx) which you can clone and just install & run.

### Additional Contexts
**Stackblitz seems to not be working for this repo**, for which I've submitted an issue to as well...

Starting a fresh dev server reproduces this issue, but adding an `is:inline` directive to the concerning script then removing it, triggering hot reload, makes the issues go away, as seen in the videos below:

[first part (non inline script not working)](https://imgur.com/IRQvPY9)

[second part (declared inline, then removed, then working again)](https://imgur.com/fjG7RHa)

### What's the expected result?

Non-inline `<script>` tags in an astro component is supposed to be hoisted and inserted into `<head>` of the resulting page.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/noidwasavailable/astropaper-mdx?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment] 2023-08-15 19:39
Thank you for submitting this issue!

Since your reproduction is not minimal, it's hard to tell what the issue is.

Do you think this might be a duplicate of #7426 and #7761?

**Comment by noidwasavailable** [comment] 2023-08-16 01:52
@lilnasy I think it is a duplicate of #7761 because I added tried adding a script to the reproducible example in that thread [like here](https://stackblitz.com/edit/github-u2yta7-thrmce?file=src/components/Card.astro,src/content/posts/my-post.mdx), and pretty much seems to be the same issue as mine. I'll add further comments in that issue! Thank you.

**Comment by lilnasy** [comment] 2023-08-16 13:58
Thanks for confirming!

Closing as duplicate of 7761.

**Closed by lilnasy** 2023-08-16 13:58 UTC
Labels: needs response
