### ISSUE TITLE
🐛 BUG: Astro struggle to hydrate svelte component when a slot is specified

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#2270] opened 2021-12-24 14:31 UTC
### What version of `astro` are you using?

0.22.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

It's difficult to describe in precision but i'll do my best

Sometime the components will just skip hydrating with no error / warning in both consoles

Here's some tests i've done using the exemple below and trying to reproduce what's happening on my side

## Case 1
Main.astro
```astro
<main>
  <Counter client:load/>
</main>
```
Counter.svelte
```svelte
<div class="message">
  <slot>Test</slot>
</div>
```
❌ Works fine but the default value for the slot is overwrited

## Case 2
Main.astro
```astro
<main>
  <Counter client:load></Counter>
</main>
```
Counter.svelte
```svelte
<div class="message">
  <slot>Test</slot>
</div>
```
❌ Works fine but the default value for the slot is overwrited too

## Case 3
Main.astro
```astro
<main>
  <Counter client:load></Counter>
</main>
```
Counter.svelte
```svelte
<div class="message">
  <slot/>
</div>
```
❌ Component stops hydrating completely

## Case 4
Main.astro
```astro
<main>
  <Counter client:load/>
</main>
```
Counter.svelte
```svelte
<div class="message">
  <slot/>
</div>
```
❌ Component stops hydrating completely if done after case 3
✅ But rehydrating if case 3 is skipped

## Smol conclusion
Case 3 is breaking hydratation even after page reload, process reload and changes, reverting to case 1 or 2 fixes the hydratation and then the case 4 works, wich is.. weird

I hope I have been as specific as possible with this issue, maybe it would take more tests to get a real idea of the problem here.

Have a nice holiday & a happy new year !

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gw7htw?file=src%2Fcomponents%2FMain.astro&on=stackblitz

**Comment by matthewp** [comment] 2021-12-24 15:46
Thanks for the test case!

**Comment by tony-sull** [comment] 2022-02-15 11:12
Looking back at this one, I believe it's actually a duplicate of [#2153](https://github.com/withastro/astro/issues/2153).  It looks like Astro is currently setting a value to the `default` slot (probably an empty string), Svelte would see that and replace the placeholder content in a `<slot>`

Closing this out as duplicate of #2153, and it's also worth noting here that we've been discussion changes to the `slot` API to avoid potential conflicts with native template `<slot>`s, we'll make sure any updated API handles default slot (or lack of default slots) as expected :+1:

**Closed by tony-sull** 2022-02-15 11:12 UTC
