### ISSUE TITLE
Custom Elements / Web Components with specific attributes cause the markdown renderer to break

### ISSUE THREAD

**Issue by KonnorRogers** [withastro/astro#9717] opened 2024-01-17 20:17 UTC
### Astro Info

```block
~/projects/github-rfy1xs-ea1byz 5s
❯ npx astro info
Astro                    v4.1.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### Describe the Bug

When you use a custom element that looks like this:

```html
<sl-input label="Playback Rate" min="1" step="0.25" max="3" value="1"  type="number"></sl-input>
```

EDIT: specifically this seems to be the problem:

```html
<sl-input value="1" type="number"></sl-input>
```

inside of a `.md` file, the markdown rendering pipeline results in a unhandled rejection.

Stack Trace:

```
15:12:14 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
Error: Cannot compile unknown node `number`
    at Module.unknown (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/handle/index.js:63:9)
    at Module.one (/home/projects/github-rfy1xs-ea1byz/node_modules/zwitch/index.js:121:17)
    at Object.one (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/index.js:254:27)
    at Object.all (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/index.js:273:27)
    at Module.element (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/handle/element.js:96:25)
    at Module.one (/home/projects/github-rfy1xs-ea1byz/node_modules/zwitch/index.js:121:17)
    at Object.one (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/index.js:254:27)
    at Object.all (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/index.js:273:27)
    at Module.element (/home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/handle/element.js:96:25)
    at Module.one (/home/projects/github-rfy1xs-ea1byz/node_modules/zwitch/index.js:121:17)
  Hint:
    Make sure your promises all have an `await` or a `.catch()` handler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unhandled-rejection/
  Stack trace:
    at /home/projects/github-rfy1xs-ea1byz/node_modules/hast-util-to-html/lib/handle/index.js:63:9
    [...] See full stack trace in the browser, or rerun with --verbose.

```

### What's the expected result?

I expect Astro to handle custom elements and render them as normal HTML and not error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rfy1xs-ea1byz?file=src%2Fcontent%2Fdocs%2Findex.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2024-01-18 15:43
Here's a minimal reproduction that doesn't require starlight: https://stackblitz.com/edit/github-qdnomy?file=src%2Fpages%2Findex.md

**Comment by matthewp** [comment] 2024-01-18 15:48
Custom elements are not required here, was able to reduce down to just this:

```
<div type="number" value="1"></div>
```

**Comment by matthewp** [comment] 2024-01-18 17:19
There's an underlying issue with the rehype stack: https://github.com/syntax-tree/hast-util-raw/issues/22 Will need to see if I can fix this there.

**Comment by matthewp** [comment] 2024-01-18 17:34
There's another discussion about this same bug here: https://github.com/syntax-tree/hastscript/issues/21

**Comment by KonnorRogers** [comment] 2024-01-19 14:42
@matthewp thanks for digging in! much appreciated. Are there any workarounds for this? Such as modifying the AST directly in a remark plugin or something?

**Comment by matthewp** [comment] 2024-01-19 19:01
Yeah, that's what i would do if it's urgent. Another would be to add a script to dynamically add the `type` in the browser.

**Comment by KonnorRogers** [comment] 2024-01-24 14:46
@matthewp thanks for the help!

**Comment by matthewp** [comment] 2024-02-01 16:58
hastscript has been updated, but the parent modules that depend on it have not, so we cannot yet upgrade. Since we have automation for upgrading packages I'm going to close this issue as its now out of our hands.

**Closed by matthewp** 2024-02-01 16:58 UTC
Labels: - P4: important
