### ISSUE TITLE
create-astro: invalid template name doesn't fail

### ISSUE THREAD

**Issue by Jutanium** [withastro/astro#6379] opened 2023-02-27 21:13 UTC
### What version of `astro` are you using?

2.0.16

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When running create-astro with the template command, passing a non-third-party template name (e.g. `pnpm create astro --template empty`) - if the template doesn't exist, no error will be shown, and you'll get an empty directory with a `tsconfig.json` file at the end of the wizard.

It seems that [this failure branch](https://github.com/withastro/astro/blob/95164bfdd2c1cbe5f1fafeab9e998ee4c85df3e3/packages/create-astro/src/actions/template.ts#L81-L88) only runs on third party template names (e.g. `pnpm create astro --template asdf/asdf`), not on names without a slash.

### Link to Minimal Reproducible Example

pnpm create astro --template empty

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by liruifengv** [comment] 2023-02-28 10:03
Repeats my issue: https://github.com/withastro/astro/issues/6275

**Comment by ematipico** [comment] 2023-02-28 10:15
Closing, duplicate of #6275

**Closed** 2023-02-28 10:15 UTC
