### ISSUE TITLE
Astro component with table and slot wrongly parsed

### ISSUE THREAD

**Issue by mb21** [withastro/astro#12300] opened 2024-10-24 19:10 UTC
### Astro Info

```block
﻿﻿Astro                    v4.16.7
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
```

### Describe the Bug

The following page:

```astro
---
import MailLayout from '../components/MailLayout.astro'

const name = 'foo'
---

<MailLayout>

  <tr>
    <td>
      <a href="/foo" target="_blank">
        {name}
      </a>
    </td>
  </tr>

  <div slot="footer">
    Footer
  </div>
</MailLayout>
```

that uses `components/MailLayout.astro:`

```astro
---
---

<main>
  <slot />
</main>

<footer>
  <slot name="footer" />
</footer>
```

Is converted to the following HTML, which is obviously wrong:

```html
<body>
    <main>
        <a href="/foo" target="_blank"> foo </a>
        <a href="/foo" target="_blank">
            <div slot="footer">
                Footer
            </div>
        </a>
    </main>
    <footer></footer>
</body>
```

### What's the expected result?

Correct HTML with non-empty `<footer>` and not duplicated link.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-h3l48b?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ArmandPhilippot** [comment] 2024-10-24 19:51
Hi @mb21, your reproduction is missing the footer part, and the code published in the issue is missing `table` element.

Once wrapped by `<table>`, the table is correctly rendered. But indeed, the `<footer>` is empty and the `<a>` duplicated.

However, if you use text (e.g. `Foo`) instead of `{name}`, there no longer seems to be a rendering problem!

If you make the same observation, I think your problem is similar to the one I (perhaps poorly) described here: https://github.com/withastro/compiler/issues/1015

Do not hesitate to explain your case in the open issue. Your case seems a little different than mine, but I feel like the problem is the same. And if you have a better title, I'd be happy to update it! (maybe something like: `Rendering issue when using a variable inside a <table>`?)

**Comment by mb21** [comment] 2024-10-28 08:19
Yeah, seems to be about the same issue. I would close as a duplicate, but yours has been "needs triage" for four months?! Maybe time for me to switch more components over to JSX 🙄

**Comment by bluwy** [comment] 2024-10-28 13:50
The compiler needs a bit more love, currently we don't have the bandwidth to fix some of its issues, but will eventually get to it soon.

I'll close this for now in favour of the linked compiler issue.

**Closed by bluwy** 2024-10-28 13:50 UTC
Labels: needs triage
