### ISSUE TITLE
[vite:load-fallback] The argument 'path' must be a string or Uint8Array without null bytes

### ISSUE THREAD

**Issue by J-env** [withastro/astro#7329] opened 2023-06-08 06:15 UTC
### What version of `astro` are you using?

2.5.6+

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

There are currently no reproducible examples, I haven't found the reason yet, but it was fine before Astro2.5.6.

<img width="1679" alt="image" src="https://github.com/withastro/astro/assets/25259920/61cc6e03-0ba2-4f21-b8c1-7052bbd5daa3">

<img width="1678" alt="image" src="https://github.com/withastro/astro/assets/25259920/a298e2e4-6273-41c3-90c1-14a4435a333f">

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-06-11 16:20
Seems to be similar to https://github.com/withastro/astro/issues/7302, perhaps upgrading all the Astro deps to latest fixes it?

**Comment by J-env** [comment] 2023-06-13 01:42
Sorry, I deleted some pages based on environment variables. Is there a better way to achieve this?

In `astro:build:setup` hook: [Example](https://stackblitz.com/edit/github-sdeict-ermhpn?file=astro.config.mjs)

**Comment by matthewp** [comment] 2023-08-11 16:32
Are you trying to prevent it from building certain pages by mutating the `pages` Set? If so that's not what that is for, we don't currently have an API to do this.

**Comment by natemoo-re** [comment] 2023-08-17 20:22
I'm going to close this since there hasn't been a response in a while and you're likely trying to do something unsupported.

We currently have a [roadmap discussion for supporting incremental builds](https://github.com/withastro/roadmap/discussions/237) which I welcome you to chime in on!

**Closed by natemoo-re** 2023-08-17 20:22 UTC
Labels: needs response

**Comment by kyr0** [comment] 2024-01-24 16:28
This is still a thing; I just ran into this... I don't have time atm to create a reproduction repo but here's what I found:
- I had a `client:load` directive on a `<SomeAstroComponent />` that was used in a layout Astro component. Once I removed the directive, the error disappeared. The error was 1:1 the same as reported be the original reporter. The `SomeAstroComponent` was following this structure:

```
---
---
<cookie-consent />
<script>
    // TypeScript code that defines the cookie-constent web-component
</script>
```

**Comment by orbitz** [comment] 2024-01-26 09:42
I ran into this as well and removing client:load resolved it as well.  Not sure why.

**Comment by xenolito** [comment] 2024-01-28 11:44
Exactly the same issue here. Error only at build and with client:visible directive.

**Comment by RazvanCristian** [comment] 2024-02-04 23:38
I have encountered the same problem, it happens on static build when applying `client:*` to an astro component. For React components for some reason it works.

**Comment by Dgarc359** [comment] 2024-03-14 21:44
Hey there. I am working on deploying an Astro site to AWS.

I have a pretty simple example [here](https://github.com/Dgarc359/looper/tree/build-bug-repro) that fails under the same situations as described by the OP. Specifically, [this line here](https://github.com/Dgarc359/looper/blob/4d12868ae0cdb32ff882360a07eb56269afce8b6/src/pages/index.astro#L9) where `client:load` directive is supplied will break build. If I remove this directive, then I have found that sticking all the built out astro files leads to no user interaction. Willing to provide more info if it helps me resolve this!

For reference, this project is running [astro 4.4.11](https://github.com/Dgarc359/looper/blob/4d12868ae0cdb32ff882360a07eb56269afce8b6/yarn.lock#L873)

**Comment by mleister97** [comment] 2024-03-24 16:01
This is still an issue for me. I cannot add `client:` directives to my components, one of the main reasons why I want to try astro

**Comment by mleister97** [comment] 2024-03-24 16:13
Please see the issue in the logs:
```
You are attempting to render <TestGallery client:visible />, but TestGallery is an Astro component. Astro components do not render in the client and should not have a hydration directive. Please use a framework component for client rendering.
```

**Comment by mleister97** [comment] 2024-03-24 17:08
Hey everyone,

I recently started using Astro and ran into the same problem some of you might be facing. Basically, I didn't fully understand how Astro works.

Here's the deal: Astro components don't support client directives. You might have noticed warnings about this when you build your project. You can also find this information buried in Astro's documentation: https://docs.astro.build/en/guides/framework-components/#can-i-hydrate-astro-components

So, what do I do now? Well, I'm using a Svelte component, which is known for being lightweight compared to React or Vue. To get started, you'll need to install Svelte. After that:

Usage:
```
<Photoswipe client:visible/>
```

Photoswipe.svelte
```
<script>
    import PhotoSwipeLightbox from 'photoswipe/lightbox'
    import {onMount} from 'svelte'
    import 'photoswipe/style.css'

    onMount(() => {
        const lightbox = new PhotoSwipeLightbox({
            gallery: '.gallery',
            children: 'a',
            pswpModule: () => import('photoswipe')
        })
        lightbox.init()
    })
</script>
<div id="photoswipe-loader" />
```


See this for more: https://docs.astro.build/en/guides/client-side-scripts/

**Comment by Danielnewheart** [comment] 2024-04-01 00:35
Hi everyone, I saw this thread when I encounter this problem. Clearly, this problem only happened on build mode, and all `client:*` directive would make astro confused, but in dev mode it wouldn't happened. I suggest Astro should have more consistent result.

version: v4.5.9

**Comment by miromannino** [comment] 2024-04-07 17:16
To me it happened once because by mistake I added a client:idle on a astro component which was using React elements with client:idle. Could it be it happens only when there are nested client:* components?

**Comment by JoaoScheleder** [comment] 2024-04-26 15:06
I had this error, i fixed by removing duplicated  `client:load` 
```
// wrapper.astro
---
import { ReactDummyComponent } from "./react/dummy-component.react";
---
<ReactDummyComponent client:load>
</ReactDummyComponent >
```

```
// index.astro
---
import { Wrapper} from "./astro/wrapper.astro";
---
<Wrapper client:load>
</Wrapper >
```

> [!NOTE]
> I removed client:load from the index.astro

**Comment by TM312** [comment] 2024-05-14 08:38
> I had this error, i fixed by removing duplicated `client:load`
> 
> ```
> // wrapper.astro
> ---
> import { ReactDummyComponent } from "./react/dummy-component.react";
> ---
> <ReactDummyComponent client:load>
> </ReactDummyComponent >
> ```
> 
> ```
> // index.astro
> ---
> import { Wrapper} from "./astro/wrapper.astro";
> ---
> <Wrapper client:load>
> </Wrapper >
> ```
> 
> Note
> 
> I removed client:load from the index.astro

Great insight. Resolved it for me too.

**Comment by ArcherHume** [comment] 2025-02-18 02:11
Just to confirm for anyone else – what resolved it for me was this:

> I had this error, i fixed by removing duplicated `client:load`
> 
> ```
> // wrapper.astro
> ---
> import { ReactDummyComponent } from "./react/dummy-component.react";
> ---
> <ReactDummyComponent client:load>
> </ReactDummyComponent >
> ```
> 
> ```
> // index.astro
> ---
> import { Wrapper} from "./astro/wrapper.astro";
> ---
> <Wrapper client:load>
> </Wrapper >
> ```
> 
> Note
> 
> I removed client:load from the index.astro

It seems that a client:load component freaks out if it has a client:load on a component inside it.

**Comment by jrioscloud** [comment] 2025-03-20 00:10
For me removing `client:load` fixed it as well

**Comment by 1071125093** [comment] 2025-05-19 08:33
> Just to confirm for anyone else – what resolved it for me was this:
> 
> > I had this error, i fixed by removing duplicated `client:load`
> > ```
> > // wrapper.astro
> > ---
> > import { ReactDummyComponent } from "./react/dummy-component.react";
> > ---
> > <ReactDummyComponent client:load>
> > </ReactDummyComponent >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > // index.astro
> > ---
> > import { Wrapper} from "./astro/wrapper.astro";
> > ---
> > <Wrapper client:load>
> > </Wrapper >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note
> > I removed client:load from the index.astro
> 
> It seems that a client:load component freaks out if it has a client:load on a component inside it.

it works for me

**Comment by SHUAXINDIARY** [comment] 2025-08-01 09:00
You can try upgrade your astro version to 5.12.7 ，It will solve
