### ISSUE TITLE
Dynamic Tag styles not working with define:vars

### ISSUE THREAD

**Issue by jameswolfisz** [withastro/astro#4715] opened 2022-09-10 21:12 UTC
### What version of `astro` are you using?

v1.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

In a **Component** when using `define:vars` in `<style>` that targets a Dynamic Tag class the design tokens do not get passed to the the css.

```
---
const Element = "div"
const bg = "red"
---

<Element class="stack">
  <slot />
</Element>

<style define:vars={{ bg }}>
  .stack {
    background-color: var(--bg);
  }
</style>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lkh5ef?file=src/components/Stack.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2022-09-12 13:13
This looks like a duplicate of https://github.com/withastro/astro/issues/4400

**Closed by matthewp** 2022-09-12 13:13 UTC
