### ISSUE TITLE
Incorrect encoding for frontmatter extracted from markdown files by Astro.glob

### ISSUE THREAD

**Issue by toonddd** [withastro/astro#4695] opened 2022-09-09 14:52 UTC
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Special characters in strings defined in markdown file frontmatter are garbled when obtained via `Astro.glob`.

Encoding is fine when consuming the same markdown content in an Astro layout component.

Attached StackBlitz very clearly shows exactly what goes wrong.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-zrvfhr?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-09-13 09:13
Looks like adding

```html
<head>
  <meta charset="utf-8" />
</head>
```

fixes the issue. Astro is returning the HTML as-is without encoding it when checking the network request. Closing this one as it's working as intended!

**Closed by bluwy** 2022-09-13 09:13 UTC
Labels: p4-important

**Comment by mortencallesen** [comment] 2024-06-07 13:29
> Looks like adding
> 
> ```
> <head>
>   <meta charset="utf-8" />
> </head>
> ```
> 
> fixes the issue. Astro is returning the HTML as-is without encoding it when checking the network request. Closing this one as it's working as intended!

This does fix the issue indeed...!! THANKS!
