### ISSUE TITLE
Unable to properly check React components

### ISSUE THREAD

**Issue by lxchapu** [withastro/astro#9467] opened 2023-12-19 03:08 UTC
### Astro Info

```block
Astro                    v4.0.6
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

When I use the `astro check` command, there is an error for React components. It seems unable to properly check the props of React components.

<img width="768" alt="image" src="https://github.com/withastro/astro/assets/40556555/86e80187-94ae-451a-a9a4-96489f944477">

### What's the expected result?

No errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-3sdx2x?file=src%2Fcomponents%2FTestButton.tsx,package.json&title=Astro%20Starter%20Kit:%20Basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-12-19 04:41
Duplicate of https://github.com/withastro/language-tools/issues/727

**Closed by Princesseuh** 2023-12-19 04:41 UTC
Labels: needs triage
