### ISSUE TITLE
@solid-js/router working in build and preview but not in dev

### ISSUE THREAD

**Issue by AirBorne04** [withastro/astro#4871] opened 2022-09-26 10:09 UTC
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When running the example simple routing with [@solidjs/router](https://github.com/solidjs/solid-router.git) example the workflow of `astro build` and `astro preview` is running fine. Running `astro dev` is failing with the error:
```
The requested module 'solid-js/web' does not provide an export named 'effect'
```
The error seems to originate from `solid-js/web` is imported with the `server` version which does not have an `effect` exported. I am struggling to find out why this is happening and how to work around it.

### Link to Minimal Reproducible Example

https://github.com/AirBorne04/minimal-astro-cloudflare-solid.git

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2022-09-26 18:38
Seems like this library is not intended to be used on the server. Can you use `client:only` or optionally only load it in an island when you know you are in the client?

**Comment by DevHusariaSolutions** [comment] 2022-09-27 21:50
Bro I faced 2 critical issues related to Astro in SolidJS cooperation. The truth is - Astro is more focused in React and Preact development, so SolidJS is like child from another family here :/ Astro is great and promising, but pararell evolving with such different solutions is not so eazy

**Comment by AirBorne04** [comment] 2022-09-28 10:27
@DevHusariaSolutions I mainly am trying to fix the ssr functionality at the moment. And while i totally get the focus on more widely used frameworks i see astro as a big opportunity for solid to shine. Also astro does save a lot of time in then project, therefore i am good with helping to improve it as well.

> Astro is more focused in React and Preact development, so SolidJS is like child from another family

funny because to big extend netlify seems to be pushing both of them astro and solidjs

**Comment by matthewp** [comment] 2022-10-06 14:27
@DevHusariaSolutions It's not true that Astro is focused on other frameworks. We treat all of our integrations equally.

Issues of the type: `__ library doesn't work with ___ integration` are really difficult to fix because they often require debugging the library itself to figure out what the problem is. Usually it comes down to a configuration issue.

These types of issues are best fixed by members of the respective communities who understand the context better. I would love to make Solid.js libraries work better in Astro, but I don't have the luxury of stopping everything I'm doing to solely focus on that.

I believe that Solid has more difficulties because libraries ship with untranspiled code. Vite 3 changed it so that dependencies are loaded through regular Node.js by default. This will cause any library that needs to be transpiled to fail. Using `noExternal` can fix that.

I'm not sure if that's the problem with this specific issue, however.

**Closed** 2022-10-12 13:29 UTC
Labels: p3-minor-bug, component library doesn't work
