### ISSUE TITLE
Integration: Image, `base` is not being respected during build

### ISSUE THREAD

**Issue by aFuzzyBear** [withastro/astro#4436] opened 2022-08-23 12:03 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm 

### What operating system are you using?

Linux

### Describe the Bug

User had reported an issue with the build output of the images not being correctly displayed.
User has a `config.base` setting within  that is not being respected during build. 
To reproduce : `yarn build && yarn preview`
Link to conversation can be found (here](https://discord.com/channels/830184174198718474/1010297508305584230)

### Link to Minimal Reproducible Example

https://github.com/aFuzzyBear/astro-asset-routing-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ChristineTham** [comment] 2022-08-23 22:54
Thank you for posting this. I have this problem too, and have been wanting to post an issue, but you beat me to it! Basically the static url generated does not include config.base during build - works in dev.

**Comment by ota-meshi** [comment] 2022-08-29 10:39
I think it may have been fixed in v1.0.9.

https://github.com/withastro/astro/pull/4469

**Comment by ChristineTham** [comment] 2022-08-30 02:30
> I think it may have been fixed in v1.0.9.
> 
> #4469

Not for me. The issue is the generated img url does not include `base`

**Comment by jeffwinegar** [comment] 2022-08-30 23:06
I bumped the original minimal reproducible example [https://github.com/jeffwinegar/astro-asset-routing-test](https://github.com/jeffwinegar/astro-asset-routing-test) to astro 1.1.2 and @astrojs/image 0.3.7 and ran a new test. I can confirm that these latest versions do not fix the issue. I haven't had the opportunity to help find a fix but would be willing to help where I can if anyone has a good place to start digging.

**Comment by ChristineTham** [comment] 2022-09-01 00:15
This appears fixed in @astrojs/image release 0.4.0, so I recommend the issue can be closed.

**Comment by jeffwinegar** [comment] 2022-09-01 01:30
> This appears fixed in @astrojs/image release 0.4.0, so I recommend the issue can be closed.

Just ran a new test myself and I can confirm that @astrojs/image 0.4.0 fixes this issue for me.

**Closed** 2022-09-12 14:25 UTC
Labels: p4-important, image
