### ISSUE TITLE
Middleware not called for non-custom 404 page

### ISSUE THREAD

**Issue by xriter** [withastro/astro#7881] opened 2023-07-31 15:13 UTC
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When you have `middleware.ts` setup, and a **custom** 404 page, the middleware will get called when you hit a 404 page. However, if you don't have a custom 404 page but rely on the default, the middleware won't get called.

Wondering if this is a deliberate decision?

### What's the expected result?

Consistency between the custom and non-custom 404 page. Both should call the middleware.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pt4enm?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-07-31 16:09
@xriter do you have this issue in development AND production?

**Comment by lilnasy** [comment] 2023-08-03 19:39
Even when 404.astro is added, middleware only runs in dev mode.

Repro: https://stackblitz.com/edit/github-pt4enm-xnujgy (added 404.astro and node adapter to the above repro)

Workaround: create a slug route and set Astro.response.status to 404.

**Comment by ematipico** [comment] 2023-08-25 11:23
I am going to close this issue as not planned.

This is the expected behaviour because we can't control default 404 pages, especially in adapters like Vercel, Netlify, etc.

**Closed by ematipico** 2023-08-25 11:23 UTC
Labels: - P3: minor bug, feat: middleware, feat: 404
