### ISSUE TITLE
Build form submission handler using API Route in Astro JS framework

### ISSUE THREAD

**Issue by karandaid** [withastro/astro#5683] opened 2022-12-27 23:01 UTC
### What version of `astro` are you using?

v1.7.2

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to Build a form submission handler for JS-free form submission. But the api is not receiving the data sent by the html form. I am following this [documentation](https://astro.build/blog/experimental-server-side-rendering/).

The signin.json.js file contains an export async function called post that takes in a request parameter and logs it to the console. It then returns a new Response object with the request parameter stringified as JSON and a status of 200.

The index.astro file contains an HTML form with an action of /api/signin.json and a method of post. It has two input fields, one of type text with the name text and a value of test, and the other of type submit.

Upon form submission, the output in the terminal shows the request object that was logged to the console. However, the output in the browser shows a JSON object with several properties, but none of them contain the data that was submitted in the form. It is unclear why the data from the form is not being received by the API. It could be a problem with the form itself, the way the data is being processed by the post function, or something else.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k8d9n9?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment] 2022-12-28 19:30
@karandaid  [This is the correct way](https://stackblitz.com/edit/github-k8d9n9-geygfn?file=src%2Fpages%2Fapi%2Fsignin.js,src%2Fpages%2Findex.astro) to access form data

**Comment by matthewp** [comment] 2023-01-03 13:54
Thanks for the answer @MoustaphaDev. Closing as not a bug.

**Closed by matthewp** 2023-01-03 13:54 UTC
