### ISSUE TITLE
<= operator breaks compiler

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#6979] opened 2023-05-03 19:43 UTC
### What version of `astro` are you using?

2.3.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

If the `<=` operator is used inside a JSX `{}` expression, the compiler throws the following error:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/63650415/236028151-f46f65b1-d6ef-41e8-bef6-873e182ac8af.png">

```astro
---
const limit = 5;
---

{
  limit <= 5 && <span id={`limit-${limit}`}>{limit}</span>
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kpzhe7?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-05-03 21:24
Closing as a duplicate of https://github.com/withastro/compiler/issues/723

**Closed by Princesseuh** 2023-05-03 21:24 UTC
