### ISSUE TITLE
remarkPluginFrontmatter returns undefined using Content Collections with remark plugin

### ISSUE THREAD

**Issue by prototypa** [withastro/astro#6016] opened 2023-01-28 22:17 UTC
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have not been able to get a remark plugin to work for me when using new **Astro 2.0 Content Collection**.
The new _remarkPluginFrontmatter_ variable always returns `undefined`.

```javascript
const { remarkPluginFrontmatter } = await entry.render();
```

I leave a simple example where you can see the problem. Thanks.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vpb7vm?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thomasledoux1** [comment] 2023-01-29 08:05
Duplicate of https://github.com/withastro/astro/issues/5859 I think. PR is already merged, so will be fixed in next release probably

**Closed as completed** 2023-01-29 16:34 UTC
