### ISSUE TITLE
I can't catch an error in the `loadRemoteImage` function when the fetch function occurs error

### ISSUE THREAD

**Issue by wulinsheng123** [withastro/astro#5392] opened 2022-11-14 08:25 UTC
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

I can't catch an error in the `loadRemoteImage` function when the fetch function occurs error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lmp1qc?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-11-14 09:46
I don't think it's the fetch function that has an error, it seems like because when parsing the image format:

https://github.com/withastro/astro/blob/eab4a0279fd28163cea9da2b010c5ccde5645e6f/packages/integrations/image/src/loaders/index.ts#L263-L265

It doesn't support `.gif`, hence `transform.format` is `undefined`. Looks like a duplicate of https://github.com/withastro/astro/issues/5028 (with the same repro)

**Comment by wulinsheng123** [comment] 2022-11-14 10:11
> I don't think it's the fetch function that has an error, it seems like because when parsing the image format:
> 
> https://github.com/withastro/astro/blob/eab4a0279fd28163cea9da2b010c5ccde5645e6f/packages/integrations/image/src/loaders/index.ts#L263-L265
> 
> It doesn't support `.gif`, hence `transform.format` is `undefined`. Looks like a duplicate of #5028 (with the same repro)

I mean that I need to see a full error, I need to know what happens in fetch when `loadRemoteImage` failed.

**Comment by wulinsheng123** [comment] 2022-11-14 10:14
like this 
![image](https://user-images.githubusercontent.com/27261522/201633951-05093768-42fe-4646-bc1e-316b2043b17a.png)
I don't know what's wrong with `loadRemoteImage `

**Comment by wulinsheng123** [comment] 2022-11-14 13:14
> Thanks! The timeout error is interesting, I think it makes sense then to log out the error. I was confused as the repro doesn't show the issue.

If Chinese people wants to access google link. We must use vpn, but the vpn can’t proxy terminals, so will happens errors

**Comment by wulinsheng123** [comment] 2022-11-14 13:18
> > Thanks! The timeout error is interesting, I think it makes sense then to log out the error. I was confused as the repro doesn't show the issue.
> 
> example like If Chinese people wants to access google link. We must use vpn, but the vpn can’t proxy terminals, so will happens errors.
And a lot company’s internal context didn’t allow to access

**Closed** 2022-11-16 21:55 UTC
Labels: p2-nice-to-have
