### ISSUE TITLE
Nested hydrating components aren't working properly

### ISSUE THREAD

**Issue by markpinero** [withastro/astro#4687] opened 2022-09-09 01:37 UTC
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

If a hydrated component toggles visibility of a child component that's hydrated by (client:visible/only tested), the parent component will not function properly in some instances.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9nofqr?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by markpinero** [comment] 2022-09-09 01:41
Only way I've found that works via https://discord.com/channels/830184174198718474/845451724738265138/966277614056652831:

```
<Parent client:visible>
  <Child client:visible />
</Parent>
```

Child.tsx
```
import NoSSR from 'react-no-ssr'

export default function Child() {
  return (
    <NoSSR>
      ...
    </NoSSR>
  )
}
```

**Comment by matthewp** [comment] 2022-10-12 13:27
Thanks! This was a duplicate of another issue that has since been fixed. Here's a working example now: https://stackblitz.com/edit/github-9nofqr-1yg2kk?file=src%2Fpages%2Findex.astro

**Closed by matthewp** 2022-10-12 13:27 UTC
Labels: p3-minor-bug
