### ISSUE TITLE
Dynamic routes have no nullable option

### ISSUE THREAD

**Issue by sopyb** [withastro/astro#6733] opened 2023-04-02 18:10 UTC
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

node, mode: standalone

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chromium

### Describe the Bug

I have a route /profile/[id] and i'd like to make it so id was optional and instead we'd just get undefined or null

I tried [id?] and [id]? and the docs don't seem to mention it so I am assuming that it doesn't exist.

### Link to Minimal Reproducible Example

?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-04-04 09:29
Do Rest Parameters cover your usecase? <https://docs.astro.build/en/core-concepts/routing/#rest-parameters>

In the meantime, I'll be closing this issue since it's not a bug. If rest parameters don't cover this, please post a feature request at <https://github.com/withastro/roadmap/discussions>

**Closed by Princesseuh** 2023-04-04 09:29 UTC
