### ISSUE TITLE
Tailwind class taken from json file is applied but not its style when using literal template

### ISSUE THREAD

**Issue by nullgaro** [withastro/astro#11248] opened 2024-06-13 14:46 UTC
### Astro Info

```block
> astrobug@0.0.1 astro
> astro info

Astro                    v4.10.2
Node                     v22.3.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

When I take a class name from the data.json file and try to add it with a literal template to the li element it will add the class but not the style, until I manually add the class once and then I can even work with the class from the json.

IMPORTANT: Check the video (video.mp4) to understand better what happens.

https://github.com/withastro/astro/assets/90156486/f7df1a68-4485-4b8f-b4cf-322208cbcc18

Additionally when I stop the local server and start it again I'll have lost the "progress".

### What's the expected result?

To be applied the style directly

### Link to Minimal Reproducible Example

https://github.com/nullgaro/astrobug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by V3RON** [comment] 2024-06-13 15:36
@nullgaro
The problem is that you are loading data.json from the public directory, which is not included in your Tailwind configuration (tailwind.config.mjs). Tailwind scans all the files specified in the configuration for classes to include in the built CSS.

To fix this, add ./public/data.json to the content property in your tailwind.config.mjs. This will ensure it works correctly.

**Comment by ascorbic** [comment] 2024-06-14 11:28
I think @V3RON has the fix for this so I'm going to close it. If there is still an issue, please do reply explaining why, and tag me and I'll reopen it.

**Closed by ascorbic** 2024-06-14 11:28 UTC

**Comment by nullgaro** [comment] 2024-06-14 16:46
Thanks for the quick answer, everything is fine!
