### ISSUE TITLE
SolidJS integration on Vercel Edge breaks with "Ua is not supported in the browser"

### ISSUE THREAD

**Issue by Coretteket** [withastro/astro#6989] opened 2023-05-04 09:04 UTC
### What version of `astro` are you using?

2.3.4

### Are you using an SSR adapter? If so, which one?

Vercel Edge

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

It appears that issue #5915 has re-appeared recently. Using versions `astro@^2.3.4`, `@astrojs/solid-js@^2.1.1`, `@astrojs/vercel@^3.3.0`, I'm getting the following error in Vercel logs, and an empty SolidJS component on client. Note that this error only appears when deployed.

```
Error: Ua is not supported in the browser, returning undefined
    at (entry.mjs:56:32412)
    at (entry.mjs:56:32522)
    at (entry.mjs:56:33846)
    at (entry.mjs:42:1044)
```

The minimal reproducible example is identical to that of issue #5915, except for the updated packages as described above.

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-vercel-solid

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkelly17** [comment] 2023-05-04 21:54
I don't have a min example to contribute, but I may be getting the same thing on Cloudflare as well.  Same deps cause the same blank issue, and locking to 
astro/cloudflare 6.2.2 and @astrojs/solid-js 2.1 seems to fix it. So, not sure if was the bump to 2.1.1 in astro/solid or some shared logic for the edge betwen 6.2.2 and 6.2.4, but seems like it was solid-js 2.1 is my guess.

**Comment by johannesspohr** [comment] 2023-05-05 22:02
I tried to mess around with a little, and I was able to make some progress, but still not 100%:

- The conditional exports for `solid-js/web` contains a `worker` section, that is listed before the `browser` exports, so it should be used when adding `worker` to Vite's `resolve.conditions`. If I try to do that in the cloudflare `astro:build:setup` hook, it still uses `web/dist/web.js`, which is causing the error, and not `web/dist/server.js`, as it should imho (but I might be missing something)

- I added a resolve alias to force vite to use the server version when building for server, similar to the [existing workaround for `react-dom`](https://github.com/withastro/astro/blob/main/packages/integrations/cloudflare/src/index.ts#L78) - we need to manually remove it again when building for the client, because the `template` function can't be resolved otherwise, but I get a correctly SSR'd website then - the only issue is that the hydration keys are not matching (my simple counter button example has a key of `s00`, and it expects `s00-0`).

@astrojs/clouflare/dist/index.ts

```
if (target === "server") {
  vite.resolve = vite.resolve || {};
  vite.resolve.alias = vite.resolve.alias || {};
  const aliases = [
      { find: "solid-js/web", replacement: "solid-js/web/dist/server.js" }, // this works somewhat
      { find: "react-dom/server", replacement: "react-dom/server.browser" }
  ];
  if (Array.isArray(vite.resolve.alias)) {
    vite.resolve.alias = [...vite.resolve.alias, ...aliases];
  } else {
    for (const alias of aliases) {
      vite.resolve.alias[alias.find] = alias.replacement;
    }
  }
  vite.resolve.conditions.push("worker"); // this has no effect

  vite.ssr = vite.ssr || {};
  vite.ssr.target = vite.ssr.target || "webworker";
} else {
  vite.resolve.alias.splice(vite.resolve.alias.find(a => a.find === "solid-js/web")); // this is needed because otherwise it will use the server version on the client
}
```

**Comment by bluwy** [comment] 2023-05-15 14:35
While https://github.com/withastro/astro/pull/7092 fixes the case for cloudflare, I think there was an unintentional breaking change somewhere. Gonna look into this again this week

**Comment by bluwy** [comment] 2023-05-16 10:28
Looks like https://github.com/withastro/astro/pull/4888 is causing quite some issues:

1. I don't think the solid integration should change `ssr.target` to `node`. The deployment platform, in this case, vercel edge and cloudflare, should always set this strictly as `webworker`.
2. https://github.com/withastro/astro/pull/6934 undid the fix in https://github.com/withastro/astro/pull/4888. That's why it caused the regression.

So I'm thinking of a plan of:

1. Remove the solid integration `ssr.target = 'node'` setting
2. Make vercel edge and cloudflare always set `ssr.target = 'webworker'`
3. Set cloudflare condition to `workerd` and `worker`: https://github.com/withastro/astro/pull/7092
4. Set vercel edge condition to `edge-light` ([spec/proposal](https://runtime-keys.proposal.wintercg.org/#edge-light)) and `worker` (though not documented, this is the only way to make solid-js work) (NOTE: [research link](https://github.com/search?q=org%3Avercel%20edge-light&type=code))

**Comment by bluwy** [comment] 2023-05-17 13:13
Step 1-4 should be done now, so updating to the latest version of `@astrojs/vercel` and `@astrojs/cloudflare` should fix it when it's released. Unfortunately this still leaves solidjs in a state of a regression, but we've done changes like this in the past so I'm leaning towards "upgrading packages to latest" as the fix for now.

Marking this closed as the stuff to do is completed, the next release should come around today or tomorrow for Astro 2.5 + the other packages.

**Closed by bluwy** 2023-05-17 13:13 UTC
Labels: framework-solid, p4-important

**Comment by pilcrowOnPaper** [comment] 2023-05-19 04:23
OK so I was getting the same error after updating everything to the latest version. Took quite a while to debug but I needed to remove the `noExternal` config that was used to fix the same issue in an older version:

```ts
export default defineConfig({
	 vite: {
		ssr: {
			noExternal: ["solid-js"]
		}
	}
});
```

**Comment by sncalvo** [comment] 2023-08-31 22:08
Currently getting this error with `@astrojs/deno` and `@astrojs/cloudflare` after upgrading all packages to latest. Has anyone else experienced this after Astro 3.0 or upgrade of a related library?

**Comment by johannesspohr** [comment] 2023-09-01 13:40
My cloudflare deployment using astro 3 and latest SolidJS integration is working fine, so I assume it's something unrelated.
