### ISSUE TITLE
HTML minification with Doctype tag

### ISSUE THREAD

**Issue by proyb6** [withastro/astro#7162] opened 2023-05-22 15:24 UTC
### What version of `astro` are you using?

2.5.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

After ran thru Astro HTML minification in 2.5.x release, I found curiosity why isn't docttype tag being minified?

```
<!DOCTYPE html>
<html ...>
```

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-05-23 07:05
That's intended :)

**Comment by bluwy** [comment] 2023-05-23 08:15
Duplicate of https://github.com/withastro/compiler/issues/766

The doctype is injected at https://github.com/withastro/astro/blob/5b6a0312a822565404a6334576677fc574cfcd56/packages/astro/src/runtime/server/render/page.ts#L42

Maybe we can remove the `\n`?

**Comment by proyb6** [comment] 2023-05-24 06:55
@bluwy Yeah, I think I have seen some project in Next does it. But there is another problem with a long tailwind classess, does not minified, it just preserve white space which is a cumbersome to clean up whitespace manually in every files.

```
<p class="text-lg ...
        font-semibold
        ...
">
```

**Comment by matthewp** [comment] 2023-05-24 13:07
We can remove it. It just means passing down the minification option to the runtime (probably via the `result` object).

**Comment by matthewp** [comment] 2023-05-24 13:07
Would love a PR for this @proyb6 if you can.

**Comment by proyb6** [comment] 2023-05-28 04:27
@matthewp I did the PR! Thank you.
https://github.com/withastro/astro/pull/7228

**Comment by bluwy** [comment] 2023-05-29 13:07
> We can remove it. It just means passing down the minification option to the runtime (probably via the `result` object).

Do we need a ternary for that instead of always prepending `<!DOCTYPE html>` without the new line?

**Comment by wulinsheng123** [comment] 2023-05-30 03:06
let me fix it

**Comment by wulinsheng123** [comment] 2023-05-30 06:07
@matthewp @bluwy There is a problem with the SSG which the building property’s (compressHTMl) can’t pass down.

**Closed** 2023-06-05 08:02 UTC
Labels: p2-nice-to-have

**Comment by proyb6** [comment] 2023-06-07 14:41
@bluwy @JerryWu1234  I think #7242 patch for Astro 2.6.0 did not removed the new line after doctype?
