### ISSUE TITLE
nested dynamic routing can't work with encode URL

### ISSUE THREAD

**Issue by loveloki** [withastro/astro#11557] opened 2024-07-26 03:10 UTC
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  none
Integrations             none
```

### Describe the Bug

Nested dynamic routing using on-demand rendering mode via `output: 'server'` cannot work with encoded URLs.

config:
```
export default defineConfig({
  output: 'server',
});
```

![image](https://github.com/user-attachments/assets/4523f660-3e96-4d15-9685-6bd6a5a1e49c)

### What's the expected result?

Nested dynamic routing can work with encode URL

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tu5dpb?file=src%2Fpages%2F%5Bid%5D%2F%5Blink%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment] 2024-07-29 09:32
I'm closing this as a duplicate of #8516. I think I have a fix, but it would be a breaking change so would probably need to wait for Astro 5. I'll go into a bit more detail in the other issue. The ugly workaround would be to double-encode it: `const astro = encodeURIComponent(encodeURIComponent('https://astro.build'))`

**Closed by ascorbic** 2024-07-29 09:32 UTC
Labels: needs triage

**Comment by loveloki** [comment] 2024-07-29 09:59
> I'm closing this as a duplicate of #8516. I think I have a fix, but it would be a breaking change so would probably need to wait for Astro 5. I'll go into a bit more detail in the other issue. The ugly workaround would be to double-encode it: 我将其作为以下副本关闭 #8516 。我想我已经解决了，但这将是一个重大更改，因此可能需要等待 Astro 5。我将在另一期中详细介绍。丑陋的解决方法是对其进行双重编码：`const astro = encodeURIComponent(encodeURIComponent('https://astro.build'))`

thanks! It's a temporary method available
