### ISSUE TITLE
`import.meta.env.MODE` always `development`

### ISSUE THREAD

**Issue by hirasso** [withastro/astro#7463] opened 2023-06-23 15:22 UTC
### What version of `astro` are you using?

v2.7.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

All of them :)

### Describe the Bug

In `astro.config.mjs`, I am doing the following:

```js
console.log('mode:', import.meta.env.MODE);
console.log('production:', import.meta.env.PROD);
console.log('development:', import.meta.env.DEV);
```

When I run `astro dev`, this is the (expected) output:

```shell
production: false
development: true
mode: development
```

But when I run `astro build`, `MODE` is _still_ `development`:

```shell
production: true
development: false
mode: development # < expected "production"
```

### What's the expected result?

When running `astro build`, `import.meta.env.MODE` should be "production".

### Link to Minimal Reproducible Example

None needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-06-26 09:32
Duplicate of https://github.com/withastro/astro/issues/6241

**Closed by bluwy** 2023-06-26 09:32 UTC
