### ISSUE TITLE
In dev mode styles are duplicate when using @import

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#9097] opened 2023-11-14 15:06 UTC
### Astro Info

```block
Astro                    v3.5.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When adding the following code to an astro page
```html
<style>
  @import "/styles.css";
</style>
```
The styles in the styles.css are applied twice in dev mode. This can be seen by checking the styles on the html tag, there you can see that red is displayed twice.

### What's the expected result?

That the styles are added once

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-hgkbnw?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-11-17 14:25
Can you trim down the reproduction. I think only a single page, no components, just the `@import` is really needed to show the problem here. Thanks!

**Comment by RogierdeRuijter** [comment] 2023-11-17 15:35
@matthewp cleaned it up!

**Comment by lilnasy** [comment] 2023-11-22 17:28
- Related: https://github.com/withastro/astro/issues/5857

That one was deemed an architectural limitation but this may be different as there is an explicit import.

**Comment by bluwy** [comment] 2023-11-24 08:59
I made an initial fix at https://github.com/withastro/astro/tree/fix-css-tracking, however it's not easy due to the way we handle HMR.

Currently, the modules of `@import` while belonging to the Astro style tag, they also belong to the main Astro file internally. That means when we try to crawl the Astro file for CSS to be added to the rendered HTML, we will see the `@import` modules as part of the Astro file and add them to the rendered HTML too.

We need to refactor how we handle HMR a bit before we can fix this nicely, particularly:

https://github.com/withastro/astro/blob/ae29fad70b8f5d32baca00625e1e8ed94fee47f6/packages/astro/src/vite-plugin-astro/hmr.ts#L70-L75

(Note: the code above only handles direct imports and not recursively, means it only tracks `A.astro -> B.css` but not `A.astro -> A.astro?style.css -> B.css`)

I can try to re-do the HMR handling a bit for Astro 4.0 and see how it goes.

**Comment by mayank99** [comment] 2023-12-21 19:13
something else i noticed is the styles are getting scoped in prod version, which i don't think is intended.

in dev mode, both unscoped and scoped styles are present.
![](https://github.com/withastro/astro/assets/9084735/e8e5779b-0c40-4f37-b63f-cee81729a7a8)

repro: https://stackblitz.com/edit/withastro-astro-dtgcxj?file=src%2Fstyles.css,src%2Fpages%2Findex.astro

**Comment by ascorbic** [comment] 2024-10-02 13:06
I'm closing this. I just tested both @RogierdeRuijter and @mayank99's repros (thanks!) with `astro@4.15.10` and can no longer reproduce the issue.

**Closed by ascorbic** 2024-10-02 13:06 UTC
Labels: feat: styling, - P3: minor bug, feat: dev
