### ISSUE TITLE
`Astro.clientAddress` is not available in static mode.

### ISSUE THREAD

**Issue by Ehesp** [withastro/astro#10290] opened 2024-03-01 14:51 UTC
### Astro Info

```block
Astro                    v4.4.7
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

After version `4.4.6`, we're experiencing a potential regression. We're using cloudflare pages as our target, and our astro config looks like so:

```
export default defineConfig({
  server: {
    host: true,
    port: 8788,
  },
  output: 'server',
  adapter: cloudflare({
    runtime: {
      mode: 'local',
      type: 'pages',
    }
})
```

We have been successfully our server rendered application alongside static pages (blog posts) using the `prerender = true` flag, e.g

```
// pages/blog/index.astro
export const prerender =  true;
```

This has been working, even with the ` output: 'server',` flag set. However, in the `4.4.7` the dev server not longer works (however production builds do, and the pre-rendered pages are generated as expected).

The error thrown is:

```
StaticClientAddressNotAvailable: `Astro.clientAddress` is only available when using `output: 'server'` or `output: 'hybrid'`. Update your Astro config if you need SSR features.
    at get clientAddress [as clientAddress] (file:///.../node_modules/astro/dist/core/render-context.js:134:17)
```

We have somewhat of a 'hack' in our middleware to get this working: 

```
export const onRequest: MiddlewareHandler = (ctx, next) => {
  // Astro runs middelware for SSG as well (for every page).
  // As of now, we don't need anything from middlewares for SSG pages.
  
  // ctx.locals.runtime is only available in SSR mode.
  if (!ctx.locals.runtime) {
    return next();
  }

  return ssrMiddleware(ctx, next);
```

I'm not entirely sure if this is a regression, or something has been fixed which should prevent this. But it's been working ok before this version was released.

### What's the expected result?

It works?

Also clarification around the situation on cloudflare pages & pre-rendering would be useful, since it's not clear from the docs whether this should be possible?

In the reproduction I get an `/home/projects/github-tmnqm5/node_modules/@cloudflare/workerd-linux-64/bin/workerd: line 26: a command can only contain words and redirects` error - no idea what this is but it should give an idea as to what's going on.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tmnqm5?file=src%2Fpages%2Fstatic.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment] 2024-03-01 15:39
Does the stackblitz need to be updated, I don't see a use of clientAddresss?


Whatever it is, it was likely introduced in [#10274](https://github.com/withastro/astro/pull/10274/files#diff-664d1d4d2278c97ecff30c034f6799d88cb6229b38c5a7afcf03fb596231b679R79).

**Comment by lilnasy** [comment] 2024-03-01 15:44
I copied over the repro to a gitpod instance to see both `/` and `/static` being served correctly in dev mode.

**Comment by Ehesp** [comment] 2024-03-01 15:46
Is the middleware commented out? I did that by accident and saved. Let me see if I can repro locally with a fresh setup.

**Comment by Ehesp** [comment] 2024-03-01 16:11
Yeah it works ok in a fresh setup, so I assume some of my middleware (it's a big project) is calling something which triggers this to happen. So after doing some trial and error, its one of my middleware which triggers the error (tRPC)... no idea why though:

```ts
// middleware
ctx.locals.trpc = createCaller({ ...ctx, server: true });

// trpc
export const createCaller = t.createCallerFactory(router);
```

Appreciate this is way outside of your scope, but it's basically doing this: https://trpc.io/docs/server/server-side-calls#create-caller

So my question is; is that change a regression or not?

**Comment by lilnasy** [comment] 2024-03-01 16:13
`...ctx` would read all properties of `APIContext`, including `clientAddress`.

**Comment by lilnasy** [comment] 2024-03-01 16:17
I can reproduce the error, and currently it is expected. We should consider whether we should change that. However, it would be more urgent if there was a difference between dev and build. You mentioned that there is, but I can't reproduce it - the build fails the same as dev.

**Comment by Ehesp** [comment] 2024-03-01 16:46
Ah good catch on the `...ctx` part, didn't spot that.  I can confirm you're correct, it fails in prod too so must have got mixed up with the version I was testing out. 

I'll pin the version for now on 4.4.6 so we can get it working, but I'd be keen to know if this is something which intended overall, as obviously we can't live on that version forever and would have to figure out an alternative plan.

**Comment by Ehesp** [comment] 2024-03-01 17:16
I can probably work around it now actually knowing `...ctx` causes it - just not sue if I'm hacking against something which shouldn't be working though.

**Comment by lilnasy** [comment] 2024-03-01 17:17
It was intended since the introduction of `clientAddress`. However, it's possible it was not being enforced until recently.

If that is the case and it affects multiple users in a way they can't easily fix, we should backtrack.

**Comment by Fryuni** [comment] 2024-03-01 21:24
This was documented and failing (not sure if with the same exact error) at least just before v4 when I started using this error to detect whether a script was running on build time or SSR. That integration didn't break in the recent builds. There are other ways around it like the `locals.runtime`, but trying to read the `clientAddress` was the most practical at the time.

I'm fine with either, but things might be breaking in either direction

**Comment by Ehesp** [comment] 2024-03-01 22:37
Thanks. I've managed to work around this error now so things are back to working again.

I'm still pretty confused about prerendering pages with cloudflare pages though - it's in server mode (docs suggest you should use hybrid), the pages are served statically, but the middleware still seems to run?

Am I doing something which isn't intended (or supposed to work)?

**Comment by lilnasy** [comment] 2024-03-01 22:55
The middleware runs whenever a page is being rendered. For static projects and prerendered pages, that's during build; and for SSR projects and on-demand rendered pages, that's when the page is requested.

https://docs.astro.build/en/guides/middleware/

https://docs.astro.build/en/basics/rendering-modes/

**Comment by lilnasy** [comment] 2024-03-07 17:14
@Ehesp There haven't been any other reports of this being a problem. I'm inclined to close this issue. Do you think there's something about your issue that hasn't been properly considered?

**Comment by Ehesp** [comment] 2024-03-08 07:38
Hey, knowing the cause was destructing the context, I worked around the problem.

**Closed** 2024-03-08 07:39 UTC
Labels: needs discussion
