### ISSUE TITLE
fetch not available in endpoints

### ISSUE THREAD

**Issue by mef** [withastro/astro#6443] opened 2023-03-07 11:32 UTC
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

Node.js adapter

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

Using `fetch` in an endpoint works well in development mode, but fails when executing the build using the node.js SSR adapter (`@astrojs/node@5.0.4`) with node.js version `v16.17.1`.

`npm run build` runs successfully. However, running either `npm run preview`  or `node dist/server/entry.mjs`  fails with the following error message:

```
file:///home/me/development/project-name/dist/server/chunks/pages/all.35ef890f.mjs:3021
        fetch(thirdPartyURL + '?locale=en', fetchOptions)
        ^

ReferenceError: fetch is not defined
    at getData (file:///home/me/development/project-name/dist/server/chunks/pages/all.35ef890f.mjs:2898:8)
    at file:///home/me/development/project-name/dist/server/chunks/pages/all.35ef890f.mjs:2902:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async Module.preview (file:///home/me/development/project-name/node_modules/@astrojs/node/dist/preview.js:13:23)
    at async preview (file:///home/me/development/project-name/node_modules/astro/dist/core/preview/index.js:33:18)
    at async runCommand (file:///home/me/development/project-name/node_modules/astro/dist/cli/index.js:170:22)
    at async cli (file:///home/me/development/project-name/node_modules/astro/dist/cli/index.js:180:5)
```

Possible workarounds:

* upgrade to node.js v18, which ships with an implementation of  `fetch` (flagged as experimental, also based on undici ([details](https://nodejs.org/en/blog/announcements/v18-release-announce/))
* import a node.js implementation of `fetch` from the dependency `undici` - which is installed with Astro - inside the endpoint file:

```
import { fetch } from 'undici'
```

Looking at the [tests for global fetch](https://github.com/withastro/astro/blob/main/packages/astro/test/fetch.test.js), it seems that the support is only tested in astro components and framework components, but not in endpoint files.

Is this the expected behaviour? I would have assumed that fetch would also be supported in endpoint files in SSR mode, just as it works in dev mode.

### Link to Minimal Reproducible Example

[This github repository](https://github.com/mef/astro-fetch-in-endpoint-issue) shows the problem.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-03-07 16:41
@mef are you able to provide an example to reproduce the issue? 

The documentation shows that it's possible to use `fetch` in the endpoints: https://docs.astro.build/en/core-concepts/endpoints/

**Comment by matthewp** [comment] 2023-03-07 21:30
@ematipico it's because we're not applying the polyfill in the Node adapter as we are in others (like Netlify).

**Comment by mef** [comment] 2023-03-08 09:17
Hi,

I just created an astro project demonstrating the issue: https://github.com/mef/astro-fetch-in-endpoint-issue.

When creating it I realized that using `fetch` inside the `get`  function of the endpoint actually works. 

Using `fetch` outside of it crashes the process. My use case implies fetching data outside of the `get` function in order to retrieve data ahead of time, before client requests, since multiple time-consuming requests need to be performed.

**Comment by matthewp** [comment] 2023-03-08 15:18
Just an idea, to ensure that some code always runs first, use dynamic import for the "main".

```js
import "fetch-polyfill";

import("./main");
```

**Comment by natemoo-re** [comment] 2023-06-27 21:22
Great news! I [tried to reproduce this](https://stackblitz.com/edit/github-vmhe4n?file=package.json) on the latest version of Astro ([`2.7.1`](https://github.com/withastro/astro/releases/tag/astro%402.7.1)) and was unable to reproduce the problem. Upgrading `astro` (and all relevant adapters) should fix any issues with polyfill ordering.

This was likely fixed in https://github.com/withastro/astro/pull/7036 by changing our page bundling approach. Please let us know if you run into any issues when upgrading!

**Closed by natemoo-re** 2023-06-27 21:22 UTC
Labels: p4-important
