### ISSUE TITLE
Output URL of index.html with `format: "file"`

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#6167] opened 2023-02-07 18:43 UTC
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a configuration with [format file](https://docs.astro.build/en/reference/configuration-reference/#buildformat) and following pages:

```
foo/index.md
foo/other.md
index.md
```

The build output is confusing:

```
▶ src/pages/index.md
  └─ /index.html                  ✅ This is expected
▶ src/pages/foo/index.md
  └─ /foo.html                    🤯 WTF?
▶ src/pages/foo/other.md
  └─ /foo/other.html              ✅ This is expected
```

How I understood the file format setting is that Astro would not add artificial `index.html` but I didn't expect it to actively remove explicitly created index pages, rename them and move them one level up.

Apart from the confusion of URLs, it actively breaks relative links in the pages as they are not siblings anymore.

I understand that changing this behavior would be a breaking change. Maybe a way to enforce keeping `index.html` would be a better fix. I tried `foo/index.html.md` but got `foo.html.html`, which is even more confusing.

### Link to Minimal Reproducible Example

TBD

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-02-07 21:30
My guess is that this is caused by the fact that the routing implementation doesn't distinguish between the two, so when we go to generate the files it doesn't know the difference. As you said, this would be a breaking change, however wrong it may be.

Given that, I'm going to close the issue as there's nothing actionable to be done about it. I would recommend starting a roadmap discussion to get this changed (which would need to happen in 3.0): https://github.com/withastro/roadmap/discussions

**Closed by matthewp** 2023-02-07 21:30 UTC

**Comment by shishkin** [comment] 2023-02-08 11:11
I created https://github.com/withastro/roadmap/discussions/474 for further discussion.
