### ISSUE TITLE
[Vercel] Setting headers fails on Node18 Fetch API Response

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#5467] opened 2022-11-24 12:30 UTC
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Node 18 introduced [Fetch API Response](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#response). When using it with Astro on Vercel, it fails with error:

```json
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "TypeError: response.headers.raw is not a function",
  "reason": {
    "errorType": "TypeError",
    "errorMessage": "response.headers.raw is not a function",
    "stack": [
      "TypeError: response.headers.raw is not a function",
      "    at setResponse (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/request-transform.js:61:46)",
      "    at Server.handler (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/entrypoint.js:22:11)",
      "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
  },
  "promise": {},
  "stack": [
    "Runtime.UnhandledPromiseRejection: TypeError: response.headers.raw is not a function",
    "    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)",
    "    at process.emit (node:events:525:35)",
    "    at process.emit (node:domain:489:12)",
    "    at emit (node:internal/process/promises:149:20)",
    "    at processPromiseRejections (node:internal/process/promises:283:27)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
  ]
}
```

This is likely due to Vercel adapter [using `headers.raw()`](https://github.com/withastro/astro/blob/55a1b5bb58a07cbf6d86818c28c199751bde03b5/packages/integrations/vercel/src/serverless/request-transform.ts#L90), not available on the [Web API Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) class.

Is there a reason `.raw()` call is required?

### Link to Minimal Reproducible Example

TBD

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by shishkin** [comment] 2022-11-24 12:37
Potentially duplicate of #5461

**Comment by bluwy** [comment] 2022-11-24 16:02
Yeah this is a duplicate of #5461

**Closed by bluwy** 2022-11-24 16:02 UTC
