### ISSUE TITLE
Slot placeholder text renders after manually-entered text instead of being overwritten by it

### ISSUE THREAD

**Issue by bnonn** [withastro/astro#6821] opened 2023-04-12 01:25 UTC
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Any component with a `<slot>` containing placeholder text, will render that placeholder text even when it should be overwritten.

E.g., create SlotTest.astro:

```astro
---
---
<p class="SlotTest">
	<slot>Placeholder text.</slot>
</p>
``` 

Use this component in index.astro:

```astro
---
import SlotTest from '../components/SlotTest.astro';
---
<!-- ... -->
<SlotTest>Custom text.</SlotTest>
```

- Expected rendered text: **Custom text.**
- Actual rendered text: **Custom text.Placeholder text.**

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pdtwok?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bnonn** [comment] 2023-04-12 01:26
I originally created the minimal reproducible example on my own machine in Astro 2.2.1. The StackBlitz example uses Astro 2.2.2.

**Comment by Princesseuh** [comment] 2023-04-12 06:12
Duplicate of https://github.com/withastro/astro/issues/6788

**Closed by Princesseuh** 2023-04-12 06:12 UTC
