### ISSUE TITLE
appear different in the display between dev and pro

### ISSUE THREAD

**Issue by JerryWu1234** [withastro/astro#7300] opened 2023-06-06 05:28 UTC
### What version of `astro` are you using?

last

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

I integrated with Vue and add the `appEntrypoint` for Vue
such as 
```js
vue({
      appEntrypoint: '/src/pages/_app.js',
    }),
```
and I imported the Css in the _app.js file,
the Css can't load in the pro

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tnp3km?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FAc.vue,src%2Fpages%2F_app.js,src%2Flayouts%2FLayout.astro,dist%2Findex.html

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-16 19:43
Closing as a duplicate of https://github.com/withastro/astro/issues/6827

**Closed by natemoo-re** 2023-08-16 19:43 UTC
Labels: - P3: minor bug
