### ISSUE TITLE
🐛 BUG: class:list breaks scoped styles

### ISSUE THREAD

**Issue by jkjustjoshing** [withastro/astro#3208] opened 2022-04-26 18:43 UTC
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux (via Codesandbox), also reproduced on Mac

### Describe the Bug

The following 3 elements should have the same classes, but they do not.
```
<style>
  .test {
      color: red;
  }
</style>
<p class='test'>This is red</p>
<p class={'test'}>This is also red</p>
<p class:list={['test']}>This should be red but isn't</p>
```

The first two have a class of "test", but also a class for scoped styles. The third one has a class of "test", but no class for scoped styles.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-bug-demo-class-list-7rv9vs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nonphoto** [comment] 2022-05-04 20:02
It seems like `class:list` will override all classes on the element as `<p class="a" class:list={["b"]}/>` becomes `<p class="b"/>`

**Comment by Princesseuh** [comment] 2022-05-10 18:04
Closing as a duplicate of https://github.com/withastro/astro/issues/3125

**Closed by Princesseuh** 2022-05-10 18:04 UTC
Labels: bb:investigate
