### ISSUE TITLE
Markdoc: import aliases don't work in markdoc.config.mjs

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#8261] opened 2023-08-29 06:08 UTC
### Astro info

```block
Astro version            v2.10.14
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  Couldn't determine.
Integrations             @astrojs/markdoc
```

### What browser are you using?

Chrome, Safari

### Describe the Bug

In `markdoc.config.mjs`, import aliases like `import { heading } from '~/markdoc/nodes/heading.markdoc.js'` throws an error:

```
[config]  error   Cannot find package '~' imported from ... 
```

Import alias defined in `tsconfig.json:
```json
{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "strictNullChecks": true,
    "baseUrl": "src",
    "paths": {
      "~/*": ["./*"]
    }
  }
}

```

### What's the expected result?

The import alias should resolve as expected (in the example, to `./src/markdoc/nodes/heading.markdoc.js`)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mjht3m?file=markdoc.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-31 21:38
Yes, thanks for opening an issue. I think this is because we load the `markdoc.config.mjs` through a slightly different pipeline than most other files. We probably aren't applying the correct resolution logic for aliases.

**Comment by bluwy** [comment] 2024-01-03 15:56
I think this is expected behaviour. The markdoc config needs to be loaded during the dev server startup, so we don't have access to Vite to handle the aliases. The markdoc config is only loaded as plain JS/TS for now with special support for importing `.astro` files. Closing this for now.

**Closed by bluwy** 2024-01-03 15:56 UTC
Labels: - P3: minor bug, pkg: markdoc
