### ISSUE TITLE
compressHTML in config don't work as expected

### ISSUE THREAD

**Issue by lubowiecki** [withastro/astro#8496] opened 2023-09-11 09:24 UTC
### Astro Info

```block
"Astro                    v3.0.12\nNode                     v18.15.0\nSystem                   Windows (x64)\nPackage Manager          pnpm\nOutput                   static\nAdapter                  none\nIntegrations             @astrojs/tailwind\n                         @astrojs/sitemap"
```

#### I have this config:

```
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";

// https://astro.build/config
export default defineConfig({
  site: "https://www.reksio-wet.pl",
  integrations: [tailwind(), sitemap()],
  compressHTML: true,
});
```

#### and this file index.astro:

```
<html>
  <head></head>
  <body>
    <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint facere 
      inventore nulla explicabo libero delectus voluptatibus, 
      est, ut fugiat recusandae quam, iste natus. 
      Iste, non minus. Beatae sit nisi sint!
    </p>
  </body>
</html>
```

#### When I run astro build I get this file in dist folder:

```
<!DOCTYPE html><html><head><link rel="stylesheet" href="/_astro/rodo.d2d0dbb6.css" /></head><body><p>
Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint facere 
      inventore nulla explicabo libero delectus voluptatibus, 
      est, ut fugiat recusandae quam, iste natus. 
      Iste, non minus. Beatae sit nisi sint!
</p></body></html>
```

### What's the expected result?

dist/index.html

```block
<!DOCTYPE html><html><head><link rel="stylesheet" href="/_astro/rodo.d2d0dbb6.css" /></head><body><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint facere inventore nulla explicabo libero delectus voluptatibus, est, ut fugiat recusandae quam, iste natus. Iste, non minus. Beatae sit nisi sint!</p></body></html>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-qesr2a?file=dist%2Findex.html

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-09-11 10:32
That's not a bug, it's intentional. Newlines inside HTML tags have a meaning actually, You can check this issue, which provides more background: https://github.com/withastro/compiler/issues/815

**Comment by matthewp** [comment] 2023-09-12 18:07
Closing, the intent of this feature is not to make every page output to be only 1 line.

**Closed by matthewp** 2023-09-12 18:07 UTC
Labels: needs response

**Comment by alexander-lozovsky** [comment] 2023-12-29 16:06
@matthewp if it is expected behaviour, maybe worth updating docs https://docs.astro.build/en/reference/configuration-reference/#compresshtml? Because now it says "By default, Astro removes **all** whitespace from your HTML, including line breaks, from .astro components". 

Right now I'm updating an app from Astro v2.8.0 to v3.6.4, and facing some issues due to breaking changes in `compressHTML` handling. Astro v3 preserve line breaks in `.astro` components, while v2 doesn't
