### ISSUE TITLE
`{@html}` broken after hydration since Svelte 4.0.2

### ISSUE THREAD

**Issue by wackbyte** [withastro/astro#7557] opened 2023-07-04 06:39 UTC
### What version of `astro` are you using?

2.7.3

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Linux (NixOS)

### What browser are you using?

Firefox (Librewolf)

### Describe the Bug

Since Svelte 4.0.2, the `{@html}` tag seems to be broken after being hydrated from props. On page load, it appears for a moment, but quickly disappears after hydration.

I think that this may originate from sveltejs/svelte#8880.

### What's the expected result?

The `{@html}` tag should not disappear after being hydrated from props. This is its behavior in Svelte 4.0.1 and earlier.

### Link to Minimal Reproducible Example

https://gitlab.com/wackbyte/astro-svelte-html-hydration-broken

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-07-04 14:38
This should be reported to Svelte. Looks like an unintended breaking change.

I tried debugging this but I can't quite figure out why it's happening. I noticed the `<p>` element that contains the `@html` is being detached here: https://github.com/sveltejs/svelte/blob/800f6c076be5dd87dd4d2e9d66c59b973d54d84b/packages/svelte/src/runtime/internal/Component.js#L145

I difference in your repro with a non-wrapper and wrapper islands, is that we're creating the Svelte component with `hydratable: true` directly vs letting Svelte create that nested Svelte component. We're creating the Svelte component like so:

https://github.com/withastro/astro/blob/7419bb6cf200c51a79eb8fd30e113cf43485cb73/packages/integrations/svelte/client.js#L11-L20

Closing for now as it's not something that can be fixed in Astro.

**Closed by bluwy** 2023-07-04 14:38 UTC

**Comment by dummdidumm** [comment] 2023-07-04 16:08
The problem is that the resulting HTML is invalid. In the reproduction, the result is `<p><p>testing</p></p>`. Nested `p` tags are invalid HTML so the browser shuffles things around in a weird way and then Svelte's hydration mechanism has no chance to pick up things correctly. If you ensure the HTML is valid (surrounding the `{@html content}` with a `div` for example) then the error should go away.

**Comment by wackbyte** [comment] 2023-07-04 20:15
Ah, you're right, it seems to always happen with nested `p` tags. I'll go open an issue in the Svelte repo.

**Comment by wackbyte** [comment] 2023-07-04 20:47
I was just setting up a repo to reproduce it in SvelteKit but it looks like it already got fixed :P
