### ISSUE TITLE
Typescript error on multiline "|"

### ISSUE THREAD

**Issue by hsnfirdaus** [withastro/astro#8701] opened 2023-09-28 21:14 UTC
### Astro Info

```block
Astro                    v3.2.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

For example, i have type like this:
```
export type IconType =
  | "3d"
  | "acrobat"
  | "audio"
  | "binary"
  | "code"
  | "code2"
  | "compressed"
  | "document"
  | "drive"
  | "font"
  | "image"
  | "presentation"
  | "settings"
  | "spreadsheet"
  | "vector"
  | "video";
```
It doesn't give any error / warning in VSCode, but when run it give astro error screen on browser:
```
Unexpected "|"
```

When i add prettier ignore line, so the type keep one line:
```
// prettier-ignore
export type IconType = "3d" | "acrobat" | "audio" | "binary" | "code" | "code2" | "compressed" | "document" | "drive" | "font" | "image" | "presentation" | "settings" | "spreadsheet" | "vector" | "video";

```

The error is gone

### What's the expected result?

The typescript should't give error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-chdwmi?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-09-28 22:01
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2023-09-28 22:01 UTC
Labels: needs triage
