### ISSUE TITLE
Components reused in different pages do not have CSS

### ISSUE THREAD

**Issue by BrunoKrugel** [withastro/astro#6875] opened 2023-04-19 19:04 UTC
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Create a react component that will be reused in two different pages, in `npm run dev` it will work fine but in the deployed page or in `npm run build` and `npm run preview`, the second page will not have any CSS linked to the reused component.

In this example, in the main page the component BigText has the following CSS:

![ray-so-export (4)](https://user-images.githubusercontent.com/30608179/233174035-2e7331ef-a055-4d45-8331-1a99a325d5f8.png)

However, in the second page, the component has the same class `css-1whbz33` but does not have the CSS

![ray-so-export (3)](https://user-images.githubusercontent.com/30608179/233173938-79f4c7ad-9ed0-4a14-a663-0645f4cb51a5.png)

You can check this issue in the following github pages:

https://brunokrugel.github.io/Astroplay/
https://brunokrugel.github.io/Astroplay/Welcome/

Also, in `npm run dev` the first time that I open the main page it works fine, but after the first reload, the component will also not have a CSS, but in the preview you can reload the page and this behavior will not occur.

### Link to Minimal Reproducible Example

https://github.com/BrunoKrugel/Astroplay

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment] 2023-04-21 13:39
Thanks for reporting this!

**Comment by MoustaphaDev** [comment] 2023-04-22 14:04
I made a more [minimal reproduction](https://stackblitz.com/edit/github-jx35jv?file=astro.config.mjs,src%2Fpages%2Findex.astro,src%2Fcomponents%2FBigText.jsx)
I found that when the `sx` prop changes, the styles are injected, otherwise they aren't.

My guess is that it's a weird caching issue happening here, I'll keep investigating later today.

**Comment by tonyski** [comment] 2023-05-15 06:07
This issue has been going on for a long time. What is the current progress? :smiley_cat:

**Comment by bluwy** [comment] 2023-06-22 09:17
I think this is part of https://github.com/withastro/astro/issues/4432#issuecomment-1259062851. Astro doesn't handle CSS-in-JS well yet, and here it shows some quirks with it. From the [material ui docs](https://mui.com/material-ui/guides/server-rendering/#handling-the-request), looks like emotion does has caching that needs to be handled specifically in SSR and client, which is not easily achievable with the APIs we expose today.

I'll close this in favor of #4432 so we could find a middleground with all the CSS-in-JS flavours.

**Closed by bluwy** 2023-06-22 09:17 UTC
Labels: p4-important, library doesn't work
