### ISSUE TITLE
Build error when exporting `Props`-type that uses the `Polymorphic`

### ISSUE THREAD

**Issue by andrejilderda** [withastro/astro#7875] opened 2023-07-31 11:35 UTC
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox

### Describe the Bug

When exporting a type that is using the `Polymorphic`-helper I get a `Expected ">" but found "const"`-build error. For example, this does not work:
```ts
export type Props = Polymorphic<{
  as: "a" | "button";
  variant?: "primary" | "secondary";
}>;
```

First assigning the type to a temp variable DOES work:
```ts
type ComponentProps = Polymorphic<{
  as: "a" | "button";
  variant?: "primary" | "secondary";
}>;

export type Props = ComponentProps;
```

<sup><sub>Thanks for this great framework!</sub></sup>

### What's the expected result?

I expected to be able to export `Props` that uses the `Polymorphic`-type directly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gneamo?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FButton.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-07-31 11:36
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2023-07-31 11:36 UTC
Labels: needs triage
