### ISSUE TITLE
🐛 BUG: solid adapter breaks react components depending on integrations array order

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#4033] opened 2022-07-23 20:33 UTC
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

WIndows

### Describe the Bug

If `solid()` comes before `react()` in the integrations array in `astro.config.ts`, then it breaks react components with the following error 🙃

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
    at Proxy.useState (project\node_modules\react\cjs\react.development.js:1622:21)
    at __vite_ssr_exports__.default (/src/Component.tsx:8:51)
    at Proxy.createComponent (project\node_modules\solid-js\dist\server.cjs:252:15)
    at eval (project/node_modules/@astrojs/solid-js/server.js?v=715ab7fa:27:80)
    at Proxy.renderToString (project\node_modules\solid-js\web\dist\server.cjs:250:86)       
    at renderToStaticMarkup (project/node_modules/@astrojs/solid-js/server.js?v=715ab7fa:27:37)
    at Object.check (project/node_modules/@astrojs/solid-js/server.js?v=715ab7fa:10:19)      
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:183:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e3lhnb?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2022-07-23 20:41
Similar issue, albeit with Preact: https://github.com/withastro/astro/issues/3611

**Comment by tony-sull** [comment] 2022-07-28 13:46
Yep, looks like this will be the same bug.  Closing this out as a duplicate of #3611 so we can prioritize that one based on it seeming to hit SolidJS + any other JSX framework

**Closed by tony-sull** 2022-07-28 13:46 UTC

**Comment by mayank99** [comment] 2022-08-02 23:20
I'm still having this issue in the RC. Here's an updated repro: https://stackblitz.com/edit/github-fpdu2n
