### ISSUE TITLE
HTML Markdown links of URLs are rendered incorrectly

### ISSUE THREAD

**Issue by nmattia** [withastro/astro#7640] opened 2023-07-13 14:17 UTC
### What version of `astro` are you using?

2.8.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Safari

### Describe the Bug

When writing an HTML anchor tag with a URL as content inside a markdown file, the resulting HTML is incorrect.

For instance, the following _markdown_ content:

```md
<a href="https://nmattia.com">https://nmattia.com</a>
```

will render to this HTML:

```html
<p><a href="https://nmattia.com"></a><a href="https://nmattia.com">https://nmattia.com</a></p>
```

And the following _markdown_ content:

```md
<a target="_blank" href="https://nmattia.com">https://nmattia.com</a>
```

will render to this HTML:

```html
<p><a target="_blank" href="https://nmattia.com"></a><a href="https://nmattia.com">https://nmattia.com</a></p>
```

### What's the expected result?

```md
<a target="_blank" href="https://nmattia.com">https://nmattia.com</a>
```

should render to this HTML:

```html
<p><a target="_blank" href="https://nmattia.com">https://nmattia.com</a></p>
```

(plus or minus a `<p>` tag)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mxgmhv?file=src%2Fpages%2Ftest.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-07-17 09:19
This happens because in GFM, links are automatically turned into `<a>` tags. You can actually see the exact same behaviour on GitHub itself, so not really sure if it's our fault or not..

<img width="689" alt="image" src="https://github.com/withastro/astro/assets/3019731/89945f68-0673-41f8-8d7c-8aae4b8df530">

**Comment by sahilsuman933** [comment] 2023-07-19 07:45
Can I work on this issue, @Princesseuh

**Comment by Princesseuh** [comment] 2023-07-19 07:46
> Can I work on this issue, @Princesseuh 

Sure, but as my previous message said, it's possible the issue is not in our repo but in remark-gfm

**Comment by nmattia** [comment] 2023-07-19 08:58
I see @Princesseuh ! I didn't know astro was using GFM.

I think this behavior makes sense on GitHub where the input is not trusted and has to be thoroughly sanitized. For Astro on the other hand, would it be a bad idea to be a bit more lax and allow markdown content to be more powerful?

**Comment by sahilsuman933** [comment] 2023-07-19 09:27
Yes, @Princesseuh. You are correct. The issue is not within the Astro repository. Can you suggest to me any other minor issue that I can work on?

**Comment by Princesseuh** [comment] 2023-07-19 09:43
> Yes, @Princesseuh. You are correct. The issue is not within the Astro repository. Can you suggest to me any other minor issue that I can work on?

A lot of the issues tagged with `p2` are relatively small and should be "easy" to tackle

**Comment by sahilsuman933** [comment] 2023-07-19 09:54
Okay, @Princesseuh . I have one more issue. I am stuck building the Astro in my local environment. I have also tried to build this project on Codespace, but I am facing the same issue. I searched for all possible solutions and found that a similar issue existed in a previous version of Astro, which was resolved using the "yarn build" and "yarn preview" commands. However, these commands no longer work since Astro has shifted from yarn to pnpm.

Can you please help me set up this project?


![image](https://github.com/withastro/astro/assets/34382211/3ec63133-b428-4f90-be21-0fe262825d89)

System Configuration:
![image](https://github.com/withastro/astro/assets/34382211/76ec6afb-ada2-4412-8947-1649c1dc80d3)

![image](https://github.com/withastro/astro/assets/34382211/3089bddd-23b5-4d35-8103-6c4286d3b371)

**Comment by Princesseuh** [comment] 2023-07-19 09:58
I don't see any issues in your screenshot, you're running `dev`, which never stops and watch the projects for changes. If you need further help, I'd recommend posting in the #dev channel on our Discord: https://astro.build/chat as to avoid polluting this issue further.

**Comment by rishi-raj-jain** [comment] 2023-09-18 10:09
Shall we be closing this?

**Comment by bluwy** [comment] 2023-10-13 14:26
Yeah, closing this as it's normal GFM behaviour. We can't change it from the outside.

**Closed by bluwy** 2023-10-13 14:26 UTC
Labels: feat: markdown, - P3: minor bug
