### ISSUE TITLE
`astro check` does not seem to consider React integration

### ISSUE THREAD

**Issue by imballinst** [withastro/astro#9451] opened 2023-12-17 10:35 UTC
### Astro Info

```block
➜  /workspace git:(master) yarn astro info
yarn run v1.22.19
$ astro info
Astro                    v4.0.6
Node                     v18.19.0
System                   Linux (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
Done in 1.27s.
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers

### Describe the Bug

I tried to create an Astro with React integration example: https://codesandbox.io/p/devbox/hardcore-allen-3x33sc?file=%2Fpackage.json. When I want to build the thing, it gave me this error below. These are valid JSX in React and I am not sure why these errors showed up.

```
yarn run v1.22.19
$ astro check && astro build
02:40:05 [check] Getting diagnostics for Astro files in /workspace...
src/components/Counter.tsx:22:9 - error ts(2322): Type '{ children: Element; className: string; }' is not assignable to type 'HTMLAttributes'.
  Property 'className' does not exist on type 'HTMLAttributes'.

22    <div className="counter-message">{children}</div>
           ~~~~~~~~~
src/components/Counter.tsx:20:13 - error ts(2322): Type '{ children: string; onClick: () => void; }' is not assignable to type 'ButtonHTMLAttributes'.
  Property 'onClick' does not exist on type 'ButtonHTMLAttributes'. Did you mean 'onclick'?

20     <button onClick={add}>+</button>
               ~~~~~~~
src/components/Counter.tsx:18:13 - error ts(2322): Type '{ children: string; onClick: () => void; }' is not assignable to type 'ButtonHTMLAttributes'.
  Property 'onClick' does not exist on type 'ButtonHTMLAttributes'. Did you mean 'onclick'?

18     <button onClick={subtract}>-</button>
               ~~~~~~~
src/components/Counter.tsx:17:9 - error ts(2322): Type '{ children: any[]; className: string; }' is not assignable to type 'HTMLAttributes'.
  Property 'className' does not exist on type 'HTMLAttributes'.

17    <div className="counter">
```

I also posted similar question on Discord [here](https://discord.com/channels/830184174198718474/1185409843931140217/1185409843931140217) and there seems to be another person who said that this also happens on Solid as well (and not only React).

### What's the expected result?

`astro check` should properly respect React integration, so that `onSubmit` and other JSX-based HTML attributes like `className`, `onClick` are considered valid.

I have `astro check` for my personal website as well, but it is using an older versions (`astro@3.4.0` with `@astrojs/check@0.2.1`), which seems to still work normally: https://github.com/imballinst/imballinst.dev/blob/main/package.json#L8.

So maybe something happened between that version and the current version that caused this kind of issue.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/hardcore-allen-3x33sc?file=%2Fpackage.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rigel772** [comment] 2023-12-17 10:55
same problem here, I am getting ts errors like:
```
  Property 'className' does not exist on type 'AnchorHTMLAttributes'.

22       <a href={href} className={styles.card}>
```
```
  Property 'className' does not exist on type 'HTMLAttributes'.

30       <p className={styles.name}>{name}</p>
```
```
  Property 'key' does not exist on type 'IntrinsicAttributes & Props'.

113               key={`${refIndex}-${slugify(item.data)}`}
```
... with typical react map it errors the key attribute...

**Comment by Rigel772** [comment] 2023-12-17 11:06
in my case the problem appeared after upgrading from astro 3 to astro 4
last successfull build with:
```
19:51:46.425 | dependencies:
19:51:46.425 | + @astrojs/check 0.2.1
19:51:46.425 | + @astrojs/rss 3.0.0
19:51:46.425 | + @resvg/resvg-js 2.4.1
19:51:46.426 | + astro 3.1.3
19:51:46.426 | + fuse.js 6.6.2
19:51:46.426 | + github-slugger 2.0.0
19:51:46.426 | + remark-collapse 0.1.2
19:51:46.426 | + remark-toc 9.0.0
19:51:46.426 | + satori 0.10.8
19:51:46.426 | + typescript 5.2.2
19:51:46.427 |  
19:51:46.427 | devDependencies:
19:51:46.427 | + @astrojs/react 3.0.2
19:51:46.427 | + @astrojs/sitemap 3.0.0
19:51:46.427 | + @astrojs/tailwind 5.0.0
19:51:46.427 | + @divriots/jampack 0.20.2
19:51:46.427 | + @types/github-slugger 1.3.0
19:51:46.428 | + @types/react 18.2.22
19:51:46.428 | + @typescript-eslint/parser 6.7.3
19:51:46.428 | + astro-eslint-parser 0.15.0
19:51:46.428 | + commitizen 4.3.0
19:51:46.428 | + cz-conventional-changelog 3.3.0
19:51:46.428 | + eslint 8.50.0
19:51:46.428 | + eslint-plugin-astro 0.29.0
19:51:46.429 | + husky 8.0.3
19:51:46.429 | + lint-staged 14.0.1
19:51:46.429 | + prettier 3.0.3
19:51:46.429 | + prettier-plugin-astro 0.12.0
19:51:46.429 | + react 18.2.0
19:51:46.429 | + react-dom 18.2.0
```
and following confing does not build:
```
 "dependencies": {
    "@astrojs/check": "^0.3.3",
    "@astrojs/mdx": "^2.0.1",
    "@astrojs/rss": "^4.0.1",
    "@astrojs/ts-plugin": "^1.3.1",
    "@resvg/resvg-js": "^2.6.0",
    "@types/react-dom": "^18.2.18",
    "astro": "^4.0.6",
    "fuse.js": "^6.6.2",
    "github-slugger": "^2.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "remark-collapse": "^0.1.2",
    "remark-toc": "^9.0.0",
    "satori": "^0.10.11",
    "typescript": "^5.3.3"
  },
  "devDependencies": {
    "@astrojs/react": "^3.0.7",
    "@astrojs/sitemap": "^3.0.3",
    "@astrojs/tailwind": "^5.0.3",
    "@divriots/jampack": "^0.20.2",
    "@types/github-slugger": "^1.3.0",
    "@types/react": "^18.2.45",
    "@typescript-eslint/parser": "^6.14.0",
    "astro-eslint-parser": "^0.15.0",
    "commitizen": "^4.3.0",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^8.56.0",
    "eslint-plugin-astro": "^0.29.1",
    "husky": "^8.0.3",
    "lint-staged": "^14.0.1",
    "prettier": "^3.1.1",
    "prettier-plugin-astro": "^0.12.2"
  },
```

**Comment by Rigel772** [comment] 2023-12-17 11:51
I reverted the code to last week (building ok) commit in hope it will be ok but the errors persist...

**Comment by imballinst** [comment] 2023-12-17 13:50
> I reverted the code to last week (building ok) commit in hope it will be ok but the errors persist...

@Rigel772 that's curious, you mentioned that the reverted code was OK during the build stage, but the errors persist? Any chance some dependencies/cache stuff linger in the `node_modules` (or equivalent)?

**Comment by Princesseuh** [comment] 2023-12-17 13:58
Duplicate of https://github.com/withastro/language-tools/issues/727

**Closed by Princesseuh** 2023-12-17 13:58 UTC
Labels: needs triage
