### ISSUE TITLE
[@astrojs/image] 'picture' css selector is ignored in <style>, unless <style is:global>

### ISSUE THREAD

**Issue by paulrudy** [withastro/astro#5481] opened 2022-11-26 08:00 UTC
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using `<Picture />` from the @astrojs/image integration, 'picture' as a css selector is ignored in <style>. Children (e.g. `picture img`) are also ignored.

Setting `<style is:global>` forces the selector not to be ignored.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gdrvd6?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment] 2022-11-26 17:44
This is normal I guess because styles are scoped to your component by default, thus the styles applied to the `picture` **element** won't select the `picture` element which is  in `<Picture>` **component**

**Comment by paulrudy** [comment] 2022-11-26 18:13
Ok, that makes sense. But then why does the `<Image />` component respond to the `img` css selector?

**Comment by bluwy** [comment] 2022-11-28 08:30
`img` currently work because it's passed down [here](https://github.com/withastro/astro/blob/5fa12852399e36ad88e6131502bd45971dad9820/packages/integrations/image/components/Picture.astro#L70), which means the styles are indirect applied. But generally selectors in `<style>` can't target Components so if needed you can pass a class to the `Picture`/`Image` component, or use deep styling like:

```css
.wrapper > :global(picture) {
  color:red;
}
```

```html
<div class="wrapper">
  <Picture />
</div>
```

Closing as the `img` bug is a duplicate of https://github.com/withastro/astro/issues/5112

**Closed by bluwy** 2022-11-28 08:30 UTC
