### ISSUE TITLE
🐛 BUG: buildOptions.site is partially respected

### ISSUE THREAD

**Issue by vhollo** [withastro/astro#2751] opened 2022-03-10 08:31 UTC
### What version of `astro` are you using?

0.23.6

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Set buildOptions.site = http://example.com/blog

1) As for the root path
- /blog/ is working, 
- /blog is 404.

2) For static assets
- /images/penguin.png is 404,
- /blog/images/penguin.png is 404.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xnn2ws?devtoolsheight=33&file=src/pages/index.astro

**Comment by X7md** [comment] 2022-03-10 09:38
I think you need to use `projectRoot` 

https://docs.astro.build/en/reference/configuration-reference/#site

**Comment by RafidMuhymin** [comment] 2022-03-10 15:02
The biggest issue I am seeing is that the `buildOptions.site` config is not even respected at build. I was able to reproduce it in the official [`subpath`](https://stackblitz.com/github/withastro/astro/tree/latest/examples/subpath) starter.

**Comment by SgiobairOg** [comment] 2022-03-14 23:51
Think I'm also seeing symptoms of this issue. Following instructions to deploy to github pages results in broken styles and scripts. None of the URLs receive the buildOptions.site domain and are relative to root.

Repository here: https://github.com/SgiobairOg/japan-days
Pages: https://sgiobairog.github.io/japan-days/

If you inspect you can see for the index.css in assets, the root folder was added. But for the stylesheets in /style, nothing is added. If I edit those links in the dev tools to be "./styles/..." they work.

Think it's probably the same root cause, but let me know if this should be a separate issue.

Version is 0.24.0

**Comment by delucis** [comment] 2022-03-22 11:25
Just wanted to flag that this big is related to this issue: https://github.com/withastro/astro/issues/2409

**Comment by tony-sull** [comment] 2022-04-18 15:22
Closing this to use the #2409 as the primary since it's the oldest issue related to `base` begin ignored in `astro build` :+1:

**Closed by tony-sull** 2022-04-18 15:22 UTC
