### ISSUE TITLE
Defining a typescript type in an astro file can break the page

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#12179] opened 2024-10-10 13:51 UTC
### Astro Info

```block
Astro                    v4.16.0
Node                     v20.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When writing the following type in the index.astro file, the page breaks.

```
export type MyType = 
  | "hi"
  |."bye";
```

It has to do with indenting. If it is on 1 line or the | sticks to the left side there is no error. This is a problem because prettier format it this way.

### What's the expected result?

No error

### Link to Minimal Reproducible Example

https://github.com/RogierdeRuijter/astro-type

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-10-10 16:14
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2024-10-10 16:14 UTC
Labels: needs triage
