### ISSUE TITLE
🐛 BUG: unexpected compilation dom result

### ISSUE THREAD

**Issue by MustafaWael** [withastro/astro#2559] opened 2022-02-09 08:31 UTC
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

# There is an unexpected behavior after adding a html select element with options using array higher order function (map).

when adding the **html select element** with options using array higher order function (map) the **NEXT** element transformed as a text in the DOM (browser)

but it works fine after adding an empty comment after last option or not using an array higher order function (map).

``` astro
---
const langs = [
  'HTML',
  "CSS",
  "Javascript",
  "React.js",
  "Next.js"
]
---

<select>
  <!-- Default option -->
  <option value='all'>all</option>

  <!-- works fine if options are typed as hardcoded or adding an empty comment after this line -->
  {langs.map(lang => <option value={lang}>{lang}</option>)}
</select>

<!-- this elements transformed to text -->
<p>p tag for testing</p>
<p>Another p tag for testing</p>

```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-7wtvpz?file=src%2Fpages%2Findex.astro

**Comment by MustafaWael** [comment] 2022-02-11 00:21
> Can you rename the issue please @MustafaWael ?

ah sorry, i forgot to give it a name, I renamed it now

**Comment by tony-sull** [comment] 2022-02-15 12:19
Closing as a duplicate of [#2559](https://github.com/withastro/astro/issues/2559) and including the example above as another reproduction for there

Thanks for filing this issue with a good repro example!  This may be a tricky one to track down and every example should help narrow it down a bit :+1:

**Closed by tony-sull** 2022-02-15 12:19 UTC
