### ISSUE TITLE
`astro check` checks `dist`

### ISSUE THREAD

**Issue by huseeiin** [withastro/astro#11671] opened 2024-08-11 12:04 UTC
### Astro Info

```block
Astro                    v4.13.2
Node                     v22.4.1
System                   Linux (x64)
Package Manager          bun
Output                   server
Adapter                  my-adapter
Integrations             @astrojs/svelte
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

build for the first time
then run `build` package.json script again
now `astro check` will check files in `dist` folder

### What's the expected result?

it should exclude `dist`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t2mccw?file=package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-08-11 12:35
Duplicate of https://github.com/withastro/language-tools/issues/643

**Closed by Princesseuh** 2024-08-11 12:35 UTC
Labels: needs triage
