### ISSUE TITLE
Lottie-web working on dev mode, but in production it stop working

### ISSUE THREAD

**Issue by rodrigo-mahamud** [withastro/astro#5529] opened 2022-12-05 10:36 UTC
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

Npm

### What operating system are you using?

Windows

### Describe the Bug

Ihave this issue when i build the production version, in dev environment lottie works perfectly, but when i build the production version this errors appears and no longer work.

https://user-images.githubusercontent.com/76396937/205616329-84f673c8-af1b-46b8-bf81-fb4f6989894c.mp4

![image](https://user-images.githubusercontent.com/76396937/205616461-7f4cd98f-b3eb-4b26-a832-4c6b364ea188.png)

### Link to Minimal Reproducible Example

https://ephemeral-souffle-654544.netlify.app/portafolio/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2022-12-05 12:32
I'm seeing `TypeError: undefined is not an object (evaluating 'm[i].T=r[2]')` when visiting the website. Could you test disabling minify to see where that's coming from?

Also the network log showed that `final.mp4` isn't available (404), perhaps that's the issue too?

It's hard to debug this one without a reproduction.

**Comment by matthewp** [comment] 2023-02-08 19:53
Closing since there isn't a response. Please reopen with more info if you can, thanks!

**Closed by matthewp** 2023-02-08 19:53 UTC
Labels: needs response, library doesn't work
