### ISSUE TITLE
🐛 BUG: "PostCSS configuration was not passed or is invalid" with svelte renderer

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#2273] opened 2021-12-24 16:10 UTC
### What version of `astro` are you using?

0.22.1

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

When rendering a page with a svelte component, the following error will show (even if I am not using postcss) : 
```
[svelte-preprocess] PostCSS configuration was not passed or is invalid. If you expect to load it from a file make sure to install "postcss-load-config" and try again.

Error: Cannot find module 'postcss-load-config'
Require stack:
- /sandbox/node_modules/svelte-preprocess/dist/transformers/postcss.js
- /sandbox/node_modules/svelte-preprocess/dist/autoProcess.js
- /sandbox/node_modules/svelte-preprocess/dist/index.js
```

This will not fail the build and the component seems to function as normal, but still floods the console.

### Link to Minimal Reproducible Example

Astro.new svelte starter example (https://codesandbox.io/s/github/snowpackjs/astro/tree/latest/examples/framework-svelte)

**Comment by Tc-001** [comment] 2021-12-24 16:14
I could reproduce it on the starter, but it seems that after caching for the first time the error will not show.
Forking the sandbox starts a new instance and reproduces it (same with restarting from the server control panel)

**Comment by SteveALee** [comment] 2022-01-01 19:57
Ditto but different config. I copied the svelte example

What version of astro are you using?
0.22.3

What package manager are you using?
npm

What operating system are you using?
WSL (in VS Code terminal)

**Comment by jonathantneal** [comment] 2022-01-21 23:04
Verified in 0.22.17

**Comment by ludwigschubert** [comment] 2022-01-23 08:23
## Workaround

To get rid of the warning, I added `"postcss-load-config": "^3.1.1"` to `devDependencies`, and added an effectively empty `postcss.config.js`:
```js
module.exports = {
  plugins: []
};
```
(I used that opportunity to learn about postcss and ended up adding the `autoprefixer` plugin. \o/)

## Link to Minimal Reproducible Example

https://codesandbox.io/s/sharp-breeze-j782n?file=/postcss.config.js

**Comment by natemoo-re** [comment] 2022-03-03 22:13
Sorry this took so long, will be fixed in https://github.com/withastro/astro/pull/2715

**Comment by natemoo-re** [comment] 2022-03-04 21:24
Sorry y'all. Had to revert #2715 due to this change breaking some things in the new static build mode in astro 0.24. I'm hoping to (re)fix this ASAP.

**Comment by jonburger** [comment] 2022-03-14 22:14
Probably doesn't help, but I'm experiencing the same issue today using:

0.24.0 / npm 7.20.3 / MacOS

**Comment by FredKSchott** [comment] 2022-03-15 22:42
Sorry about this one, yall! 
FYI a short-term fix that you can run for this was outlined here:

```
1. `npm install postcss-load-config`
2. `echo "module.exports = {}" > postcss.config.js`
```

**Closed** 2022-03-15 23:32 UTC
