### ISSUE TITLE
manual i18n routing not working with prerendered 404 page

### ISSUE THREAD

**Issue by stefanprobst** [withastro/astro#10785] opened 2024-04-13 09:36 UTC
### Astro Info

```block
Astro                    v4.6.1
Node                     v20.12.2
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

with the recently added `manual` i18n routing strategy, and [this middlwware](https://github.com/stefanprobst/issue-astro-i18n-manual/blob/main/src/middleware.ts), i want to redirect the "/" root route to the default locale "/en".

in a production build, when the `src/pages/404.astro` file has `export const prerender = false`, i get the expected 307 redirect. however, when `404.astro` has `export const prerender = true` i get a 404.

---

to reproduce:

1. `git clone git@github.com:stefanprobst/issue-astro-i18n-manual.git && cd issue-astro-i18n-manual && pnpm install`
2. `pnpm run build`
3. `pnpm run preview`
4. `curl -i http://localhost:3000` which prints: "HTTP/1.1 404 Not Found"

now, change the prerender mode in 404.astro to `false`:

1. `sed -i "s/prerender = true/prerender = false/" src/pages/404.astro`
2. `pnpm run build`
3. `pnpm run preview`
4. `curl -i http://localhost:3000` which prints: "HTTP/1.1 307 Temporary Redirect"

### What's the expected result?

root route "/" should be redirected to default locale "/en" when `404.astro` has `export const prerender = true` (or with `output: "hybrid"`).

### Link to Minimal Reproducible Example

https://github.com/stefanprobst/issue-astro-i18n-manual

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2024-06-14 18:07
@ascorbic this could be a fun one to understand the i18n logic. @ematipico can help you with this one possibly.

**Comment by ascorbic** [comment] 2024-06-17 10:05
Hey! It looks like the issue here is that middleware isn't being invoked on the request for `/`, so the manual redirect isn't happening. For prerendered pages, middleware is run at build time by default. It's only run at request time for SSR routes, or if you are using edge middleware. You have no `index.astro` in the root, so it's not prerendered - meaning the middleware is not run. For that reason, when a request comes for it at runtime it's not found. Because the 404 is a prerendered route, the middleware isn't invoked at runtime, meaning it can't intercept the request and redirect it.

In your case where you only want to redirect the root `/` requests, the simplest fix is to create a prerendered `index.astro` in the root. This will run the middleware at build time and generate the correct redirect.

For a more general solution if you want the middleware to run for _all_ 404 requests, either have to not prerender the 404, or use edge middleware (which runs at runtime, even on prerendered pages).

The bug here is that in dev, middleware is running for 404 routes even if they're marked as prerendered. I will open an issue to fix that so the behaviour is the same.

**Comment by ascorbic** [comment] 2024-06-17 10:06
I'm going to close this because it's behaving as expected, but will open a separate issue for the dev behaviour. Thanks for the comprehensive report and excellent reproduction.

**Closed by ascorbic** 2024-06-17 10:06 UTC
Labels: - P3: minor bug, feat: i18n

**Comment by stefanprobst** [comment] 2024-06-17 14:12
@ascorbic thanks for your response!

one question: what do you mean by "edge middleware"? i am deploying with the nodejs adapter, and using astro's "hybrid" rendering.

**Comment by ascorbic** [comment] 2024-06-17 15:15
It only applies to some platforms such as Netlify and Vercel, that support running middleware in edge functions. It's not somethign that can be done with the Node adapter
