### ISSUE TITLE
`class` and `class:list` props are rendered incorrectly

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#7942] opened 2023-08-03 22:05 UTC
### What version of `astro` are you using?

v2.10.1

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

stackblitz

### What browser are you using?

Arc :)

### Describe the Bug

Astro.props returns unexpected results when accessing `class` and `class:list` props.

### What's the expected result?

I would expect `Astro.props.class` to return a space delimited list of the classes applied to an astro component, omitting the scoping rule changes.

I would expect `Astro.props['class:list']` to either error on access or to be undefined, since `class:list` is a reserved prop / directive for combining classes, its result should reside in `class`.

I would expect passing both `class` and `class:list` to an astro component to result in combining the two props && maybe the astro language tools would lint that this is unexpected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xffh8h?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2023-08-07 20:22
Definitely think we can track this as a duplicate of https://github.com/withastro/astro/issues/7747. Something about `class:list` behavior is not right at the moment. Hoping we can get consensus on the correct behavior and fix it!

**Closed by natemoo-re** 2023-08-07 20:22 UTC
Labels: needs triage
