### ISSUE TITLE
Incorrect TS error on Astro.redirect

### ISSUE THREAD

**Issue by gersomvg** [withastro/astro#11168] opened 2024-05-31 09:26 UTC
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### Describe the Bug

```astro
---
const route = '/page-a';
return Astro.redirect(route, 307);
---

Hello world!
```

Gives this error when using `@astrojs/check`:

```
src/pages/index.astro:4:7 - error ts(6133): 'route' is declared but its value is never read.

4 const route = '/page-a';
        ~~~~~
```

### What's the expected result?

To not get this TS warning. I'm using `strictest` tsconfig which means this is an error and it prevents me from running `astro build` unless I'm disabling TS checks.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-us5tdu?file=src%2Fpages%2Findex.astro

(open new terminal and type `npx astro check`)

**Comment by Princesseuh** [comment] 2024-05-31 12:53
Duplicate of https://github.com/withastro/language-tools/issues/476

**Closed by Princesseuh** 2024-05-31 12:53 UTC
Labels: needs triage
