### ISSUE TITLE
🐛 BUG: inconsistent 127.0.0.1 and localhost in dev and preview

### ISSUE THREAD

**Issue by millette** [withastro/astro#2669] opened 2022-02-27 03:26 UTC
### What version of `astro` are you using?

0.23.2

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Running astro dev, hostname is 127.0.0.1 (and --hostname doesn't do anything) whereas astro preview the hostname is localhost (and here --hostname works as expected - but not yet document <https://github.com/withastro/docs/issues/165>).

There's a suble difference between localhost and 127.0.0.1 depending on OS configuration (IPv4 vs IPv6, etc.)

Note that the example doesn't really help since it's a cli problem.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/gqaiqojag?file=package.json

**Comment by wlto** [comment] 2022-02-27 22:02
Getting a similar issue with `astro dev` as well. I've set `localhost` as the host in my config file but the CLI log still outputs `[astro] Local: http://127.0.0.1:3000/`.

Dig a little deeper and I believe the problem is around this line in core dev file (I'm just taking a look at the built file in `dist` in the boilerplate (via the `npm init astro` command):

<img width="763" alt="CleanShot 2022-02-27 at 16 57 44@2x" src="https://user-images.githubusercontent.com/28908853/155901621-783c9389-063d-4336-bf45-41b858a6fd4f.png">

The log on line 23 outputs `address { address: '127.0.0.1', family: 'IPv4', port: 3000 }`. So it seems like it doesn't respect the host in the Vite config for some reason.

I'm relatively new to open-source development so not sure where to go from here. But just posting this issue here in case it helps. Any insights or advice from the core team would be appreciated. I really like this project so hope I can contribute somehow 😄

**Comment by wlto** [comment] 2022-02-28 02:53
Was looking at the difference between the `preview` and `dev` code. And noticing that the address in `core/preview/index.js` is taking the hostname directly from the config file:

<img width="1223" alt="CleanShot 2022-02-27 at 21 50 14@2x" src="https://user-images.githubusercontent.com/28908853/155915997-c4c1cd4d-59c2-4b80-809e-dff7ed18bda0.png">

Does it make sense if we do something similar for `core/dev/index.js`?

<img width="752" alt="CleanShot 2022-02-27 at 21 52 50@2x" src="https://user-images.githubusercontent.com/28908853/155916224-a9958d39-006e-446e-a75f-c42966610969.png">

**Comment by wlto** [comment] 2022-02-28 22:52
Some more updates. Figured it might be a Vite bug so took a look at their repo and found [this issue](https://github.com/vitejs/vite/pull/7092).

So I'm guessing this is something related to Vite.

**Comment by wlto** [comment] 2022-03-05 22:15
Good news! The PR I linked above https://github.com/vitejs/vite/pull/7092 was just merged to Vite's main branch. Hopefully we can see a new version with the fix soon :)

**Comment by FredKSchott** [comment] 2022-03-11 16:42
Woo! Closing this as an upstream issue. Also, @bholmesdev has been doing some work for v0.24.0 to have an updated CLI output with a new `--host` flag to match Vite's support more closely. Please try it out with `npm install astro@next` and report back if you have any issues!

**Closed by FredKSchott** 2022-03-11 16:42 UTC

**Comment by Blackan06** [comment] 2024-11-20 07:36
You need run astro config set airflow.expose_port true or import code in .astro/config.yaml
airflow:
  expose_port: "true"
