### ISSUE TITLE
Astro `5.1` Vercel Server Islands (404 error)

### ISSUE THREAD

**Issue by mrchantey** [withastro/astro#12807] opened 2024-12-22 00:12 UTC
### Astro Info

```block
Astro                    v5.1.0
Node                     v20.18.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel
Integrations             none
```

### Describe the Bug

Upgrading to `5.1` broke server islands for my deployed vercel app (404 not found).
I'm guessing this is related to `@astrojs/vercel` because `astro dev` works and so does `astro preview` with the node adapter.

Downgrading back to Astro `5.0.3` fixes the issue.

## Error message

```
GET https://bevyhub-nwfn5wvd4-petes-projects-607490fb.vercel.app/_server-islands/SceneList?e=SceneList&p=6206378E2AA7D4943B1A9B8ERr6EJavY%2FQcTfhxEVgYPhHg%2FGv6%2BIL581IbjZrUf6kpi00FN1XNfQ4snx9kCq0jH&s=%7B%7D 404 (Not Found)
```

## Details

`package.json`
```json
"@astrojs/vercel": "^8.0.1",
"astro": "^5.1.0",
```
`astro.config.mts`
```ts
export default defineConfig<never>({
  site: "https://bevyhub.dev",
  adapter: vercelAdapter(),
  output: 'server',
  scopedStyleStrategy: 'attribute',
})
```
`src/pages/discover.astro`
```tsx
---
export const prerender = true
import { ContentLayout } from '@comp-astro/layout'
import { SceneList } from '@comp-astro/content'
import { CircularProgress } from '@design'

---
<ContentLayout>
  <h1>Discover</h1>
  <SceneList server:defer>
    <CircularProgress slot="fallback"/>
  </SceneList>
</ContentLayout>

### What's the expected result?

For vercel server islands to work the same as in `5.0`

### Link to Minimal Reproducible Example

sorry im on the free plan so cant share vercel links

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Trombach** [comment] 2024-12-22 12:09
Duplicate of #12803

**Closed** 2024-12-23 04:27 UTC
Labels: needs triage
