### ISSUE TITLE
Typescript aliases are not working in astro.config.ts

### ISSUE THREAD

**Issue by zokkis** [withastro/astro#9782] opened 2024-01-23 08:33 UTC
### Astro Info

```block
Astro                    v4.2.1
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-purgecss
                         astro-compress
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Using Typescript aliases inside the `astro.config.ts` throws an error. But if I use the same file but a relative/absolute path the File is found and everything works fine.

There is nothing inside the [Docu](https://docs.astro.build/en/guides/configuring-astro/) which describes this behavior, but aliases are essential to typescript and should be supported.

And there is nothing `fancy` in the file, its a normal string-export and as I saied the file dont has any problems, because relative/absolute paths are working.

### What's the expected result?

I would like to have support for [aliases](https://www.typescriptlang.org/tsconfig#paths) even in the config.
I also tried to edit the [vite.config](https://dev.to/tilly/aliasing-in-vite-w-typescript-1lfo), but still the same error.

I don't need any `fancy`-functions, only a import of constants or pure-functions.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-umcujs-lyef16?file=astro.config.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by gitZokki** [comment] 2024-01-23 15:06
After further search, I found the Bug in
https://github.com/withastro/astro/blob/17f27e7cebe612ba38fcee09e35df0a8e0ce86cd/packages/astro/src/core/config/vite-load.ts#L8

after adding: 
```
resolve: {
  alias: {
    '@utils': 'C:/Development/test/squalid-flare/src/utils'
  }
}
```
to the config its working (only for @utils alias)

I thing the tsconfig should be read and the paths should be mapped

**Comment by castarco** [comment] 2024-02-08 16:08
Besides adding the aliases, you also have to set the `"compilerOptions.baseUrl"` option in your `tsconfig.json` file, so the defined aliases can be properly resolved.

**Comment by gitZokki** [comment] 2024-02-08 16:22
> Besides adding the aliases, you also have to set the `"compilerOptions.baseUrl"` option in your `tsconfig.json` file, so the defined aliases can be properly resolved.
> 
> Also, try to not use absolute paths for your aliases, prefer always relative paths.

As written in the Issue, its working but not in the config.ts... and the baseUrl is set. The problem is the vite-config while reading the config.

See #9789

**Comment by matthewp** [comment] 2024-04-03 13:59
Closing as we decided in https://github.com/withastro/astro/pull/9789 not to support this feature as it would deviate from how `astro.config.mjs` works.

**Closed by matthewp** 2024-04-03 13:59 UTC
Labels: pkg: astro, needs discussion, - P2: has workaround

**Comment by dnbkr** [comment] 2024-09-09 09:09
just wanted to add here that, while I respect that the decision not support this has been made, I do have a (imo) common use case that would support the case to make this work

I want my app to insert some data into my database when the server launches. For this, I have been writing an Integration to use the server start hook. My script wants to reuse my app's various typescript modules for database connection etc. and they all use relative imports. This is not possible because of this limitation with the config file.

**Comment by zokkis** [comment] 2024-09-09 14:14
https://zokki.net/en/blog/ts-paths-aliases-in-astro-config/

I wrote a short Tutorial on how to add the support by yourself.

**Comment by andrew-braun** [comment] 2025-11-04 07:33
@zokkis Thanks for this! Added it using `pnpm patch` and it worked just fine :)

In my case, I'm currently storing a lot of my page data directly in files next to the pages, including redirect information about the page. I pull from those files to dynamically assemble my redirect list. Those data files in turn are importing things from elsewhere, so I'd either have to convert a bunch of random things back to relative paths, write a pre-build script that gathers my redirects for me, or manually maintain the redirect list. The pre-build script is viable, but having relative imports in the config file is just super convenient :)

Update: still works in v6--you just have to redo the patch as the vite-load.js file has been changed a bit.
