### ISSUE TITLE
ElementPlusError: [IdInjection] Looks like you are using server rendering, you must provide a id provider to ensure the hydration process to be succeed

### ISSUE THREAD

**Issue by catch6** [withastro/astro#6726] opened 2023-04-01 08:12 UTC
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac(m1 pro)

### What browser are you using?

Microsoft Edge

### Describe the Bug

When I run "pnpm run dev", the console throws an error 
```
ElementPlusError: [IdInjection] Looks like you are using server rendering, you must provide a id provider to ensure the hydration process to be succeed
usage: app.provide(ID_INJECTION_KEY, {
  prefix: number,
  current: number,
})
    at Object.debugWarn (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/element-plus@2.3.2_vue@3.2.47/node_modules/element-plus/lib/utils/error.js:19:44)
    at Object.useId (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/element-plus@2.3.2_vue@3.2.47/node_modules/element-plus/lib/hooks/use-id/index.js:22:11)
    at setup (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/element-plus@2.3.2_vue@3.2.47/node_modules/element-plus/lib/components/form/src/form-item2.js:41:29)
    at callWithErrorHandling (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+runtime-core@3.2.47/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:171:22)
    at setupStatefulComponent (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+runtime-core@3.2.47/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7194:29)
    at setupComponent (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+runtime-core@3.2.47/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7149:11)
    at renderComponentVNode (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+server-renderer@3.2.47_vue@3.2.47/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:628:17)
    at renderVNode (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+server-renderer@3.2.47_vue@3.2.47/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:22)
    at renderVNodeChildren (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+server-renderer@3.2.47_vue@3.2.47/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:770:9)
    at renderVNode (/Users/zhanghao/Projects/VSCodeProjects/auth/node_modules/.pnpm/@vue+server-renderer@3.2.47_vue@3.2.47/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:747:13)
```
but I have configured ID_INJECTION_KEY according to the official SSR recommendation of element-plus.
astro.config.mjs:
```js
integrations: [tailwind(), vue({
  appEntrypoint: '/src/pages/_app'
})],
```
/src/pages/_app.ts
```ts
import type { App } from 'vue'
import { ID_INJECTION_KEY } from 'element-plus'

export default (app: App) => {
  app.provide(ID_INJECTION_KEY, {
    prefix: 1024,
    current: 0,
  })
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3kxjxl?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-04-28 17:26
Duplicate of https://github.com/withastro/astro/issues/6827, going to fix there.

**Closed by matthewp** 2023-04-28 17:26 UTC
