### ISSUE TITLE
@astrojs/image local images are not processed at build time in SSR

### ISSUE THREAD

**Issue by Wykks** [withastro/astro#5137] opened 2022-10-21 09:19 UTC
### What version of `astro` are you using?

1.5.2 (@astrojs/image 0.10.0)

### Are you using an SSR adapter? If so, which one?

@astrojs/node (2.0.1)

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Hi!

When using @astrojs/image in SSR mode, local images should be processed at build time. Currently they are processed at **every** request, and not even cached. Which is super slow.

Reproduction notes :

I moved an image to src/assets/cereal.jpg.
Statically imported in `ProductListing.astro` like this 

`import cereal from '../assets/cereal.jpg'; `

Used Picture component to have it converted in multiple formats

Then you can run `npm run build` and `npm run server`, disable the browser cache, and at every refresh, the image take almost 1sec to show because it's being processed from scratch every time.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qgrgl7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2022-11-16 20:36
Closing as a duplicate of https://github.com/withastro/astro/issues/5008, we hope to work on this soon.

**Closed by matthewp** 2022-11-16 20:36 UTC
