### ISSUE TITLE
🐛 BUG: HMR not working for hoisted scripts

### ISSUE THREAD

**Issue by flowen** [withastro/astro#3424] opened 2022-05-23 18:34 UTC
### What version of `astro` are you using?

1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

HMR doesn't work. 
I need to restart the server for it to compile

### Link to Minimal Reproducible Example

https://codesandbox.io/s/angry-elbakyan-gptwcm
[Here's a repo](https://github.com/flowen/astro-bug)
### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment] 2022-05-23 20:59
Confirmed, looks like inline scripts aren't rebuilt during `astro dev`.  I was thinking that would have been fixed in [#3336](https://github.com/withastro/astro/pull/3336) 🤔

**Comment by Vibeesarma** [comment] 2022-05-24 12:26
there is one issue I found button on click event not worked

**Comment by tusamni** [comment] 2022-05-24 18:12
Seems like I have this as well on a Windows 11 machine.

**Comment by tony-sull** [comment] 2022-05-24 20:52
Working on this issue as we speak 👍  I actually found the fix for OS X and Linux pretty quickly, for some reason it's still not working on Windows though so I'm hoping to find that fix as well before sending the PR out for review

**Comment by flowen** [comment] 2022-05-30 16:25
> Working on this issue as we speak 👍 I actually found the fix for OS X and Linux pretty quickly, for some reason it's still not working on Windows though so I'm hoping to find that fix as well before sending the PR out for review

Hi Tony, any update on this fix? If you're busy with other stuff, would it be possible to push the OSX fix or in a patch or smth? That way I could continue my project, because right now I'm just not able to work without reworking a lot of stuff. Hope that's okay :)

**Closed** 2022-05-31 18:13 UTC
Labels: p4-important, s1-small, hmr
