### ISSUE TITLE
🐛 BUG: v0.24: "dist" directory cannot be a symbolic link (0.23.x is ok)

### ISSUE THREAD

**Issue by patrickdung** [withastro/astro#2788] opened 2022-03-14 19:11 UTC
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Previously on v0.23.x (non experimental build) the directory ./dist is a symbolic link to /var/www/html
The build run fine.

Now using v0.24 (new static build), the build failed. It is giving out many nodeJS modules not found messages...

Workaround:
1) remove ./dist (symbolic link) and create it as a directory
2) configure astro.config.mjs to write to /var/www/html as the ```dist``` destination
Edit 2: this only works for v0.24 (legacy-build), not the new static build

### Link to Minimal Reproducible Example

N/A

Edit: it's 0.24 *new static build* have problem, can't use symbolic link for ./dist

**Comment by natemoo-re** [comment] 2022-03-16 14:59
Interesting! @matthewp might be able to take a look.

**Comment by FredKSchott** [comment] 2022-03-16 22:36
Duplicate of https://github.com/withastro/astro/issues/2817, both of these are caused by the same issue. Tracking a fix there!

**Closed by FredKSchott** 2022-03-16 22:36 UTC
