### ISSUE TITLE
getStaticPaths doesn't support Allman style braces

### ISSUE THREAD

**Issue by swift502** [withastro/astro#4685] opened 2022-09-08 20:47 UTC
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The following syntax of the [getStaticPaths](https://docs.astro.build/en/reference/api-reference/#getstaticpaths) function causes an error:

```astro
export async function getStaticPaths()
{  // <-- Note that the opening brace is on a new line
  return [
    { params: { id: '1' } },
    { params: { id: '2' } },
    { params: { id: '3' } }
  ];
}
```

Putting the opening brace on a new line causes the following error:

![image](https://user-images.githubusercontent.com/24359130/189223219-92221f01-9c71-4688-9ea0-5c088f9cadf0.png)

This error message is suggesting that the function doesn't exist, but it does exist under valid JS syntax.
Regardless of people's coding style preference, I think that any valid JS syntax should be supported, and that this error doesn't make much sense in this case.

Let me know what you think!
Jan

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-aatmky?file=src/pages/fruits/[fruit].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-09-08 20:58
Thanks for opening an issue! This isn't us trying to enforce a particular coding style, it's just a compiler bug! I'm surprised nobody ran into this earlier.

I'll try to get a fix in the compiler ASAP.

**Comment by swift502** [comment] 2022-09-08 21:06
I look forward to seeing how this is fixed! I tried to figure out how the validation works but couldn't find anything. 😅

**Comment by JohnDaly** [comment] 2022-09-18 08:06
I think the compiler issue might be caused by the `HoistExports` function of `js_scanner.go`?

## Input:
```ts
const foo = 'bar';
export async function getStaticPaths()
{  // <-- Note that the opening brace is on a new line
  return [
    { params: { id: '1' } },
    { params: { id: '2' } },
    { params: { id: '3' } }
  ];
}
```

## Output:
The body of `getStaticPaths` is not being hoisted here
```ts
export async function getStaticPaths()
const foo = 'bar';
{
  return [
    { params: { id: '1' } },
    { params: { id: '2' } },
    { params: { id: '3' } }
  ];
}
```

My guess is that [this check](https://github.com/withastro/compiler/blob/4d815f1ee891a5f458416676e813a1818e8b34f1/internal/js_scanner/js_scanner.go#L89) for a `LineTerminatorToken` might be the reason that the body of the function is not being hoisted. When the opening brace is on the next line, the count of `pairs['{']` will be 0 when the `LineTerminatorToken` is encountered

**Comment by Enteleform** [comment] 2022-09-18 08:22
I had created an issue for this and it was moved to:
https://github.com/withastro/compiler/issues/512

**Comment by natemoo-re** [comment] 2022-09-28 15:51
This is fixed by https://github.com/withastro/compiler/pull/523, which should hopefully go out in the next release.

**Comment by swift502** [comment] 2022-09-28 16:08
I'll upgrade as soon as the next release comes out, test it out and close this issue.

**Closed** 2022-09-28 19:18 UTC
Labels: p5-urgent

**Comment by natemoo-re** [comment] 2022-09-28 20:19
Thanks @swift502! Sorry, GitHub closes linked issues automatically. Feel free to reopen if this is *not* fixed in the next version.

**Comment by swift502** [comment] 2022-09-28 20:21
@natemoo-re Of course that'll work too! 😄
