### ISSUE TITLE
Solid Component renders without text when it is in MDX and the layout is nested.

### ISSUE THREAD

**Issue by pontakornth** [withastro/astro#6907] opened 2023-04-25 08:32 UTC
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Edge

### Describe the Bug

If I placed a Solid component inside `MDX` file and the layout is nested, the text cannot be rendered if the text is from interactive part of Solid (e.g Signal or props)

To reproduce, I provide minimal reproducible example. However, it only occurs on production.

### Steps 
1. Run `npm run build` on Stackblitz
2. Run `npm run preview` to preview the build.

Current workaround is to have a simple empty component imported somewhere in an `.astro` file as it somehow fixes the issue.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-wxe3b9?file=src%2Fcomponents%2FCounter.jsx,src%2Flayouts%2FBaseLayout.astro,src%2Flayouts%2FBlogPost.astro,package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by erikasby** [comment] 2023-07-12 17:20
I set up a dev environment locally and checked the stackblitz example you provided and it works perfectly fine. (Windows; Astro v2.8.1)

As I understand the build version should work the same as your production one, so not sure how to test the bug then, or maybe it is already fixed in the later versions.

**Comment by bluwy** [comment] 2023-12-27 14:22
I also can't reproduce this now after upgrading all the packages to latest. I'll close this one for now as fixed, but if I'm mistaken please let us know and we can re-open it.

**Closed by bluwy** 2023-12-27 14:22 UTC
Labels: pkg: solid, - P3: minor bug
