### ISSUE TITLE
@astrojs/rss uses trailing slash on home page when it shouldn't

### ISSUE THREAD

**Issue by patrickreiner** [withastro/astro#10994] opened 2024-05-09 19:02 UTC
### Astro Info

```block
Astro                    v4.8.2
Node                     v20.12.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/sitemap
```

### Describe the Bug

In my astro.config.mjs I set:

export default defineConfig({
...
trailingSlash: 'never',
})

and in my vercel.json I set:

{
"cleanUrls": true,
...
"trailingSlash": false
}

and in my rss.xml.js I set:

export async function GET(context) {
  return rss({
    trailingSlash: false,
  })
}

and yet, the RSS feed still puts a slash on the home page, viewable here:

http://astro-rss-trailing-slash.patrickreiner.com/rss.xml

### What's the expected result?

RSS home page should not have a trailing slash.

Should be:

<link>https://astro-rss-trailing-slash.patrickreiner.com</link>

Not:

<link>https://astro-rss-trailing-slash.patrickreiner.com/</link>

### Link to Minimal Reproducible Example

https://github.com/patrickreiner/astro-rss-trailing-slash

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by BryceRussell** [comment] 2024-05-10 22:33
Hello! 👋

There was a discussion about this on another issue here: https://github.com/withastro/astro/issues/10723#issuecomment-2051625034

In summary: The urls are treated as the same, there is no difference between `https://example.com` and `https://example.com/` except visual

**Comment by mingjunlu** [comment] 2024-05-10 23:12
@BryceRussell Thanks! I somehow missed that issue

**Comment by BryceRussell** [comment] 2024-05-10 23:32
@mingjunlu No worries!

@patrickreiner I am going to go ahead and close this since this is expected behavior. If you have any other issues feel free to open another issue 😀

**Comment by patrickreiner** [comment] 2024-05-11 10:30
Hi @BryceRussell, thank you, I agree with your label of "nice to have" where it's not breaking anything, but it would be nice to have the visual consistency. @astrojs/sitemap for example used to work like this as well (where the home page always had a trailing backslash) but that behavior was recently corrected as you can see here https://astro-rss-trailing-slash.patrickreiner.com/sitemap-0.xml

**Comment by BryceRussell** [comment] 2024-05-11 11:42
You're right! Sorry, I did not realize the sitemap had a similar change recently and did not consider that this could be changed even if it is only visual. For reference, there is a [workflow for triaging issues](https://github.com/withastro/astro/blob/main/CONTRIBUTING.md#issue-triaging-workflow) that I try to follow, but I am still learning 😅 I will re-open this issue

**Comment by BryceRussell** [comment] 2024-05-11 12:04
It looks like this issue happens because the links are transformed from a string, to a `URL`, and then back to a string

https://github.com/withastro/astro/blob/a78fa266850a0c8e0b42a0909eacbd577483b9f6/packages/astro-rss/src/util.ts#L20

https://github.com/withastro/astro/blob/a78fa266850a0c8e0b42a0909eacbd577483b9f6/packages/astro-rss/src/index.ts#L219-L224

Example:

```
// Returns 'http://example.com/'
new URL('http://example.com').toString()
```

**Comment by V3RON** [comment] 2024-05-13 17:19
@BryceRussell That's exactly the reason. I'm willing to work on it if you don't mind 😉

**Comment by Fryuni** [comment] 2024-05-14 01:12
For awareness, the recent change on the sitemap was not just cosmetic like it is here; in that case, it affects SEO by having the canonical URL of a page mismatched between the page and the sitemap.

**Closed** 2024-05-15 14:33 UTC
Labels: - P2: nice to have, pkg: rss
