### ISSUE TITLE
remarkPluginFrontmatter always undefined

### ISSUE THREAD

**Issue by ref-thomasledoux1** [withastro/astro#5974] opened 2023-01-25 09:14 UTC
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm using a remark plugin to calculate the reading time for my blogs (created as per the docs https://docs.astro.build/en/guides/markdown-content/#example-calculate-reading-time), and I want to display this time on my blog overview page now.
I'm use Content Collections, so I'm reading the blogs with the following command: `const allBlogPosts = await getCollection("blog");`.
I then loop over the blogs in my `.astro` file, and use `const { remarkPluginFrontmatter } = await post.render();` to get the frontmatter from my plugin. 
Sadly, this now always seems to be `undefined`.
Am I missing something in my config? 
I went through the changelog, and think my configuration is up to date with what is expected.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/github/thomasledoux1/website-thomas-astro/feature/use-prerender?file=%2Fsrc%2Fpages%2Fblog%2Findex.astro&selection=%5B%7B%22endColumn%22%3A69%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A22%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cldbfxbqx001a8rgxdxcehre7%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Fpages%252Fblog%252Findex.astro%2522%252C%2522%252Fastro.config.mjs%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cldbfxd1t00i23b6ha49a2ik3%2522%253A%257B%2522key%2522%253A%2522cldbfxd1t00i23b6ha49a2ik3%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522cldbfzjdt001i3b6h5g2d8myj%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cldbfztvl00eu3b6h93p0a32f%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fblog%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cldbfzob900b23b6h4prf42z3%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cldbfxd1t00i23b6ha49a2ik3%2522%252C%2522spacesOrder%2522%253A%255B%2522cldbfxd1t00i23b6ha49a2ik3%2522%255D%257D

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-01-25 17:40
@bholmesdev is this expected?

**Comment by bholmesdev** [comment] 2023-01-25 18:07
@matthewp No, this should be working as described here. I received a message on where this might've broken in the code. Can assign to me!

**Comment by bluwy** [comment] 2023-01-26 05:35
I think this is a duplicate of https://github.com/withastro/astro/issues/5859

**Comment by bholmesdev** [comment] 2023-01-26 15:42
Yep, closing in favor of the duplicate! Tracking a fix already 👍

**Closed by bholmesdev** 2023-01-26 15:42 UTC
Labels: p4-important, content-collections
