### ISSUE TITLE
🐛 BUG: Astro fails to inject `css` from `vanilla-extract` files

### ISSUE THREAD

**Issue by erwagasore** [withastro/astro#2536] opened 2022-02-04 21:19 UTC
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm, yarn

### What operating system are you using?

Mac

### Describe the Bug

Using `vanilla-extract` as css-in-js library and integrate it into `astro` using `vite` plugin. CSS `class names` are being properly produced but css injection is not happening. Thus classes assigned to the DOM are referencing to nothing.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-with-vanilla-extract

**Comment by pruthvi2103** [comment] 2022-02-06 13:33
Hey I figured out a quick fix for this issue, we can have a component have the `client-visible` prop and all styles imported in this component work, even outside (as VE zero runtime, the injection happens here). Not a great fix but pretty elegant for the timebeing

Think something like 

```
// index.astro
---
// Component imports and setup JavaScript go here!
import GlobalStyles from 'xyz'
---

<html lang="en">
	.
	.
	.
	<GlobalStyles client:visible/> // This supplies all the css (should import all the vanilla extract css)
		<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
	.
	.
	.
</html>

```

Forked your example and reproduced with the svelte example: https://stackblitz.com/edit/astro-with-vanilla-extract-g1u1pg?file=src%2Fpages%2Findex.astro

Hope this helps

**Comment by pruthvi2103** [comment] 2022-02-19 16:05
after some more investigation, I see if we actually import a css.ts file via the script tag, it also injects the css. however nothing is happening at build. time `dist` folder has js instead of the css that vanilla extract produces usually

eg: 

```
<script type="module" src={Astro.resolve('../styles/reset.css.ts')}></script>
```
Actually injects the css which is kinda intresting

**Comment by erwagasore** [comment] 2022-04-04 17:39
@matthewp any chance you are looking into this. Thanks

**Comment by matthewp** [comment] 2022-05-10 20:21
Thanks for filing. I have an updated example here: https://stackblitz.com/edit/astro-with-vanilla-extract-etfugz?file=src%2Fpages%2Findex.astro,src%2Fstyles%2Findex.css.ts

The vanilla-extract plugin works with Vite's default SPA templates, but doesn't work with Astro which renders purely server side. Not all Vite plugins work in Astro for this reason.

Supporting this library in Astro likely needs some Astro specific logic in the plugin. I'd be happy to help anyone wanting to add support. For one, Astro expects CSS dependencies to end with `.css` (or another style extension) but this one ends with JS. That *might* be the reason this doesn't work, I'm not sure.

Closing as this plugin doesn't support Astro at the moment.

**Closed by matthewp** 2022-05-10 20:21 UTC

**Comment by kennetpostigo** [comment] 2022-05-15 18:03
Hey @matthewp I'd love to help get a astro plugin working with vanilla-extract, do you know what changes need to be made in the plugin to make it compatible?
