### ISSUE TITLE
Vercel (Edge?) + Content Collections - Failed to execute 'encode' on 'TextEncoder'

### ISSUE THREAD

**Issue by ref-thomasledoux1** [withastro/astro#6073] opened 2023-01-31 18:21 UTC
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a page `blog/index.astro` which renders out previews for a few blog posts.
These blog posts are read by using the Content Collections features, but not sure it's related to that specifically?
Now the Edge functions is failing to render the page.
I get the following error:
```
TypeError: Failed to execute 'encode' on 'TextEncoder': parameter 1 is not of type 'String'.
    at (chunks/astro.dc54f0c1.mjs:45:5575)
    at (chunks/astro.dc54f0c1.mjs:90:13)
```

Not getting any errors while running the development server btw. 
### Link to Minimal Reproducible Example

https://codesandbox.io/p/github/thomasledoux1/website-thomas-astro/feature/use-prerender

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment] 2023-02-01 13:15
Closing as duplicate of #5915. Fix coming shortly!

**Closed by bholmesdev** 2023-02-01 13:15 UTC
Labels: core, adapter-vercel
