### ISSUE TITLE
Astro cannot find component unless index.astro is explicitly written

### ISSUE THREAD

**Issue by jinsupark** [withastro/astro#9391] opened 2023-12-10 01:45 UTC
### Astro Info

```block
Astro                    v3.6.4
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
```

### Describe the Bug

When importing a component in Astro, directories that include index.astro cannot be imported unless index.astro is explicitly written:

**What I want to do**
```js
// source file: src/components/rinseui/Dropdown/index.astro
import Dropdown from '@components/rinseui/Dropdown';
```

The above does not work and a "Cannot find module" error is thrown.

**What works** 
```js
// source file: src/components/rinseui/Dropdown/index.astro
import Dropdown from '@components/rinseui/Dropdown/index.astro';
```

This will work but not as elegant.

### What's the expected result?

I expect to be able to simply omit the index.astro like:

```js
// source file: src/components/rinseui/Dropdown/index.astro
import Dropdown from '@components/rinseui/Dropdown';
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zwy7bx?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-12-10 03:10
Omiting file extensions is a TypeScript thing that only works for TypeScript files, other file extensions always need extensions. I'll note that the ecosystem is generally moving away from omitting file extensions due to the ambiguities issues it causes with bundler and stuff.

I'll close this issue since this is expected behaviour.

**Closed by Princesseuh** 2023-12-10 03:10 UTC
Labels: needs triage
