### ISSUE TITLE
Unable to build with sdk that includes axios

### ISSUE THREAD

**Issue by braco** [withastro/astro#7330] opened 2023-06-08 06:18 UTC
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

deno

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

One of the routes includes an sdk that includes axios.

`yarn build`

is throwing this error:

```
[commonjs--resolver] Cannot bundle Node.js built-in "http" imported from "node_modules/.deno/axios@0.27.2/node_modules/axios/lib/adapters/http.js". Consider disabling ssr.noExternal or remove the built-in dependency.
```

I'm interpreting this to mean that axios is using the node version of itself and the `require('http')` is causing this error.  But other than that I'm a little baffled, where is this error coming from? The main search result I can find is a bug on vite.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2023-06-11 16:47
Hmm it looks like we didn't set `target: "webworker"` here unlike other similar integration setup:
https://github.com/withastro/astro/blob/4f7091206c62f6546abdbdb895035b052cf383af/packages/integrations/deno/src/index.ts#L91-L93

It might also be fixed by https://github.com/withastro/astro/pull/7288

**Comment by natemoo-re** [comment] 2023-08-17 20:18
I'm going to close this since I assume that https://github.com/withastro/astro/pull/7288 fixed it and there's no reproduction for me to confirm. If you're still running into trouble, please feel free to [open a new issue](https://astro.build/issues).

**Closed by natemoo-re** 2023-08-17 20:18 UTC
Labels: - P3: minor bug, feat: ssr
