### ISSUE TITLE
Invalid Hook Call in React

### ISSUE THREAD

**Issue by cameronmcefee** [withastro/astro#4220] opened 2022-08-09 20:32 UTC
### What version of `astro` are you using?

1.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When running my site with the React plugin in development, I see `InvalidHookCall` warnings. In the repro, run:

```
yarn
yarn start
```
When you load http://localhost:3000/ you'll se the error in the terminal output.

The error only exists when using a hook, and given the simple usage, I'm confident the use is accurate. Thus, my assumption is that the cause is a mismatch in versions of React as cited in the third possibility of the message.

```
3. You might have more than one copy of React in the same app
```

With my spelunking in #4084 I know that Astro uses a custom renderer, so I suspect the issues lies therein somewhere. As further evidence of my suspicion, in the [official docs for this issue](https://reactjs.org/warnings/invalid-hook-call-warning.html) they recommend the following:

```javascript
// Add this in node_modules/react-dom/index.js
window.React1 = require('react');
```

While this example obviously fails in SSR, if you do something simple like just logging "hello world" from that file, I see the log in the terminal (presumably for SSR) but not in the browser console, so I'm guessing react-dom is not used during hydration.

### Link to Minimal Reproducible Example

https://github.com/cameronmcefee/invalid-hook-call-example

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Mrahmani71** [comment] 2022-08-09 21:08
I had the same problem, I fix it like this:
```
## Incorrect
function Nav(){}
export default Nav;

## Incorrect
const Nav = () => {}
export default Nav;


## Correct
export default function Nav(){}
```
I think, you need to change your component.tsx, like this

`
export default function Component() {
  const [test, setTest] = useState(true);
  return <p>Hello world</p>;
};
`

**Comment by FredKSchott** [comment] 2022-08-09 22:35
I can reproduce this as well, however I only see one copy of react in your node_modules folder:
<img width="938" alt="Screen Shot 2022-08-09 at 3 34 26 PM" src="https://user-images.githubusercontent.com/622227/183773472-509f7fff-0d52-4ba6-8812-003774030f0f.png">
 
@Mrahmani71 that also fixes it for me, which is wild! @natemoo-re anything odd that our JSX compilation step could be doing?

**Comment by FredKSchott** [comment] 2022-08-09 22:50
@natemoo-re and I tracked this down to `packages/astro/src/vite-plugin-jsx/tag.ts` not understanding anything other than `export default function X` and `export function X`. If anyone likes working with Babel, this would be a fun PR to add an understanding of `export { X}` and `export const X` and `export default const X`!

**Comment by ShivamJoker** [comment] 2022-08-10 15:40
Hey Astro team I am also facing the same while using some basic hooks it will be great to get this fixes in coming days

**Comment by hippotastic** [comment] 2022-08-10 19:55
I also just encountered this issue. In addition to what was already reported here, I have found the following:

```js
// ❌ Exporting an anonymous function causes the warning to be logged
export default function () { /*...*/ }

// ✅ Exporting a named function works well
export default function Counter() { /*...*/ }
```

**Comment by joshuaiz** [comment] 2022-08-12 19:32
Seeing this as well. What is interesting in my case is after using `--trace-warnings` the trace indicates the error is coming from an `.astro` component which obviously cannot have any React hook calls (and it does not).

**Comment by ptrkvsky** [comment] 2022-08-17 05:25
![Screenshot from 2022-08-17 07-23-43](https://user-images.githubusercontent.com/33042640/185041203-c120e842-971d-4332-bf35-7320d6cb8cc6.png)
Same here 
`07:22:29 AM [astro] reload /src/hooks/useScrollSpy.tsx
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
![Screenshot from 2022-08-17 07-25-16](https://user-images.githubusercontent.com/33042640/185041290-9d946db8-4669-4c41-91ee-d1498a8eb0f1.png)
`

**Comment by JeffMusgrave** [comment] 2022-08-19 16:10
I am also getting this same issue when I try to use the component library Chakra-UI. I've tried bot the strict TS settings and JS settings. Both throw the same warnings and won't render correctly.

Is there any ETA for a fix?

**Comment by rndy28** [comment] 2022-08-20 05:50
same here, but
```js
export default function SomeComponent(){}
```
seems to fixed it. is there any progress regarding what causing the issue?

**Comment by cameronmcefee** [comment] 2022-08-23 21:44
My console is once again at peace. Thank you.

**Comment by joshuaiz** [comment] 2022-08-24 02:02
Yes thank you. Sigh.

**Comment by miklschmidt** [comment] 2022-09-02 13:39
Maybe this should be reopened since the fix was reverted, or is it tracked somewhere else?

**Comment by DevRSC** [comment] 2022-09-03 14:56
I still face this issue when using arrow functions. I hope they'll fix this issue

**Comment by bluwy** [comment] 2022-09-04 08:46
It doesn't look like there's a separate issue, or is fixed with a different PR. Re-opening.

**Comment by OmarZeidan** [comment] 2022-09-05 22:26
Facing the same issue here! Any updates on this team? 

<3

**Comment by maxdevjs** [comment] 2022-09-12 10:45
Experiencing this issue today

> with a simple named function (not an <strong>arrow</strong> function)

The following code logs the warning message:

```jsx
function Showcase() {
  const [name, setName] = useState('Name here')
  return <div>Hello { name }</div>
}

export default Showcase
```

The following code does <strong>not</strong> log the warning message:

```jsx
export default function Showcase() {
  const [name, setName] = useState('Name here')
  return <div>Hello { name }</div>
}
```

**Closed** 2022-09-21 19:53 UTC
Labels: framework-react, framework-preact, p4-important, s1-small
