### ISSUE TITLE
🐛 BUG: JavaScript heap runs out of memory

### ISSUE THREAD

**Issue by bgdfry** [withastro/astro#1711] opened 2021-10-29 21:09 UTC
### What package manager are you using?

NPM

### What operating system are you using?

Mac

### Describe the Bug

When trying to build our ~12,000 page site with dynamically rendered pages we are running into the following error while attempting to build out the pages. We are currently using `"@astrojs/renderer-svelte": "^0.1.2",` and this issue is only occurring after importing multiple Svelte files into `[name].astro` in our example repo.

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

### Steps to Reproduce

1. Clone https://github.com/sikemausa/astro-example
2. npm install
3. npm build
4. Above error occurs

### Link to Minimal Reproducible Example (Optional)

https://github.com/sikemausa/astro-example

**Comment by matthewp** [comment] 2021-11-02 14:07
Very interesting and thanks for the reproduction! I'm going to test this when working on the implementation of the new build process in `@next`. I'm unsure if it will prevent this or not, but it is being designed to be better for large sites, so hopefully.

In any case, marking this as accepted as building large sites is something we want to do, for sure.

**Comment by jasikpark** [comment] 2021-11-09 23:39
https://github.com/seancdavis/ssg-build-performance-tests/issues/74 might be helpful for this 🤔

**Comment by khrome83** [comment] 2021-11-10 20:03
@matthewp when looking at the older build process, a lot of information is kept in memory. I have not reviewed since the change to Vite. But we had bottleneck issues with Sapper in the past. And it had to do with processing the data and requesting file writes faster than we can write. And that held true for doing different things past file writes. For example, asking for a transform. 

It was many layers of queues that were trying to ensure the next were not overloaded, and we could parallel requests without impacting memory heap or disk I/O. So we would intentionally limit the items in the queue and only add to the top when things from the bottom were pulled out and finished writing.

As my college @nealalpert said, 

> "By not putting an enormous amount of data onto the heap we dramatically sped up the export process for large numbers of pages rather than slowing it down with the queue bottleneck as they might have initially thought."

This improved our efficiency and reduced memory. 

Here is a repo my college is hosting for the reworked version of Sapper. https://github.com/nealalpert/sapper/tree/export-updates/src/api

That Sapper project has since been vaporware. And we would love to move off it to Astro instead of maintaining this custom fork.

**Comment by bgdfry** [comment] 2021-11-23 14:40
Wanted to give a quick update on this. We tested this again on the repo above with the newest versions of Astro and `@astrojs/renderer-svelte`, but it is unfortunately still breaking with the same error when attempting to build a larger number (16000) of pages.

**Comment by stephanbogner** [comment] 2021-12-02 10:50
I have the same error on Astro version 0.21.5 and Node 16.13.0 (on Mac via nvm) with roughly 2300 pages.

—

**FYI: I also tested the approach to generate the pages myself:**
So instead of using `[slug].astro`, I tried it with a Node script that generates many index.astro files in the respective directory.
But same error ... so it's apparently not related to the "routing" approach.

—

**I am now trying a "dirty" approach of just increasing memory:**
`npm run build --node-flags --max-old-space-size=8192 --no-warnings` (from [Stackoverflow](https://stackoverflow.com/a/55021566))

Result on crash:
```
<--- Last few GCs --->

[67261:0x7fd98d000000]   626859 ms: Scavenge 4089.1 (4125.3) -> 4088.0 (4125.8) MB, 4.6 / 0.0 ms  (average mu = 0.247, current mu = 0.252) allocation failure 
```
Still crashes with 4gb of RAM full so that apparently doesn't work either ...

**Comment by matthewp** [comment] 2021-12-02 18:33
Thanks for your patience everyone. Let me explain where the memory problems come from and what we intend to do about it. I'll say that this is one of our highest priorities.

Due to the flexibility of .astro syntax to define links to assets like styles, scripts, and images inside of the `src/` directory, Astro has always revolved around scanning the generated HTML by parsing each page during the build. 

In < 0.20 when using snowpack we had to scan the HTML to find assets to copy to `dist/` but that was it (still not great).

In 0.21 with the adoption of Vite we get a nice feature where Vite will hash files for you. Additionally Vite does some HTML post-processing to convert our inline scripts into external scripts. The unfortunately side-effect is that we now are both forced to scan *and then later update* the HTML since the filenames change.

So unfortunately, build performance and memory usage has regressed in 0.21.

---

We know that building non-trivial sites involves building a lot of pages and we should be able to support building to tens of thousands (if not more).

Our plan is to make .astro files more statically discoverable so neither scanning nor updating HTML will be necessary.  Instead assets will be declared statically and discovered per .astro file; not per page. So you won't pay additional costs for having more pages, other than the time it takes to render the page.

This plan requires some breaking changes. You can see the [1.0 unification doc](https://github.com/withastro/rfcs/discussions/1) to see the direction we are heading. These changes will come before 1.0 and are the primary thing we (and I) are working towards (aside from other 0.21 bug fixes).

So unfortunately the answer here is not a quick fix, and if it makes sense in your project to stay on 0.20 a little longer then that's still a great static site builder.

**Comment by trevormunoz** [comment] 2021-12-02 21:12
Thanks @matthewp for sharing this clear explanation and for the broader sense of where these issues fall in the team's priorities on the roadmap to 1.0! Makes it much easier to hold on for a resolution even if it takes more time and worry less about bigger sites that are working well on 0.20 not being left behind.

**Comment by matthewp** [comment] 2021-12-22 16:09
Update on this, there's an `--experimental-static-build` flag now in the main branch that should be able to handle very large sites. I tested on a site that is ~1000 pages and the build time went from 18 seconds to about 4 seconds. I haven't tested on a >10k page site yet but it should be able to handle it without a problem.

This flag isn't quite ready for use yet as its missing support for hydrated components and likely has other bugs that might block real use. But we are getting close and I'll let everyone know when its closer to being ready to experiment with.

**Comment by 684efs3** [comment] 2021-12-30 19:09
The ability to build large sites statically is a big pain point with the other static site generators. Would be huge if Astro can address this and have the ability to build 10,000+, 100,000+, and possibly even 1 million + pages.

**Comment by bgdfry** [comment] 2021-12-30 21:50
Hey @matthewp 👋 
I just gave this a go using the `--experimental-static-build` flag, but it's still breaking at 16k pages with the same memory error. I was able to get it to export with ~1600 files, but that was the closest I got.

**Comment by davideast** [comment] 2022-01-13 18:05
I'm running into this error on a site with ~1,400 pages. I'm upgrading from `0.20` and the build time was ~2 minutes and now locally it builds in about ~7-8 even with `--experimental-static-build`. I run into the allocation error when running the build in GitHub actions.

I'm not sure if I'm doing something wrong (I probably am) with a `getStaticPaths()` page, but when using `--verbose` I can see it generate the same page multiple times. 

Is there something specific I should look for when debugging this?

**Comment by matthewp** [comment] 2022-01-13 19:01
Hey @bgdfry and @davideast, are your thousands of pages `.md` files mostly? From what I've seen that's our current blocker on page size.

**Comment by davideast** [comment] 2022-01-13 19:05
Yep! It's all `.md` files really.

**Comment by khrome83** [comment] 2022-01-13 19:08
Answering for @bgdfry who reports to me. No, we were using an API to get data, and it's not just making pages based on markdown. I don't think the sample repo @sikemausa created for us (also reported to me) used markdown at all as you can see in the source above in the initial report.

**Comment by matthewp** [comment] 2022-01-13 19:14
Thanks

@davideast Yeah this is a known issue, because each `.md` file gets converted into an Astro component. So running thousands of JavaScript files through Vite/Rollup is a bit of a blocker. I have an idea to treat `.md` files more like data that I think will fix this problem. I'll let you know when I have something ready there.

----

@khrome83 Thanks, looking at your repo I wouldn't expect that style of building to be an issue, so I'll check out your repo and report back.

**Comment by davideast** [comment] 2022-01-13 19:25
@matthewp Good news on my side! We discovered a bug in my `getStaticPaths()` code that was generating about ~800 extra pages (oops). We're down to ~500 now and our build is ~100 seconds, which is totally doable for us at the moment. 

But as a note, we did not use `--experimental-static-build` flag because it dropped the CSS from our build.

**Comment by matthewp** [comment] 2022-01-13 19:43
@khrome83 That repo is very helpful. I can see from testing it out that generating all of the pages at one time is a bottleneck; we should throttle it so that we only allow N number of pages to be built in parallel. That will be enough to fix the issue where the build never completes.

Looking into ways to make it faster, still.

**Closed** 2022-01-14 21:14 UTC

**Comment by wuyasong** [comment] 2023-11-18 02:11
I have too many image, maybe 100, I use `astro build --experimental-static-build` still out of memory

**Comment by wuyasong** [comment] 2023-11-18 02:12
but I use `NODE_OPTIONS=--max_old_space_size=8192 npm run build` is okay

**Comment by montsamu** [comment] 2024-03-14 14:44
Static build was fine, and trying "hybrid" build with sst or cloudflare was fine, but when building with netlify as the SSR adapter even `NODE_OPTIONS=--max_old_space_size=8192` was not enough. Maybe something still a bit suspect with the netlify adapter for a hybrid build of a large site?

**Comment by davemagro** [comment] 2024-05-12 11:52
issue still persists even with only less than 10 pages.

**Comment by GoogleFeud** [comment] 2024-05-25 13:50
I'm getting this issue just trying to build the blog post starting project, with 1 new page and 2-3 new astro components. Interestingly enough, it only happens If a `dist` (or whatever your `outDir` is set to) folder already exists in the root. Also happens at the start, during the `check` phase.

**Comment by nakorndev** [comment] 2024-10-03 05:49
> I'm getting this issue just trying to build the blog post starting project, with 1 new page and 2-3 new astro components. Interestingly enough, it only happens If a `dist` (or whatever your `outDir` is set to) folder already exists in the root. Also happens at the start, during the `check` phase.

Confirmed. When delete the `dist` is working again.

**Comment by sanscontext** [comment] 2024-10-21 19:09
I'm also running into this issue, and it's unfortunately making our team consider if we can continue using Astro for our project.

**Comment by thomasgauvin** [comment] 2024-11-05 04:31
Same issue here. Deleting `dist` fixes the problem.
