### ISSUE TITLE
🐛 BUG: Markdown rendered through fetchContent is not equivalent to Markdown rendered when accessing via a view

### ISSUE THREAD

**Issue by joeinnes** [withastro/astro#2328] opened 2022-01-06 12:20 UTC
### What version of `astro` are you using?

0.22.6

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### Describe the Bug

I am using a dynamic route to fetch content and display my Markdown.

This works for static Markdown files. However, on a few Markdown files, I would like to implement Components in Markdown which was introduced in 0.21.

When I access these through the `html` key on the `astro` object, these components are not rendered.

Note: I think the actual fix to my issue would rather be to have a default layout option so that I can allow the built-in routing to manage the rendering, otherwise I guess the renderer would need to insert inline script tags to render components. But this adds cruft to my Markdown which I'd rather avoid if possible, and this difference in rendering essentially precludes storing any Markdown outside of the Astro project.

### Link to Minimal Reproducible Example

This is broken, won't install 0.22.7, rolled back to 0.22.6 and installed. Repro here: https://stackblitz.com/edit/github-qyrlrr?file=src/pages/[slug].astro

**Comment by jonathantneal** [comment] 2022-01-21 23:41
I’m unable to see this issue in your example, using either 0.22.6 or 0.22.7. Would you check again, and let me know why I might not be seeing something break?

**Comment by luin** [comment] 2022-01-22 05:16
@jonathantneal I can reproduce with [the example](https://stackblitz.com/edit/github-qyrlrr?file=src/pages/[slug].astro) provided by @joeinnes . The screenshots of what I'm seeing:

**/content/test:**
<img width="320" alt="CleanShot 2022-01-22 at 13 14 34@2x" src="https://user-images.githubusercontent.com/635902/150625718-d084ce37-e265-44a8-a1e6-56addfcec857.png">

----
**/test:**
<img width="349" alt="CleanShot 2022-01-22 at 13 14 43@2x" src="https://user-images.githubusercontent.com/635902/150625728-5c9e8262-893f-40cf-9b4b-2edb8923ebc0.png">

---

The component `Adder` is not rendered correctly on /test.

**Comment by joeinnes** [comment] 2022-01-22 09:31
The behaviour @luin sees is what I see. The component accessed through file system rendering works as expected. The component which is rendered using `fetchContent` does not include the component.

I have no idea why you wouldn't be able to see this, to be honest. 

Which browser are you using? I'm using Brave[0]. I wouldn't have thought that browser differences would matter here because it's server side rendering that's impacted, but then with WebContainers, the browser is the server, so maybe...

[0]: Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (x86_64)

**Comment by Princesseuh** [comment] 2022-01-29 00:12
Instead of rendering the content of `fetchContent` with `astro.raw.html` you need to render it using the Content component, like so:

`<page.Content />`

This is a bit awkward situation at the moment because it isn't documented anywhere apart from random Discord threads. Hopefully once `fetchContent` is reworked, this will be a bit more obvious (and documented)

[Here's an example from my own website](https://github.com/Princesseuh/princesseuh.dev/blob/redesign/src/layouts/ArticleLayout.astro)

**Comment by tony-sull** [comment] 2022-02-15 11:44
Thanks for filing this issue!  Closing it as a duplicate of [#2158](https://github.com/withastro/astro/issues/2158) as the primary issue to make sure the docs get updated to clarify how this is expected to work :+1:

**Closed by tony-sull** 2022-02-15 11:44 UTC
