### ISSUE TITLE
4.1.0 removed build information

### ISSUE THREAD

**Issue by tmkn** [withastro/astro#10449] opened 2024-03-14 22:46 UTC
### Astro Info

```block
Astro                    v4.5.0
Node                     v18.17.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

I'm building a SSG site.
Prior to `4.1.0` when building it would show the built page's title alongside the time it took but now it only shows the time like:
![image](https://github.com/withastro/astro/assets/2671613/375d2a1c-e4db-4402-bd9f-eec3f9bdc5e5)

Imo the page title was very useful, would love to see it return.

### What's the expected result?

To work like in astro up to 4.0.1, where the title was written out: 
![image](https://github.com/withastro/astro/assets/2671613/c03e2d03-c7e3-4b8e-80a9-c1f0af94d26f)

### Link to Minimal Reproducible Example

https://github.com/tmkn/npmsmell/tree/bf1443f8c884246cdb88ebdebccf4ae54de6a1d5

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment] 2024-03-15 07:20
The issue is that the way we log the pages this way:

1. When we start rendering that path, print out `├─ /something/index.html`
2. After rendering, we append the time `(+10ms)`

The problem (I think) is [this line](https://github.com/tmkn/npmsmell/blob/1e29ef06888a0ad022068ecd7eb2d8600bcdf252/src/npm.ts#L33) where I'm seeing a "Fetched some-dep" message that was clearing step 1. Hence you don't see the file path from step 1.

If we could detect that the line was cleared  from step 1. (Cursor 0 maybe?). Then maybe we can relog the entire line for completeness. This way if the page has console.logs, it wouldn't look weird too.

**Comment by matthewp** [comment] 2024-03-15 12:12
@bluwy are you sure this change wasn't intentional?

**Comment by Princesseuh** [comment] 2024-03-15 12:26
> @bluwy are you sure this change wasn't intentional?

No, Fred's changes definitely did not remove the entire log, ha. I think Bjorn's assessment is correct, it's caused by the line getting cleared.

**Comment by bluwy** [comment] 2024-03-15 14:11
Yeah, I think the new logging changes (from https://github.com/withastro/astro/pull/9487) might not have anticipated logging/clearing while rendering pages, so the logging could be off when that happens.

I'm hoping the fix won't be too hard though, so in the case where the line is cleared or some logging happened, we re-print the entire line again, e.g.

```
15:19:54   └─ /index.htmllogging
something
something
15:19:54   └─ /index.html (+4ms)
```

I think it's a nice-to-have, so it's great if it can be fixed, but if not it's likely not a big deal.

**Comment by mingjunlu** [comment] 2024-03-15 14:23
I wonder if we could simply switch the order of the first 2 steps. Would it bring any negative impact to the user?

```markdown
# Before
1. Print out ├─ /something/index.html
2. Render the path
3. Append the time (+10ms)

# After
1. Render the path
2. Print out ├─ /something/index.html
3. Append the time (+10ms)
```

**Comment by tmkn** [comment] 2024-03-15 15:03
thanks for the input.

yes, I'm fetching some data when a page is built, as pointed out I'm using `OraLogger` which uses `ora` to display progress.
I had a feeling that this behaviour could be the problem, but since it worked before I filed a report.

However I'm totally fine to adapt the data fetching logic (use something else than `ora`) but atm I don't know with what, as other loggers would behave the same I imagine.

With the release of the db feature I think its a better place to load the data in the `seed.ts` file (never really liked how its currently done, on demand). If I could access the log functions in the `seed.ts` I could pass it to my data fetching logic and wouldn't run into this issue , I think 🤔

**Comment by ematipico** [comment] 2024-03-15 16:25
I am not sure we can do much about it. Other loggers can kick in and do something that won't look nice at the end. We don't have control over ALL logging.

I see three options:
- render how it was before (not very optimal)
- render the time on a new line, indeed (not optimal)
- render the path, **clear the line** after the build of the page, render the path with time

**Comment by mingjunlu** [comment] 2024-03-18 09:48
@ematipico Thanks for laying out these options! I'm willing to give option 3 a try. Let's see if we can make this work 💪

**Comment by bluwy** [comment] 2024-03-18 10:05
Just to leave another option, my idea was:

1. Print the path
2. Render the path page
3. Use `readline` and check if the current line is still the same as printed in no1:
   1. If so, append the time
   2. If not, re-print the path + time

**Comment by mingjunlu** [comment] 2024-03-18 10:21
@bluwy Thanks for adding this! Working on it 📝

**Comment by matthewp** [comment] 2024-04-02 21:08
@mingjunlu are you still working on this?

**Comment by mingjunlu** [comment] 2024-04-03 00:45
Sorry that I forgot to update. I got stuck while trying to get the logged result using `readline`. After [discussing](https://discord.com/channels/830184174198718474/1219266536397738096) with @bluwy, the safest way seems to be keeping it as is since option 3 might accidentally remove important lines.

**Comment by ematipico** [comment] 2024-04-03 14:00
Thank you @mingjunlu for your time and updates. I close this issue; it seems there isn't much we can do; other loggers are interfering with Astro ones.

**Closed by ematipico** 2024-04-03 14:00 UTC
Labels: - P2: nice to have
