### ISSUE TITLE
Console flooded with hint output for React/Typescript projects

### ISSUE THREAD

**Issue by pringshia** [withastro/astro#9390] opened 2023-12-09 04:45 UTC
### Astro Info

```block
Astro                    v4.0.3
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

## **Observation:**
When I re-run `npm run build` or run `npx astro check` on an already built Astro project with **React/Typescript integration**, my console output **gets absolutely flooded with Typescript hint output** (this is due to 48 hints logged, and  too within minified, bundled code which gets all logged to output as preview).

A new project that exhibits this bug can be scaffolded with:
```
npm create astro@latest myproject -- --yes
cd myproject
npx astro add react --yes

# Generate the output dir
npm run build

# Notice that the checks incorrectly run on the output dir
npx astro check # or: npm run build
```

## **Suspicion**:
I think this is occurring because the diagnostics run by `npx astro check` are running Typescript hint checks in the `dist/` folder, **which should instead be ignored**.

## **Workaround**:
For now I am doing the following workaround.

Add the `outDir` property to `.tsconfig.json`:
```json
{
   "compilerOptions": {
      "outDir": "dist"
   }
}
```

This prevents the Typescript diagnostic checks from running on the bundled output generated in that directory. Another option would be to add `"exclude": ["dist"]` at the root level of `.tsconfig.json`, but the above solution feels more robust and semantically correct.

### What's the expected result?

Typescript diagnostic hints shouldn't be run on generated bundle code in the `dist/` output folder.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ztemdb?file=tsconfig.json

Run `npm run build && npx astro check`

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-12-09 09:31
Duplicate of https://github.com/withastro/language-tools/issues/643

**Closed by Princesseuh** 2023-12-09 09:31 UTC
Labels: needs triage
