### ISSUE TITLE
The latest version of Svelte 5 doesn't work with Astro

### ISSUE THREAD

**Issue by adamdinhvu** [withastro/astro#11193] opened 2024-06-06 11:44 UTC
### Astro Info

```block
Astro                    v4.9.3
Node                     v20.12.2
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
```

### Describe the Bug

Astro instantly brings an Unhandled rejection error:

`No matching export in "node_modules/svelte/src/internal/client/index.js" for import "add_snippet_symbol"

    node_modules/@astrojs/svelte/client-v5.js:2:9:
      2 │ import { add_snippet_symbol } from 'svelte/internal/client';`

This happens in a completely blank Astro project

### What's the expected result?

-

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u6s3yg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment] 2024-06-06 11:53
Duplicate of #11149

**Closed by florian-lefebvre** 2024-06-06 11:54 UTC
Labels: needs triage
