### ISSUE TITLE
base configuration option is not working when using layout inside of collection

### ISSUE THREAD

**Issue by JLarky** [withastro/astro#5968] opened 2023-01-24 21:28 UTC
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

clone `bug--astro-collections-base` branch from https://github.com/JLarky/astro-fork

now inside `examples/blog` I did two changes:
- use `/prefix` as `base` in astro config
- use `layout` in .md collections (it works fine with regular .md, the issue is just in collections)

I also added yellow bg in the style tag to show that some of css assets still have the right prefix, but not all of them :)

Now `astro dev` works fine, but `astro build && astro preview` produces builds that don't respect `base` property so some assets point to `/_astro` instead of `prefix/_astro`

| dev (expected) | prod (bugs) |
| ------ | ------ |
|  <img width="767" alt="image" src="https://user-images.githubusercontent.com/7026/214418639-8ff8ed1c-4a00-4573-8e16-7feed640d31d.png">     |   <img width="874" alt="image" src="https://user-images.githubusercontent.com/7026/214418909-eec90811-947b-4c05-9d29-9ee62124e5e7.png">     |

### Link to Minimal Reproducible Example

https://github.com/JLarky/astro-fork/commits/bug--astro-collections-base

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-01-25 17:45
Oh, that's surprising. Will look into this soon.

**Comment by bholmesdev** [comment] 2023-01-26 15:59
Interesting find! Thanks for following up on our Twitter DM with this issue. So to confirm, removing the `layout:` frontmatter property resolves your issue? Or is this unrelated?

**Comment by HundredPercentCoverage** [comment] 2023-01-26 22:37
Sorry to piggyback but it might be related - when I set a default value in my blog content collection config for `layout`, it doesn't seem to apply the layout if I remove the property from the frontmatter, i.e.

```
// schema
const blogCollection = defineCollection({
  schema: z.object({
    title: z.string(),
    description: z.string(),
    pubDate: z.date(),
    updatedDate: z.date().optional(),
    layout: z.string().default("../../layouts/BlogPost.astro"),
    heroImage: z.string().optional(),
    tags: z.array(z.string()),
  })
});
```

This frontmatter renders as expected:
```
---
title: ...
pubDate: ...
layout: "../../layouts/BlogPost.astro"
description: ...
heroImage: ...
tags: ...
---

Text here
```

But if I remove the `layout` prop it doesn't render correctly and just shows `Text here` as bare HTML rendered text.

**Comment by JLarky** [comment] 2023-01-27 01:58
> Interesting find! Thanks for following up on our Twitter DM with this issue. So to confirm, removing the `layout:` frontmatter property resolves your issue? Or is this unrelated?

yes, this is the current workaround that I used for my website, just not to use `layout` in collections :)

**Comment by natemoo-re** [comment] 2023-02-09 20:27
Looks like this was fixed by @matthewp in https://github.com/withastro/astro/pull/6182! Just double checked locally and I am unable to reproduce on the latest.

**Closed by natemoo-re** 2023-02-09 20:27 UTC
Labels: p5-urgent, content-collections
