### ISSUE TITLE
Error launching new project on M1

### ISSUE THREAD

**Issue by TobiasGrether** [withastro/astro#5504] opened 2022-11-30 19:17 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac (M1)

### Describe the Bug

When trying to create a new project using `npm create astro@latest`, the process of creating a new project starts normally. After entering a project name however, the process errors out.

The following log messages occur:
```
34 http fetch GET 200 https://registry.npmjs.org/create-astro 317ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 timing command:create Completed in 9475ms
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:527:28)
38 verbose stack     at maybeClose (node:internal/child_process:1090:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
39 verbose cwd /Users/tobiasgrether/Documents/work/somework
40 verbose Darwin 22.2.0
41 verbose node v18.2.0
42 verbose npm  v9.1.2
43 error code 1
44 error path /Users/tobiasgrether/Documents/work/somework
45 error command failed
46 error command sh -c create-astro
47 verbose exit 1
48 timing npm Completed in 9505ms
49 verbose code 1
```

The screen prompts the following: 
<img width="738" alt="Screenshot 2022-11-30 at 20 17 01" src="https://user-images.githubusercontent.com/39413320/204888441-686bb127-00d7-4e8a-8edc-34894d9a53d3.png">

This is the case for all templates, not just the minimal or best practise one.

Versions:
- NodeJS: 18.2.0
- NPM: 9.1.2

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2022-12-01 22:05
npm 9 maybe the cause here?

**Comment by noClaps** [comment] 2022-12-05 01:08
Can reproduce with NPM 8.19.3 and Node 19.2.0 on Windows 11

**Comment by AlexanderZhou39** [comment] 2022-12-07 04:35
experiencing the same issue
![Screenshot 2022-12-06 at 8 35 08 PM](https://user-images.githubusercontent.com/66284119/206089387-013ffca3-53e8-49fe-891e-37cebd675310.png)

**Comment by smithl** [comment] 2022-12-13 18:38
m1 max running 12.6

`20 verbose title npm create astro@latest
21 verbose argv "create" "astro@latest"
22 timing npm:load:setTitle Completed in 4ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 6ms
25 verbose logfile logs-max:10 dir:/Users/*/.npm/_logs/2022-12-13T18_33_57_351Z-
26 verbose logfile /Users/*/.npm/_logs/2022-12-13T18_33_57_351Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 36ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 http fetch GET 200 https://registry.npmjs.org/create-astro 779ms (cache revalidated)
35 timing arborist:ctor Completed in 1ms
36 timing arborist:ctor Completed in 1ms
37 timing command:create Completed in 14288ms
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:527:28)
38 verbose stack     at maybeClose (node:internal/child_process:1090:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
39 verbose cwd /Users/*/Documents/personal/*/astro
40 verbose Darwin 21.6.0
41 verbose node v18.0.0
42 verbose npm  v9.2.0
43 error code 1
44 error path /Users/*/Documents/personal/*/astro
45 error command failed
46 error command sh -c create-astro
47 verbose exit 1
48 timing npm Completed in 14359ms
49 verbose code 1
50 error A complete log of this run can be found in:
50 error     /Users/*/.npm/_logs/2022-12-13T18_33_57_351Z-debug-0.log`

**Comment by natemoo-re** [comment] 2023-02-07 22:32
I'm going to close this as a duplicate of https://github.com/withastro/astro/issues/5227. 

I believe this is an upstream issue with [`giget`](https://github.com/unjs/giget), so please follow-up there. See [my original comment](https://github.com/withastro/astro/issues/5227#issuecomment-1421512995) for more info.

**Closed by natemoo-re** 2023-02-07 22:32 UTC
Labels: p4-important
