### ISSUE TITLE
View transitions - FOUC when using back button browser

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/astro#7833] opened 2023-07-27 09:16 UTC
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome 115.0.5790.102

### Describe the Bug

I activated View Transitions on my website, and I added a specific transition between the titles of my blog posts on the overview page, and the title on the blog detail page.
When I click on the blog preview on the overview, I can see the title transition, works fine.
But when I hit the back button in my browser, I see a flash of unstyled content, so the CSS seems to be applied later? 
Not sure how/why this is happening.
Can be tested on https://website-thomas-astro-58u9o7hec-thomasledoux1.vercel.app/blog.
GitHub: https://website-thomas-astro-58u9o7hec-thomasledoux1.vercel.app/blog

### What's the expected result?

No FOUC

### Link to Minimal Reproducible Example

https://github.com/thomasledoux1/website-thomas-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-07-28 16:42
Thanks for the repro! Will take a look today and see what's going on.

**Comment by FrancoJavierGadea** [comment] 2023-07-28 20:47
I have the same problem here: https://64c233ea8c4b4d00081f2eb7--libros1812.netlify.app/

In localhost, it works great, but when I deploy it, flashing appears.

Although applying an inline CSS patch helped, it's not the ideal solution.

**Comment by matthewp** [comment] 2023-07-28 21:01
I think the problem is likely because it naively swaps the entire documentElement. I think it probably needs to diff the head instead. Working on that.

**Comment by lukeshafer** [comment] 2023-07-30 00:56
Looks like the issue is understood here, but thought I'd mention that I'm experiencing the same/similar issue - FOUC when navigating, and only on the deployed site. I can provide more information if needed

**Comment by davycoe** [comment] 2023-07-30 18:29
> Looks like the issue is understood here, but thought I'd mention that I'm experiencing the same/similar issue - FOUC when navigating, and only on the deployed site. I can provide more information if needed

I've a similar FOUC when navigating using Chrome. Deployed to CloudflarePages, FireFox seems to work as expected,

Example here: [https://7974c724.astro-transitions.pages.dev/](url)

**Comment by matthewp** [comment] 2023-07-31 17:29
This will be fixed in #7861. With that change, links are left untouched if they exist on both pages, so there should be no FOUC. New links are preloaded before the DOM swap happens.

You can test it out with the preview release:

```
npm install astro@next--view-transitions --save
```

You shouldn't need to change any of your code. If anyone's able to try it out and let me know if it solves the issue you're seeing. Thanks!

**Comment by lukeshafer** [comment] 2023-08-01 00:23
Also can confirm the issue is fixed after upgrading! I had also noticed a thing where the favicon would be removed after a transition, but that issue is also fixed now (which I thought it might be, given the head diffing) -- in case anyone brings it up!

**Comment by thomasledoux1** [comment] 2023-08-01 17:46
@matthewp I can’t test it at the moment, since my site’s build seems to fail when updating Astro to the version you provided. Some TS error regarding the astro.config.ts: “Type ‘AstroIntregration’ is not assignable to type ‘false | AstroIntegration | (false | AstroIntegration | null | undefined)[] | null | undefined’”. Not sure what’s causing it, but if the others in this issue were able to test this and say it’s working fine, I would just go for it 😊

**Closed** 2023-08-02 18:42 UTC
Labels: - P4: important, feat: view transitions
