### ISSUE TITLE
🐛 BUG: Stackblitz throws error on new React projects via astro.new

### ISSUE THREAD

**Issue by pReya** [withastro/astro#3442] opened 2022-05-25 18:58 UTC
### What version of `astro` are you using?

1.0.0-beta.33

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When creating a new React sandbox via Stackblitz, using the https://astro.new/framework-react?on=stackblitz URL, the project will build successfully, but there is an error in the console:

```
20:54:43 [vite] Internal server error: Cannot set properties of undefined (setting 'isSelfAccepting')
  Plugin: vite:import-analysis
  File: /home/projects/nbwiqmpvq.github/node_modules/.vite/deps/astro_client_visible_js.js?v=3b203b12
      at ModuleGraph.updateModuleInfo (/home/projects/nbwiqmpvq.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:57342:29)
      at TransformContext.transform (/home/projects/nbwiqmpvq.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:57117:57)
      at async Object.transform (/home/projects/nbwiqmpvq.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38900:30)
      at async doTransform (/home/projects/nbwiqmpvq.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:55857:29)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-react?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment] 2022-05-27 20:51
Yep, going to close as a duplicate of #3404. Hoping to tackle that first thing next week.

**Closed by natemoo-re** 2022-05-27 20:51 UTC
