### ISSUE TITLE
Cannot find module 'astro:content'

### ISSUE THREAD

**Issue by azan-n** [withastro/astro#5711] opened 2023-01-01 06:52 UTC
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm, pnpm

### What operating system are you using?

macOS 13

### Describe the Bug

I have been eagerly waiting for even a beta of the Content Collections RFC to start shipping my blog. Thanks to @bholmesdev   I got a chance much earlier than I could expect. I upgraded from 1.6.4(?) to 1.8.0 but I got the TS error `Cannot find module 'astro:content' or its corresponding type declarations.ts(2307)` when trying to import the `defineCollection` function.

## Steps to reproduce
1. `pnpm create astro@latest` or `npm create astro@latest`
2. Create a 'content' directory and create a 'config.ts' within the folder
3. Write `import { defineCollection, z } from "astro:content"` within the 'config.ts'

Continuing with this state of the application leads to no errors during the build or in the dev server.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j2falm?file=content/config.ts

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by azan-n** [comment] 2023-01-02 13:13
> Try running `pnpm astro sync` in your terminal.

I have tried this with `npx`, `pnpm`, and `pnpx` in separate repos. Regardless, the error does not go away.

**Comment by bholmesdev** [comment] 2023-01-02 14:09
@azan-n hm, and do you see a `src/content/types.generated.d.ts` file? If not, there might be something else going wrong. You can also quit and restart your editor, or reset the TS language server using the VS Code command palette (cmd + shift + P): 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/51384119/210242420-c600315a-1941-498d-bc21-625bdfc1c91d.png">

**Comment by bholmesdev** [comment] 2023-01-02 18:01
Update: just realized types only generate if there is at least one `.md` or `.mdx` file inside a collection directory. It won't run on an empty `content/` folder! Let me know if adding a file resolves your issue.

I also agree this is pretty confusing. Will address with a bug fix 👍

**Comment by azan-n** [comment] 2023-01-03 04:10
> do you see a `src/content/types.generated.d.ts` file?

No.



> reset the TS language server

I make it a point after every generation command. I realize TS can be a bit slow to catchup.



> at least one `.md` or `.mdx` file inside a collection directory

In all cases, I have had .md files in nested or the same directory as content/. I have no generated file in it, and the error persists.


> I also agree this is pretty confusing. Will address with a bug fix 👍

Thanks so much for the support. I've had quite some time on my badge writing documentation. I'd love to help with it if required.

**Comment by bholmesdev** [comment] 2023-01-06 21:22
@rizkysaskiaputra Ah yes, I think an empty config file will block type gen as well. I think relaxing the error detection on collection files before generating types would be helpful. Good to know that works for you though!

**Comment by azan-n** [comment] 2023-01-14 07:41
> @rizkysaskiaputra Ah yes, I think an empty config file will block type gen as well. I think relaxing the error detection on collection files before generating types would be helpful. Good to know that works for you though!

My config file has been complete with schema declarations and the import statement. I just updated to 1.9.2 and still face the same issue.

**Comment by bholmesdev** [comment] 2023-01-14 23:52
So glad to hear that @azan-n! To anyone following the thread, you'll find future content collections improvements on the 2.0 beta branch. Install in your projects with `npm i astro@beta`. If you have the MDX integration, bump with `npm i @astrojs/mdx@beta` as well.

**Comment by natguy** [comment] 2023-01-24 04:52
Hello, I'm getting a postCSS / @astrojs/tailwind error when I update this existing project to astro@beta & @astrojs/mdx@beta .

Does @astrojs/tailwind 2.1.3 need to be updated too?

error   Cannot read properties of undefined (reading 'postcss')
  File:
    /Users/.../node_modules/@astrojs/tailwind/dist/index.js:78:22
  Code:
    77 |         const tailwindConfig = (userConfig == null ? void 0 : userConfig.value) ?? getDefaultTailwindConfig(config.srcDir);
    > 78 |         config.style.postcss.plugins.push(tailwindPlugin(tailwindConfig));
         |                      ^
      79 |         config.style.postcss.plugins.push(autoprefixerPlugin);
      80 |         if (applyBaseStyles) {
      81 |           injectScript("page-ssr", `import '@astrojs/tailwind/base.css';`);
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'postcss')

**Dependencies:**

"dependencies": {
    "@astrojs/markdown-remark": "^1.2.0",
    "@astrojs/mdx": "^1.0.0-beta.2",
    "@astrojs/rss": "^2.0.0",
    "@astrojs/sitemap": "^1.0.0",
    "@astrojs/tailwind": "^2.1.3",
    "@astropub/md": "^0.1.4",
    "astro": "^2.0.0-beta.4",
    "tailwindcss": "^3.2.4"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.9"
  }
  
**tailwind.config.cjs:**
  
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {},
	},
	plugins: [
    require('@tailwindcss/typography'),
  ],
}

Note: build and sync didn't fix the missing 'astro:content' module.

Thanks.

**Comment by bholmesdev** [comment] 2023-01-24 12:10
@natguy Ah yes, you'll need to install `@astrojs/tailwind@beta` as well. We've introduced a small breaking changes to the integration internals. Happy to share we _are_ baselining our betas today though, so you'll be free to install `@latest` soon enough 😄

**Comment by Rolanddoda** [comment] 2023-01-27 18:18
Facing the same problem while upgrading to 2.0.2 from 1.9. `.astro` folder is not getting generated. It works when creating a new project though which is very strange. I even tried deleting `node_modules` and `pnpm-lock-yaml` and re-installing but it doesn't work

**Comment by ilievskif** [comment] 2023-01-30 19:26
> @natguy Ah yes, you'll need to install `@astrojs/tailwind@beta` as well. We've introduced a small breaking changes to the integration internals. Happy to share we _are_ baselining our betas today though, so you'll be free to install `@latest` soon enough 😄

This was the solution. Thank you!

**Comment by bholmesdev** [comment] 2023-01-30 19:58
@ilievskif Nice! We just baselined all of our betas, so installing `@latest` for Astro core and the Tailwind integration should do the trick too 🙌

**Comment by bholmesdev** [comment] 2023-04-05 18:24
@MerlinMason Interesting, there _shouldn't_ be anything else to configure here. I assume you tried running `astro sync` or `astro dev` to generate the `astro:content` module?

**Comment by MerlinMason** [comment] 2023-04-06 08:45
Hi Ben, thanks for getting back to me!

Yeah the `.astro/types.d.ts` file exists, I'm running my dev server with `astro check --watch & astro dev`. There's also a `src/env.d.ts` which references the generated types. Regenerating the types with `astro sync` doesn't seem to make a difference.

I'm able to import `astro:content` into my `.astro` pages and the linter is happy, but importing into `rss.xml.js` or `config.ts` and it complains.

Looking inside `.astro/types.d.ts` I can see the following module has been declared 10 times (is that expected?)

```ts
declare module 'astro:content' {
	interface Render {
		'.mdx': Promise<{
			Content: import('astro').MarkdownInstance<{}>['Content'];
			headings: import('astro').MarkdownHeading[];
			remarkPluginFrontmatter: Record<string, any>;
		}>;
	}
}
```

And then there's a few other type definitions, but nothing else that mentions `astro:content`.

**Comment by bholmesdev** [comment] 2023-04-07 13:55
Got it, thanks for confirming @MerlinMason. And that definitely _shouldn't_ be declared 10 times! 😅 I'll look into that separately.

And admittedly... it sounds like everything is wired up correctly for you. I'm wondering if there's some eslint rule that's conflicting here. Can you send your eslint and prettier configs to be sure?

**Comment by MerlinMason** [comment] 2023-04-18 22:01
Hi Ben, apologies for the huge delay here, I've been away on holiday and just catching up with messages - thanks again for looking into this!

Here's my config files, apologies the Eslint config is slightly long.

<details>
<summary>Prettier</summary>

```json
{
    "tabWidth": 4,
    "printWidth": 100,
    "arrowParens": "always",
    "proseWrap": "always",
    "overrides": [
        {
            "files": "*.mdx",
            "options": {
                "printWidth": 80
            }
        }
    ]
}
```

</details>

<details>
<summary>Eslint</summary>

```js
{
    "env": {
        "browser": true,
        "es2021": true,
        "jest/globals": true
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "globals": {
        "React": true,
        "JSX": true
    },
    "processor": "disable/disable",
    "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:react/recommended",
        "plugin:astro/recommended",
        "airbnb",
        "plugin:react/jsx-runtime",
        "plugin:react-hooks/recommended",
        "plugin:jest/recommended",
        "plugin:jest/style",
        "prettier"
    ],
    "plugins": ["react", "@typescript-eslint", "import", "jsx-a11y", "jest", "disable", "prettier"],
    "rules": {
        "import/extensions": 0,
        "import/no-extraneous-dependencies": ["error", { "devDependencies": true }],
        "react/require-default-props": 0,
        "react/function-component-definition": [2, { "namedComponents": "arrow-function" }],
        "react/jsx-filename-extension": [2, { "extensions": [".js", ".jsx", ".tsx", ".mdx"] }],
        "react/jsx-props-no-spreading": 0
    },
    "settings": {
        "react": {
            "version": "detect"
        },
        "import/parsers": {
            "@typescript-eslint/parser": [".ts", ".tsx"]
        },
        "import/resolver": {
            "typescript": {
                "alwaysTryTypes": true // always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
            }
        }
    },
    "overrides": [
        {
            "files": ["**/*.mdx"],
            "extends": ["plugin:mdx/recommended"],
            "settings": {
                "mdx/code-blocks": true,
                "mdx/language-mapper": {}
            }
        },
        {
            // we need to make sure we're not linting js files twice
            "files": ["**/*.js", "**/*.jsx"],
            "settings": {
                "disable/plugins": "@typescript-eslint"
            }
        },
        {
            "files": ["*.astro"],
            "parser": "astro-eslint-parser",
            "parserOptions": {
                "parser": "@typescript-eslint/parser",
                "extraFileExtensions": [".astro"]
            }
        }
    ]
}
```

</details>

**Comment by johny** [comment] 2023-05-10 21:26
This issue should be reopened, its still happening unfortunately  🤷

**Comment by bholmesdev** [comment] 2023-05-17 16:37
@johny Curious if you have a repro different from Merlin's above? This should be handled with [the fixes outlined above](https://www.amazon.com/Importer520-Video-Computer-Monitor-Connector/dp/B00CKV2398?linkCode=df0&hvadid=216534554317&hvpos=&hvnetw=g&hvrand=15386164264052510168&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9003534&hvtargid=pla-350316073408), so I have a feeling we're fixing edge cases now

**Comment by bholmesdev** [comment] 2023-05-17 17:27
@MerlinMason Late reply incoming! I poked around your setup, and I found `eslint-config-airbnb` and the `import` plugin were causing the issue.  

First removing airbnb, I found installing [eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript) fixed any `import/nounresolved` errors. Trying to add airbnb _back,_ a bit of Googling brought me to [eslint-config-airbnb-typescript](https://www.npmjs.com/package/eslint-config-airbnb-typescript). Here's my final eslint and dependencies:

<details>
<summary>.eslintrc.json</summary>

```json
{
    "env": {
        "browser": true,
        "es2021": true,
        "jest/globals": true
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": "latest",
        "sourceType": "module",
        "project": "./tsconfig.json"
    },
    "globals": {
        "React": true,
        "JSX": true
    },
    "processor": "disable/disable",
    "extends": [
        "airbnb",
        "airbnb-typescript",
        "plugin:@typescript-eslint/recommended",
        "plugin:react/recommended",
        "plugin:astro/recommended",
        // "plugin:react/jsx-runtime",
        // "plugin:react-hooks/recommended",
        "plugin:jest/recommended",
        "plugin:jest/style",
        "prettier"
    ],
    "plugins": ["import", "jest", "disable"],
    "rules": {
        "import/extensions": 0,
        "import/no-extraneous-dependencies": ["error", { "devDependencies": true }],
        "react/require-default-props": 0,
        "react/function-component-definition": [2, { "namedComponents": "arrow-function" }],
        "react/jsx-filename-extension": [2, { "extensions": [".js", ".jsx", ".tsx", ".mdx"] }],
        "react/jsx-props-no-spreading": 0
    },
    "settings": {
        "react": {
            "version": "detect"
        },
        "import/parsers": {
            "@typescript-eslint/parser": [".ts", ".tsx"]
        },
        "import/resolver": {
            "typescript": {
                "alwaysTryTypes": true
            }
        }
    },
    "overrides": [
        {
            "files": ["**/*.mdx"],
            "extends": ["plugin:mdx/recommended"],
            "settings": {
                "mdx/code-blocks": true,
                "mdx/language-mapper": {}
            }
        },
        {
            "files": ["**/*.js", "**/*.jsx"],
            "settings": {
                "disable/plugins": "@typescript-eslint"
            }
        },
        {
            "files": ["*.astro"],
            "parser": "astro-eslint-parser",
            "parserOptions": {
                "parser": "@typescript-eslint/parser",
                "extraFileExtensions": [".astro"]
            }
        }
    ]
}
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "@astrojs/markdoc": "^0.1.2",
    "@astrojs/mdx": "^0.19.1",
    "astro": "^2.4.1",
    "eslint-config-airbnb": "^19.0.4",
    "kleur": "^4.1.5",
    "react": "^18.2.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.59.6",
    "@typescript-eslint/parser": "^5.59.6",
    "eslint": "^8.40.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-import-resolver-typescript": "^3.5.5",
    "eslint-plugin-airbnb": "0.0.1-security",
    "eslint-plugin-astro": "^0.27.0",
    "eslint-plugin-disable": "^2.0.3",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-mdx": "^2.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "jest": "^29.5.0",
    "typescript": "^5.0.4"
  }
}
```

</details>

Hope this helps!

**Comment by bholmesdev** [comment] 2023-05-23 22:02
Closing since this issue hasn't seen any replies. Seems reported issues with `astro:content` are linter-specific. Feel free to respond to my messages above as we debug @MerlinMason!

**Closed by bholmesdev** 2023-05-23 22:02 UTC
Labels: p3-minor-bug, content-collections

**Comment by lloydjatkinson** [comment] 2023-06-23 10:59
This is an issue again with Astro 2.7:

```
 FAIL  src/domain/article-query.spec.ts [ src/domain/article-query.spec.ts ]
 FAIL  src/domain/book-query.spec.ts [ src/domain/book-query.spec.ts ]
 FAIL  src/domain/note-query.spec.ts [ src/domain/note-query.spec.ts ]
Error: Failed to load url astro:content (resolved id: astro:content) in /workspace/lloydatkinson.net/src/domain/types.ts. Does the file exist?
```

**Comment by bluwy** [comment] 2023-06-23 13:38
@lloydjatkinson can you open a new issue with a repro? Thanks!

**Comment by RayyanNafees** [comment] 2023-07-22 07:25
I just solved the issue by adding module declaration for `.astro` files in `src/env.d.ts`

```typescript
declare module '*.astro'
```

**Comment by tsevdos** [comment] 2023-09-08 19:00
If you are getting this error while deploying to Cloudflare Pages (SSG), you can resolve it with 2 options:

Either your change your build command to `npx astro sync && npm run build` on Cloudflare's dashboard (very easy solution)

OR 

You generate the types locally by running the sync command locally `npx astro sync` and then commit / push the generated `tsconfig.tsbuildinfo` file to your repo. You only need to do this, if you change your .md / .mdx schema. Finally, you might have this file listed on your .gitignore file so be careful.

**Comment by number44** [comment] 2023-09-19 18:53
I had the same problem.The command "npm run astro check" worked for me.

**Comment by arvi** [comment] 2023-09-30 08:45
Had the same problem and `npm run build` then restarting TS server is what worked for me. 😄

**Comment by AndresdoSantos** [comment] 2023-10-01 18:41
I did everything, `astro sync`, `astro dev`, `astro build`, restart TS and reload window and it didn't work.

**Comment by bennycode** [comment] 2023-10-04 15:29
In my case the error `TS2307: Cannot find module  astro:content` showed in a blank Astro project. I had to run `npm run dev` and afterwards my WebStorm 2023.2.2 was able to find the type definitions for Astro. 🚀

**Comment by pranav-solvative** [comment] 2023-10-06 12:28
> npm run astro check

yes for me also...thank you :)

**Comment by SotaNoniwa** [comment] 2023-12-09 08:55
Runing `npx astro sync` then close VSCode and restart it again resolved mine.

**Comment by Keoooo** [comment] 2023-12-22 01:14
@SotaNoniwa  good fix 🚀

**Comment by IsTheMartin** [comment] 2024-02-10 04:15
Hi all, I'm facing this issue in Astro v4.3.2, is there a workaround or solution for that issue?

I've followed all your comments mentioned above a none of them have helped to me :(

**Comment by rdthree** [comment] 2024-10-30 03:15
I have the same error, driving me up the wall, tried all of the above, oddly my site builds just fine.

![image](https://github.com/user-attachments/assets/4a827dc6-a6ee-4bda-a62e-20868f30ec39)

https://github.com/rdthree/astro-rd3-sketchbook/blob/master/src/content/config.ts

**Comment by piotrkulpinski** [comment] 2024-12-17 15:06
Adding the following line to `tsconfig.json` fixed those issues for me: 
```
"include": [".astro/types.d.ts", "**/*"],
```

**Comment by WillDelish** [comment] 2024-12-28 20:54
Fyi to anyone who stumbles here from google search'n, I had to change this in my astro file to get typescript happy:

`"extends": "astro/tsconfigs/base",` instead of `"extends": "astro/tsconfigs/strict",` + restart typescript server in VS code. This made a few astro imports work just fine, a relic from migrating to Astro v5 it seems.

**Comment by bholmesdev** [comment] 2025-01-06 15:18
@WillDelish hm, relaxing typescript settings shouldn't be a requirement for using `astro:` modules. Think you can reproduce this [in a GitHub issue](https://github.com/withastro/astro/issues/new/choose)?

**Comment by JoepKockelkorn** [comment] 2025-02-22 19:44
Somehow I experienced this issue as well because I had this import:
```typescript
import { z, type RenderedContent } from 'astro:content';
```

Versions I used:
```
Astro                    v5.3.0
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/partytown
```

I thought I found a workaround by explicitly installing zod and changing the type import so I'm not using "real" code from the `astro:content` import:
```typescript
import type { RenderedContent } from 'astro:content';
import { z } from 'zod';
```

This worked locally,  but not in CI. Then I moved some code around and then it worked in CI as well. You can find my commits here on this PR: https://github.com/JoepKockelkorn/joepkockelkorn.com/pull/69. My first commit where it started failing is [this one](https://github.com/JoepKockelkorn/joepkockelkorn.com/pull/69/commits/dac1eba58b6c1b8b846826656e244cd4d70819cf).

**Comment by njfamirm** [comment] 2025-04-21 05:04
I'm use astro sync, but currently have same issue, tsconfig is correct

**Comment by c100k** [comment] 2025-06-20 14:35
> Why do we have to do all this nonsense? Moreover, the problem is not fixed! It is a disaster to produce patch solutions without knowing what the problem is.

To be honest, I cannot agree more with this. In all seriousness, I'm trying to migrate my docs from Next.js to Astro because I heard only good things about it. But encountering this issue straight after installing astro makes me question my choice.

When executing `pnpm astro sync`, it gives the following output:

```sh
Auto-generating collections for folders in "src/content/" that are not defined as collections.
This is deprecated, so you should define these collections yourself in "src/content.config.ts".
The following collections have been auto-generated: docs
```

I'd be glad to define them myself instead of relying on imports that go red if I don't sync. But the [documentation](https://docs.astro.build/en/guides/integrations-guide/mdx/#usage) does not explain how.

Is there a way to simply create a MDX page (in `pages/`) instead of all of this ?

**Comment by dmitrykaigorodov** [comment] 2025-10-22 08:57
Facing this problem today

**Comment by florian-lefebvre** [comment] 2025-10-22 12:38
Hi! This is an old issue, please open a new one with a reproduction so it doesn't get lost
