### ISSUE TITLE
🐛 BUG: Vite configuration in astro.config.mjs not working

### ISSUE THREAD

**Issue by jaimytaco** [withastro/astro#2776] opened 2022-03-12 18:05 UTC
### What version of `astro` are you using?

0.23.7

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Astro doesn't respect vite configuration in astro.config.mjs.

With this configuration, the assets folder should be renamed 'static'.

```
export default {
  vite: {
    build: {
      assetsDir: 'static'
    }
  }
}
```

If you want this to work you are force to use a vite.config.ts file with this:

```
import { defineConfig } from 'vite'
export default defineConfig({
    build: {
        assetsDir: 'assets'
    }
})
```

Also tried with other Vite's build configurations with same luck.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-njkbwr

**Comment by FredKSchott** [comment] 2022-03-14 03:59
Astro only supports partial `vite` configuration, many are either overwritten by Astro or not respected for various reasons. For `assetsDir` specifically, you're not seeing any changes because Astro owns the `public` directory, not Vite. Vite is probably getting that config correctly, but Astro continues to use `public`.

I think that clear warning messages here when you use unsupported Vite config would be very useful! That probably won't be prioritized by core until we are closer to v1.0, but if anyone would like to contribute something soon I'd be happy to help you create a PR.

**Comment by FredKSchott** [comment] 2022-03-14 04:01
Closing as expected behavior. The config that you are probably looking for is: https://docs.astro.build/en/reference/configuration-reference/#public

#2782 created to track better warnings

**Closed by FredKSchott** 2022-03-14 04:01 UTC

**Comment by leifmarcus** [comment] 2022-11-18 13:01
@jaimytaco we tried in our project to set aliases in Vite that will work in vue components.  We created an astro integration as follows

```ts
// file: ./src/integrations/viteConfig.ts
import type { AstroIntegration } from 'astro';

export default (): AstroIntegration => {
  return {
    name: 'project-name-vite-config',
    hooks: {
      'astro:config:setup': ({ updateConfig }) => {
        updateConfig({
          vite: {
            resolve: { alias: { /*...*/ } }
          },
        });
      },
    },
  };
};
```

After this, the aliases could be resolved as expected.
