### ISSUE TITLE
Middleware intermittently not working on iOS/ARM

### ISSUE THREAD

**Issue by ZeldOcarina** [withastro/astro#8191] opened 2023-08-22 15:43 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I have a tried a clean install of Astro with npm create astro@latest but I just cannot get my `middleware.ts` to run.

I need to pass to components some context data and perform some global transformations on my response data but cannot do that.

### What's the expected result?

Middleware running correctly.
Not flagging willing to submit a pull request as I would not know where to start from.

### Link to Minimal Reproducible Example

https://github.com/ZeldOcarina/astro-middleware-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment] 2023-08-22 16:31
I just checked out your repro and I could see the log

![Screenshot 2023-08-22 at 17 31 15](https://github.com/withastro/astro/assets/602478/3c11d2e2-e171-4849-b27d-7d7b34cb9212)

**Comment by ZeldOcarina** [comment] 2023-08-22 16:49
![image](https://github.com/withastro/astro/assets/42982095/d1473034-99cd-4eb6-bb4c-f6640700fada)
Well I don't see it.. :( I am using npm, may that be a factor?

**Comment by ZeldOcarina** [comment] 2023-08-22 16:57
@ematipico I think you closed this a little too hastily.. :(

**Comment by ematipico** [comment] 2023-08-22 17:07
Even with `npm`, I can see the log. It's essential to be able to replicate the issue. And I am using a mac like you.

**Comment by natemoo-re** [comment] 2023-08-22 18:54
Here's a [StackBlitz repro](https://stackblitz.com/edit/github-yrtoof?file=src%2Fmiddleware.ts), which definitely seems to be working.

@ZeldOcarina could you run `npx astro info` and share the output?

**Comment by ZeldOcarina** [comment] 2023-08-22 18:56
Of course!!

```
mattiarasulo@Host-006 astro-test % npx astro info

Astro version            v2.10.12
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             None or couldn't determine.
```

**Comment by lilnasy** [comment] 2023-08-23 14:13
Couldn't reproduce on windows or linux.

**Comment by ematipico** [comment] 2023-08-23 15:02
@ZeldOcarina it's possible that your terminal doesn't log for some reason. Why don't you try to **use** it by doing writing something into `context.locals`, or something else.

**Comment by ZeldOcarina** [comment] 2023-08-23 15:54
Hi! All logs on standard routes etc. work properly. It's only the middleware that is not running at all, it's so weird..
May it be the M1 architecture?

**Comment by lilnasy** [comment] 2023-08-23 15:56
Did you check if the middleware gets executed?

**Comment by ZeldOcarina** [comment] 2023-08-23 16:13
I did by hardcoding some locals and no locals is being passed down to the components etc..

**Comment by lilnasy** [comment] 2023-08-23 16:22
Could you upload the dist folder somewhere, maybe in a branch.

That would at least rule out an astro bug from something about your environment.

**Comment by ZeldOcarina** [comment] 2023-08-23 16:35
Of course!
I've added the `dist` folder under the same branch!
Builded the app and removed `dist` from `.gitignore`.
Thanks a lot for your help!

**Comment by lilnasy** [comment] 2023-08-23 16:49
Ah, it's a static build. `/dist` contains only html, css, and js.

It maybe worth adding an adapter (`npm run astro add node`) to see if you get the issue in the final build (`node dist/server/entry.mjs`) as well.

**Comment by ZeldOcarina** [comment] 2023-08-23 16:52
Ok done!
Interesting the middleware is called _empty-middleware for some reason and it's actually empty!

**Comment by lilnasy** [comment] 2023-08-23 17:11
Ok, I see what you see now — not "Request received!".

Building again myself runs the middleware and logs to the console.

Not sure what the issue is. Best guess: you need reinstall astro, or node. Run npm and other commands in a container if that doesn't work.

**Comment by ZeldOcarina** [comment] 2023-08-23 17:15
That's super weird.. I even tried with Bun and yarn..

**Comment by ZeldOcarina** [comment] 2023-08-23 17:18
I can confirm building in a Codespace container is working.
I think still this should be investigated as it's a very weird behavior..

**Comment by lilnasy** [comment] 2023-08-23 17:19
It's hard to investigate because as far as I can tell, the cause is is somewhere on your system.

**Comment by ZeldOcarina** [comment] 2023-08-23 17:21
I will try to open a remote M1 from a service I know and see if I can reproduce there.. it may be something that has to do with the ARM architecture..

**Comment by ematipico** [comment] 2023-08-23 17:35
I think the best course of action is creating a thread on discord, in the support channel, and chat with people there.

This seems to be an issue specific to someone machine/environment and unfortunately it's very hard to debug unless you do it yourself from the source code.

**Comment by ZeldOcarina** [comment] 2023-08-23 18:09
Ha I got it!
Bug happens only if I clone the repo on my external SSD, won't happen on my main drive.
Do you have an external disk you can try it on @ematipico?

**Comment by ematipico** [comment] 2023-08-23 19:26
I don't think there's much we can do. This is something related to your machine and environment, I can't look for an external hard drive 😅

**Comment by natemoo-re** [comment] 2023-08-23 19:43
Wow that is very strange! I have no idea what could be causing this problem when running on an external SSD. I agree that there's probably not much we can do, since it seems so environment specific... I tried searching through Vite, Rollup, Node issues but can't seem to find anything similar to this either.

**Comment by lilnasy** [comment] 2023-08-23 19:50
There is this one issue: https://github.com/withastro/astro/issues/8164#issuecomment-1686046234.

**Comment by ZeldOcarina** [comment] 2023-08-23 20:39
Yeah so far only pnpm has always refused to work on the external SSD but I guess next time I will need to upgrade my Mac for that super expensive Apple storage instead of hacking together an NVME enclosure..
Thanks for your time, closing this for now!

**Comment by WinnieS0728** [comment] 2023-09-20 09:17
same issue here

using `mac mini m2 macOS 13.5.2（22G91）`

node version `v18.16.0`
npm version `9.5.1`
bun version `1.0.2`

package.json :
```
  "dependencies": {
    "@astrojs/node": "^6.0.0",
    "astro": "^3.1.1"
  }
```

astro.config :
```
import { defineConfig } from 'astro/config';

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({});
```

also tried node adapter 
```
import { defineConfig } from 'astro/config';

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: node({
    mode: "standalone"
  })
});
```

and the result here (all test get same result)

![image](https://github.com/withastro/astro/assets/116339731/a810fc02-8d4b-4100-abf0-46d2bb0ad668)

i clone your astro-middleware-bug repo and get the same issue.

tried npm and bun both not working

realy wierd.

**Comment by ematipico** [comment] 2023-09-20 09:53
It really is. All the similar issues that I've seen so far are around project saved in file system that is different from the one where the OS is saved.

**Comment by WinnieS0728** [comment] 2023-09-20 11:54
thanks for replying.

not working in my macbook pro M1. 😢

both my device doesn't have external drives, only the default built-in SSD.

so in my situation I don't know how to fix it.

maybe it's my personal setting error.

I will post my install detail tomorrow, or borrow a windows OS laptop and try again.

**Comment by ZeldOcarina** [comment] 2023-09-20 13:59
Could it be something related to the file system formatting? Maybe the error is in APFS or something like that?

**Comment by ZeldOcarina** [comment] 2023-09-20 16:18
@lilnasy I think you do have a reproduction repo, let's not be too picky on that.. issue should not be closed..

**Comment by lilnasy** [comment] 2023-09-20 16:23
So far I thought the linked repo would reproduce the issue on an external disk. But if someone is encountering the bug without it, there's probably another factor to consider.

Either way, I marked it as need repro because it's not an actionable issue, it's just going to sit here.

**Comment by ZeldOcarina** [comment] 2023-09-20 16:26
Ok thanks! :)

**Comment by WinnieS0728** [comment] 2023-09-21 01:32
here is my install detail

+ type `npm create astro@latest` in folder terminal, and choose some setting.

![image](https://github.com/withastro/astro/assets/116339731/c853a6e1-0d14-4066-938a-2b0b2da7bbad)

i get this dependencies in package.json

```
  "dependencies": {
    "astro": "^3.1.1"
  }
```

+ add `middleware.ts` inside src folder

+ type `tree -I node_modules` and now my project look like this.

![image](https://github.com/withastro/astro/assets/116339731/8912d649-f9fb-4ff1-9eb2-720579b947e3)

+ inside `middleware.ts` export a onRequest function

```
import { defineMiddleware } from "astro:middleware";

export const onRequest = defineMiddleware((context,next)=>{
    console.log('middleware');

    return next()
}) 
```

+ inside `pages > index.astro` add ` console.log('page') ` in frontmatter

+ run `npm run dev` and go to http://localhost:4321/

now i got this issue

![image](https://github.com/withastro/astro/assets/116339731/28a1aff7-8d61-48a5-b0f9-aabf2c73174d)

no 'middleware' but only 'page' in terminal log

seems like my onRequest didn't work 🫠.

did i miss any step or do anything wrong ??

I publish this folder to a github repo.

[github repo link](https://github.com/WinnieS0728/middleware-demo)

can anyone test if this is my personal issue.

thanks for reading this long post.

glad to get any advice.

**Comment by lilnasy** [comment] 2023-09-21 01:42
@WinnieS0728 Pretty sure it's something about your (and ZeldOcarina's) system.
<img width="371" alt="image" src="https://github.com/withastro/astro/assets/69170106/53d5874e-73e8-4da5-8a01-f66f1d9a902b">

**Comment by WinnieS0728** [comment] 2023-09-21 01:58
well i just `create a new folder` and do

+ type `git clone https://github.com/WinnieS0728/middleware-demo`

+ cd ./middleware-demo

+ npm i 

+ npm start

still got same issue.

![image](https://github.com/withastro/astro/assets/116339731/45000b95-4aea-4548-941d-971f3177b5fe)

but when i do these same step inside my `github folder`

and look what i got

![image](https://github.com/withastro/astro/assets/116339731/4e9954c7-b4cc-4402-90ab-de3dd467b545)

now thing become SUPER WIERD 🤣

**Comment by lilnasy** [comment] 2023-09-21 02:04
@WinnieS0728 Your investigation might be really helpful!

You have traditional chinese characters in the path in the first case where you encounter the issue.

Could you post a screenshot where you run the `pwd` command in both cases?

And see if adding a chinese character to the `GitHub` directory names breaks it as well.

**Comment by WinnieS0728** [comment] 2023-09-21 02:07
+ chinese characters new folder

**Comment by WinnieS0728** [comment] 2023-09-21 02:21
## chinese characters new folder

pwd 
/Users/winnie.chang/Desktop/未命名檔案夾

result
![image](https://github.com/withastro/astro/assets/116339731/aaea7972-dd47-48b6-80b3-b817549ae36b)

## english characters new folder

pwd
/Users/winnie.chang/Desktop/new folder

result
![image](https://github.com/withastro/astro/assets/116339731/8f734e92-6644-4a1d-8415-175f2c7b1270)

## chinese characters new folder in github folder

pwd
/Users/winnie.chang/Documents/GitHub/未命名檔案夾/middleware-demo

result
![image](https://github.com/withastro/astro/assets/116339731/b6861b01-13d5-4c8d-979b-eb75a96b2aa4)



## english characters new folder in github folder

pwd
/Users/winnie.chang/Documents/GitHub/new folder in github

result
![image](https://github.com/withastro/astro/assets/116339731/70a2e79a-71f8-4858-9e61-7d3466810f29)

## direct inside github folder

pwd
/Users/winnie.chang/Documents/GitHub

result
![image](https://github.com/withastro/astro/assets/116339731/99c1f04e-2b58-4113-ad94-3a10a3f52a97)


seems like only work direct inside github folder

**Comment by lilnasy** [comment] 2023-09-21 02:28
> english characters new folder in github folder
/Users/winnie.chang/Documents/GitHub/new folder in github

Could you remove spaces from this folder. Maybe `/Users/winnie.chang/Documents/GitHub/new/`.

**Comment by WinnieS0728** [comment] 2023-09-21 02:35
## new folder without space in github folder

pwd
/Users/winnie.chang/Documents/GitHub/new

result
![image](https://github.com/withastro/astro/assets/116339731/fa389a20-43c3-4da8-8ca5-455cebe05e58)

## new folder without space

pwd
/Users/winnie.chang/Desktop/newFolder

result
![image](https://github.com/withastro/astro/assets/116339731/fc355fcf-82c7-4962-99b5-3dd1664889a5)

i think you just resolve the issue 🥳.

**Comment by lilnasy** [comment] 2023-09-21 02:40
@ZeldOcarina Is there a space in the full path in your project?

**Comment by lilnasy** [comment] 2023-09-21 02:43
I can reproduce the issue on linux. middleware-demo -> "middleware demo" (with space)
<img width="371" alt="image" src="https://github.com/withastro/astro/assets/69170106/de535b23-565b-4cad-81ec-2fbcdc81e705">

**Comment by WinnieS0728** [comment] 2023-09-21 02:58
so i think maybe is not personal issue ?

I don't know about detail, but I'm guessing is something like astro compiler detect folder name when build running env can't read space or chinese ?

**Comment by lilnasy** [comment] 2023-09-21 03:04
@WinnieS0728 The fix in #8614 should work for chinese characters as well.

**Comment by WinnieS0728** [comment] 2023-09-21 03:15
how about the space.

in my case i typed space almost 80% of my project if name have more than 1 words.

the chinese characters '未命名檔案夾' is means 'unnamed folder', and it's the default name when create a new folder in my mac.

i almost never use chinese characters in my projects.

**Comment by lilnasy** [comment] 2023-09-21 03:16
Both spaces and non-english characters are fixed.

**Comment by WinnieS0728** [comment] 2023-09-21 03:21
Thank you so so so much.

I search this issue almost a day around google, youtube and even Bing AI.

no one have same issue 🫠.

thanks for your help.

**Comment by lilnasy** [comment] 2023-09-21 03:22
Thank you, you're the one who figured what the problem even is! Fixing is the easy part.

**Closed** 2023-09-21 05:35 UTC
Labels: - P2: has workaround, feat: middleware

**Comment by ZeldOcarina** [comment] 2023-09-21 06:08
whoo whoo thanks a bunch @lilnasy @WinnieS0728 !
Yes there was some blank spaces in my OS. Sorry if the issue name was misleading, we made it!
