### ISSUE TITLE
🐛 BUG: Svelte components with the `client:only` don't render out their `<slot />`

### ISSUE THREAD

**Issue by austinjherman** [withastro/astro#2215] opened 2021-12-16 21:34 UTC
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Svelte components with the `client:only` directive do not render out their `<slot />`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-agx2hb?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by jonathantneal** [comment] 2022-01-21 23:42
Verified. Definitely seems related to https://github.com/withastro/astro/issues/2265

**Comment by tony-sull** [comment] 2022-02-15 10:45
Based on the investigation in #2265, this is related to how Astro currently handles slots in `client:only` and shouldn't be framework specific

Closing this out as a duplicate of #2265 as the primary issue since it has a bit extra detail in follow-up comments 👍

**Closed by tony-sull** 2022-02-15 10:45 UTC
