### ISSUE TITLE
Cannot process image using Astro Image component - missing Sharp in dev

### ISSUE THREAD

**Issue by mpmccauley** [withastro/astro#9536] opened 2023-12-27 22:37 UTC
### Astro Info

```block
Astro                    v4.0.8
Node                     v19.3.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

New empty Astro site created. The only actions performed were adding an image stored in `src/assets` to the index page via Astro image component (https://docs.astro.build/en/guides/images/#image--astroassets).

The docs mention needing to manually install Sharp if using pnpm, but I was using npm.

After running `npm run dev`, i get the following error in the terminal:

```
Could not process image request: MissingSharp: Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (/home/mike/code/test/sharp-test/node_modules/astro/dist/assets/services/sharp.js:19:11)
    at async Object.transform (/home/mike/code/test/sharp-test/node_modules/astro/dist/assets/services/sharp.js:31:15)
    at async Module.GET (/home/mike/code/test/sharp-test/node_modules/astro/dist/assets/endpoint/node.js:67:30)
    at async callEndpoint (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/core/endpoint/index.js:124:16)
    at async #tryRenderRoute (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/core/pipeline.js:119:16)
    at async DevPipeline.renderRoute (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/core/pipeline.js:58:20)
    at async handleRoute (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/vite-plugin-astro-server/route.js:248:18)
    at async run (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/vite-plugin-astro-server/request.js:50:14)
    at async runWithErrorHandling (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
    at async handleRequest (file:///home/mike/code/test/sharp-test/node_modules/astro/dist/vite-plugin-astro-server/request.js:44:3) {
  loc: undefined,
  title: 'Could not find Sharp.',
  hint: "See Sharp's installation instructions for more information: https://sharp.pixelplumbing.com/install. If you are not relying on `astro:assets` to optimize, transform, or process any images, you can configure a passthrough image service instead of installing Sharp. See https://docs.astro.build/en/reference/errors/missing-sharp for more information.\n" +
    '\n' +
    'See https://docs.astro.build/en/guides/images/#default-image-service for more information on how to migrate to another image service.',
  frame: undefined,
  type: 'AstroError'
}
```

### What's the expected result?

I would expect the Image component to work without needing to manually install Sharp based on the docs. Also, even after installing Sharp, the error is still there.

### Link to Minimal Reproducible Example

https://github.com/mpmccauley/sharp-test

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-12-27 22:41
Duplicate of https://github.com/withastro/astro/issues/9345, Node 19 is unsupported, I'd recommend updating to Node 20, deleting node_modules and trying to install again

**Closed by Princesseuh** 2023-12-27 22:41 UTC
Labels: needs triage

**Comment by mpmccauley** [comment] 2023-12-28 01:41
Thanks for the quick reply! The installation instructions show >18 is okay so I figured 19 would be fine. Upgrading and reinstalling worked!

**Comment by LouisJS** [comment] 2023-12-28 22:26
Astro v4.0.8
Node v20.10.0
System macOS (x64)
Package Manager npm
Output server
Adapter @astrojs/vercel/serverless
Integrations @astrojs/react
@astrojs/tailwind

Using npm run dev in development works. But as soon as i host it on Vercel : https://louis-lecocq.vercel.app/

**Comment by silveltman** [comment] 2024-01-07 13:18
I'm still having the same issue with the following setup:
```
Astro                    v4.1.1
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
                         @astrojs/sitemap
                         astro-robots-txt
                         bookshop
                         unocss

**Comment by hirasso** [comment] 2024-11-10 12:02
The pnpm equivalent is `pnpm add sharp`. I'm installing it in my GitHub workflow like this:

```yaml
#...
# @see https://pnpm.io/continuous-integration#github-actions
- name: Setup and install pnpm
  uses: pnpm/action-setup@v4
  with:
    run_install: true

# Astro needs sharp to process images. Sharp is not installed automatically in CI
# @see https://github.com/withastro/astro/issues/9536#issuecomment-1880058215
- name: Install sharp
  run: pnpm add sharp
#...
```
