### ISSUE TITLE
(low priority) Extracted CSS are always named based on the first page they were fond, not the layout which include them

### ISSUE THREAD

**Issue by mschoeffmann** [withastro/astro#7696] opened 2023-07-18 01:51 UTC
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome (latest), Safari (latest)

### Describe the Bug

When a CSS is imported inside a layout, and then used by multiple pages in multiple subdirectories, this CSS gets the filename of the very first rendered page where the CSS file was needed.

I think a more defined name like the name of the layout or something not so random would be more clear?

You see in attached StackBlitz after `astro build`:
The CSS is named `test-a.hash.css` (first page) instead of `default.hash.css` (layout).

Even if this is not a major thing, it makes it hard to find sources of issues on already deployed sites.

### What's the expected result?

A more "undefined" name for the global CSS. Like "hoisted" for the scripts. Or the name of the including layout.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-css-file-naming?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-07-18 07:28
Duplicate of https://github.com/withastro/astro/issues/7469

**Closed** 2023-07-18 07:28 UTC
Labels: needs triage
