### ISSUE TITLE
SyntaxError: Identifier 'prevRefreshReg' has already been declared

### ISSUE THREAD

**Issue by taoeffect** [withastro/astro#8578] opened 2023-09-16 03:10 UTC
### Astro Info

```block
Astro                    v3.1.0
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          unknown  (it's npm 10.1.0)
Output                   static
Adapter                  none
Integrations             @astrojs/preact
                         @astrojs/react
                         @astrojs/mdx
```

### Describe the Bug

![Screenshot 2023-09-15 at 8 07 07 PM](https://github.com/withastro/astro/assets/138706/4b0517bb-bdb2-40d2-a778-d16526c1a17a)

We are using the Astro docs template (I think it's the same one Astro docs is based on, which seems to no longer be advertised on the themes page for some reason) for our documentation.

After updating all our dependencies, including the latest version of Astro, we're seeing the above console errors.

I don't know how to create a minimal reproducible example of this, but you can reproduce by cloning this repo and using the branch `fix-deps`: https://github.com/okTurtles/shelterprotocol.net/tree/fix-deps

I did my best to search these issues for this error, as well as the Discord, and couldn't find anything, and am at my wit's end on figuring out why this is happening, because the variable `prevRefreshReg` doesn't even appear anywhere in our code, so it must be coming from one of the astro/react dependencies.

### What's the expected result?

For there to be no console errors.

### Link to Minimal Reproducible Example

https://github.com/okTurtles/shelterprotocol.net/tree/fix-deps

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment] 2023-09-16 07:35
@taoeffect

Can you link the starter repo that you're using? Happy to get a fix out.

**Comment by taoeffect** [comment] 2023-09-16 15:30
@rishi-raj-jain Do you mean the documentation template? I wish I could but I don't remember where it was, and it's not longer on the Astro themes page for some reason.

**Comment by rishi-raj-jain** [comment] 2023-09-16 16:40
@taoeffect do you see anything on https://github.com/withastro/astro/tree/main/examples?

**Comment by rishi-raj-jain** [comment] 2023-09-16 16:41
It might have been taken down? Not sure though. For documentation, you should have a look at starlight.astro.build, super cool documentation!

**Comment by rishi-raj-jain** [comment] 2023-09-16 16:41
Let me know if the issue is still there or we need to close this issue.

**Comment by taoeffect** [comment] 2023-09-16 16:59
@rishi-raj-jain 

> @taoeffect do you see anything on https://github.com/withastro/astro/tree/main/examples?

No, but I think I found it!

https://github.com/astro-community/astro/tree/main/examples/docs

**Comment by bluwy** [comment] 2023-09-18 08:36
You're using both the [react and preact integration](https://github.com/okTurtles/shelterprotocol.net/blob/96e3c2249b3ad53df2e335bf7575a9ea86dc93c6/astro.config.mjs#L10-L11) without setting `include`, which means both integrations will try to process your `.tsx` files, which causes the error.  It's documented [here](https://docs.astro.build/en/guides/integrations-guide/react/#combining-multiple-jsx-frameworks).

**Closed by bluwy** 2023-09-18 08:36 UTC
Labels: needs triage

**Comment by bluwy** [comment] 2023-09-18 08:41
That repo isn't maintained by us. It looks like a community fork and only supports Astro v2. I'm looking at the original repro in the issue description.

**Comment by rishi-raj-jain** [comment] 2023-09-18 08:43
@bluwy 

But I see the people in https://github.com/astro-community is the team at Astro (Sarah, Peter). Might want to atleast put a notice in the readme?

**Comment by taoeffect** [comment] 2023-09-20 15:55
> You're using both the [react and preact integration](https://github.com/okTurtles/shelterprotocol.net/blob/96e3c2249b3ad53df2e335bf7575a9ea86dc93c6/astro.config.mjs#L10-L11) without setting include, which means both integrations will try to process your .tsx files, which causes the error. It's documented [here](https://docs.astro.build/en/guides/integrations-guide/react/#combining-multiple-jsx-frameworks).

Thank you @bluwy 🙏 

We got it working 👍
