### ISSUE TITLE
🐛 BUG: Regular expression in getStaticPaths freezes dev server/build process

### ISSUE THREAD

**Issue by delucis** [withastro/astro#2935] opened 2022-03-29 18:46 UTC
### What version of `astro` are you using?

0.25.4

### What package manager are you using?

npm (8.5.0)

### What operating system are you using?

macOS 12.2.1 / Stackblitz

### Describe the Bug

Using a regular expression within `getStaticPaths` causes both the dev server and the build process to hang.

**Example**

```astro
export function getStaticPaths() {
  const posts = Astro.fetchContent('../../content/*.md');
  return posts.map(post => ({ 
    params: {
      slug: post.file.pathname
        .split('/')
        .pop()
        .replace(/\.md/, ''), // <-- Using a RegExp here breaks `getStaticPaths`!
    },
    props: { title: post.title },
  }));
}
```

`astro dev` hangs when you access a URL that matches the file pattern containing the relevant `getStaticPaths`. `astro build` just hangs. There’s no output (just a silent Node process clocking in 100% CPU in my activity monitor), so I haven’t been able to debug further.

In the Stackblitz reproduction I have two dynamic routes. One with the above example code, the other that just uses a string in the `replace` function call. Only the route with the regular expression triggers the bug.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-oggtm5?file=src/pages/broken-posts/[slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Edgars-DP** [comment] 2022-03-30 05:44
Duplicate of https://github.com/withastro/compiler/issues/323, that is a de-stale of https://github.com/withastro/astro/issues/2043

**Comment by delucis** [comment] 2022-03-30 06:10
Thanks — didn't think to check the compiler repo, but definitely looks like the same bug. (I'll leave this open for core to triage in case https://github.com/withastro/compiler/issues/323 has been overlooked.)

**Comment by natemoo-re** [comment] 2022-03-30 17:02
Thanks @Edgars-DP and @delucis! It's definitely still being tracked in https://github.com/withastro/compiler/issues/323, hoping to tackle it ASAP.

I'm going to close this in favor of https://github.com/withastro/compiler/issues/323.

**Closed by natemoo-re** 2022-03-30 17:02 UTC
