### ISSUE TITLE
🐛 BUG: Vite plugin has been applied twice

### ISSUE THREAD

**Issue by antfu** [withastro/astro#1969] opened 2021-11-22 16:21 UTC
### What version of `astro` are you using?

^0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Mac / Linux

### Describe the Bug

Any plugins defined in astro.config.js will be applied twice

```ts
  {
    name: 'my-plugin',
    configResolved(config) {
      console.log(config.plugins.map((i) => i.name));
    },
  }
```

you will see `my-plugin` shows up twice

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5hwrzj-xrj4dg?file=my-plugin.mjs&on=stackblitz

**Comment by matthewp** [comment] 2021-11-22 17:46
Thanks! I think this is caused by the fact that we are loading code in SSR and then also running the build. I'll debug it to confirm though.

I'm assuming the reason this is a problem is that your plugin is keeping state within the plugin's closure? I've noticed in some of the core vite plugins that they use the config as a key in a WeakMap, I wonder if this is the reason why.

I'll reach out to the Vite team and see if they consider this a bug (after I've debugged it enough to confirm what I think is happening is what's happening).

**Comment by matthewp** [comment] 2021-11-29 14:36
As this is expected behavior with how our build currently works, I'm going to close this bug. Will note that in a future iteration of the build process this should no longer happen, however.

The fact that the Vite plugins run twice is a deficiency of Astro and not something that plugins should have to worry about or try to work around.

**Closed by matthewp** 2021-11-29 14:36 UTC
