### ISSUE TITLE
🐛 BUG: Tailwind Breakpoints not working correctly in .jsx files in Astro Framework

### ISSUE THREAD

**Issue by ArshdeepSahni** [withastro/astro#2823] opened 2022-03-17 16:08 UTC
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

# Bug
The `lower screen size breakpoint` is contradicting and getting applied instead of the `actual/higher screen size breakpoint` (for e.g. in the `screen size of md`, the `md:class` is not getting applied and instead the `sm:class` is getting applied)

# Minimal Reproducible Example
In the components Directory, In the Counter.jsx file, 
There a `- button` in which i 've assigned the classes with breakpoints : `text-lg md:text-5xl`

<img width="577" alt="Screenshot 2022-03-17 at 9 37 25 PM" src="https://user-images.githubusercontent.com/56549294/158843308-27eee35a-7697-46db-83ec-377f90aa0895.png">

## Mobile View
<img width="467" alt="Screenshot 2022-03-17 at 9 34 58 PM" src="https://user-images.githubusercontent.com/56549294/158842805-b5b1639f-6db2-46e0-ad4a-9e3e99f9fdf6.png">

## Web View
<img width="186" alt="Screenshot 2022-03-17 at 9 34 49 PM" src="https://user-images.githubusercontent.com/56549294/158842813-2525dec6-a7a9-421d-8188-533108d749a6.png">

# Problem
No change in Font Size of the `- Button`

### Link to Minimal Reproducible Example

https://codesandbox.io/s/zealous-edison-2ix5es?file=/src/components/Counter.jsx

**Comment by natemoo-re** [comment] 2022-03-17 16:18
I see Tailwind classes in the reproduction, but no code that initializes Tailwind itself (a CSS file with `@tailwind base;`).

Please update your reproduction to follow our [Tailwind Guide](https://docs.astro.build/en/guides/styling/#-tailwind) so we can determine if this is still an issue.

**Comment by jrcharles** [comment] 2022-03-18 16:42
I also have this issue

Even just importing in the tailwind UI.  Expected output.
<img width="1283" alt="Screen Shot 2022-03-18 at 12 41 40 PM" src="https://user-images.githubusercontent.com/29494771/159045723-a2937083-9ddc-4222-8ff5-ce2d8ddb2788.png">

Actual output
<img width="1680" alt="Screen Shot 2022-03-18 at 12 41 29 PM" src="https://user-images.githubusercontent.com/29494771/159045778-d6b6ba3d-e710-4474-b3d1-89cc6160fa49.png">

**Comment by SebasG22** [comment] 2022-03-20 15:19
This is happening when I migrate the `"astro": "~0.23.0",` to `"astro": "~0.24.0",`.

The styles for mobile are always applied on bigger screens.
"astro": "~0.23.0" works fine

**Comment by adrianbarbic** [comment] 2022-03-21 06:20
I am seeing the same issue. Mobile styles being show on desktop when upgrading to 0.24.3 (currently on 0.23.7 and styles are working fine.)

**Comment by MKlblangenois** [comment] 2022-03-21 09:51
Same error here.

With `astro@0.23.x` (with ` --experimental-static-build`) and `astro@0.24.x`, the compiled file show a double backslash on prefixed Tailwind classes :

![Capture d’écran 2022-03-21 à 10 48 37](https://user-images.githubusercontent.com/42929225/159237843-b5d8b2fc-c2a8-46ae-bac9-8c9be51c14d3.png)

**Comment by tony-sull** [comment] 2022-03-23 09:25
Looks like the reproduction linked above is using Tailwind's playground CDN, this should be working fine with tailwind installed similar to our `with-tailwindcss` starter ([Stackblitz reproduction](https://stackblitz.com/edit/github-z3kqux?file=src%2Fcomponents%2FCounter.jsx))

@MKlblangenois are you seeing that double slash issue on `0.24.3`?  I checked the output in `dev` and `build` in the Stackblitz link above and am only seeing one slash.  Any chance you can share a link to the project where you're seeing that double escaping problem so I can dig in a bit deeper?

**Comment by MKlblangenois** [comment] 2022-03-23 09:56
> @MKlblangenois are you seeing that double slash issue on `0.24.3`? I checked the output in `dev` and `build` in the Stackblitz link above and am only seeing one slash. Any chance you can share a link to the project where you're seeing that double escaping problem so I can dig in a bit deeper?

Yes ! I can reproduce this issue even on [Stackblitz](https://stackblitz.com/edit/astrotailwind-doubleslash-issue) based on my starter theme. (package updated, tried with node `14` and `16`).

Github repo url : https://github.com/MediakodTeam/astro-tailwind-doubleslash-issue
Stackblitz reproduction : https://stackblitz.com/edit/astrotailwind-doubleslash-issue

**Comment by adrianbarbic** [comment] 2022-03-23 09:56
Went through the Stackblitz demo and realised that I has setup the css with this in the html head
```
    <style global>
      @import "../styles/global.css";
    </style>
```

Needed to update to just import the styles with:
```
import '../styles/global.css';
```

**Comment by tony-sull** [comment] 2022-05-10 18:40
> Yes ! I can reproduce this issue even on [Stackblitz](https://stackblitz.com/edit/astrotailwind-doubleslash-issue) based on my starter theme. (package updated, tried with node 14 and 16).

Looks like this reproduction also just needs to be using ESM imports (`import '../styles/global.scss`) in the frontmatter rather than an inline style with `@import`

Closing this issue as it seems like we're all set, but please reopen if you are still seeing an issue with ESM imports 👍

**Closed by tony-sull** 2022-05-10 18:40 UTC

**Comment by alexbezhan** [comment] 2023-06-09 14:30
I'm having the same problem. Integrated tailwind according to the [documnetation](https://docs.astro.build/en/guides/integrations-guide/tailwind/). 
When running locally `npm run dev` the styles apply correctly, but when deployed on Netlify with `npm run build && netlify deploy --prod` the styles that contain `lg:` prefix don't exist.
