### ISSUE TITLE
Vercel adapter doesn't work with <Code /> component

### ISSUE THREAD

**Issue by Ehesp** [withastro/astro#6174] opened 2023-02-08 11:41 UTC
### What version of `astro` are you using?

2.0.8

### Are you using an SSR adapter? If so, which one?

Vercel (^3.0.1)

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When including the `<Code />` component in pages, the shiki themes are not being uploaded to Vercel:

```
[ssr] Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/themes/css-variables.json' (x13)
```

```
<Code
  theme="css-variables"
  lang="js"
  code="console.log('Hello, world!');"
/>
```

See repro link for an example. This works in dev, but fails when deployed to Vercel.

### Link to Minimal Reproducible Example

https://github.com/Ehesp/astro-vercel-shiki-error

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-02-08 19:17
Thanks! It looks like this is due to the fact that shiki dynamically loads json files. I feel like we have solved this issue in the past, let me do some research and see what changed here.

**Comment by matthewp** [comment] 2023-02-08 19:18
Ah yes, we did previously fix this here: https://github.com/withastro/astro/pull/5409

**Comment by matthewp** [comment] 2023-02-08 19:22
@Ehesp the reproduction doesn't seem to use Code, or vercel. Can you update it?

**Comment by Ehesp** [comment] 2023-02-08 19:38
Oh woops I pushed the empty repo. Updated now

**Comment by matthewp** [comment] 2023-02-09 18:04
Just dropping in to say I can recreate the error. Digging into why our solution isn't working any more.

**Comment by matthewp** [comment] 2023-02-09 18:09
Pretty sure it's caused by this change: https://github.com/withastro/astro/pull/5952

Working on a fix.

**Comment by matthewp** [comment] 2023-02-09 18:40
Should be fixed by https://github.com/withastro/astro/pull/6198 Going to deploy a test app to confirm.

**Closed** 2023-02-09 19:22 UTC
Labels: p4-important

**Comment by matthewp** [comment] 2023-02-09 19:28
Being released now, thanks again for bringing this important issue to our attention @Ehesp 

https://github.com/withastro/astro/actions/runs/4137734219/jobs/7153272973

**Comment by Ehesp** [comment] 2023-02-09 20:56
@matthewp thanks, although I've just upgraded both `astro` and `@astro/vercel`, and I get another error now:

```
2023-02-09T20:54:34.138Z	2824ee7c-5fe2-449a-9519-afc400a7e0cf	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'","code":"ENOENT","errno":-2,"syscall":"open","path":"/var/task/node_modules/shiki/languages/html.tmLanguage.json","stack":["Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
Runtime.Unknown
``` 

It's a bit late here though so I'll properly check it out in the morning.

**Comment by kayn1** [comment] 2023-04-09 19:38
I have got the same error today when using `Code` with Vercel. 

> @matthewp thanks, although I've just upgraded both `astro` and `@astro/vercel`, and I get another error now:
> 
> ```
> 2023-02-09T20:54:34.138Z	2824ee7c-5fe2-449a-9519-afc400a7e0cf	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'","code":"ENOENT","errno":-2,"syscall":"open","path":"/var/task/node_modules/shiki/languages/html.tmLanguage.json","stack":["Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/html.tmLanguage.json'","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
> Unknown application error occurred
> Runtime.Unknown
> ```
> 
> It's a bit late here though so I'll properly check it out in the morning.
