### ISSUE TITLE
Newlines are removed in mdx when using <Code />

### ISSUE THREAD

**Issue by SorenHolstHansen** [withastro/astro#6440] opened 2023-03-06 21:32 UTC
### What version of `astro` are you using?

2.0.17

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a component that both displays its children as code, and puts it inside an iframe for displaying
```astro
---
// Example.astro
import { Code } from 'astro/components';

const html = await Astro.slots.render('default');
---

<div>
	<iframe
		srcdoc={`
	<!DOCTYPE html>
	<html lang='en'>
	<head>
		<meta charset='UTF-8'>
		<meta name='viewport' content='width=device-width, initial-scale=1.0'>
	</head>
	<body>
		${html}
	</body>
	</html>
	`}></iframe>
	<Code code={html} lang='html' />
</div>
```

And when I use it in an .astro file, the code is formatted exactly like i write it in the .astro file. That is, it has line breaks and everything.

However if I use the component inside an .mdx file (I am using the content collections), all newlines and tabs are gone. For instance
```md
import Example from '../../components/Example.astro';

<Example>
	<div>
		<p>Hello</p>
		<p>There</p>
	</div>
</Example>
```
This would render the code like this in the browser:
```
<div><p>Hello</p><p>There</p></div>
```
but i want it to render like this
```
<div>
	<p>Hello</p>
	<p>There</p>
</div>
```
I saw that I could add two spaces to the end of the lines, but that adds `<br />` tags, which I don't want.

Is there any workaround for this, or do I have to drop the content collections for this?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-esxxkd?file=src/pages/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment] 2023-03-06 21:37
I think this is just how JSX works. Newlines are not preserved in JSX.

**Comment by bluwy** [comment] 2023-03-07 14:00
Yeah I think that's how JSX works too. A workaround would be wrapping the content like:

```jsx
<Example>
  {`
  <div>
    <p>Hello</p>
    <p>There</p>
  </div>
  `}
</Example>
```

And unescape the HTML characters. An Astro integration or Vite plugin could automate this. Closing for now as this is working as intended internally and out of scope in Astro.

**Closed by bluwy** 2023-03-07 14:00 UTC

**Comment by SorenHolstHansen** [comment] 2023-03-07 20:30
Ahh, alright, thanks for the help!
