### ISSUE TITLE
Tailwind integration not support to load tailwind.config.ts

### ISSUE THREAD

**Issue by helbing** [withastro/astro#7030] opened 2023-05-07 22:10 UTC
### What version of `astro` are you using?

2.4.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Tailwind CSS v3.3 supports the ESM/TS configure file now. But Tailwind integration will report the error `The "path" argument must be of type string. Received undefined` when I saved the `astro.config.mjs` with the configure file`tailwind.config.ts`.

- [Tailwind CSS v3.3: Extended color palette, ESM/TS support, logical properties, and more](https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-typescript-support)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-un678m

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-05-07 22:18
Closing as a duplicate of https://github.com/withastro/astro/issues/6695

**Closed** 2023-05-07 22:19 UTC
