### ISSUE TITLE
Endpoints and SSR pages break when deployed to Netlify when using `@libsql/client`

### ISSUE THREAD

**Issue by gamebox** [withastro/astro#7601] opened 2023-07-07 23:13 UTC
### What version of `astro` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

Chrome (and Arc)

### Describe the Bug

Adding the `@libsql/client` package to my project causes any endpoints (or SSR'd pages) to break when deployed (or ran with `netlify serve`).

The error we get varies on what you try to do, but usually of the form:

<img width="523" alt="Screenshot 2023-07-07 at 6 10 52 PM" src="https://github.com/withastro/astro/assets/1380687/820fa775-1b5e-4d99-9e8f-daded9260a8d">

Or similar with the TypeError about `page19.page is not a function`.

There is a very detailed discussion about this issue on the support channel on Discord: https://discord.com/channels/830184174198718474/1126350487361441873

### What's the expected result?

If my project with `@libsql/client` works on my local dev server, it should work with both `netlify serve` locally, and also deployed to Netlify proper.

### Link to Minimal Reproducible Example

https://github.com/natemoo-re/bug--astro-netlify-libsql

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by gamebox** [comment] 2023-07-08 05:17
I don't want to expand the scope of this issue, but I do want to note that moving to the Node provider still produces some strange behavior.  This is with standalone mode and output: 'server' (I also tried 'hybrid').

**Comment by ematipico** [comment] 2023-07-10 16:18
I tried the minimal example but it breaks locally :(

**Comment by ematipico** [comment] 2023-07-10 16:49
I managed to reproduce the issue. The deployment on netlify doesn't help much, bug using the node adapter uncovers an interesting error: 

```
ReferenceError: __filename is not defined in ES module scope
```

It seems that `@libsql/client` imports some code that eventually uses some Node.js native stuff, which won't work on netlifly.

**Comment by ematipico** [comment] 2023-07-10 16:52
The bundled code comes from https://github.com/TooTallNate/node-bindings

**Comment by natemoo-re** [comment] 2023-07-10 17:54
> I managed to reproduce the issue. The deployment on netlify doesn't help much, bug using the node adapter uncovers an interesting error.

I added a [commit](https://github.com/natemoo-re/bug--astro-netlify-libsql/pull/1) that seems to fix the `@libsql/client` issue when using the `@astrojs/node` adapter. Basically, `@libsql/client` cannot be bundled for the reasons @ematipico outlined above. By adding the following configuration, we can exclude `@libsql/client` and its dependencies from the build process.

```js
import { defineConfig } from 'astro/config';
import node from '@astrojs/node';

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: node({ mode: 'standalone' }),
  vite: {
    ssr: {
      // DO NOT BUNDLE these packages
      external: ['@libsql/client']
    }
  }
});
```

**Comment by natemoo-re** [comment] 2023-07-10 18:00
My guess is that configuring this package to be excluded from the Netlify build process will fix the error on Netlify as well, but their bundling is quite difficult to debug. I'm trying to tweak the settings on this right now.

**Comment by natemoo-re** [comment] 2023-07-10 18:34
OK! I think I was finally able to wrangle the Netlify build settings to make things work. The latest changes should be on https://github.com/natemoo-re/bug--astro-netlify-libsql.

Summary of changes:

- `astro.config.mjs` should specify `@libsql/client` in the `vite.ssr.external` array
```js
import { defineConfig } from 'astro/config';
import netlify from "@astrojs/netlify/functions";

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: netlify(),
  vite: {
    ssr: {
      // DO NOT BUNDLE these packages
      external: ['@libsql/client']
    }
  }
});
```
- `netlify.toml` should **also** specify `@libsql/client` to be excluded from Netlify's production bundling
```toml
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@libsql/client"]
```
- Root `package.json` should include `"packageManager": "pnpm@8.6.2"` and `"type": "module"`
- Root `.npmrc` file should exist and include `shamefully-hoist=true`

**Comment by gamebox** [comment] 2023-07-10 19:33
Thanks for the update @natemoo-re , but doesn't that mean (some transitive depa requiring node apis) that the app will not work on Netlify due to the library being excluded?

**Comment by natemoo-re** [comment] 2023-07-10 22:55
It should work still. Excluding the library from bundling just means it will be referenced from `node_modules` like normal. Netlify should copy over your `node_modules` directory.

**Comment by natemoo-re** [comment] 2023-08-03 17:47
Closing this since there hasn't been any activity lately. Assuming those changes fixed the problem! Please open a new issue if you run into anything else.

**Closed by natemoo-re** 2023-08-03 17:47 UTC
Labels: needs response, - P4: important, feat: ssr, pkg: netlify
