### ISSUE TITLE
Unexpected "|"

### ISSUE THREAD

**Issue by vighnesh153** [withastro/astro#7519] opened 2023-06-29 10:21 UTC
### What version of `astro` are you using?

2.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The following code causes the astro tool to choke. Replace your `index.astro` file's content with the following to reproduce. Run `npm run dev` and open the localhost url in any browser.

```ts
---
export type TypographyVariant =
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'subtitle1'
  | 'subtitle2'
  | 'body1'
  | 'body2'
  | 'button'
  | 'caption'
  | 'overline'
  | 'inherit';

---

<h1>Hi</h1>
```

### What's the expected result?

It should not choke?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ab8kkq?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment] 2023-06-29 11:15
Wouldn't it work like this:

```astro
---
export type TypographyVariant =
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'subtitle1'
  | 'subtitle2'
  | 'body1'
  | 'body2'
  | 'button'
  | 'caption'
  | 'overline'
  | 'inherit';

---

<h1>Hi</h1>
```

**Comment by ElianCodes** [comment] 2023-06-29 11:22
Just checked this, seems to be the formatting that makes the error appear

Doesn't work:
```ts
export type TypographyVariant = 'h1'
  | 'h2'
  | 'h3';
```
or
```ts
export type TypographyVariant = 
  | 'h1'
  | 'h2'
  | 'h3';
```
does work:
```ts
export type TypographyVariant = 'h1'
| 'h2'
| 'h3';
```
or
```ts
export type TypographyVariant = 
| 'h1'
| 'h2'
| 'h3';
```

**Comment by vighnesh153** [comment] 2023-06-29 13:36
So, a bug in the TS transformer?

**Comment by Princesseuh** [comment] 2023-06-29 13:36
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2023-06-29 13:36 UTC
