### ISSUE TITLE
Astro throws error "[ERROR] Expected > but found const"

### ISSUE THREAD

**Issue by daniele-orlando** [withastro/astro#9965] opened 2024-02-03 19:24 UTC
### Astro Info

```block
Astro                    v4.3.2
Node                     v21.1.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/preact
                         @astrojs/solid-js
                         @astrojs/vue
                         @astrojs/mdx
                         astro-imagetools
```

### Describe the Bug

Using the code

```
export type Props<T extends HTMLTag> = Polymorphic<{
    as: T
}>
```

throws the error

```
[ERROR] Expected ">" but found "const"
```

If I change the code to

```
type Props<T extends HTMLTag> = Polymorphic<{
    as: T
}>
```

or to
```
export type Props<T extends HTMLTag> = {
    as: T
}>
```

does not throw the error.

### What's the expected result?

The syntax

```
export type Props<T extends HTMLTag> = Polymorphic<{
    as: T
}>
```

should work without errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/edit/github-q3bakq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-02-03 21:38
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2024-02-03 21:38 UTC
Labels: needs triage
