### ISSUE TITLE
MDX rendered by a layout does not emit CSS

### ISSUE THREAD

**Issue by kurtextrem** [withastro/astro#7426] opened 2023-06-20 08:13 UTC
### What version of `astro` are you using?

2.6.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn (and pnpm)

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When you use a layout to render a MDX page:

(Layout.astro)
```astro
---
const { post } = Astro.props;
const { Content } = await post.render();
---

<Content />
```

and the MDX page contains something that uses CSS modules, such as:

```jsx
import Tweet from "../../components/Tweet.astro";
<Tweet id="1382838799420514317" />
```

where `<Tweet>` is an Astro component:

```astro
---
import { EmbeddedTweet } from "react-tweet";
import { getTweet } from "react-tweet/api";

interface Props {
    id: string;
}

const { id } = Astro.props;
const tweet = await getTweet(id);
---

<EmbeddedTweet tweet={tweet} />
``` 

It does not emit the CSS modules correctly, not in `dev` and not on `build`. See the attached codesandbox, where `index.astro` is broken - no CSS emitted, and then `working.astro` (`/working`), the CSS is emitted correctly, because I added the `Tweet` component to the `WorkingLayout` component. So only when you add the `Tweet` component to something non-MDX-related, it emits the CSS modules correctly.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/lingering-microservice-cz8tnn?file=%2Fsrc%2Fpages%2Findex.mdx%3A1%2C1

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by RobertDS07** [comment] 2023-06-22 19:50
Hello @kurtextrem, how are you?

I've seen your codesandbox and analyzed the code. I found a possible solution by adding the [directive client:load](https://docs.astro.build/en/reference/directives-reference/#clientload) to the EmbeddedTweet component. The result is as expected.

Here is the [link](https://codesandbox.io/p/sandbox/compassionate-jepsen-yjldk7?file=%2Fsrc%2Fcomponents%2FTweet.astro%3A2%2C37) to my sandbox with the possible solution.

I'm not sure if it's expected to have to add this directive to a React library, but...

![image](https://github.com/withastro/astro/assets/63268954/a5b67c8b-405b-4bbc-b6e3-7e00de340920)

**Comment by kurtextrem** [comment] 2023-06-23 07:32
@RobertDS07 Thanks! I think this solution however makes Astros biggest benefit (not shipping JS) redundant...

**Comment by kurtextrem** [comment] 2023-06-27 13:03
Does anyone have a hint at where to start looking if I want to fix this bug?

**Comment by natemoo-re** [comment] 2023-08-16 20:46
This seems to be a duplicate of https://github.com/withastro/astro/issues/7761 so I'm going to track that there. Feel free to chime in on that conversation!

**Closed by natemoo-re** 2023-08-16 20:46 UTC
Labels: - P3: minor bug
